### ISSUE TITLE
OPERADOR SOLVERA

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#10]
Estimados buenas tardes,
Seguimos con el caso Solvera por solicitud de Lucas,
Adjunto mails y link de voucher

![image](https://user-images.githubusercontent.com/45457355/124990267-829a8880-e016-11eb-8049-05cf58081603.png)

![image](https://user-images.githubusercontent.com/45457355/124990144-5b43bb80-e016-11eb-8a29-f33bc6572d0d.png)

![image](https://user-images.githubusercontent.com/45457355/124990309-91813b00-e016-11eb-82fa-c052802ce752.png)

![image](https://user-images.githubusercontent.com/45457355/124990363-a78efb80-e016-11eb-81d5-c419a5384867.png)

https://adm.ebooking.com.ar/bookings/detail/60a3ef9ce649d8bfc3179144?purchaseGroupId=354878#heading_60a3ef9ce649d8bfc3179144

**Comment by Jlavign** [comment]
Estimados buenos días,
Tendrán novedades?

**Comment by gabrielmarinsaldaJT** [comment]
Buenas tardes

@moliveto se puede atender este pedido? No se si es conveniente cambiar el nombre de un proveedor

**Comment by gabrielmarinsaldaJT** [comment]
Les explico lo que tienen que hacer para cerrar esta issue:

Entren al ADM y vayan a Administracion/Proveedores

![image](https://user-images.githubusercontent.com/26115345/126494060-72307542-0878-4bb1-94c7-def2d1f997ce.png)

Busquen al proveedor Omnibees y selecciones el primero de la lista

![image](https://user-images.githubusercontent.com/26115345/126494173-b7d4a1a5-b2fe-4286-b5c9-ce5434ac5e8f.png)

Seleccionen la pestaña Chain Codes

![image](https://user-images.githubusercontent.com/26115345/126494473-d04d1fb1-3ca4-41ca-8fa7-7acf355fcd8f.png)

Una vez ahí, en el fondo de la tabla, está el ChainCode de Majestic

Fijense que el SistAgenCode está en blanco, ahi tienen que agregarlo ustedes

Preguntenle a Pagos por si no lo tienen

**Comment by gabrielmarinsaldaJT** [comment]
Estaba duplicado el ChainCode y fallaba, le borre uno que tenia mal agregado y salió todo andando
