### ISSUE TITLE
Sandos cadena directa - SIN DISPONIBILIDAD

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#101]
### Descripcion del error

Estimados buenas tardes
No visualizamos resultados de cadena directa con Sandos para una fecha específica, adjunto link, en el Sandos Playacar
Consulté aparte con la ejecutiva de la cadena quien me reporta que si poseen disponibilidad en la habitación RIVIERA

Gracias!

### Paso a paso para reproducir el error

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5caa060e86315a56f0e438b7/sandos-playacar?checkIn=2021-12-23&checkOut=2021-12-29&nationality=AR&residence=AR&occupancies=2*30,30*2*3,3%7C2*30,30*0*%7C3*30,30,30*0*%7C2*30,30*2*2,1&currency=USD

Acá va la búsqueda de sólo una doble
https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5caa060e86315a56f0e438b7/sandos-playacar?checkIn=2021-12-23&checkOut=2021-12-29&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

Ya para Enero si hay dispo Cadena Directa.
Pero si vemos, con otros proveedores si hay dispo de ese tipo de habitación RIVIERA

### Link al error y/o Localizador

a

**Comment by gabrielmarinsaldaJT** [comment]
Cuando pasen estos problemas, hay que indicarle al proveedor lo sucedido.

Desde nuestro lado no podemos hacer mas nada que enviar un mail que lo puede enviar cualquiera

Si lo hacen ustedes, se ahorran el tiempo de gestión hasta que nosotros lo veamos, lo analizemos y enviemos un mail

Cualquier cosa puedo enseñarles como se hace o **qué** decirles expecíficamente para que revisen la carga de precios online

**Comment by gabrielmarinsaldaJT** [comment]
Mail enviado al proveedor

**Comment by agostinaf25** [comment]
Gabi, gracias por tu respuesta!!!
Previo a generar la issue consulté con Andrea Galaviz reservas6@sandos.com la dispo de este hotel y me reportó que poseen habitaciones disponibles de tipo RIVIERA, para las fechas reportadas. 
De igual modo, si, podrías indicarnos qué otro dato solicitarle al proveedor o informarle para la celeridad del caso
Gracias desde ya!

**Comment by gabrielmarinsaldaJT** [comment]
Hola @agostinaf25 !! 

De nada, me gusta ayudarlos

Preguntenle al proveedor si tiene dispo **online** porque para ellos es igual si venden por integración o por mail

Asique pregunten con frases como

"No vemos la dispo online"
"No recibimos disponibilidad mediante la integración"

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Me contestaron esto:

> Buenos Dias Gustavo:
> 
> Podrias intentar hacer la busqueda del 24 de diciembre al 29 por favor e indicarme si te arroja disponibilidad.
> 
> Saludos Cordiales.

**Comment by agostinaf25** [comment]
Gabi querido
Si, trae dispo en esas fechas
https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5caa060e86315a56f0e438b7/sandos-playacar-playa-del-carmen-playacar--mexico?checkIn=2021-12-24&checkOut=2021-12-29&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

Cómo seguimos?

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

El problema es que sólamente el 23 de Dic no hay dispo.

Recomiendo enviarle un mail al proveedor explicándole que solamente ese día no hay dispo, a ver si se dan cuenta y nos solucionan el problema

Me salgo de la issue para evitar que se acumule, ya no puedo hacer mas nada al respecto
