### ISSUE TITLE
Autos - Trifthy - Tarifa recomendada

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#102]
### Descripcion del error

Estimados
Desde el staff de ventas nos hicieron llegar una observación acerca de la rentadora Thrifty y Dollar
Al momento de buscar disponibilidad, se visualiza un cartel verde con la leyenda 'Tarifa Recomendada' junto a un producto que no tiene todas las inclusiones para el mercado estadounidense
'La *TARIFA RECOMENDADA* de estas rentadoras debería ser **L8LGA** y no **L8LTY**, ya que a esta última le falta el seguro SLI (seguro adicional contra daños a terceros) que es obligatorio'

Podrían indicarle a la rentadora que modifiquen esta clasificación, a fin de evitar inconvenientes?

### Paso a paso para reproducir el error

https://www.juantoselli.com/#/autos/buscar?pickUpDate=2021-11-10&pickUpTime=07:30&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida-estados-unidos&returnDate=2021-11-17&returnTime=11:00&nationality=AR&residence=AR&currency=USD

Filtrar Trifthy y los productos arriba señalados

### Captura del error

![image](https://user-images.githubusercontent.com/88336164/133490154-442ee92b-4501-4d82-946f-5a569790fc09.png)
![image](https://user-images.githubusercontent.com/88336164/133490201-d136dde9-7c60-4c5a-a1ee-819764329b5f.png)

### Link al error y/o Localizador

https://www.juantoselli.com/#/autos/buscar?pickUpDate=2021-11-10&pickUpTime=07:30&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida-estados-unidos&returnDate=2021-11-17&returnTime=11:00&nationality=AR&residence=AR&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Problema resuelto

Ahora las tarifas recomendadas son las que nos solicitan

Saludos!
