### ISSUE TITLE
Traslados - Horario

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#103]
### Descripcion del error

Estimados
Visualizamos que en la parte de Traslados, al seleccionar **Sólo Ida** no nos muestra los recuadros para elegir Hora Vuelo/Hora Recogida
Si bien puede aplicar para transfers interhoteles, puede haber un aeropuerto involucrado por lo que seria una herramienta útil
Sería una buena implementación que esto se encuentre tanto en trf in/out como en los one way a fin de manejar el mismo criterio para ambos.

### Paso a paso para reproducir el error

Traslados
Sólo Ida
Colocar nombre hotel o AEP, en cualquiera de los dos campos

Allí no figura el bloque
![image](https://user-images.githubusercontent.com/88336164/133493209-7d9f8522-6bac-4af0-a4de-911a144f74eb.png)

### Captura del error

Acá si
![image](https://user-images.githubusercontent.com/88336164/133493301-9cb2617b-b933-4ba6-a8c1-33dd495207f7.png)
Acá no :( 
![image](https://user-images.githubusercontent.com/88336164/133493575-4e1ade50-32a7-49c9-ac6c-83fcd3fb98df.png)

### Link al error y/o Localizador

a

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado por @ivanpuglia
