### ISSUE TITLE
Reclamo de cliente al agregar reserva a un grupo existente

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#104]
### Idea a implementar

Buenas tardes,
Desde agencia detectamos que al agregar un nuevo servicio a un grupo existente, realizar la posterior búsqueda y previo a confirmar, **le impide al cliente elegir vendedor y copia los datos de pasajeros de otras reservas (problema planteado por el cliente)**.
Les brindo las credenciales de una agencia que reportó esto:

- euginofal@yahoo.com.ar
- Contraseña: matias1

Agarre cualquier grupo de la agencia, agregue un nuevo servicio y pude visualizar lo siguiente:

![image](https://user-images.githubusercontent.com/40358708/133653986-cbec349c-7ba0-4d2a-97ef-79813ef3b104.png)

No permite elegir vendedor diferente

![image](https://user-images.githubusercontent.com/40358708/133654068-e2da7bc6-bd7f-45a3-9f81-2aaf1ad847c5.png)

Copia los datos de pasajeros del mismo grupo. 

¿Es esto lo más óptimo para el usuario? A mi parecer, esta bien que el vendedor no pueda elegirse al agregar reservas a un grupo, pero pongo en tela de juicio el hecho de que se copien los datos de los pasajeros. 

Aguardo su respuesta, gracias!

**Comment by IvanFacundoRosas** [comment]
Lo discutimos con los mandamases y llegamos a las siguientes conclusiones:
1) Está bien que se copien los datos de los pax; es uno de los valores agregados del nuevo sistema de Grupos
2) La agencia no debería poder cambiar el vendedor

Queda así. Cierro issue.
