### ISSUE TITLE
Reservas en Revisar A2B

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#106]
### Descripcion del error

Hola Chicos,
En el siguiente link se encuentran 6 reservas **en revisar** de A2B

https://adm.ebooking.com.ar/bookings?dateFrom=2018-12-31&status=7

Las mismas  muestran en los logs, el siguiente error en el _metodo postbookreview:_

"Your login details have not been recognized"

Quería saber si es un error generalizado y en qué estado deberian estar cada una de ellas. También para saber si debo consultarle al proveedor. 
Muchas gracias

### Paso a paso para reproducir el error

no aplica

### Captura del error

no aplica 

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2018-12-31&status=7

### Plataforma

chrome

**Comment by julianbenegaslane** [comment]
Las credenciales cambiaron, se soluciona en la proxima publicacion
