### ISSUE TITLE
Circuito Special Tours, tomado por ebooking, diferencia en costo y el nombre de la pax se repite multiples veces

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#107]
### Descripcion del error

1. El costo en Ebooking es diferente al de Special 
Costo Ebooking: U$D 2452,45
Costo Special: U$D 2493

2. El nombre en de la pax en Ebooking se repite multiples veces

Localizador Ebooking 794580
Localizador Special Tours: 402428541 

### Paso a paso para reproducir el error

Ingresar a ambos localizadores y de detexcta el error. Me avisan si necesitan algo 

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/133809850-408d2805-cd79-42e7-b2d3-fb5ca8c529cd.png)
![image](https://user-images.githubusercontent.com/88200755/133810018-0b4dd734-354d-4114-af9c-6f93adeeeec3.png)

![image](https://user-images.githubusercontent.com/88200755/133810394-b6fb1271-a7d7-420e-80f5-63aa3cd25228.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6038f407b82d506b20fad0d1?purchaseGroupId=348981#heading_6038f407b82d506b20fad0d1

**Comment by IvanFacundoRosas** [comment]
Arreglado lo de los paxes. El resto irreproducible. Quedamos con Natalia que se reabriría si aparece el mismo error en otra reserva.
