### ISSUE TITLE
Tickets Disney

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#108]
### Descripcion del error

Vendedora indica que:
"Cotice y reserve un pase de Disney, pase básico 2 dias para 5 pax. cuando lo cotizo da como les copio abajo, USD 1899,59.- pero cuando paso al paso siguiente, me cambia la tarifa a USD 1803.81, independientemente de si la comision es el 13% a agencias o el 9% a nosotros.

En este caso, yo reserve ayer y puse toselli porque no esta la mutual cargada, pero de todas formas me da mas económico. y según lo que liquida Action, estaria bien, pero no entiendo porque da la cotización mas cara y despues mas barato en la reserva, porque ni sumando el iva y gastos da eso.

Lo podrán chequear porfa? tengo miedo de liquidarle mal a la agencia y que despues vaya a perdida."

### Paso a paso para reproducir el error

1- Se busca disponibilidad con los datos indicados
2- Se encuentra diferencia en cotización inicial con la mostrada al final posterior a tomarla.

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/133848756-5e47cfe5-c018-4a0a-9c25-e23a3787ae20.png)
Theme Park Base Ticket. E - Ticket. (Walt Disney World)
![image](https://user-images.githubusercontent.com/45457355/133848846-38fc99e9-e2f5-4ba9-a682-a48de25b9230.png)
![image](https://user-images.githubusercontent.com/45457355/133848855-19d17907-d166-49b1-adcf-980ef2502eba.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5aa7dd3f3dfcee50fc39c792&destinationName=orlando-florida&fromDate=2021-11-16&toDate=2021-11-17&nationality=AR&residence=AR&occupancies=5*30,30,30,30,30*0*&disney=true&currency=USD

**Comment by julianbenegaslane** [comment]
El precio de los tickets varia levemente dependiendo el dia en el que se quiera reservar, por cuestiones de simplicidad, nosotros mostramos la opcion mas cara de las fechas disponibles.
Una vez seleccionada la fecha, el precio que se muestra es el adecuado.
