### ISSUE TITLE
ATRACCIONES no aparece disponibilidad.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#109]
### Descripcion del error

Buenas tardes,
¿Nos ayudarías con este caso enviado por Carolina sobre ATRACCIONES?

### Paso a paso para reproducir el error

Te hago un breve resumen.
Carolina indica que está chequeando una excursión clásica en Europa en nuestro sistema, que está integrado con el de Hotelbeds, y no le sale.
En la web directo si sale,

Desde Hotelbeds le solicitan lo siguiente:

Nos podrían adjuntar los logs (petición y respuesta) xml/json correspondientes al servicio/actividad que nos comentan que no les aparece?
De este modo podremos investigarlo en profundidad.

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/133849245-71890788-467e-42ff-b669-25e0953a8494.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5a21b155fc2d560873053f75&destinationName=paris-y-sus-alrededores-isla-de-francia--francia&fromDate=2022-04-16&toDate=2022-04-17&nationality=AR&residence=AR&occupancies=1*30*0*&disney=false&currency=USD

**Comment by julianbenegaslane** [comment]
error de mapeo, solucionado. Se va a ver reflejado la proxima actualizacion de productos.

**Comment by Jlavign** [comment]
Muchas gracias!
