### ISSUE TITLE
Localizador #T4ZH2GU/01 TRAVCO TEST

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#11]
Estimados buenas tardes,
Revisando el cancelador de OPT encontré la siguiente reserva creada hoy con Travco,
La misma es JTMock y contiene pax TEST, confirmada, cobrada con gastos, para las fechas 31/12/9999.
Mi pregunta es si la misma debe ser enviada a cancelar con Operador o si se debe mantener por algo en especial.

https://adm.ebooking.com.ar/bookings/detail/60e69c6e0a1ff14a7d4d1c82?purchaseGroupId=357684#heading_60e69c6e0a1ff14a7d4d1c82

**Comment by gabrielmarinsaldaJT** [comment]
Buenos días

La reserva es un test, NO es NonRefundable asique la cancelé sin problemas

Saludos
