### ISSUE TITLE
ERROR MAPEO. AGREGAR A BLACKLIST

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#110]
### Descripcion del error

BUENAS TARDES 

ES PARA INFORMAR EL SIGUIENTE ERROR ES LA RVA QUE TOMO ISTRIA 

Hay algo raro con esta reserva. Cuando la tomamos, buscamos el Secrets Costa Mujeres y en la parte de Reservas en eBooking, figura como Secrets. Pero el mail llegó como Dreams. 
Claramente no son lo mismo en cuanto a categoría, pese a estar uno al lado del otro. Pero necesitaría confirmar que la reserva está con el Secrets. ¿Te podrías fijar porfa?

RESPUESTA DEL OPERADOR 

Buenos dias.

Tenga en cuenta que el error de mapeo proviene de su lado; se adjuntan los registros.

La reserva se puede cancelar sin cargos hasta el 24-01-2022, por lo tanto, consulte con el cliente si está de acuerdo con el Hotel correcto que tenemos en nuestro sistema, de lo contrario continúe y cancele la reserva antes de que se apliquen los cargos.

Es importante cancelar la reserva antes de la fecha límite si no es necesario, de lo contrario se aplicará la penalización completa.

### Paso a paso para reproducir el error

1- Se localiza reserva
2- Se visualiza error de mapeo

### Captura del error

![Uploading image.png…]()

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/612fc830f71cdf3b0d48aa78?purchaseGroupId=359665#heading_612fc830f71cdf3b0d48aa78

**Comment by gabrielmarinsaldaJT** [comment]
Estimados, cómo están?

Ustedes pueden agregar hoteles a la BlackList, por lo que no es necesario que lo hagamos nosotros

De cualquier manera, ya ha sido agregado
