### ISSUE TITLE
Reservas en Revisar Hotelbeds

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#111]
### Descripcion del error

Hola Chicos, 

Podrán ayudarme a reconfirmar que las siguientes reservas de Hotelbeds se encuentren en error?

https://adm.ebooking.com.ar/bookings/detail/614397b10f30163c2a240e78?purchaseGroupId=360630#heading_614397b10f30163c2a240e78

https://adm.ebooking.com.ar/bookings/detail/614397b10f30163c2a240e53?purchaseGroupId=360630#heading_614397b10f30163c2a240e53

Del mismo grupo habian otras en revisar, pero dentro del check out se encontraban en error 500. De estas dos, en Check out no encuentro el error, pero tampoco contemplo un ID, sí las veo como confirmada.

### Paso a paso para reproducir el error

Revisar logs. 

### Captura del error

no aplica

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/614397b10f30163c2a240e78?purchaseGroupId=360630#heading_614397b10f30163c2a240e78  /  https://adm.ebooking.com.ar/bookings/detail/614397b10f30163c2a240e53?purchaseGroupId=360630#heading_614397b10f30163c2a240e53

### Plataforma

google chrome

**Comment by gabrielmarinsaldaJT** [comment]
No las puedo encontrar en el proveedor

Sugiero enviarle un mail al proveedor consultándole si existen las reservas en su sitio

Enviarle nuestro RecordLocator y que ellos verifiquen

Cierro issue
