### ISSUE TITLE
ERROR ADM NROS GRUPO 360483 // 360486

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#114]
### Descripcion del error

Estimados buenas tardes,
Solicito nos puedan ayudar con los siguientes casos,

Caso 1- Solicitamos colocar en grupo 0 la reserva SISTEMAS nro 3186939 que contiene el grupo 360486. Ya que no nos deja realizar la modificación manualmente.

Caso 2- Verificamos que en dicho grupo existe un listado de reservas las cuales la vendedora indica fueron cotizaciones, pero así mismo no se muestran en el listado del grupo seleccionado, lo podemos ver al ingresar al grupo 360483 
Vendedora indica que:
"Recién entro al adm de TT para cancelar unas reservas, y en el mismo grupo en el que tenia esas reservas, me aparecieron varias cosas mas, que por lo que veo, fueron solo cotizaciones, pero quedan como ELIMINADO o SIN CONFIRMAR.

Esto es nuevo?? siempre va a pasar eso cuando se haga una coti va a quedar asi?

De todas formas, nada de todo eso que me figura, esta ok, asique cancelo y ya? Me las elimina?"``

### Paso a paso para reproducir el error

Caso 1.
1- Buscar en ADM grupo 360486
2- Verificar y modificar reserva SISTEMAS nro 3186939

Caso 2.
1- Buscar en ADM grupo 360483
2- Visualizar reservas de Stuba
3- Visualizar en parte inferior de alguna de las reservas del grupo un listado de reservas en estado undefined

### Captura del error

Caso 2.
![image](https://user-images.githubusercontent.com/45457355/134052633-523c371c-0651-45a6-ab39-2bdb47700069.png)
![image](https://user-images.githubusercontent.com/45457355/134052709-d45d8a77-0530-4339-be0c-79173d5b27cc.png)
![image](https://user-images.githubusercontent.com/45457355/134052758-460a1c99-dac9-4476-a7b2-6acf891a57ee.png)

### Link al error y/o Localizador

Caso 1. https://adm.ebooking.com.ar/bookings/detail/61328ba2de4522d281d0a5fa?purchaseGroupId=360486#heading_61328ba2de4522d281d0a5fa
Caso 2. https://adm.ebooking.com.ar/bookings/detail/61411d360f30163c2afde0bd?purchaseGroupId=360483#heading_61411d360f30163c2afde0bd

**Comment by Jlavign** [comment]
Estimados buenas tardes, 
Tendran novedades?

**Comment by Jlavign** [comment]
Estimados buenos días,
Tendrán novedades?

**Comment by IvanFacundoRosas** [comment]
@Jlavign 

Arreglado con un filtro que esconde las cotizaciones. Las cotizaciones se limpian periódicamente.
