### ISSUE TITLE
[EXPEDIA] Emisión de voucher

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#115]
### Descripcion del error

Estimados buenas tardes,
La siguiente reserva loc 9175722856692 Sebastián indica que no fue realizada por él y agencia indica que tampoco lo hizo.
Así mismo también indica que ninguno de ellos emitió voucher de la misma.
Solicito nos puedan indicar que sucedió para así poder elevar el reclamo al Operador.

### Paso a paso para reproducir el error

1- Buscar resrva loc 9175722856692

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/134244500-b73f087a-7ddf-4c6f-b6f7-7c3034138c94.png)
![image](https://user-images.githubusercontent.com/45457355/134244559-6e4e57c3-5c8c-4abd-b74f-e0544d5d9125.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6126ecdbd858fdd2e2f02ce3?purchaseGroupId=356961#heading_6126ecdbd858fdd2e2f02ce3 https://adm.ebooking.com.ar/bookingsOptimizer/optimizationsHistory

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos, cómo les va?

La reserva se confirmó el día 23/06/2021 y se envío un mail de confirmación a Eugenia Hadad y Sebastián Massa
(Ver mail de confirmación en Gmail)

Además, podemos ver que el día 28/06/2021 fue marcada como pagada por Cristian Gulli
![image](https://user-images.githubusercontent.com/26115345/134561764-db1bba91-9d15-48a1-9111-4a47d0c611a3.png)

Aguardo sus comentarios

**Comment by Jlavign** [comment]
Muchas gracias por la info.
