### ISSUE TITLE
Ebooking Mayo 2022 no trae busqueda de Avis/Budget 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#117]
### Descripcion del error

Ebooking Mayo 2022 no trae busqueda de Avis/Budget 
En la pagina d ela compañia si trae la busqueda 

Ebooking para esa fecha solo trae Sixt y Alamo 

### Paso a paso para reproducir el error

Realice la busqueda 

Pick up: 
01/may/22 16:30 - Aeropuerto de Malaga (AGP)
Drop Off: 
06/may/22 13:00 - Aeropuerto dre Granada (GRX)

y no arroja resultado con las compañias Avis/Budget

Repliqué la busqueda en la pagina ambas compañias y si arroja resultado

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/134408680-512b4ede-9c8d-4d95-867b-2b714afb5403.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/autos/buscar?pickUpDate=2022-05-01&pickUpTime=16:30&pickUpOfficeId=AGP&pickUpCityId=5a21b03cfc2d5608730471cf&pickUpCityName=malaga-malaga-espana&returnDate=2022-05-06&returnTime=13:00&returnOfficeId=GRX&returnCityId=5a21acd8fc2d56087302cb15&returnCityName=granada-granada-espana&nationality=AR&residence=AR&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Hola @natisalino cómo estás?

Lamentablemente, este error es idéntido al de la issue #100 y no tenemos manera de solucionarlo desde nuestro lado

Ya hemos abierto tickets para Avis/Budget y estamos insistiendo en el tema para que le den una solución de una buena vez

Te mantendremos al tanto

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado de parte del proveedor
