### ISSUE TITLE
NO ES POSIBLE A[SERVICIO y/o PROVEEDOR] Breve descripcion del error

### ISSUE THREAD

**Issue by ProductoToselli** [toselli/issues#119]
### Descripcion del error

Al intentar cargar un cupo ONLINE, en el ADM no aparece la pestaña "Aereos y Hoteles" 
Esta pestaña era la que relacionaba los aereos del sistema de cupos y los grupos de hoteles generados en el ebooking con la opción de poner los cupos online. 

### Paso a paso para reproducir el error

1. Salidas
2. Administrar salidas
3. NUEVA SALIDA
4. Modo Internacional
5. Cupos confirmados

### Captura del error

![image](https://user-images.githubusercontent.com/91271802/134526751-f41126c1-2faa-41bd-8a41-e913d8d25b6f.png)
![image](https://user-images.githubusercontent.com/91271802/134526835-f1c5c342-b318-4b81-ad24-0888eac9398e.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/tours/new

**Comment by IvanFacundoRosas** [comment]
Se arregló con una modificación en la DB. Cierro.
