### ISSUE TITLE
Reserva en revisar BONOTEL

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#121]
### Descripcion del error

Tengo la reserva en revisar de bonotel.
Más allá que he mandando a consultar al proveedor por el estado, ya que desde su web, pareciera que esta confirmada, quiero reportar que para esa misma propiedad,  hoy se intentaron tomar reservas y quedaron todas en revisar. Las cuales he pasado a Error, en método book "
En particular consulto por esta, ya que la vendedora la tomo el 17/09 y esta insistente debido a que quiere emitir el voucher. Por lo tanto necesito saber si desde nuestro lado la tenemos confirmada y contrastar con lo que me diga el proveedor, así de corresponder pasarla a confirmada inactualizable o en su defecto en error. 

### Paso a paso para reproducir el error

NA

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/134567693-f40891b3-2044-45ff-983b-38646739ed66.png)
![image](https://user-images.githubusercontent.com/87333634/134568095-66ad2795-388b-47a2-b580-921aad07c24f.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61450256625663854a645f1f?purchaseGroupId=360684#heading_61450256625663854a645f1f

### Plataforma

Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Reserva revisada y logs revisados y testeados

El response es correcto y está bien que quede en ToCheck, el proveedor devuelve Status.UN al momento de consultar la reserva

Se envía un mail consultándole este comportamiento

**Comment by GuadaVivas** [comment]
chicos cierro issue, proveedor responde con HCN, reserva confirmada. Gracias.
