### ISSUE TITLE
[ATRACCIONES] lenguaje invalido

### ISSUE THREAD

**Issue by julianbenegaslane** [toselli/issues#123]
### Descripcion del error

> hola chicos, esty tratando de tomar una excursion y al completar todos los datos me sale este cartel, a que se debe??
me avisan?

### Paso a paso para reproducir el error

Exc toledo y segovia desde mad, para el 18/03

### Captura del error

![image](https://user-images.githubusercontent.com/58426772/134573420-09d22e5f-d5b3-4742-a01a-ac6a550f9c2a.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/atracciones/finalizar-compra/614c7a0612640997ab31755d?currency=USD

**Comment by agostinaf25** [comment]
Buenas tardes
Ya no visualizo el tour que la vendedora estaba buscando, me adjuntó print, lo dejo aquí así tenemos la misma info
![image](https://user-images.githubusercontent.com/88336164/134730128-b9de6cbf-9bed-44d5-b137-107ba63c8729.png)

Habras tenido algun comentario del operador?
Cualquier cosita, avisame porfa

Gracias desde ya

**Comment by julianbenegaslane** [comment]
Error solucionado, se va a ver reflejado la proxima publicacion.
