### ISSUE TITLE
POR FAVOR MOVER FECHA DE VENCIMIENTO (URGENTE)

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#124]
### Descripcion del error

Hola, Equipo.

La vendedora Celeste Pagliero nos solicita mover 2 días el vencimiento de pago de la reserva Loc C654KW del 25/09/2021 al 27/09/2021, nos lo solicita con el fin de que no se caiga esa venta.
¿Es esto posible?

Por mi parte, realice el intento de modificarlo manualmente pero vuelve a la fecha del 25/09/2021

Espero me puedan ayudar.
Gracias

### Paso a paso para reproducir el error

Mover el vencimiento del 25/09/2021 al 27/09/2021

### Captura del error

![image](https://user-images.githubusercontent.com/88722251/134697813-6cf526b4-dda0-48f5-9b32-13025b5e32a9.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61361c6c54280b12ae974a35?purchaseGroupId=359906#heading_61361c6c54280b12ae974a35

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Le expliqué a Juan Manuel lo que debe hacer en esos casos, les recomiendo que le consulten a él para futuros casos similares

Cierro issue

Saludos
