### ISSUE TITLE
Hotel Iberostar Berkeley en blanco

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#129]
### Descripcion del error

Al ingresar a la búsqueda del hotel Iberostar Berkeley, no muestra ninguna información sino que queda totalmente en blanco.
Indistintamente a las fechas, no es en alguna en particular.

### Paso a paso para reproducir el error

Buscar ya sea Miami Beach y sus alrededores o directamente el hotel Iberostar Berkeley
Ingresar al avail de la propiedad

### Captura del error

![image](https://user-images.githubusercontent.com/88336164/135121173-d186d130-8ae9-41b5-a85e-4f436b992e0c.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca9eccb86315a56f0e28d7d/iberostar-berkeley?checkIn=2022-04-01&checkOut=2022-04-08&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by agostinaf25** [comment]
Estimados
Nos reportaron la misma cuestion con el hotel foresteria-del-pescatore 
https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8c4ac86315a56f0bcd134/foresteria-del-pescatore?checkIn=2022-05-31&checkOut=2022-06-03&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by agostinaf25** [comment]
Estimados buen día
Esto fue solucionado?
Quedo atenta
Gracias!
Agostina

**Comment by gabrielmarinsaldaJT** [comment]
Buenos días @agostinaf25 

Hemos tenido avances y ya sabemos el origen del problema

Apenas tengamos una solución te avisamos

Saludos!

**Comment by agostinaf25** [comment]
Barbaro Gabi gracias
Podrías dejarla abierta asi le damos seguimiento?
En tanto se solucione, cerramos
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, perdón

No me había dado cuenta que se había cerrado

Estamos aprendiendo a usar Github y quise nombrar esta issue para demostrar una duplicidad y no sabía que si cerraba una, la otra también se cerraba

Dejamos esta entonces para darle seguimiento

Perdón y gracias por la paciencia

**Comment by agostinaf25** [comment]
Un exito, gracias!
Seguimos acá :)

**Comment by gabrielmarinsaldaJT** [comment]
Listo estimados

Ya se ven los hoteles sin fotos en eBooking

Estamos trabajando en una Tarea que va a restaurar las fotos de los hoteles que no tienen
