### ISSUE TITLE
Reservas Assist Card en revisar

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#13]
Hola chicos buenas tardes!

Las siguientes reservas se encuentra en estado Revisar, las tres de assit card. No logro interpretar los logs. Podrán ayudarnos y brindarnos información sobre cuál estado tienen finalmente y si se llegaron a confirmar? O simplemente las coloco en Error...

https://adm.ebooking.com.ar/bookings/detail/60e7741bbe7e93b7783687b1?purchaseGroupId=357715#heading_60e7741bbe7e93b7783687b1

https://adm.ebooking.com.ar/bookings/detail/60e772edbe7e93b7782d438a?purchaseGroupId=357715#heading_60e772edbe7e93b7782d438a

https://adm.ebooking.com.ar/bookings/detail/60e76c1cbe7e93b778f6ce86?purchaseGroupId=357712#heading_60e76c1cbe7e93b778f6ce86

Muchas gracias !

**Comment by julianbenegaslane** [comment]
Hola Guada, ninguna de las 3 se llego a confirmar, debido a un error en el paso de checkout.
Gracias por el aviso.
