### ISSUE TITLE
Cambiar teléfonos publicados en home del sitio web

### ISSUE THREAD

**Issue by sebamkt** [toselli/issues#130]
### Descripcion del error

Necesitamos corregir la información publicada sobre los teléfonos de emergencia. 
Están publicados los números de cabecera de cada sucursal, cuando solamente debieran figurar solo 3 números que te paso a continuación: 

**0351 152751584
0261 156162045
0341 155805484**

Corregir esta es super importante porque aquellas agencias con pasajeros con inconvenientes necesitan contactarse por fuera del horario y el número fijo de cada sucursal no debería estar publicado. Por favor, deberían estar los 3 números de arriba indicados. Me avisas cuando hayan podido ajustar esto? Gracias! Si hay alguna manera en que yo pueda cambiarlos, cualquier cosa me avisas y lo veo yo. 

Los números de emergencia es posible verlos en el lateral inferior derecho (Cuando estás logueado con un usuario respectivo). Si no estás logueado con usuario y contraseña no deberían mostrarse ningún número.  

![image](https://user-images.githubusercontent.com/46228590/135159344-46f1794a-162b-4897-9ea9-08dfe9551d0a.png)

### Paso a paso para reproducir el error

Directamente desde el home cuando estás logueado con usuario y contraseña. Si no estás logueado no deberían mostrarse estos números.

### Captura del error

![image](https://user-images.githubusercontent.com/46228590/135159428-d2b77b86-5a39-4acc-bc28-473f081291db.png)

### Link al error y/o Localizador

https://www.juantoselli.com/#/

### Plataforma

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

**Comment by sebamkt** [comment]
Buen día chicos! Alguna novedad respecto a esto?

**Comment by gabrielmarinsaldaJT** [comment]
Hola @sebamkt cómo estás?

Estamos trabajando en ello, tenenos un poco de paciencia porque no sabemos bien de donde podemos modificarlo asique estamos investigando el caso

Saludos!

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado Seba, si no lo podés visualizar te pido que hagas un Ctrl+R

Saludos
