### ISSUE TITLE
Avis/Budget - Plan recomendado no es el correcto

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#131]
### Descripcion del error

El plan que figura como Recomendado (See Europe) es uno del que se debe pagar suplemento en destino
Deberia ser el Super See Europ All Inclusive, el cual tiene todo lo obligatorio para circular

### Paso a paso para reproducir el error

para Budget sucede lo mismo (y son los mismos planes), solo que en este caso pedi una ofinina puntual que es de avis, por eso no me dio alternativa de budget para que les pase captura. 
Es la segunda vez que veo esto, ayer me paso lo mismo con Budget. 

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/135298795-d08176de-206d-4505-ac74-e13feb717537.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/autos/buscar?pickUpDate=2021-10-16&pickUpTime=18:30&pickUpOfficeId=MXP&pickUpCityId=5a21b159fc2d560873053fea&pickUpCityName=milan-y-sus-alrededores-lombardia-italia&returnDate=2021-10-21&returnTime=17:00&returnOfficeId=ML5&returnCityId=5a21b159fc2d560873053fea&returnCityName=milan-y-sus-alrededores-lombardia-italia&nationality=AR&residence=AR&currency=USD

**Comment by natisalino** [comment]
tambien veo que no esta tirando (para esta misma busqueda) alternativas en la tarifa Super See Europ All Inclusive y en la web de la compañia sí.

**Comment by gabrielmarinsaldaJT** [comment]
Parece ser que esa tarifa no aplica para esas oficinas según lo que entiendo

Serías tan amable de pasame algún link a la página de Avis con los resultados que nos indicas?

Saludos

**Comment by natisalino** [comment]
Hola Gabi! 
No puede ser, porque si lo busco por la compañia sí me lo dà con ese plan. Además, la busqueda siempre tiene que arrojarte resultado de los mismos vehículos con los dos planes. Si te arroja con uno, deberia por defecto darte con los dos planes. 
te paso captura de la compañia donde pongo esas ciudades y fechas y me da los dos planes: 

![image](https://user-images.githubusercontent.com/88200755/136078066-c1bbf9d7-f07f-484f-8a39-c10c1ca15bdc.png)

Avisame lo que necesites de mi parte
Saludos!
Nati

**Comment by natisalino** [comment]
Envio una captura mas grande asi podes ver los parametros de busqueda: 
![image](https://user-images.githubusercontent.com/88200755/136078315-92c05020-de7b-49de-9f0b-6a9fc956ef6c.png)

**Comment by gabrielmarinsaldaJT** [comment]
Buenas tardes.

Han podido ver algo de esto?

Sigo sin recibir respuesta del proveedor a pesar de haberle insistido muchas veces

De no poder continuar con esto, podemos cerrar la issue?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Cerramos issue por falta de resp del provider
