### ISSUE TITLE
[GoGlobal] Modificacion.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#132]
### Descripcion del error

Estimados solícito me puedan ayudar modificando las siguientes reservas.

Reserva 1 (LOC 18628695) - Reserva Cancelada modificada, no utilizada, quitar estado de cobro a No Cobrada. La reserva fue utilizada bajo otro loc traído por JtMock.

Reserva 2 (LOC 18635460)- Reserva utilizada. Cambiar estado de cobro a Cobrada y colocar Voucher F920449 de la anteriormente mencionada. Intentamos colocar los datos del Hotel en la reserva y rompió. 

### Paso a paso para reproducir el error

1- Buscar reservas 
2- Modificar datos solicitados.

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/135301438-4fcd2d19-e4aa-4dfa-80df-ab91a795f8e7.png)
![image](https://user-images.githubusercontent.com/45457355/135301507-9ae0f421-4963-4cf7-a9e6-bdb871c9c6dd.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/60414dc145c76b1527e41c84?purchaseGroupId=349800#heading_60414dc145c76b1527e41c84 https://adm.ebooking.com.ar/bookings/detail/6049b92c65adf06b9219bbc0?purchaseGroupId=350830

**Comment by josecaserez** [comment]
Se acaba de corregir la reserva LOC 18635460 (https://adm.ebooking.com.ar/bookings/detail/6049b92c65adf06b9219bbc0?purchaseGroupId=350830). Por favor intentar modificar el estado de cobrado y el voucher.

**Comment by Jlavign** [comment]
Muchas gracias Jose
