### ISSUE TITLE
Búsquedas sin resultados

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#135]
### Descripcion del error

Al realizar búsquedas de hoteles aleatorios, no se despliega ningún resultado. 

### Paso a paso para reproducir el error

1. Entrar a Ebooking
2. Pestaña Alojamiento
3. Replicar links de búsqueda adjuntados. Adjunto otro link más: https://ebooking.com.ar/#/alojamiento/disponibilidad/5d006e104e80e0a53e58cacf/mendoza-suites-mendoza--argentina?checkIn=2021-10-07&checkOut=2021-10-10&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Captura del error

![image](https://user-images.githubusercontent.com/40358708/135621833-717309f3-02e6-4017-84f4-c34fa68e75b8.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca8d58d86315a56f0c42d40/hotel-cordoba-villa-carlos-paz--argentina?checkIn=2021-10-07&checkOut=2021-10-10&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Hola Abraham!

Esta issue desemboca en el mismo error que tenemos en otra issue (La issue #129 ) apenas la tengamos resuelta te avisaremos con esa

Cierro esta para evitar duplicidad

Saludos!
