### ISSUE TITLE
[VIATOR] Modificación de voucher

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#137]
### Descripcion del error

Solicito me puedan ayudar modificando el voucher de los siguientes pasajeros.
BR-832030766 y BR-831978108
Ambos tienen en su voucher JUAN TOSELLI como pasajero en vez de su pax lider.

### Paso a paso para reproducir el error

1- Buscar reservas en ADM
2- Visualizar Voucher

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/135680939-7131e95b-53d7-4db7-bc76-f879ec053dd0.png)
![image](https://user-images.githubusercontent.com/45457355/135680999-b40022a1-8681-4fd5-981e-096a689e9c67.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61549b8afd72f57d03d688b2?purchaseGroupId=361435#heading_61549b8afd72f57d03d688b2 https://adm.ebooking.com.ar/bookings/detail/61546597fd72f57d03ce36ff?purchaseGroupId=361435#heading_61546597fd72f57d03ce36ff

**Comment by gabrielmarinsaldaJT** [comment]
Hola @Jlavign cómo estás?

Voy a cerrar esta issue ya que no veo que sea un error de sistemas

Al principio pensé que lo era, pero revisando un poco veo que los Voucher que generamos desde el ADM redirigen a la página de Viator. Por lo que les aconsejo que le escriban al proveedor consultándole sobre el caso

Saludos!

**Comment by gabrielmarinsaldaJT** [comment]
Hola @Jlavign cómo estás?

Voy a cerrar esta issue ya que no veo que sea un error de sistemas

Al principio pensé que lo era, pero revisando un poco veo que los Voucher que generamos desde el ADM redirigen a la página de Viator. Por lo que les aconsejo que le escriban al proveedor consultándole sobre el caso

Saludos!
