### ISSUE TITLE
[ENTERPRISE] ERROR VOUCHER

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#138]
### Descripcion del error

Estimados buenas tardes,
Fernando indica que en voucher de reserva 1331702331COUNT no aparecen datos de Lugar de Alquiler y Lugar de Devolución

### Paso a paso para reproducir el error

1- Buscar reserva 1331702331COUNT 
2- Visualizar voucher

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/135681960-9774e70b-366c-4010-b254-007faa4f6ba0.png)
![image](https://user-images.githubusercontent.com/45457355/135682028-d941b367-9cef-4735-bf79-4c8a6917c318.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/614b3680a143b5eaa2502926?purchaseGroupId=360876#heading_614b3680a143b5eaa2502926

**Comment by gabrielmarinsaldaJT** [comment]
Listo chicos, solucionado
