### ISSUE TITLE
No dispo Avis/Budget

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#139]
### Descripcion del error

Buenas tardes
No hay dispo con las rentadoras Avis y Budget para las fechas 24/04/2022 al 04/05/2022
En la oficina de Miami particularmente
Podrían revisarlo?
Directamente en su web SI hay dispo en esas fechas, verificado en https://carrental-int.com/avis/res/availability.php

### Paso a paso para reproducir el error

Buscar en Vehiculos
Ciudad de retiro: Miami y sus Alrededores
Oficina de retiro: MIA Miami Intl Airport
Fecha recogida: 24/04/2022 Hora: 12.30p,m.
Fecha de devolución: 04/05/2022 Hora: 10.00 am

### Captura del error

![image](https://user-images.githubusercontent.com/88336164/135903565-fb650c1a-d479-4ba5-bd5c-7d7757bf23f9.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2022-04-24&pickUpTime=12:30&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida-estados-unidos&returnDate=2022-05-04&returnTime=10:00&nationality=AR&residence=AR&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Hemos revisado este caso y es idéntico a muchos otros que tenemos

Estamos insistiéndole al proveedor pero no hay novedades

Cierro por duplicidad

Saludos!
