### ISSUE TITLE
Web Corradi Viajes

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#140]
### Descripcion del error

Desde la agencia nos envían esta petición acerca de su web https://corradi.tur.ar/#/

Podrían ayudarnos?
Adjunto print

![image](https://user-images.githubusercontent.com/88336164/136048338-46e82707-1039-4aa0-91ec-1f78c3bb8b25.png)

### Paso a paso para reproducir el error

a

### Link al error y/o Localizador

https://corradi.tur.ar/#/

**Comment by abrahamfariaz** [comment]
Buenos días Julian,
¿Tenés alguna novedad?
Gracias!

**Comment by agostinaf25** [comment]
Alguna novedad de esto?
Graciass

**Comment by abrahamfariaz** [comment]
Según reviso en la web de corradi, está solucionado
