### ISSUE TITLE
[EXPEDIA] ERROR COSTO CON PROVEEDOR.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#148]
### Descripcion del error

Estimados buenas tardes,
Solícito me puedan ayudar verificando si está sucediendo algún inconveniente con el operador Expedia en sus costos.
Me enviaron 3 casos de reservas donde el Operador nos pasa un valor mayor al que poseemos.

### Paso a paso para reproducir el error

1- Buscar reservas en ADM
2- Verificar con voyager (expedia)

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/136278466-8a09b416-a701-48d9-b208-91223ab49a9c.png)
![image](https://user-images.githubusercontent.com/45457355/136278515-b5f65923-6109-4acd-b01d-33da8095dc86.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/60d354ee7714a80c417776ad?purchaseGroupId=356965#heading_60d354ee7714a80c417776ad https://adm.ebooking.com.ar/bookings/detail/607029c1e945dd3126881b4e?purchaseGroupId=352918#heading_607029c1e945dd3126881b4e https://adm.ebooking.com.ar/bookings/detail/60d354ed7714a80c417750d1?purchaseGroupId=356965#heading_60d354ed7714a80c417750d1

**Comment by abrahamfariaz** [comment]
Estimados buenas tardes,
¿Alguna novedad?
Gracias!

**Comment by Jlavign** [comment]
Estimados buenas tardes,
¿Alguna novedad?

**Comment by Jlavign** [comment]
Estimados buenos días,
Tendrán novedades?

**Comment by Jlavign** [comment]
Estimados buenas tardes,
¿Alguna novedad? Necesitamos brindar respuesta.

**Comment by Jlavign** [comment]
Estimados buenas tardes,
¿Alguna novedad? Necesitamos brindar respuesta.
El caso tiene varios meses ya.

**Comment by abrahamfariaz** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by GuadaVivas** [comment]
Se cierra issue no hay logs.
