### ISSUE TITLE
LOCALIZADOR  9191745892974 MODIFICACIÓN

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#15]
Estimados buenas tardes,
Me pueden ayudar con la modificación solicitada?

![image](https://user-images.githubusercontent.com/45457355/125515510-f7c402a5-b3c6-430a-9533-0df30aa3c3ad.png)

**Comment by moliveto** [comment]
Por ampliar explicacion

**Comment by moliveto** [comment]
entiendo que:
pero es por que Expedia todavia no lo hizo en su sistema 

cuando Expedia lo refleje en su sitio hay que actualizar de nuestro lado sync
