### ISSUE TITLE
Diferencia gross profit Expedia

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#154]
### Descripcion del error

Genero issue de un caso que comencé con Marcelo el 13/08.
Se han detectado diferencias en el gross profit entre Expedia y Juan Toselli. Expedia me explicó en una Meet que ellos calculan el 55% del Marketing Fee.
Para puntualizar, en la planilla que adjunto, tomemos el caso de la fila 2 en el cual el monto de FEE es de 7.26 USD y el 55% es 4.21 USD y nosotros obtenemos desde el administrador 4.96 USD. 
Existen diferencias más grotescas si visualizan la planilla, por tanto, me gustaría saber si hay algo que podamos hacer para disminuir las diferencias. Intuyo que tal vez la diferencia parte del FEE y no del porcentaje del 55%, pero desconozco los montos acordados con Expedia.

### Paso a paso para reproducir el error

1. Abrir la planilla adjunta
2. Buscar la fila de ejemplo 2

### Link al error y/o Localizador

X

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad con el caso? Se van acumulando las diferencias mensuales para reclamarle al proveedor. 
Gracias!

**Comment by abrahamfariaz** [comment]
Estimados buenas tardes,
¿Alguna novedad?
Gracias!

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad? 
Se siguen acumulando mes a mes las diferencias entre Expedia y Toselli, ocasionando diferencias

**Comment by abrahamfariaz** [comment]
Buenos días ¿Cuál es la solución brindada?
Gracias!

**Comment by abrahamfariaz** [comment]
Buenas tardes
¿Han podido ver mi comentario anterior?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna actualización de este caso?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Done

**Comment by abrahamfariaz** [comment]
Gabi, esto quiere decir que fue arreglado el origen de la diferencia y lo que extraiga desde la parte de reportes en el administrador va a estar ok?

**Comment by abrahamfariaz** [comment]
Buenas tardes @gabrielmarinsaldaJT 
¿Has podido visualizar mi comentario anterior?
Gracias!

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad de mi pregunta?
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Las diferencias del grossprofit de expedia son porque a veces calcula un aproximado al 55%, por lo que nunca va a dar igual o lo hará en raras ocasiones

Desde nuestro lado no podemos hacer nada

Saludos!
