### ISSUE TITLE
W41KM8 RESERVA EN ESTADO DE ERROR

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#16]
Estimados buenas tardes,
Nos están solicitando el pago por la siguiente reserva LOC W41KM8 la cual esta en estado de error, pero al consultar con Itaparica nos informan que la misma esta confirmada y con gastos,

Adjunto url de reserva:
https://adm.ebooking.com.ar/bookings/detail/5fa041438d09ff68c4811bba?purchaseGroupId=340469#heading_5fa041438d09ff68c4811bba

**Comment by gabrielmarinsaldaJT** [comment]
Mail enviado al proveedor, es un error de Login

**Comment by gabrielmarinsaldaJT** [comment]
Itaparica nos cambió el Usuario

Las nuevas credenciales ya están en Slack asique no hay mas nada que hacer mas que esperar a que se refresque el sistema de Juniper y las credenciales estén OK

**Comment by Jlavign** [comment]
Estimados, buenos días,
Entiendo eso, así mismo me sigue generando confusión, 
Es error del operador o nuestro?
Debemos abonar la reserva? debo indicar a pagos
