### ISSUE TITLE
Mostrar vencimiento Toselli en check out

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#167]
### Idea a implementar

Estimados
A raíz de la issue #161 la sugerencia radica en colocar en el check out, el vencimiento asignado por nosotros, en base a la condición del proveedor (prepago, postpago, etc). 
Esto a fin de evitar inconvenientes y confusiones al respecto; y la generación de reservas no reembolsables en vano

Quedo atenta
Gracias desde ya

**Comment by gabrielmarinsaldaJT** [comment]
Done it!

**Comment by agostinaf25** [comment]
Estimado que buena noticia!!!
Agradecida desde ya y excelente felicitado 😸
