### ISSUE TITLE
Reserva Europamundo, costo en 0

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#17]
Hola chicos! cómo están?

Tenemos la siguiente reserva: 

https://adm.ebooking.com.ar/bookings/detail/608b0932ad416057aed8cf4e?purchaseGroupId=353875#heading_608b0932ad416057aed8cf4e

Nati Salino indica que la reserva en el proveedor esta confirmada OK, nosotros la tenemos en 0 confirmada pero veo que en un log tiene un Error 500.
A su vez le consulté a la vendedora el costo que debería figurar en la reserva : 

"El costo de la reserva, para que controles: €UR 2166.40
La venta al publico es de: €UR 2708.00"

Podrán indicarme si, efectivamente está confirmada y si en el  costo coloco €UR 2166.40 y tildo inactualizable?

Muchas gracias!

**Comment by IvanFacundoRosas** [comment]
Está confirmada en Europamundo. El costo es €2166.40 y la venta es €2708.00

Proceda a colocar el costo en €2166.40 y tildar como inactualizable.

**Comment by IvanFacundoRosas** [comment]
https://github.com/toselli/eBookingV4/issues/6250
