### ISSUE TITLE
[NEXUS] RESERVA NO EXISTE EN ADM

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#170]
### Descripcion del error

Estimados buenas tardes,
Solícito me puedan ayudar, ya que Operador nos solicita pago por una reserva que no está en adm y ellos la tiene con todos los datos desde la suya.

### Paso a paso para reproducir el error

1- Buscar reserva 6F1Z5N 
2- Verificar los datos que adjunto

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/137554504-2e623026-452c-4150-8c84-7f6e8f64ebb7.png)
![image](https://user-images.githubusercontent.com/45457355/137554540-4e65215f-adcb-4649-a922-fa9a1abf3ce7.png)
![image](https://user-images.githubusercontent.com/45457355/137554582-9544e273-7be0-4225-97d5-ea4176fc586b.png)
![image](https://user-images.githubusercontent.com/45457355/137554631-b7a25738-d4dc-4237-a55a-53b1dc9d2abc.png)

### Link al error y/o Localizador

Nohay

**Comment by gabrielmarinsaldaJT** [comment]
Estimados, cómo va?

Les recomiendo escribirle al proveedor para consultar por la dispo. Desde la integración podemos ver que no recibimos disponibilidad y no hemos cambiado nada desde nuestro lado
