### ISSUE TITLE
Reserva Expedia 9187571411726 costo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#18]
Buenas tardes!

Tenemos la reserva: 

https://adm.ebooking.com.ar/bookings/detail/60bc249905132d42e4ee97ee?purchaseGroupId=355663#heading_60bc249905132d42e4ee97ee

Encontramos una discrepancia en el costo del adm con el que debería figurar en el book. Pero vemos que en el mail de confirmación el total comisionable es correcto.
No obstante el vendedor plantea que el costo debería ser el siguiente: 

![image](https://user-images.githubusercontent.com/87333634/125526448-dab3cb61-d4ae-4076-a275-36f310b0479f.png)

Podrán brindarnos mayor información ? Por qué el vendedor reclama ese mismo?
Muchas gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Nuevo caso de optimización y el proveedor es Expedia

Sugiero que vean issues anteriores para verificar

**Comment by GuadaVivas** [comment]
Gabi,
Podrás pasarme el link de la issue anterior?  Ya que aun no logro cerrar el caso

**Comment by gabrielmarinsaldaJT** [comment]
Guada, no tengo el link

Lo habiamos hablado hace unos días

Dame un rato porque tengo que retomarlo ahora, apenas tenga novedades te aviso

**Comment by GuadaVivas** [comment]
Hoila chicos, cierro el caso, se le aviso al vendedor que el costo correcto es 1237.24
