### ISSUE TITLE
Listado de agencias en Peru

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#188]
### Descripcion del error

Andres Baraldi solicita un listado de las agencias en Peru para establecerles un extra Markup del 2%, y nosotros no podemos extraer ese listado desde el administrador ni en Mongo.
¿Pueden ayudarnos con esta solicitud? 
Gracias!
Abraham

### Paso a paso para reproducir el error

X

### Link al error y/o Localizador

x

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Estamos revisando esto

La verdad, ninguna agencia tiene un Código de país, por lo que está complicado buscarla por ese parámetro

Serían tan amable de pasarme un ejemplo de una agencia de Perú? Necesito ver si tienen algún dato clave para buscarlas en el Mongo

**Comment by abrahamfariaz** [comment]
Hola Gabi!
Si claro, te paso el ID de una agencia del Peru: 60884989477e30f199f60dd6
Quedo atento!

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, lamentablemente no tenemos manera de diferenciar las agencias de Perú de cualquier otra

Si tienen una lista de agencias de Perú, recomiendo que las busquen una por una
