### ISSUE TITLE
Búsqueda

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#19]
Estimados buenas tardes, 
Adjunto solicitud de Pablo negro:

Podrán verificar que en estos dos links es la misma búsqueda, pero la primera es con un menor de 9 años y al segunda sin el menor. Y no sale la misma habitación.

Búsqueda con el menor

https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca902c986315a56f0cd3db0/hotel-xcaret-mexico?checkIn=2021-10-09&checkOut=2021-10-14&nationality=CO&residence=CO&occupancies=2*30,30*1*9&currency=USD

Y esta es la búsqueda sin el menor

https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca902c986315a56f0cd3db0/hotel-xcaret-mexico?checkIn=2021-10-09&checkOut=2021-10-14&nationality=CO&residence=CO&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Juampi

Obvio que es diferente la habitacion, en una hay 3 pasajeros y en otra hay 2

Cuál es el problema?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Novedades?

Puedo cerrar esta issue?

**Comment by Jlavign** [comment]
Gaby buenas tardes,
Sisi ya le indique a vendedor, cerra isue, muchas grax
