### ISSUE TITLE
[Sixt] Mal calculo de precio de venta

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#191]
### Descripcion del error

Estimados
Estoy cotizando un auto con Sixt, en el momento del avail me muestra una tarifa X + impuestos, pero cuando paso al check out esto cambia.
Visualizo una discrepancia en algun monto que la rentadora suma pero no esta mostrandonos y que el precio de venta no es el correcto en la pestaña detalle compra.
Adjunto prints y procedimiento.

### Paso a paso para reproducir el error

https://www.juantoselli.com/#/autos/buscar?pickUpDate=2021-10-27&pickUpTime=14:00&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2021-11-12&returnTime=00:00&nationality=AR&residence=AR&currency=USD

Filtrar por Sixt
Auto: Toyota RAV4 o similar
Producto: SX9768334

En avail la tarifa es USD 738.56 + USD 82.44 de impuestos

Al avanzar al check out, selecciono una agencia para que me muestre correctamente la comisión
**Precio de venta**: USD 738.56
Impuestos: USD 60.68
Iva: USD 9.47
Gastos: 8.18 
**Neto a pagar**: USD 834.43

El neto es más caro que el precio de venta que figura en el detalle, ese ítem esta mal ya que el pvp es de usd945

Podriamos chequearlo?
Adjunto prints.

### Captura del error

Avail
![image](https://user-images.githubusercontent.com/88336164/138772930-442376a3-f6d0-45e8-87fe-e18dd63d7f5d.png)

Check out
![image](https://user-images.githubusercontent.com/88336164/138877365-9334586b-c05a-4649-9519-0d2aca4b8c5a.png)

### Link al error y/o Localizador

https://www.juantoselli.com/#/autos/buscar?pickUpDate=2021-10-27&pickUpTime=14:00&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2021-11-12&returnTime=00:00&nationality=AR&residence=AR&currency=USD

**Comment by abrahamfariaz** [comment]
Estimados buenas tardes,
¿Alguna novedad?
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Abraham, cómo estás?

Estamos viéndolo, apenas tengamos novedades te avisamos

Saludos

**Comment by agostinaf25** [comment]
Hola chicos
Tenemos algun avance respecto a esto?
Quedo atenta
GraciaS!!!

**Comment by gabrielmarinsaldaJT** [comment]
Chicos

Perdón que no cerré esta issue

Estaba duplicada con otra y ya está solucionado

Saludos!
