### ISSUE TITLE
Tour de Europanundo no aparece en la busqueda en Ebooking

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#194]
### Descripcion del error

Hay dos tours con nombres similares
Toda Europa +i id19826 (este si figura en la busqueda) -
Toda Europa Turista -id19870 (este no figura en la busqueda ni por nombre ni por id) 

### Paso a paso para reproducir el error

busqueda por nombre del tour en la pestaña de circuitos

Link del proveedor donde si figuran los tours: 
https://www.europamundo.com/itinerarios_general.aspx?nombre=TODA%20EUROPA&head=s

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/138938987-caf2933a-6d49-4e2d-9962-3b288c61643e.png)
 
![image](https://user-images.githubusercontent.com/88200755/138939060-415c83e4-11a9-4b54-aa29-bfcb086bb019.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/circuitos/buscar?cities=&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=Toda%20europa&nationality=AR&residence=AR&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Asigno a @IvanFacundoRosas 

Asumo que tenés que mapear el Tour o agregarlo a la DB

Si necesitás ayuda para subirlo a Live, no dudes en avisarme
