### ISSUE TITLE
[ITAPARICA] RESERVA AGOTADA CONFIRMADA EN OPERADOR.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#196]
### Descripcion del error

Se quiere cobrar reserva en estado Agotado.
Desde Operador Itaparica se ve reserva confirmada.

Se procedió a cancelar reserva, ya que estaba en tiempo. Aun así el problema es que no registro LOC ni se encontraba confirmada.

### Paso a paso para reproducir el error

1- Buscar reserva
2- Chequear porque surgi este inconveniente.

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/139148760-0c076662-98fb-4ff5-b6a7-6dcd2dad3856.png)
![image](https://user-images.githubusercontent.com/45457355/139148787-4c74d7be-1fa2-4d2e-a37f-8cef28636ecf.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6012b903c8ad924244007d98?purchaseGroupId=346761#heading_6012b903c8ad924244007d98

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Envíenle los logs de cancelación ya que se canceló en tiempo y forma

![image.png](https://images.zenhubusercontent.com/6154b05d87ee2058afd73e2b/951966dd-2812-41d5-a0b8-574e4b210d81)

Les paso un link para facilitarles los datos:

[Links cancelación](https://adm.ebooking.com.ar/serviceLogs/edit/6179c10e3e6c092f2db17818)
