### ISSUE TITLE
[SISTAGEN] Error al modificar cotizacion.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#199]
### Descripcion del error

Estimados buenas tardes,
Estamos teniendo inconvenientes al intentar modificar la cotización desde SQL al SIST. No se está reflejando.

### Paso a paso para reproducir el error

Buscar cotización en sql y luego buscar book en SIST. Verificar que no se realizó cambio.

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/139336756-f8165764-b568-4b37-916f-c514a1fbf8eb.png)
![image](https://user-images.githubusercontent.com/45457355/139336819-93180f09-58d7-4cc0-8ca7-ce78e609bfc4.png)
![image](https://user-images.githubusercontent.com/45457355/139336906-0ad00281-f50b-4cc8-b841-dc086641d856.png)

### Link al error y/o Localizador

nohay

**Comment by abrahamfariaz** [comment]
Estimados buenas tardes,
¿Alguna novedad?
Gracias!

**Comment by Jlavign** [comment]
Estimados buenos días,
Tendrán novedades?

**Comment by Jlavign** [comment]
Estimados buenas tardes,
Tendrán novedades sobre este pedido?

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, lamentablemente no tenemos manera de replicar esto ni sabemos de que forma solucionarlo

Sugiero contactar a Guillermo Toselli para ver si podemos darle una solución mediante el SistAgem

Asigno a @djguille a esta issue

**Comment by Jlavign** [comment]
Estimados buenas tardes,
¿Tendrán alguna novedad?

**Comment by djguille** [comment]
Hola a todos
El problema se da porque estos tickets se emitieron en USD. El sistema no está preparado para eso.
Por lo tanto, en la parte de la izquierda, el tipo de cambio es 1 y no 79,75 o 77,50 como figura en el book.
Entonces lo que hay que hacer es volver a 1 la cotización de ambos tickets.
Este tema deberíamos verlo con 'Administracion para ver qué solución se le da  a estos tickets.
Saludos.
