### ISSUE TITLE
Reservas Sabre Juan Toselli en Revisar

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#20]
Chico buenos días,

Tenemos estas reservas de Sabre en revisar:

https://adm.ebooking.com.ar/bookings/detail/60df1aee5130f1772565f0f0

https://adm.ebooking.com.ar/bookings/detail/60cf52c1991136b81290d0e7?purchaseGroupId=356804#heading_60cf52c1991136b81290d0e7

https://adm.ebooking.com.ar/bookings/detail/60cf51fa991136b81290763f?purchaseGroupId=356804#heading_60cf51fa991136b81290763f

https://adm.ebooking.com.ar/bookings/detail/60cf50bb991136b812904f31?purchaseGroupId=356804#heading_60cf50bb991136b812904f31

https://adm.ebooking.com.ar/bookings/detail/60cf503e991136b812903f3d

https://adm.ebooking.com.ar/bookings/detail/60b68610246f74f18e39cda1

Podrán indicarme si debo pasarlas a Error o hacer otro tipo de gestión?
Gracias.

**Comment by gabrielmarinsaldaJT** [comment]
Hola a todos

Si, pueden ponerlas en error

Saludos
