### ISSUE TITLE
[HOTELBEDS] 290-402427 LOGS CANCELACION

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#200]
### Descripcion del error

Estimados buenas tardes,
Solícito me puedan ayudar adjuntando los LOGS que indiquen que esta reserva esta cancelada. Para presentar a Operador evidencia del mismo.

### Paso a paso para reproducir el error

1- Buscar reserva

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/139492985-28d528be-b353-4fd8-a6f0-158277374baa.png)
![image](https://user-images.githubusercontent.com/45457355/139493087-af3f0403-dd8e-4b78-a7bf-e1021f70e669.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/5e68404dd9fee30333c589dd?purchaseGroupId=306634#heading_5e68404dd9fee30333c589dd

**Comment by Jlavign** [comment]
Estimados buenas tardes.
¿Tendrán novedades?

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Estuvimos revisando con el equipo y los logs anteriores al 01/09/2020 ya no existen.
Fueron borrados por el jefe de sistemas que ya no trabaja mas en la empresa

Saludos
