### ISSUE TITLE
[MOZIO] LOGS de Checkout

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#204]
### Descripcion del error

Hola, Equipo.

Solicitamos por favor logs del checkout de la reserva LOC ad7cb15a4c1c420e8bc8a849adbaaf03 de mozio con número de confirmación MOZ2687671
Nos solicitan un pago por un monto menor al que tenemos plasmado y para modificarlo queremos asegurarnos de eso.

Gracias, desde ya.

### Paso a paso para reproducir el error

--

### Captura del error

--

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6123fd6f481ac046889513ad?purchaseGroupId=359081#heading_6123fd6f481ac046889513ad

### Plataforma

Google Chroome

**Comment by abrahamfariaz** [comment]
Estimados buenas tardes,
¿Alguna novedad?
Gracias!

**Comment by GuadaVivas** [comment]
Hoila chicos alguna novedad?

**Comment by JuanBachmann** [comment]
Estimados,

¿Nos pueden ofrecer alguna novedad?

Gracias

**Comment by josecaserez** [comment]
Lamentablemente no existen esos logs. NO hay registros de logs anteriores al 01-09-2020 y lo que están entre 10-06-2021 hasta el 20-10-2021. De tener reserva que necesiten el log de las fechas mencionadas van a tener que ir al sistema del proveedor directamente.
