### ISSUE TITLE
[Ebooking] Users check out

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#206]
### Idea a implementar

Consulta chicos, 
Hay forma de saber/conocer los usuarios que llegan al check out y abandonan la compra?

Gracias
Quedo atenta
Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Vamos a poner esta issue como una Épica

Con esto vamos a tener esta **idea a implementar** dentro de nuestro Backlog y la tendremos en cuenta para los siguientes Sprints

Consulta, necesitás que sea un reporte? O lo necesitás para saber algo en especial?

**Comment by agostinaf25** [comment]
Gabi

Particularmente para tomar acción respecto de los usuarios que hacen esto, por ejemplo enviarles email martketing o indagar por qué abandonan la compra antes de finalizarla. 
Sería muy bueno, de hecho, poder visualizar el comportamiento íntegro de los usuarios: Cuántos de quienes se loguean avanzan, realizan compras o en qué instancia de la compra la abandonan; cuáles son los servicios más buscados; si utilizan todas las herramientas que brinda la web o no: por ejemplo filtros, mapa, descripciones, etc.
Esto nos va a permitir tener un feedback ademas, de cuán amigable está siendo la página para el usuario. Me explico?

Es algo mas integral, pero serviría para los fines comerciales, respondiendo a tu pregunta :)

**Comment by abrahamfariaz** [comment]
Buenos días, ¿En qué concluyo esta propuesta? 
Gracias

**Comment by abrahamfariaz** [comment]
Buenos días, 
Aguardo novedades
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Chicos

En su tiempo se le explicó a Agostina que era imposible de realizar

Por eso se cerró

Saludos
