### ISSUE TITLE
[Adm.ebooking] Migrar usuario

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#207]
### Descripcion del error

Buenas tardes
Necesito migrar el usuario baronibaroni@hotmail.com (id: 611aaea8800aa533581c3102) a la agencia Relatos D'Viajes (ID: 5ac5266de36b4e023c9048e6)
Nose en qué agencia esta actualmente este usuario, ya que desde el administrador no me reconoce el Id en el que la agencia esta vinculado en la base de datos

Quedo atenta

### Paso a paso para reproducir el error

a

### Link al error y/o Localizador

a

**Comment by agostinaf25** [comment]
Buen dia!
Alguna novedad de esta solicitud?
Quedo atenta!
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!
