### ISSUE TITLE
[Hotelbeds] MODIFICAR VOUCHER CHECK IN 5/11

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#209]
### Descripcion del error

Hola Chicos,

Podrán modificarme el voucher por reubicación? Sólo tengo el nombre del Hotel y dirección. Entiendo que lo demás queda igual. La vendedora lo necesita para hoy, ya que el check in es para mañana 5/11

![image](https://user-images.githubusercontent.com/87333634/140316986-f99a1d43-ff91-4e3b-bf35-b1932546b4dd.png)

### Paso a paso para reproducir el error

n/a

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6137eb30ba11f1bc0837b05b?purchaseGroupId=360014#heading_6137eb30ba11f1bc0837b05b

**Comment by gabrielmarinsaldaJT** [comment]
Bueno, en nuestra defensa.. Hace 5 días estabamos asi ---> ‎️‍🔥

Pudiste solucionarlo? Lo necesitas todavia?

**Comment by GuadaVivas** [comment]
Hola! Al final no se uso! gracias. Cierro issue
