### ISSUE TITLE
Reserva Expedia en Revisar, Gastos de cancelación 14/07

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#21]
Chicos buens tardes,

Tenemos esta reserva de Expedia en revisar, en proveedor se encuentra confirmada, no esta cobrada y no se canceló. Podrán indicarme si el get cancel es correcto para reclamar? Ya cuenta con gastos de cancelación:

https://adm.ebooking.com.ar/bookings/detail/5fd8e434d76bae27cfa811d7?purchaseGroupId=344823#heading_5fd8e434d76bae27cfa811d7

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
La reserva ejecutó un cancel dos días antes de las políticas de cancelacion

El error que tiró es {"type":"room_id.invalid","message":"Room id is invalid."}

No vieron esta reserva antes? 
Recién ahora se puso en Status ToCheck?

Lo ideal sería escribirle al proveedor y pedirle la cancelación sin gastos y enviarle éstos logs:
https://adm.ebooking.com.ar/serviceLogs/edit/60ec6e216832fb4194a1d524

Aguardo su respuesta

Saludos

**Comment by GuadaVivas** [comment]
Excelente Gabi. Ya les había enviado correo como para ir adelantando, le adjunto los logs  que me indicas cuando me reclamen por evidencia.

**Comment by GuadaVivas** [comment]
Gabi,
Adjunto respuesta

![image](https://user-images.githubusercontent.com/87333634/125960550-333e1d0d-1ad5-48f8-9ee1-4bdf4319186f.png)

Por lo que entiendo no la han cancelado y nos pide que cancelemos nosotros. Pero si cancelo, me traeria gastos. 

Aguardo.

**Comment by gabrielmarinsaldaJT** [comment]
Hola Guada, cómo va?

En el mail se le planteó al proveedor que se intentó cancelar la reserva 2 días antes de que entrara en gastos y falló?

La idea de escribirle, era eso particularmente.
Que sepan que intentamos cancelar en tiempo y forma, pero falló. Además de explicarle que si cancelamos ahora vamos a tener costos que pagar

Saludos

**Comment by GuadaVivas** [comment]
Gabi buen dia,

Exacto, se le planteó. Ahora vuelvo a reclamar.

**Comment by GuadaVivas** [comment]
Gabi,

Listo, me cancelaron sin gastos.!
