### ISSUE TITLE
[HOTELBEDS] 290-402427 LOGS CANCEL

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#210]
### Descripcion del error

Estimados bueenas tardes,
Necesito los LOGS de cancelación de la reserva 290-402427 la cual indica Hotelbeds debemos abonar y no corresponde.

### Paso a paso para reproducir el error

1- Buscar reserva

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/140412468-cb2ccf38-b968-4cf1-8f2c-6cedacbc703d.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/5e68404dd9fee30333c589dd?purchaseGroupId=306634#heading_5e68404dd9fee30333c589dd

**Comment by abrahamfariaz** [comment]
Buenas tardes, 
Alguna novedad?
Gracias!
Saludos,
Abraham

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Estuvimos revisando con el equipo y los logs anteriores al 01/09/2020 ya no existen.
Fueron borrados por el jefe de sistemas que ya no trabaja mas en la empresa

Saludos
