### ISSUE TITLE
[CUPOS] Error de carga

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#211]
### Descripcion del error

equipo, buenos días.

Espero que estén bien.

 Al intentar cargar cupos en el adm de Ebooking, estoy detectando 2 errores que no me dejan continuar la carga:

El primero caso surge si yo cargo manualmente los segmentos y los valido:

(la imagen es solo a modo de ejemplo con un cupo del 2019)

El 2do caso, es que no me crea el book madre, (si al nuevo cupo le asignamos un book madre ya creado, si lo guarda al cupo):

### Paso a paso para reproducir el error

1- buscar área cupos

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/140527470-09a97e2e-9226-4170-912b-c56f3e4a6775.png)
![image](https://user-images.githubusercontent.com/45457355/140527486-2c93a16a-ae6d-4b09-b50b-7362201cca4d.png)
Caso 2
![image](https://user-images.githubusercontent.com/45457355/140527548-afbcbf31-0a9a-48a4-8496-b38f11a3215d.png)

### Link al error y/o Localizador

Nohay

**Comment by Jlavign** [comment]
Estimados buenos días,
Tendrán novedades?

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Ya hemos crado nuevas issues junto con el departamento de cupos para ver estos temas

Cierro issue para evitar duplicidad
