### ISSUE TITLE
[NEXUS] 6F1Z5N No aparece reserva

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#212]
### Descripcion del error

Estimados buenas tardes.
Solícito me puedan ayudar con la reserva loc 6F1Z5N la cual no aparece en ADM. La misma está siendo cobrada por Nexus y no podemos presentar información que nos respalde sin reserva en adm.

### Paso a paso para reproducir el error

1- buscar reserva 
2- verificar porque no muestra datos

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/140816868-e86bee2b-a574-47c9-b0e7-9788eddcf60d.png)
![image](https://user-images.githubusercontent.com/45457355/140816909-478ddac0-29d1-4d8e-8b6c-3f81950e19eb.png)
![image](https://user-images.githubusercontent.com/45457355/140816951-1cbb1e3f-71a5-414b-8c4e-81707c21a772.png)

### Link al error y/o Localizador

Nohay

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Dos cosas para ver con esta reserva

1- Revisen las credenciales de Nexus porque no están funcionando y no podemos revisar reservas

2- Revisen si esta reserva se hizo por la integración, porque no la vemos en nuestro sistema y al consultarla nos devuelve esto:

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<soap:Body>
		<ReadBookingResponse xmlns="http://www.juniper.es/webservice/2007/">
			<BookingRS Url="http://xml.nexustours.com" TimeStamp="2021-11-09T13:40:48.1745769+01:00" IntCode="AGn49Ox6m7z16CtZ3pPR0/SjjaKvT2Dk6KhB2UCR1do=">
				<Errors>
					<Error Text=" Your agency does not have permissions for this Reservation Locator." Code="JP_READ_INCORRECT_AGENCY" />
				</Errors>
			</BookingRS>
		</ReadBookingResponse>
	</soap:Body>
</soap:Envelope>
```

**Comment by gabrielmarinsaldaJT** [comment]
Cierro issue

**Comment by Jlavign** [comment]
Gaby buenos días,
Hemos podido actualizar los datos del usuario de Nexus.

Link: Travel Partner Portal
Usuario: Juan Toselli
contraseña: Nexus-2021

La estamos pudiendo encontrar en su plataforma y siguen los reclamos por parte de Nexus/Gaby de neuquen
![image](https://user-images.githubusercontent.com/45457355/142275239-8b595d10-36c5-4fd9-89a9-fd6c3f6e07d4.png)

**Comment by gabrielmarinsaldaJT** [comment]
La reserva fue realizada por fuera del eBooking

No tenemos nada que hacer
