### ISSUE TITLE
[GRN] LOGS de cancelación

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#215]
### Descripcion del error

Hola, Equipo.

Solicito por favor los logs de cancelación de la reserva con GRN Loc  i1Fx0E5VrL3P-i8- me la solicitan desde el área de pagos.
Aguardo respuesta.

Desde ya, gracias.

Saludos,
Juan Manuel

### Paso a paso para reproducir el error

Loc i1Fx0E5VrL3P-i8-

Nº de confirmación GRN-202106-383087

### Captura del error

--

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/60be94481435bd4d2346c962?purchaseGroupId=356007#heading_60be94481435bd4d2346c962

### Plataforma

Google Chroome

**Comment by Jlavign** [comment]
Estimados buenos días.
¿Tendrá novedades?

**Comment by JuanBachmann** [comment]
Estimados, buenas tardes

¿Alguna novedad?

**Comment by JuanBachmann** [comment]
Equipo.

GRN está solicitando el pago y desde nuestro área de pago nos solicitan los logs para poder negar el pago en el caso corresponda, nos piden una respuesta por favor, ya que pasó un tiempo considerado de espera.

Aguardamos nos puedan ayudar

**Comment by Jlavign** [comment]
Estimados, buenas tardes

¿Alguna novedad?

**Comment by JuanBachmann** [comment]
Estimados,

¿Nos pueden ofrecer alguna novedad?

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Estuvimos revisando con el equipo y los logs de reservas correspondientes entre las fechas 14/06/2021 al 20/10/2021 se perdieron con la última caída del servidor y posterior migrado de bases de datos

Saludos
