### ISSUE TITLE
[mapeo] Mapeo ciudad de Rio Grande - Ushuaia

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#216]
### Idea a implementar

Estimados
A raíz de una cotización, no pude encontrar mapeada la ciudad de Río Grande - Ushuaia en el buscador de alojamientos de Ebooking.
Podríamos agregarlo?

Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Done it!

Por favor, si no en la localidad, hacer un Ctrl+R

**Comment by agostinaf25** [comment]
Gabi, ¿cómo estás?
Gracias desde ya.
Consulta, cómo puede figurar? No logro encontrar esta ciudad como tal

**Comment by gabrielmarinsaldaJT** [comment]
Hola @agostinaf25 

Figura como Rio Grande, Tierra del Fuego, Argentina

Saludos!!
