### ISSUE TITLE
[MOZIO] Error al verifiar horario de voucher.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#217]
### Descripcion del error

Estimados buenas tardes,
Vendedor nos indica que reservas MOZ2867300 y MOZ2867298 cuentan con un error en HORA DE SALIDA DEL VUELO.
El cual no es el mismo que se indica al visualizar el voucher.

### Paso a paso para reproducir el error

1- Buscar reserva.
2- Verificar voucher.
3- Informar si esta correctamente como fue tomada.

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/141006528-f7d9923a-75c6-458b-a2d7-c6ded693e2cc.png)
![image](https://user-images.githubusercontent.com/45457355/141006575-3574331d-a229-4721-9f86-413af1d4030f.png)
![image](https://user-images.githubusercontent.com/45457355/141006636-5be40aba-3822-429b-9296-dac161759fe4.png)
![image](https://user-images.githubusercontent.com/45457355/141006709-79fe24b0-de05-43a6-9e08-fb016999dc34.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6169caa03c2eaec19620e87d?purchaseGroupId=361566#heading_6169caa03c2eaec19620e87d https://adm.ebooking.com.ar/bookings/detail/6169caa03c2eaec19620e81c?purchaseGroupId=361566#heading_6169caa03c2eaec19620e81c

**Comment by gabrielmarinsaldaJT** [comment]
Modificado

Podrían revisarlo por favor?

En este caso, **no** es necesario poner la reserva como inactualizable
