### ISSUE TITLE
VOUCHER ActionTravelSightseeing

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#22]
Estimados buenas tardes,
Vendedora me solicita la siguiente información, me podrían ayudar informando como proseguir?
Mucha gracias, 

Adjunto cadena y url de reserva.

![image](https://user-images.githubusercontent.com/45457355/125848976-00528e3d-e391-4da4-81fa-21e618dc1594.png)

https://adm.ebooking.com.ar/bookings/detail/60e499df49202d9ea04982f4?purchaseGroupId=357606#heading_60e499df49202d9ea04982f4

**Comment by Jlavign** [comment]
Estimados buenas tardes,
Tendrán novedades?

**Comment by julianbenegaslane** [comment]
Recibí respuesta de actiontravel:

> Todo lo que es tickets, reserva y emisiones, me podes contactar directo a esta dirección tickets@action.travel
