### ISSUE TITLE
[EXPEDIA] MODIFICACION DE RESERVA

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#220]
### Descripcion del error

Estimados buenas tardes,
Vendedora indica que reserva tiene desayuno.

**Solicito por favor agregar al voucher de este loc 9182590059462, que incluye desayuno.

Hable al hotel y me confirmo que si tiene.**

### Paso a paso para reproducir el error

1- Buscar reserva.
2- Modificar y agregar desayuno.

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/141522955-290c5ca0-d718-4d07-a1a6-9e06995e80e5.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/618bddf2cd3d65290174103a?purchaseGroupId=365862#heading_618bddf2cd3d65290174103a

**Comment by gabrielmarinsaldaJT** [comment]
Modificada

Ponerla como inactualizable por las dudas
