### ISSUE TITLE
[IBEROSTAR] QUITAR PAX

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#221]
### Descripcion del error

Estimados buenas tardes,
Necesito que me ayuden con una reserva la cual pasa de ser 4ple a 3ple.
Sobra un pasajero que esta duplicado.

### Paso a paso para reproducir el error

1- Buscar reserva

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/141842152-2ed30da2-23a0-4d16-8784-a658909d8680.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/60d4ee71e76e1fddc31bc74f?purchaseGroupId=357095#heading_60d4ee71e76e1fddc31bc74f

**Comment by gabrielmarinsaldaJT** [comment]
Buenos días

En el proveedor figuran 3 pasajeros?

**Comment by Jlavign** [comment]
En el proveedor han sacado un pasajero por pedido de la vendedora.

**Comment by gabrielmarinsaldaJT** [comment]
Listo

Verificar que todo esté OK y les recomiendo poner la reserva como inactualizable
