### ISSUE TITLE
[ALOJAMIENTOS] Error al sincronizar el voucher

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#222]
### Descripcion del error

Hola, Equipo.

El ADM no nos permite sincronizar el voucher de la reserva 5DCVH4 desde el área de pagos lo solicitan para que figure en el SistAgent. Por favor verificar cuál el es problema.

Gracias, desde ya.

### Paso a paso para reproducir el error

Error al sincronizar voucher

### Captura del error

![image](https://user-images.githubusercontent.com/88722251/141855964-3e60eadc-c520-48fc-a5df-c50a654ee139.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/60229f8aa194f00d18e97629?purchaseGroupId=347505#heading_60229f8aa194f00d18e97629

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Juan

Podrías revisar si el Voucher F937288 en el SistAgen y verificar si fue pagado al proveedor o no?

Saludos

**Comment by JuanBachmann** [comment]
Hola Gabi

No, no está el voucher en el SistAgen

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado
