### ISSUE TITLE
[RIU] MODIFICACION.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#224]
### Descripcion del error

Estimados buenas tardes,
Favor modificar la edad del chd en la reserva a 5 años, ya que en la misma aparece como que tiene 0 años. Vendedor Walter solicitó a Riu modificación y desde nuestra plataforma no se está actualizando correctamente.

### Paso a paso para reproducir el error

1- Buscar reserva.

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/142053114-ace9f09a-5faf-4d5e-b04f-940954879ae7.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61785e5f5211b8240a5cf8c7?purchaseGroupId=363226#heading_61785e5f5211b8240a5cf8c7

**Comment by gabrielmarinsaldaJT** [comment]
Listo, recomiendo ponerla como Inactualizable para evitar problemas
