### ISSUE TITLE
[SIXT] Modificar costos

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#225]
### Descripcion del error

Hola chicos,

Solicito por favor, modificar costo de la reserva.
Yo no puedo modificarla debido a que la tenemos en euros y desde pago nos solicitan en usd.
Costo a modificar **1012 usd**

### Paso a paso para reproducir el error

n/a

### Captura del error

n/a

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6171a36b101a29d908f03c9e?purchaseGroupId=364342#heading_6171a36b101a29d908f03c9e

### Plataforma

Google Chroome

**Comment by GuadaVivas** [comment]
alguna novedad?

**Comment by gabrielmarinsaldaJT** [comment]
Solved
