### ISSUE TITLE
[OMNIBEES] Modificar reserva

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#227]
### Descripcion del error

Buenas tardes Chicos,

Necesitamos modificar la reserva, agregando un pasajero y cambiando los datos de otros dos (con Getbooking no traja ninguna modificación)
Se deberá modificar de la siguiente manera:

TRIPLE: 
Garcia Juan Pablo DNI 29102476
Martin Frigerio DNI 29191947 
Esteban Mosso DNI 29125058

Le coloqué inactualizable, porque también le hice una modificación de costos. 
En la web del proveedor no realizaron ninguna modificación, pero tenemos correo como respaldo.
Gracias. 

### Paso a paso para reproducir el error

n/a

### Captura del error

n/a

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/604918064333cec6bad950b2?purchaseGroupId=350743#heading_604918064333cec6bad950b2

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Listo! 👍

**Comment by gabrielmarinsaldaJT** [comment]
Poner como inactualizable por las dudas
