### ISSUE TITLE
[MOZIO] SOLICITUD DE LOGS

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#228]
### Descripcion del error

Hola, Equipo.

Por favor necesitamos los logs de las reservas de MOZIO 852036 y 852037 debido a que en un principio llegaron en estado REVISAR y posterior a eso se detectó que ambas tenían el mismo número de confirmación.
También les consultamos si se les ocurre qué pudo haber pasado.

Desde ya, gracias.

Saludos,
Juan Manuel

### Paso a paso para reproducir el error

852036: https://adm.ebooking.com.ar/bookings/detail/615f440d354c3dad20f9d282?purchaseGroupId=357534#heading_615f440d354c3dad20f9d282

852037: https://adm.ebooking.com.ar/bookings/detail/615f440d354c3dad20f9d27b?purchaseGroupId=357534#heading_615f440d354c3dad20f9d27b

### Captura del error

![image](https://user-images.githubusercontent.com/88722251/142276082-b88a7a61-2e02-46df-ba3d-d7a9475f6a15.png)

### Link al error y/o Localizador

--

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Estimados, buenas tardes

¿Alguna novedad?

**Comment by JuanBachmann** [comment]
Estimados,

¿Nos pueden ofrecer alguna novedad?

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, les bajé todos los logs que tenemos

Si no es lo que necesitan, lamento decirles que no tengo mas nada que darles
