### ISSUE TITLE
RESERVA GRUPAL ESTEROS

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#23]
Estimados buenas tardes,
Vendedores están teniendo inconvenientes con Cupos, asi mismo desde cupos no estan respondiendo a nuestras consultas,
Adjunto consultas:

![image](https://user-images.githubusercontent.com/45457355/125856862-9e8afaa4-699f-4eb8-b5ab-c34df5b1f625.png)

![image](https://user-images.githubusercontent.com/45457355/125856943-78e7e24f-8213-49d5-aa56-8c0f8bd8a823.png)

![image](https://user-images.githubusercontent.com/45457355/125857093-0ca90db1-2cb7-4587-bb74-55fc4f2c8058.png)

**Comment by IvanFacundoRosas** [comment]
Hola Juan Pablo, me podés dar los pasos para reproducirlo? Reenviame el mail y decime qué cupo es, cuál es específicamente el problema, etc. Gracias.

**Comment by Jlavign** [comment]
Ivan buenas tardes, les envié lo solicitado a los vendedores
![image](https://user-images.githubusercontent.com/45457355/127543945-5c258bcb-ae21-4955-a1c8-7e34da2d2024.png)
Y esta fue su respuesta:
![image](https://user-images.githubusercontent.com/45457355/127544012-d18acc2e-9b6a-47ae-80f0-2e11f4d93dbc.png)

**Comment by moliveto** [comment]
https://adm.ebooking.com.ar/airQuotas/edit/60f04cfc7629386c590105b5


https://user-images.githubusercontent.com/1890103/127551221-46f9fdea-3cff-412c-a09c-163963b911c7.mp4

**Comment by moliveto** [comment]
están cargados mal los segmentos

![image](https://user-images.githubusercontent.com/1890103/127562248-aef76976-32c3-4fbe-bb2e-dd37e203a510.png)

está rompiendo ahí porque no encuentra el aeropuerto "-"

**Comment by moliveto** [comment]
https://adm.ebooking.com.ar/airQuotas/edit/60f04cfc7629386c590105b5

https://adm.ebooking.com.ar/airQuotas/edit/60ba781c876ca009e421a13c

**Comment by IvanFacundoRosas** [comment]
Solucionado. 

@Jlavign si el problema persiste, abrir **otra** issue.
