### ISSUE TITLE
[SABRE] Informacion sobre reservas

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#230]
### Descripcion del error

Estimados buenos días,
Necesito saber si las siguientes reservas fueron realizadas correctamente. Para asi determinar su estado.

https://adm.ebooking.com.ar/bookings/detail/617a90673e6c092f2da2ece1?purchaseGroupId=364029#heading_617a90673e6c092f2da2ece1

https://adm.ebooking.com.ar/bookings/detail/6179de6f3e6c092f2d184655?purchaseGroupId=364008#heading_6179de6f3e6c092f2d184655

https://adm.ebooking.com.ar/bookings/detail/616f30c57b77987b9e39029b?purchaseGroupId=363123#heading_616f30c57b77987b9e39029b

https://adm.ebooking.com.ar/bookings/detail/616f2dfa7b77987b9e18a1f9?purchaseGroupId=363123#heading_616f2dfa7b77987b9e18a1f9

### Paso a paso para reproducir el error

1- Verificar reservas en los logs

### Captura del error

Nohay

### Link al error y/o Localizador

Nohay

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, si una reserva de Sabre no se hizo, o queda en error, no va a pasar nada ya que si no son emitidas por el GDS no hay riesgo

Saludos
