### ISSUE TITLE
[RESERVAS REVISAR] Verificar estado e informar para accionar.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#231]
### Descripcion del error

Estimados buenos días,
Solícito me puedan indicar en que estado se encuentra la siguiente reserva sin loc.

https://adm.ebooking.com.ar/bookings/detail/61950e9800218751ed7f7f0f?purchaseGroupId=366901#heading_61950e9800218751ed7f7f0f

https://adm.ebooking.com.ar/bookings/detail/619508f600218751edf7e142?purchaseGroupId=366863#heading_619508f600218751edf7e142

https://adm.ebooking.com.ar/bookings/detail/61941cba00218751ed22bfbd?purchaseGroupId=366763#heading_61941cba00218751ed22bfbd

https://adm.ebooking.com.ar/bookings/detail/6196b3ed27738254efa2d7c2?purchaseGroupId=367116#heading_6196b3ed27738254efa2d7c2

### Paso a paso para reproducir el error

1- Abrir link

### Captura del error

nohay

### Link al error y/o Localizador

Nohay

**Comment by gabrielmarinsaldaJT** [comment]
Revisadas, ninguna reserva se confirmó

Marcarlas como Error por favor

En casos similares, recomiendo confirmar con el proveedor que la reserva no se haya realizado
