### ISSUE TITLE
[Ibersotar] Error al sincronizar el voucher

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#233]
### Descripcion del error

Hola Chicos!
Estamos teniendo problema para sincronizar el voucher, nos da error y vendedor solicita que aparezca en el sist:

### Paso a paso para reproducir el error

1- Sicronizar el voucher con la flecha
2- Salta cartel rojo de error

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/142668909-096e7548-5da0-41b2-8609-acfb95e60cbd.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/609931c428274ca6a0e31a44?purchaseGroupId=354256#heading_609931c428274ca6a0e31a44

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Les consulto, el Voucher se encuentra pagado al proveedor en el SistAgen?

Saludos

**Comment by GuadaVivas** [comment]
Hola Gabi, sip:
![image](https://user-images.githubusercontent.com/87333634/146068845-f98e4613-1af4-485c-bbf9-b34017c25073.png)

**Comment by gabrielmarinsaldaJT** [comment]
Ese es el problema entonces, si quieren sincronizar una reserva pagada no se puede

Sugiero que la destilden, la sincronizen y la vuelvan a marcar pagada
Para evitar problemas, hablen con alguien de pagos que comprenda mas el SistAgen

Saludos
