### ISSUE TITLE
[Hotelbeds]Error al sincronizar voucher

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#235]
### Descripcion del error

Hola Chicos!
Estamos teniendo problema para sincronizar el voucher, nos da error y vendedor solicita que aparezca en el sist:

### Paso a paso para reproducir el error

1- Sicronizar el voucher con la flecha
2- Salta cartel rojo de error

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/142674787-eed895a1-2919-4b3a-aafb-df5ba422e30f.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61702bee0847e1c920bb1be9?purchaseGroupId=364342#heading_61702bee0847e1c920bb1be9

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Estimados, la vendedora Gianina Elizabeth Silva sigue perteneciendo a la empresa?

**Comment by GuadaVivas** [comment]
Si, ella pertenece a la empresa

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos, la reserva se encuentra pagada al proveedor

Para estos casos, deben sacarle el tilde de pagado, sync y luego tildarlo de vuelta

Aclaro que este paso hace que todo lo relacionado con la reserva (cambios de costo, cambios de occupancy, etc) quedan bajo SU responsabilidad

Saludos!
