### ISSUE TITLE
Optimización

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#236]
Buenas tardes, 
Tenemos el caso de la reserva optimizada 122823 de Tourmed, ya que la vendedora reclama que se le ha modificado el tipo de habitación durante la optimización, de superior a estándar.
Revisando los correos electrónicos automáticos del info y el historial del administrador, se visualiza una incongruencia en la información, dado que el optimizador muestra siempre estándar y en los correos electrónicos enviados se ve claramente la diferencia de superior a estándar.

**Capturas del historial del optimizador**: 

![image](https://user-images.githubusercontent.com/40358708/142680344-67f6036d-eb64-4906-8777-5d4503faf054.png)

**Capturas del correo electrónico de la reserva original**

![image](https://user-images.githubusercontent.com/40358708/142680454-fe9e6b2d-605b-4e63-b7de-de81ede35ba9.png)
![image](https://user-images.githubusercontent.com/40358708/142680468-9aeac25f-c2e8-4028-bcbc-3e8b2f3bf748.png)

**Capturas del correo electrónico de una de las nuevas reservas**

![image](https://user-images.githubusercontent.com/40358708/142680499-d609c368-c948-47f7-b9f7-63c31bba9dbb.png)
![image](https://user-images.githubusercontent.com/40358708/142680513-75031cfe-d1af-4c21-abe9-07754c5e546d.png)

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Ahora reviso todo y les comento

Sobre la issue:

-No está bien titulada, no tiene una descripción clara del problema
-No tiene link a la reserva

Por favor, recuerden de subir estos datos para facilitar la resolucion del problema

**Comment by gabrielmarinsaldaJT** [comment]
He revisado todo y probablemente hemos hecho un **downgrade** de la reserva

Recomiendo lo siguiente:

Retomar con el mismo tipo de habitación que originalmente reservó la agencia y revisar el precio que tiene con respecto a la original

Por nuestra parte vamos a hacer un test para averiguar porque falló el nombre de la reserva

Saludos!

**Comment by abrahamfariaz** [comment]
Buenos días Gabi, como estas?
Olvide responder esta issue. 
Gracias!
