### ISSUE TITLE
[Web Corradi Viajes] Botón de registro

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#237]
### Descripcion del error

Chicos
Podrían verificar en la web de nuestro cliente https://www.corradi.tur.ar/#/mi-cuenta/registro-cliente En esta parte, la de registro, el botón está inhabilitado (en transparente, como si faltaran campos de completar al llenar la solicitud)

### Paso a paso para reproducir el error

a

### Link al error y/o Localizador

https://www.corradi.tur.ar/#/mi-cuenta/registro-cliente

**Comment by agostinaf25** [comment]
Esto habrá alguien que lo pueda ver?
Gracias!

**Comment by abrahamfariaz** [comment]
Buenos días,
Este inconveniente sigue vigente aún
¿Alguna novedad?
Gracias

**Comment by GuadaVivas** [comment]
Hola chicos! sumo a esto, 
no le anda la web correctamente a la agencia 
![image](https://user-images.githubusercontent.com/87333634/157968580-0a4cd8fc-a4c5-45e7-ad7d-ef0b307537c3.png)

**Comment by abrahamfariaz** [comment]
![image](https://user-images.githubusercontent.com/40358708/164521978-473841ea-11a8-4f9f-a800-5ab4ea1b0ad2.png)

Buenas tardes, 
El error persiste ¿Alguna novedad de este caso?
Gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, levantado el https de Corradi

Asigne a los Ivanes para que vean el tema del formulario que al parecer no está validando bien

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Gracias

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes,
Sigue el inconveniente.
¿Alguna novedad del arreglo?

![image](https://user-images.githubusercontent.com/40358708/188511574-b4a8b2ad-9fd8-4438-8640-baf1b99dc9e5.png)

Gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes Ivan, ¿cómo estás?
Revisando este caso, verifico que no es posible aún desde el sitio web del Corradi, registrarse.
Adjunto captura en la cual se puede observar que el botón no se encuentra habilitado.
![Error Corradi](https://user-images.githubusercontent.com/40358708/199595368-a8f22b72-56a4-4493-86a4-b9136734bde1.png)
¿Podrías ayudar al cliente nuevamente en este caso?
¡Gracias!
Abraham

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Muchas gracias

**Comment by gabrielmarinsaldaJT** [comment]
SOLUCIONADO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Al finnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
