### ISSUE TITLE
[Alamo] Se encarece tarifa al confirmarla

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#238]
### Descripcion del error

Se nota una discrepancia en el Total Comisionable entre la del check out y el avail, respecto a la del mail de confirmación y/o la reserva realizada en el administrador mismo

### Paso a paso para reproducir el error

Tengo una reserva de ejemplo para visualizar el error que voy a indicar
Loc: 1333401022COUNT
https://adm.ebooking.com.ar/bookings/detail/619e3820af4a007497c101d1purchaseGroupId=364071#heading_619e3820af4a007497c101d1

Al realizar la búsqueda de este auto, en el avail la visualizamos a USD516 + USD13.62 de impuestos
En el check out la visualizamos igual
Pero al realizar la reserva, el total se incrementa a USD 548.25

![image](https://user-images.githubusercontent.com/88336164/143305561-536a9afd-9a19-4571-9c83-f188c93e9d81.png)

Hay USD 32 de diferencia que no sabemos de dónde proviene
En logs no detalla nada referido a ese monto o a la sumatoria del mismo
En la web del proveedor, figuran los USD 516

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/619e3820af4a007497c101d1?purchaseGroupId=364071#heading_619e3820af4a007497c101d1

**Comment by agostinaf25** [comment]
Estimados, buen dia!
Tenemos alguna novedad de esto?
Hemos recibido varias consultas del tema

Quedo atenta

**Comment by agostinaf25** [comment]
Buenas tardes equipo
La vendedora esta solicitando emitir voucher y facturar esta reserva, por lo que necesita saber qué cobrarle a la agencia
Podríamos darle celeridad a este caso?
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, mail enviado al proveedor

Hay un error en el Response que nos mandan
Les solicitamos un código de tarifa y recibimos otro

Los mantengo al tanto

Saludos!

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado

Encontramos el error y lo subiremos a producción en la próxima publicación
