### ISSUE TITLE
[DESTINATION ITALIA] URGENTE LOC P1G6PM

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#239]
### Descripcion del error

Estimados buenas tardes,
Les solicito nos puedan ayudar con el siguiente caso.
Investigando las reservas a REVISAR encontramos la reserva P1G6PM la cual se encuentra con el Operador DESTINATION ITALIA.
Al consultar en su plataforma la encontramos en estado CONFIRMADA, la reserva en estado Revisar no se cancelo por falta de funcionamiento de tarea.
Se envía mail a Operador para solicitar cancelación FOC y al enviar LOGS de intento de CANCEL nos responde VALERIA indicando que dicho LOG cancel NO PERTENECE A ELLOS. Ingresamos a verificar nuevamente el Hitorial de la reserva y efectivamente no pertenece a ellos sino a ACTION TRAVEL.

### Paso a paso para reproducir el error

1- Verificar reserva y LOGS.

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/143627181-d52e2bf7-4c56-4a22-b3ff-fea58bafac3f.png)
![image](https://user-images.githubusercontent.com/45457355/143627255-43e818d5-e587-4078-a7d3-bcbbcf3654e9.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/60d3e08f0d771a99c0374a8d?purchaseGroupId=357040#heading_60d3e08f0d771a99c0374a8d

**Comment by gabrielmarinsaldaJT** [comment]
Juan, lamentablemente no contamos con los logs de las reservas

No tenemos manera de ver cuándo se intentó cancelar

**Comment by Jlavign** [comment]
Gabriel buenas tardes,
Te quiero consultar:
Porque desconocemos el paradero de los LOGS de cancelación de la reserva y así mismo. ¿Por qué los LOGS de cancel de la reserva pertenecen a OTRO Operador?
Necesito esta información para poder proseguir con la incidencia con la que está relacionada.

**Comment by Jlavign** [comment]
Estimados buenas tardes,
Tendrán novedades?

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Lamentablemente no contamos con logs de la misma y es probable que ya no los tengamos

No se que mas podemos hacer

Saludos
