### ISSUE TITLE
Localizador Y5YN3G BookoHotel

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#24]
Estimados buenas tardes,
Les pido me puedan ayudar a dilucidar este caso, ya que hemos comenzado un reclamo a Operador Bookohotel para que se logre cancelar dicha reserva correctamente como solicito vendedora, se realizo tkt en su plataforma y se nos indica que no encuentran la misma en su plataforma,
Se envia mail a Operador con copia a comerciales y responde lo siguiente,
![image](https://user-images.githubusercontent.com/45457355/126001395-2ee8d7e7-b0ba-4a2a-b2d0-2e3d6fadfc2b.png)

Adjunto link de reserva,
https://adm.ebooking.com.ar/bookings/detail/5dcdf22d4abb597f83559e20?purchaseGroupId=284757#heading_5dcdf22d4abb597f83559e20

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, cómo va?

Revisé la reserva y me encontré con esta nota:

06/04/2020
Por Pierina: Cambio confirmado por el proveedor, via mail.

Preguntenle al proveedor, quizá cambió el localizador interno u otra cosa y por eso no se encuentra

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, alguna novedad?

**Comment by Jlavign** [comment]
Estamos averiguando con Agostina quien tenia el caso anteriormente, 
Te informo si encuentro algún dato más,
