### ISSUE TITLE
[SINCRONIZER] ADM NO SINCRONIZA RESERVA VOUCHER F937292

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#240]
### Descripcion del error

Estimados buenas tardes,
Estamos teniendo inconvenientes al intentar sincronizar el voucher F937292.

### Paso a paso para reproducir el error

1- Buscar reserva vou F937292 

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/143940550-0b5eb7a5-3c02-4017-946d-83bd76a8b302.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6022a101a194f00d18fde9a3?purchaseGroupId=347506#heading_6022a101a194f00d18fde9a3

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, cómo estan?

Podrían indicarme si la reserva figura como **pagada al proveedor** en el SistAgen?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Se sube fix

Cierro issue
