### ISSUE TITLE
[Mongo] Script reservas Toselli Tours

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#241]
### Descripcion del error

Estimados

Podrían asistirnos para modificar/hacer funcionar okkk un script en Mongo para consultar unas reservas de Toselli Tours?
Tenemos _el que adjunto debajo_ pero al ejecutarlo nos trae reservas de Juan Toselli.
El Id de Toselli Tours esta ok, no estaríamos entendiendo por qué sucede esto

Gracias!!!

### Paso a paso para reproducir el error

{ 

    $and : [ 

        { 

            "OwnerId" : "5b213676febe4ba5bb724b01" 

        }, 

        { 

            "BookingStatusEnum" : NumberInt(1) 

        }, 

        { 

            "Charged" : true 

        }, 

        { 

            "ChargedDate" : { 

                $gte : ISODate("2021-11-15T19:12:07.178+0000") 

            } 

        }, 

        { 

            "ChargedDate" : { 

                $lte : ISODate("2021-11-29T19:12:07.178+0000") 

            } 

        }, 

        { 

            $or : [ 

                { 

                    "Seller.Value" : /.*Karla.*/i 

                }, 

                { 

                    "Seller.Value" : /.*Gabriel.*/i 

                }, 

                { 

                    "Seller.Value" : /.*Gustavo.*/i 

                }, 

                { 

                    "Seller.Value" : /.*Aloma.*/i 

                }  

            ] 

        }  

    ] 

} 

me trae la siguientes rvas: F975432, F975375, F975380, F975341 Todas de Juan Toselli

### Link al error y/o Localizador

es mongo, no hay

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

La query está ok

Cual seria el problema? Cómo es la diferencia entre reservas de Toselli Tours y Juan Toselli?

**Comment by agostinaf25** [comment]
El problema es que ese filtro de fechas puntualmente trae las reservas que listo abajo
Si entras a cada una de ellas y visualizas el link de disponibilidad, te lleva a la web de Juan Toselli o Ebooking (no de Toselli Tours) y, por otro lado, son para agencias clientas de acá de Argentina.

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Estuve revisando a fondo esta query y veo que está correcta
No han hecho nada mal y sugiero que sigan haciéndolas asi

Sobre las reservas, es probable que las hayan hecho por eBooking y luego les han cambiado los usuarios a mano, o quizá Gabriel T las hizo con su usuario de ToselliTours. Recuerden que él tiene permisos root

Saludos!
