### ISSUE TITLE
[Administrador] Reservas en estado Eliminada

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#242]
### Descripcion del error

Estimados!

Podrían ayudarnos a identificar por qué las reservas de la agencia Reflejos Viajeros se encuentran en estado Eliminada?
Visualizamos que han sido realizadas por la agencia, pero ¿por qué quedarían en ese status?
No tenemos acceso a logs tampoco para verificarlo :( 
Os pueden ayudar?
Grazzieee, adjunto links

### Paso a paso para reproducir el error

https://adm.ebooking.com.ar/bookings/detail/60e327e4a97a30dcf802178a

https://adm.ebooking.com.ar/bookings/detail/60f2df353d70242d96ec5049

https://adm.ebooking.com.ar/bookings/detail/60ede197de6807b0d38a5ec1

### Link al error y/o Localizador

Arriba

**Comment by gabrielmarinsaldaJT** [comment]
Hola Agos

La agencia te reclama las reservas?

Saludos

**Comment by agostinaf25** [comment]
No no 
Pero queremos saber qué fue lo que sucedió , ya que es una agencia nueva.
si fue error de ellos, de nosotros o qué sucedió que no pudo seguir adelante

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado chicos

Era un error en un deserializador

**Comment by agostinaf25** [comment]
Gabi si filtramos por agencia reflejos viajeros, estado de rva eliminada, aun no las visualizo.
Estoy buscando mal?

**Comment by gabrielmarinsaldaJT** [comment]
Agos, las reservas Eliminadas no se pueden ver desde el ADM

Pero sí podes verlas desde el Mongo

Para encontrarlas, debés buscar que tengan el campo `BookingStatusEnum` = 5
