### ISSUE TITLE
[Administrador] Emisión vouchers 

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#243]
### Descripcion del error

Estimados

Ustedes saben que estamos experimentando algunos inconvenientes con la emisión de vouchers
Al seleccionarlos en el administrador, nos suele aparecer un cartel rojo de error en el extremo superior derecho de la pantalla.
No tengo forma de adjuntarles evidencia de esto, ya que no es algo que sucede siempre, pero se viene dando con frecuencia. 
De hecho algunos vendedores, como los encargados, que tienen facultad para la emisión también nos han notificado de que no pueden, derivándonos la gestión a nosotros.

Perdon la falta de evidencia, pero no tengo forma de adjuntarles algo :(
De igual modo, podríamos revisarlo por favor?
Gracias, como siempre

### Paso a paso para reproducir el error

El unico ejemplo que les puedo adjuntar, que lo emití yo, son unas rvas de Pablo Negro para Toselli Tours
Las quise emitir desde adm.tosellitours.com pero no pude, lo pude realizar desde adm.ebooking
Grupo: 361722

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2018-05-29&purchaseGroupId=361722

**Comment by gabrielmarinsaldaJT** [comment]
Hola Agos! Cómo estás?

Tenemos este caso reportado asique estamos trabajando en ello

Cierro esta issue ya que se duplica con otra

Saludos!
