### ISSUE TITLE
[HYD TRANSFER] NO SE VISUALIZA OPERADOR EN VOUCHER

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#244]
### Descripcion del error

Estimados buenas tardes,
Les solicito me puedan ayudar indicando el operador en el voucher de la reserva Localizador #83969

### Paso a paso para reproducir el error

1- Buscar reserva Localizador #83969

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/144107452-77e62f20-77db-4839-bdbd-98e1fd408610.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6196b28327738254ef714343?purchaseGroupId=367111#heading_6196b28327738254ef714343

**Comment by gabrielmarinsaldaJT** [comment]
Consulta sobre esto

En que parte de los Vouchers de transfer se muestra el operador?
Revisé una de Mozio y tampoco lo tiene
