### ISSUE TITLE
Prototipo Orden de Pago

### ISSUE THREAD

**Issue by gabrielmarinsaldaJT** [toselli/issues#246]
Crear prototipo de orden de pago teniendo en cuenta lo que nos solicitan y sugieren los usuarios

**Comment by ivanpuglia** [comment]
Incluye:

- [ ] Vista de lista de ordenes de pago con acciones
- [ ] Flujo completo de nueva orden de pago
- [ ] Implementación de libreria html2pdf
- [ ] Componente de subida de archivos
- [ ] Filtros de internacionalización
- [ ] Traducción
