### ISSUE TITLE
Error al poner nombre de vendedor 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#25]
Buenas tardes chico,

https://adm.ebooking.com.ar/bookings/detail/60f1735f0a15705fabf6279d?purchaseGroupId=357963#heading_60f1735f0a15705fabf6279d

De la siguiente reserva, no trajo nombre de vendedor e intente colocarle yo, aún así tildándola en inactualizable, pero no queda el nombre. 
Es de Fernando Recalde.
Muchas gracias.

**Comment by gabrielmarinsaldaJT** [comment]
Creo una issue nueva para @aletatan
