### ISSUE TITLE
[MOZIO] Integración API

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#252]
Buenas tardes,
El proveedor Mozio **nos pide realizar la integración de la API para poder efectuar modificaciones a las reservas**, ya que hemos tenido varios casos en los cuales no pueden realizarnos modificaciones y por ello, **surgen inconvenientes**. 
Adjunto a continuación la respuesta de Jeremias Padilla de Mozio

![image](https://user-images.githubusercontent.com/40358708/145033814-a20e9fc6-de39-495d-9ef3-0806b802fa0a.png)

Al consultarles sobre esta integración, obtuve la siguiente respuesta:

![image](https://user-images.githubusercontent.com/40358708/145034032-e161f61f-f874-4e16-9f20-fc1cad2677c9.png)

El contacto con quien hablo es: j.padilla@mozio.com

**Comment by gabrielmarinsaldaJT** [comment]
Abe

El problema con esto, es que es una integración enorme y no se puede hacer de un día para el otro
Para realizar un desarrollo de esta magnitud, necesitamos evaluar los pros y los contras que tendría llevarlo a cabo

Les consulto:
-Cuántas reservas de Mozio reciben modificaciones con respecto al total?
-Genera muchas pérdidas retomar una reserva con diferentes datos?
-Los vendedores usarán ésta nueva funcionalidad o lo usaría **sólo** el área de operaciones?

Luego de que nos contesten éstas preguntas, será Gabriel Toselli quien decidirá si el proyecto se hace o no, y si se hace, cuándo lo deberíamos hacer

Espero no tomen a mal ésta especie de "burocracia" pero es la mejor forma de organizarnos actualmente

Cualquier cosa que necesiten me pueden consultar

Saludos!

**Comment by abrahamfariaz** [comment]
Hola Gabe! 
Entiendo. En el plazo de un año, solo ha sucedido una vez y nos ha generado una pérdida de 37.2 USD
El tema con esas reservas que solo se pueden modificar por API es eso mismo, no es posible realizar modificaciones por teléfono, por su sitio web ni por llamada telefónica. 
Me parece recomendable que solo nosotros usemos esta funcionalidad. No sé bien cómo funcionaría para los vendedores, pero no quisiera que esto provoque cambios no controlados en las reservas. Qué pensas?

**Comment by gabrielmarinsaldaJT** [comment]
Hola Abraham!

Podrías plantearle esto a Gabriel Toselli y si él considera que es algo útil, lo asignará en el siguiente Sprint o le dará la prioridad necesaria

Me parece que tambien podríamos hacer algo un poco mas técnico para usarlo únicamente nosotros

Saludos!
