### ISSUE TITLE
[GRN // EXPEDIA] MEAL PLAN

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#254]
### Descripcion del error

Estimados buenas tardes,
Necesito nos puedan ayudar con la siguiente consulta por la incidencia 9175490154066 la cual inicialmente era GRN-202107-396630.
¿el suplemento que se coloca en "Other" en GRN esta colocado como meal plan en nuestro ADM y en el optimizador?
Si la respuesta es no, necesitamos una lista de reservas con check-in futuro que hayan tenido optimización con GRN para comenzar a revisar las mismas.

### Paso a paso para reproducir el error

1- Buscar reservas

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/60e5fed03873b3e9f355ceb2?purchaseGroupId=357685#heading_60e5fed03873b3e9f355ceb2 https://adm.ebooking.com.ar/bookings/detail/611312f94b463ea0a1b2cc93?purchaseGroupId=357669#heading_611312f94b463ea0a1b2cc93

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Esto se debió a una mala optimización

Por nuestra parte podemos asegurar que se están mostrando bien los MealPlans
