### ISSUE TITLE
[MAPEAR DESTINO] Anguila

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#255]
### Descripcion del error

Buenas tardes
Podríamos mapear la Isla de Anguila por favor?
Hoy figuran hoteles pero no la Isla como destino en si

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8f83386315a56f0cb8c1f/four-seasons-resort-and-residences-anguilla-west-end-village--anguilla?checkIn=2022-03-01&checkOut=2022-03-08&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

Gracias!

### Paso a paso para reproducir el error

a

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8f83386315a56f0cb8c1f/four-seasons-resort-and-residences-anguilla-west-end-village--anguilla?checkIn=2022-03-01&checkOut=2022-03-08&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Listo, está mapeado bajo el nombre de Isla de Anguila

Con el tiempo se irán corriendo tareas que van a agregar mas hoteles

Si necesitan agregar mas hoteles urgente, avisenme

Saludos!
