### ISSUE TITLE
No se puede Cancelar Yalago

### ISSUE THREAD

**Issue by barkergabe** [toselli/issues#26]
Tengo dos casos de reservas de Yalago que no podemos cancelar.

YAC/18582711

YAC/18572129

Me parece que algo debe estar caido o roto. Por favor revisar.
gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Me tomé el atrevimiento de fijarme que pasó

El proveedor devuelve un error 500 al intentar cancelar

`{"ErrorCode":"05102","Message":"An error has occurred","ErrorId":0}`

Recomiendo mandarles un mail con RQ y RS

Sáquenlos de acá
https://adm.ebooking.com.ar/serviceLogs/edit/60f5667f3d70242d9678ed73

Saludos

**Comment by josecaserez** [comment]
Y

> Me tomé el atrevimiento de fijarme que pasó
> 
> El proveedor devuelve un error 500 al intentar cancelar
> 
> `{"ErrorCode":"05102","Message":"An error has occurred","ErrorId":0}`
> 
> Recomiendo mandarles un mail con RQ y RS
> 
> Sáquenlos de acá
> https://adm.ebooking.com.ar/serviceLogs/edit/60f5667f3d70242d9678ed73
> 
> Saludos

Ya les envie email y esperamos respuesta pero el 20 y 21 de julio son feriados para ellos (Filipinas).

**Comment by josecaserez** [comment]
Ya respondieron desde Yalago, dicen que es un error de su sistema, que lo pasaron a su area tecnica y nos avisaran cuando se solucione. 
Mientras tanto se hizo la cancelacion por su backoffice (https://affiliate.yalago.com/Account/Login) y se recomienda que toda nueva reserva que falle en Cancelar se haga asi hasta que lo solucionen. Nota: No todas las cancelaciones fallan desde nuestro sitio.
