### ISSUE TITLE
En Toselli Tours Figura Liquidación de servicios como venta en Argentina 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#266]
### Descripcion del error

En la liquidacion en el admin de Toselli Tours la liquidacion figura como si fuera una venta en Argentina (Ebooking) y no tiene descripción del recargo de paypal como tienen las liquidaciones de Toseloi Tours. 

### Paso a paso para reproducir el error

1. Entrar al admin 
2. chequear la liquidación 

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/146185092-a7db9595-31ed-4b3a-b12b-12f939957523.png)

### Link al error y/o Localizador

9915772675

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Ya hemos solucionado el problema

Saludos!

**Comment by natisalino** [comment]
Gracias Gaby!
