### ISSUE TITLE
[MOZIO] Solicito logs de cancelación

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#268]
### Descripcion del error

Hola Chicos, necesito los logs de cancelación de las siguientes reseras, debido a que le solicitan el pago de las reservas al área de pagos. 

- [ ] -  https://adm.ebooking.com.ar/bookings/detail/5e4718f66a15af555b78e62a?purchaseGroupId=317432#heading_5e4718f66a15af555b78e62a
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e4718f66a15af555b78e57d?purchaseGroupId=317432
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e45d10ccd27a076024eff73?purchaseGroupId=317052
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e45d10ccd27a076024ef96f?purchaseGroupId=317052
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e45b673cd27a0760207f683?purchaseGroupId=316991
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e45b672cd27a0760207f5d1?purchaseGroupId=316991
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5f7e4641bb10994892fc9fea?purchaseGroupId=339096
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e8b86897a7cb14184d52544?purchaseGroupId=328295
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5dd6f7bf640acfeb67faa7fe?purchaseGroupId=298841
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5dd6f7bd640acfeb67fa4a73?purchaseGroupId=298841
- [x] - https://adm.ebooking.com.ar/bookings/detail/61a95f2d7025a3b4c3c0c53f?purchaseGroupId=369280#heading_61a95f2d7025a3b4c3c0c53f
- [x] - https://adm.ebooking.com.ar/bookings/detail/61685fc73c2eaec1962d512e?purchaseGroupId=362681
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e9770788a999fa5c24c8412?purchaseGroupId=329045
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5da86131fd69987f1eb3e834?purchaseGroupId=292470
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5d852abd2db6e103802e5278?purchaseGroupId=288030
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5dfa8220e28bb1025005e24a?purchaseGroupId=305904
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e45826cb9c08f72e8d576ad?purchaseGroupId=316951
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e4c369739c8e846a0621322?purchaseGroupId=317962
- [ ] - https://adm.ebooking.com.ar/bookings/detail/5e38923a83353cca7187af43?purchaseGroupId=314383

Muchas gracias!

### Paso a paso para reproducir el error

n/a

### Captura del error

n/a

### Link al error y/o Localizador

Arriba 

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, les pude levantar los logs de esas dos reservas


Podrían chequearlo?

Saludos

**Comment by GuadaVivas** [comment]
Hola Gabi,

Si veo los logs, pero necesitaría el get cancel.
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, cómo están?

Logré reestablecer los logs de las reservas marcadas con ✔️

La reserva marcada con ⚠️ no tiene un log de GetCancel, pero si de muchos GetBookings, les sirve?

El resto de logs han sido eliminados de nuestra BD por la persona encargada anteriormente

**Comment by GuadaVivas** [comment]
Hola Gabi, 

Sì! dame lo que tengas. El tema es que tengo que demostrar que se cancelaron a termino.

**Comment by gabrielmarinsaldaJT** [comment]
Guada

No tenemos mas logs

Saludos
