### ISSUE TITLE
[VOUCHER] Inconvenientes para sincronizar voucher

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#270]
### Descripcion del error

Hola, Equipo.

No me permite sincronizar el voucher F966011 de la reserva 202-3675882

Espero me puedan ayudar

Saludos,
Juan Manuel

### Paso a paso para reproducir el error

No me permite sincronizar voucher

### Captura del error

![image](https://user-images.githubusercontent.com/88722251/146604493-9abac83f-45e7-420c-8767-a3806a018666.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61702bee0847e1c920bb1be9?purchaseGroupId=364342#heading_61702bee0847e1c920bb1be9

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Esto se debió a un error en nuestro servidor 

Ya ha sido solucionado y los vouchers se están sincronizando correctamente

Particularme este Voucher no se puede sincronizar porque está pagado al proveedor

Saludos
