### ISSUE TITLE
[Rvas en Error] 

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#272]
### Descripcion del error

Hemos intentado realizar varias reservas, con distintos proveedores en la propiedad del link que aquí adjunto y no lo hemos conseguido, ya que luego quedan en Error o Revisar
Podremos ver qué sucede?
Gracias

### Paso a paso para reproducir el error

d

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5caa093c86315a56f0e46d49/theoxenia?checkIn=2022-05-19&checkOut=2022-05-22&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Les detallo mas abajo lo que sucede:

Reserva con:

1. GRN Connect: {"errors":[{"messages":["Supplier error:Not all items could be booked"],"code":5102}]}
2. SmyRooms: Error in reservation process, booking not confirmed. &#xD; 
3. HotelBeds: "error":{"code":"PRODUCT_ERROR","message":"ProductException(AVAILABILITY_CONFIRM, Booking confirmation error: 436-2948748)"}}

Por lo que veo, debe ser que los 3 proveedores le compran al mismo Supplier y ése da error, entonces se traslada al resto

Si quieren, pueden enviarle un mail al proveedor para chequear, pero no veo algún problema de integración, mas bien veo un problema de inventario de los providers

Saludos!
