### ISSUE TITLE
[ADM] Cliente pudo generar voucher

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#273]
### Descripcion del error

Estimados buen día
El motivo del presente es para solicitarles ayuda para indagar por qué una vendedora clienta pudo generar un voucher
Hago referencia al voucher F987193 
El cliente tomo por su cuenta la reserva y pudo generar el voucher. 
Los roles que posee son para clientes, AgencyAdmin y AgencySeller
Podrían ayudarnos?
Gracias!

### Paso a paso para reproducir el error

q

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61b36bdb71465061af75eb13?purchaseGroupId=370385#heading_61b36bdb71465061af75eb13

**Comment by agostinaf25** [comment]
Estimados
CREO que encontré el problema
La agencia ingresó desde el biz.tosellitours y en el checkout les da la opción de 'Pagar con crédito agencia'; para lo cual, cuando seleccionas esa opción y finalizas reserva, directamente la confirma con voucher generado
Adjunto un ejemplo que hice de una reserva test https://adm.ebooking.com.ar/bookings/detail/61c1d594e10bf587bea54170?purchaseGroupId=364184#heading_61c1d594e10bf587bea54170

**Comment by abrahamfariaz** [comment]
Buenas tardes, 
Esto sigue sin resolverse. Acabo de hacer una reserva y emiti voucher al simular una cuenta de un minorista de Toselli Tours.
Adjunto link de nueva reserva (la voy a cancelar): https://adm.ebooking.com.ar/bookings/detail/61d84dfb1c5189bc25d1f1ac?purchaseGroupId=364184

**Comment by abrahamfariaz** [comment]
Estimados, ¿Alguna novedad? 
Esto es potencial para la generación de incidencias.
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes ¿Alguna novedad?
Muchas gracias!

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Gracias!

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Muchas gracias

**Comment by gabrielmarinsaldaJT** [comment]
🎂🥳 FELIZ CUMPLE ISSUE!!!

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos! 

Las agencias ya no podrán generar mas vouchers

Saludos!
