### ISSUE TITLE
[Pagina blanca] Punto ar Viajes

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#276]
### Descripcion del error

Estimados 
Podrian confirmarme si a la agencia Punto Ar viajes se le vencio el certificado de seguridad?
gracias

### Paso a paso para reproducir el error

a

### Link al error y/o Localizador

https://www.puntoarviajes.com.ar/

**Comment by gabrielmarinsaldaJT** [comment]
Solved!
