### ISSUE TITLE
Sabre GetFlightInfo devuelve 500 en Live

### ISSUE THREAD

**Issue by IvanFacundoRosas** [toselli/issues#278]
En circuitos, hay una sección para cargar vuelos en caso de querer contratar un traslado.

![image.png](https://images.zenhubusercontent.com/6155ae8aac087248d9523339/2d2c90e7-545f-4f9d-a07f-f61422cc3416)

El formulario envía una request a `flightService/getFlightInfo` , pero éste devuelve un error `500 Internal Server Error`

### Lamentablemente esto sólo pasa en producción, en local sí funciona.

**Para reproducirlo**
- Elegir cualquier fecha en [Avance 2022 Lisboa y Madrid I](https://ebooking.com.ar/#/circuitos/detalle/60cf49848716a67a5fd5b039/avance-2022-lisboa-y-madrid-i?currency=USD&residence=AR&nationality=AR) y avanzar
- Para reproducirlo en local hay que levantar SpecialtoursCircuit
- Elegir la primera ciudad y la última
- No agregar noches extras
- En la pantalla de transfers, elegir 'Aeropuerto', e ingresar los siguientes datos de vuelo:
Aerolínea: Air Europa Lineas Aereas
Nº vuelo: 1159
Fecha: 14/07/2022

El error salta en SabreProvider.GetSession()

`{
	"error": "500:Internal Server Error",
	"fullerror": "\nException classes: \n   System.Exception\n\nException messages: \n   500:Internal Server Error\n\nStack Traces:\n   at SabreFlightProvider.SabreFlightProvider.GetSession() in D:\\eBookingV4master\\src\\SabreFlightProvider\\SabreFlightProvider.cs:line 327\n   at SabreFlightProvider.SabreFlightProvider.GetFlightInfo(String airlineCode, String flightNumber, DateTime departure) in D:\\eBookingV4master\\src\\SabreFlightProvider\\SabreFlightProvider.cs:line 464\n   at EBookingCoreNew.Engine.Managers.Search.GetFlightInfo(String airlineCode, String flightNumber, DateTime departure) in D:\\eBookingV4master\\src\\EBookingCoreNew\\Engine\\Managers\\Search.Flight.cs:line 383\n   at Api.Controllers.Services.FlightServiceController.GetFlightInfo(String airlineCode, String flightNumber, Nullable`1 departure) in D:\\eBookingV4master\\src\\Api\\Controllers\\Services\\FlightServiceController.cs:line 286\n   at lambda_method348954(Closure , Object , Object[] )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n"
}
`

**Comment by gabrielmarinsaldaJT** [comment]
He revisado el back y veo lo siguiente:

En el IHttpContextAccessor.HttpContext.Connection.Id hay algo que no está OK

Ahi veo que puede estar la falla, ya que al darme un Id mal y al usarlo para una RQ al ConnectionPool de Sabre, devuelve un 500

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado

En la próxima publi se verá reflejado
