### ISSUE TITLE
[Disponibilidad] Sin información ni resultados

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#279]
### Descripcion del error

Al ingresar a la disponibilidad, no brinda ninguna información de la propiedad ni busca disponibilidad

### Paso a paso para reproducir el error

1. Ingresar al link adjuntado
2. Verificar error en pantalla

### Captura del error

![image](https://user-images.githubusercontent.com/40358708/147283345-0e6ce909-2331-45e4-abb8-eaaec3d75050.png)

### Link al error y/o Localizador

https://www.juantoselli.com/#/alojamiento/disponibilidad/5e4ca9ace132e0219c1c9eab/serenade-punta-cana-beach-spa-resort-punta-cana--dominican-republic?checkIn=2023-02-04&checkOut=2023-02-14&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by abrahamfariaz** [comment]
Buenos días, esto se cerró sin resolución. 
Sigo sin visualizar disponibilidad y el vendedor reclama respuesta.
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Abraham

Hace un refresh de tu página o en su defecto Ctrl+R

La solución está publicada y está funcionando

**Comment by abrahamfariaz** [comment]
¡Tenés razón, ahora si!
Gracias
