### ISSUE TITLE
[ADM] Error en botón de Guardar Seller

### ISSUE THREAD

**Issue by gabrielmarinsaldaJT** [toselli/issues#28]
Hay un error en el botón de Save en el Seller de una reserva cuando el seller está NULL

![image](https://user-images.githubusercontent.com/26115345/126173606-77ace204-8942-4f0c-9945-d2c4c5c172d1.png)

Cuando le das al botón no pasa nada 

Adjunto Link 

https://adm.ebooking.com.ar/bookings/detail/60f1735f0a15705fabf6279d?purchaseGroupId=357963#heading_60f1735f0a15705fabf6279d

**Comment by aletatan** [comment]
@gabrielmarinsaldaJT cuando haces el debug correspondiente te das cuenta que al no tener seller guardado previamente, el sistema de notes que utilizan no contempla esa posibilidad. por lo tanto le agregue ? a la propiedad para que funcione.

![image](https://user-images.githubusercontent.com/576730/126176306-97cc0bcc-dda4-459a-8b39-eb2a547a5ca6.png)
