### ISSUE TITLE
[ADM] Modificar costo de reserva

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#280]
### Descripcion del error

Equipo,

Por favor modificar el costo de la reserva 8972964317 debe figurar un costo de 57.39 USD que corresponde a gastos de cancelación. Por nuestra parte no nos permite realizarlo.

Aguardamos.

Saludos,
Juan Manuel

### Paso a paso para reproducir el error

--

### Captura del error

--

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61a63d3c46588464e88b4de0?purchaseGroupId=368963#heading_61a63d3c46588464e88b4de0

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Solved
