### ISSUE TITLE
Sacar datos de contacto de Operaciones en voucher

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#298]
### Descripcion del error

Al revisar los vouchers del proveedor Agoda, figuran los datos de contacto del Departamento Operaciones. Esto es incorrecto debido a que solo se comunica con Operaciones el personal de Toselli, por lo cual, no debe estar expuesto este número. 

### Paso a paso para reproducir el error

1. Ingresar al link de la reserva de muestra que adjunto
2. Revisar Comentarios Voucher 

### Captura del error

![image](https://user-images.githubusercontent.com/40358708/147950768-859ed25f-3bbb-47dd-a470-da5e9ed16e93.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61cdfa0ae33eae5c776e816d?purchaseGroupId=368074#heading_61cdfa0ae33eae5c776e816d

**Comment by abrahamfariaz** [comment]
Buenos días, 
Al actualizar reservas de Agoda, sigue existiendo el contacto de Operaciones. Dejo ejemplos:

- https://adm.ebooking.com.ar/bookings/detail/61a4bf6f582e64845bb8801c?purchaseGroupId=368643#heading_61a4bf6f582e64845bb8801c
- https://adm.ebooking.com.ar/bookings/detail/618d6a837929fcbde0c8ea46?purchaseGroupId=366137#heading_618d6a837929fcbde0c8ea46
- https://adm.ebooking.com.ar/bookings/detail/61a4c52c582e64845be09e26?purchaseGroupId=364106#heading_61a4c52c582e64845be09e26

**Comment by gabrielmarinsaldaJT** [comment]
Lo vamos a sacar de las reservas donde esta

A partir de ahora, no deberia aparecer mas

**Comment by abrahamfariaz** [comment]
¿De las nuevas reservas que se generen? ¿Hay alguna posibilidad de actualizar las existentes para eliminárselo? Ya que quedan muchas por hacer check-in aún
