### ISSUE TITLE
Localizador #9191843325895

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#3]
Estimados buenas tardes,
Vendedor solicita modificación de reserva por disminución de días en alojamiento:

https://adm.ebooking.com.ar/bookings/detail/609eadf59b34a14e3a5cce5d?purchaseGroupId=354652#heading_609eadf59b34a14e3a5cce5d

Sub Total USD 2350.71

Total  USD 3147.55

TOTAL COMISIONABLE USD 2938.39

-Comisión USD 381.99
+ Property Fee USD 304 
+ Tax And Service Fee USD 492.84

![image](https://user-images.githubusercontent.com/45457355/124666965-23593e80-de85-11eb-9bf8-c33cb328f67d.png)

**Comment by gabrielmarinsaldaJT** [comment]
Juampi, podrías chequear si ya está?

**Comment by Jlavign** [comment]
Gaby buenas tardes, según veo el unico dato que no veo correcto es el de TOTAL COM que pedia Fer

![image](https://user-images.githubusercontent.com/45457355/124973294-b9b26f00-e001-11eb-9f24-9c2ed7618e8d.png)

Vendedor solicitaba 

![image](https://user-images.githubusercontent.com/45457355/124973345-ca62e500-e001-11eb-9f79-06fd8e931221.png)

**Comment by gabrielmarinsaldaJT** [comment]
Juampi, cómo va?

El tema es que no le puede dar ese número porque la comisión de Expedia es 0.84 y él está calculando con una comisión de 0.80

Recomiendo preguntarle a @moliveto cómo proceder

Saludos
