### ISSUE TITLE
EU17622RH // VA45440TA ERROR CARGA OPERADOR

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#30]
Estimados buenos días,
Solicito me puedan ayudar modificando el Operador desde Sistagent, ya que no aparece correctamente y cuando intento realizarlo me aparece el siguiente error.

![image](https://user-images.githubusercontent.com/45457355/126351851-6b091ac5-a518-46a2-9dae-acbf7c470499.png)

Así mismo intente sacando el valor inactualizable desde ADM e intente realizarlo y me indica el mismo error.

Adjunto link de reservas:

https://adm.ebooking.com.ar/bookings/detail/60bfbf5ed25e44215bdb4c3d?purchaseGroupId=356332#heading_60bfbf5ed25e44215bdb4c3d

https://adm.ebooking.com.ar/bookings/detail/60c3d728b431eac483226c12?purchaseGroupId=356332#heading_60c3d728b431eac483226c12

**Comment by gabrielmarinsaldaJT** [comment]
@Jlavign Cómo va?

Le agregué el SistAgenCode a Catalonia y ahora debería funcionar

Lo que encontré, es que todos los hoteles Catalonia tienen un SistAgenCode diferente
Le podrías consultar a pagos si hay que agregar un código para cara hotel?

**Comment by gabrielmarinsaldaJT** [comment]
Solved
