### ISSUE TITLE
[EUROPAMUNDO] Error al sincronizar voucher 

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#312]
### Descripcion del error

Estimados buenas tardes,
Estamos teniendo inconvenientes al intentar sincronizar el siguiente vocuher F996581.

### Paso a paso para reproducir el error

1- Buscar reserva en adm

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/148288637-8091fcb6-e4f3-4e85-a4d3-178ca3e3350a.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61cb37ab932f4170b281108f?purchaseGroupId=372554#heading_61cb37ab932f4170b281108f

**Comment by IvanFacundoRosas** [comment]
Se arregló con el cambio toselli/eBookingV4#6927

**Comment by Jlavign** [comment]
Se cierra por arreglo.
