### ISSUE TITLE
[SIRENIS] Modificar costo reserva y quitar OPT

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#313]
### Descripcion del error

Buenas tardes, 
El vendedor realizo gestiones offline sobre la reserva OY50305WE -según nos comenta- y logro un precio de 1956.22 USD.
¿Pueden por favor modificarle el costo y quitarle la OPT?
¡Gracias!

### Paso a paso para reproducir el error

1. Realizar modificación en mongoDB entiendo
2. Entrar al ADM con el link y colocar inactualizable
2. Verificar que se realizo correctamente la modificación

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61c45d7de10bf587be7c3fc7?purchaseGroupId=370351#heading_61c45d7de10bf587be7c3fc7

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad? 
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Abraham, podrías enviarnos un mail con copia a mi y a Gabriel Toselli con el caso?

Necesitamos saber que hizo el vendedor para proceder

Saludos!

**Comment by abrahamfariaz** [comment]
Gabi,
¡Correos enviados!
Abraham

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Caso resuelto

Olvide cerrar la issue
