### ISSUE TITLE
QUITAR OPT - 6SJR3D y Q5M4Z1

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#314]
### Descripcion del error

Buenas tardes, 
Alejandra Martinez me pide quitar las optimizaciones de las reservas 6SJR3D y Q5M4Z1, ya que en pesos argentinos queda el mismo monto. 

![image](https://user-images.githubusercontent.com/40358708/148454929-45129e01-b0e4-43cf-9faa-2f915e8c873c.png)

¿Es posible quitar las OPT en esta oportunidad?

PD: Se adjuntan dos links

### Paso a paso para reproducir el error

1. Entrar a las reservas
2. verificar el monto de opt indicado
3. Realizar las eliminaciones pertinenetes
4. Comprobar que los cambios hayan impactado

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/606da42a0b718ef4c58dad4d?purchaseGroupId=348528#heading_606da42a0b718ef4c58dad4d | https://adm.ebooking.com.ar/bookings/detail/606da4210b718ef4c58cc79b?purchaseGroupId=348528#heading_606da4210b718ef4c58cc79b

**Comment by abrahamfariaz** [comment]
Buenos días, 
Desde Administración precisan estos cambios.
Muchas gracias

**Comment by gabrielmarinsaldaJT** [comment]
Done it
