### ISSUE TITLE
[VOUCHER INEXISTENTE] Voucher no figura en SQL 

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#315]
### Descripcion del error

Hola, Equipo

Solicitamos por favor puedan pasar a No cobrada y sincronicen el voucher F1000711 de la reserva LOC GU62826SB, ya que recibimos un error y no podemos corregirlo manualmente porque no existe el voucher en SQL, es decir no cayó.

Aguardamos ayuda.

Desde ya, gracias.

Saludos,
Juan Manuel

### Paso a paso para reproducir el error

1. ingresar a la reserva
2. verificar error al sincronizar el voucher
3. verificar inexistencia del voucher en SQL

### Captura del error

![image](https://user-images.githubusercontent.com/88722251/148564190-ea37e8ef-78c4-4efe-a25a-6ab2d7a5a621.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61d743a51c5189bc254e38b2?purchaseGroupId=373438#heading_61d743a51c5189bc254e38b2

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Estimados,

¿Nos ayudan con alguna novedad?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Chicos

Cuando les pase esto, verán que el N° de Voucher tiene un total de 8 caracteres y esto no es soportado por el SistAgen

Para solucionarlo:

Borrar el número de Voucher y hacer click en el botón "Actualizar Reserva"
