### ISSUE TITLE
[AVIS] Diferencias en costo de cobro

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#318]
### Descripcion del error

Hola, Equipo

Le acercamos un caso donde desde el área de pagos nos comentan que AVIS les reclama un pago correspondiente a la reserva 18537227AR2 por un monto que difiere totalmente con el que nosotros podemos ver por LOGS y en el ADM.
¿Podrán ver a qué se debe? Ya que tenemos que informar al área de pagos el monto correcto a abonar.
Podrán verificar en los logs que dentro de los distintos métodos el Amount difiere del resto.

Agaurdamos respuesta.

Saludos,
Juan Manuel

### Paso a paso para reproducir el error

Verificar diferencia entre logs

### Captura del error

Correo desde el área de pagos: 
![image](https://user-images.githubusercontent.com/88722251/148609669-7e67078f-c524-42e4-befb-ef410dab3644.png)

ADM:
![image](https://user-images.githubusercontent.com/88722251/148609732-1fa9bef9-8db6-467e-93e9-96e3be840f74.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61a78f1dc36348ba727f724c?purchaseGroupId=369080#heading_61a78f1dc36348ba727f724c

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Estimados,

¿Nos ayudan con alguna novedad?

Saludos

**Comment by JuanBachmann** [comment]
Estimados,

¿Alguna novedad?

Saludos

**Comment by JuanBachmann** [comment]
Estimados,

¿Alguna novedad?

Saludos

**Comment by JuanBachmann** [comment]
Estimados,

¿Alguna novedad?

Saludos

**Comment by JuanBachmann** [comment]
Estimados,

¿Alguna novedad?

Saludos

**Comment by JuanBachmann** [comment]
Estimados,

¿Alguna novedad?

Saludos

**Comment by JuanBachmann** [comment]
Estimados,

¿Alguna novedad?

Saludos

**Comment by GuadaVivas** [comment]
Hola Chicos!

Alguna novedad? Desde pagos no solicitan.
Gracias!

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad? 

Gracias!

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Gracias!

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Gracias!

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Gracias!

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Gracias!

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Gracias!

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Gracias!

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Gracias!

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Gracias!
