### ISSUE TITLE
[GRN] Logs

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#321]
### Descripcion del error

Buenas tardes,
Necesitamos los logs de la reserva i1Fx0E5VrL3P-i8-, ya que el proveedor nos está cobrando 106 USD y el vendedor alega que fue cancelada en tiempo ¿Ha cambiado la política de cancelación? ¿Qué nos dice el log de cancel? 
Muchas gracias!
Abraham

### Paso a paso para reproducir el error

X

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/60be94481435bd4d2346c962?purchaseGroupId=356007#heading_60be94481435bd4d2346c962

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Lamentablemente, los logs guardados entre las fechas 14/06/2021 hasta 20/10/2021 ya no están en nuestra BD y se han perdido

Esto sucedió cuando tuvimos la caída de nuestro servidor en Noviembre y gran parte de nuestra data debió ser movida a la fuerza

Saludos
