### ISSUE TITLE
[Abreu] Aparecen suplementos como habitaciones.

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#323]
### Descripcion del error

En el caso de los hoteles de los circuitos de Turquía, el upgrade a hotel cueva que es un suplemento lo esta poninedo como un tipo de habitacion, y con tarifa menor a la habitación, deberia tomarse la habitacion y que arriba en la pestaña en la que se seleccionan con otros proveedores, por ejemplo, Media Pension, poner ahí la opcion del upgrade a hotel cueva y que al seleccionarlo ya losume en la habitacion. 

Quedo atenta a lo que necesites
saludos!
Nati 
   

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/149361030-1baa3f24-21e1-4651-96c1-814f61994e0e.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/circuitos/detalle/5fb0c9a8ce5389395baeb0c5/tesoros-de-turquia-temporada-21-22?currency=USD&residence=AR&nationality=AR

**Comment by IvanFacundoRosas** [comment]
Se granulariza la issue
