### ISSUE TITLE
I need tours - traslados

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#324]
### Descripcion del error

En I Need Tours traslados que tiene suplemento, por ejemplo de nocturnidad (que lo suma en el total del costo, no en el subtotal del mismo), al markup lo hace solo sobre el subtotal, quedando menos rentabilidad en la reserva, en casos puede llegar a afectarla (no encontré de momento un caso en el que así sea), el mismo deberia hacerse sobre el total, ya que de las dos formas se le da la misma comision a la agencia.   

Envío debajo capturas de un caso con suplemento y de un caso sin suplemento para que puedan comparar. 

Tengo unas reservas de Sixt en Toselli Tours, en donde entiendo pasa lo mismo Loc: 9915772675 y 9916398557
 

### Paso a paso para reproducir el error

.

### Captura del error

Ejemplo localizador: VQT5X2
costo: 
![image](https://user-images.githubusercontent.com/88200755/149361994-2a665716-1277-412b-bb18-d7a199acc8da.png)

venta a la agencia: 
![image](https://user-images.githubusercontent.com/88200755/149362122-d5854662-2c42-4bde-85ba-5669f45a0a57.png)

En comparacion a Ejemplo localizador: QTR5RV mismo costo sin suplemento la venta final al pax es la misma

costo: 
![image](https://user-images.githubusercontent.com/88200755/149362338-61fc80f6-84f8-450b-a809-e73548b9a924.png)

neto agencia: 
![image](https://user-images.githubusercontent.com/88200755/149362385-b1d86769-d219-41dc-b799-e4851c034d1d.png)

### Link al error y/o Localizador

VQT5X2/QTR5RV ebooking

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Nati!!

Los traslados con suplementos son una feature a implementar a futuro

Ya esta planeada y agregada al backlog


Cierro issue porque sino se hace eterna
