### ISSUE TITLE
Modificar tipografia localizador

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#325]
### Idea a implementar

Hola chicos, seria bueno que modifiquemos la tipografía del localizador corto que aparece cuando aproyamos el cursor del mouse en el localizador largo, ya que los numeros "6" y "9" son casi identicos al cero y es dificil identificar rápido el numero y no tenemos la opcion de copia y pegar para hacerlo y poder verlo bien. 
 
![image](https://user-images.githubusercontent.com/88200755/149386177-b6381551-85e3-4a35-b7c1-18bf53b572c8.png)

Saludos!
Nati

**Comment by gabrielmarinsaldaJT** [comment]
Hola Nati!

Esto es producto del zoom que tenés en tu explorador

Si agrandás la resolución de tu pantalla podrás verlo de manera mas clara

De cualquier manera, abro issue para los chicos de Front y solicitarle que hagan un poco mas grande el número de reserva

Saludos!

**Comment by natisalino** [comment]
Ah! Pero que verguenza me da haber mandado este issue.
Mil disculpas
Mala mia
Saludos!
