### ISSUE TITLE
[PALLADIUM] RESERVA CANCELADA.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#327]
### Descripcion del error

Estamos teniendo un problema con Palladium, al cual se le ha cancelado una reserva con voucher ya emitida y sin razón aparente.
El vendedor no realizó ninguna modificación y desde nuestra parte tampoco.

### Paso a paso para reproducir el error

1- verificar reserva

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/149823619-2acc5db9-b21a-4b52-a936-8a4cecab4a67.png)

6/01/2022
![image](https://user-images.githubusercontent.com/45457355/149823726-c5446587-9db9-4ea5-9a5b-e8e93c7134a7.png)

7/01/2022
![image](https://user-images.githubusercontent.com/45457355/149823782-03fee3c8-291b-4694-ac19-4ec4b5968253.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/619cdb7f361d3c9a825c37ca?purchaseGroupId=363097#heading_619cdb7f361d3c9a825c37ca

**Comment by GuadaVivas** [comment]
Buenas tardes!

Cierro issue, por duplicidad (se está analizando en 348)
