### ISSUE TITLE
[EXPEDIA] Discrepancias en suplementos

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#329]
### Descripcion del error

Hola. Equipo.

Solicitamos que puedan revisar el inconveniente que aparece en la integración con Expedia, en específico con el suplemento **breakfast**, de esta forma al solucionarlo implicará una reducción -principalmente- de incidencias en destino y, además, de tiempos frente al control de las reservas. 

Desde ya, gracias.

Saludos,
Juan Manuel

### Paso a paso para reproducir el error

Como ejemplo dejo el LOC 9179238290205 (el hotel solo ofrece desayunos con un costo adicional)

![image](https://user-images.githubusercontent.com/88722251/150001534-cc4e5456-4c4b-41a2-a31b-e1bc2eacac05.png)

![image](https://user-images.githubusercontent.com/88722251/150001625-686a3135-04d7-4172-bbc4-0fda408ae171.png)

### Captura del error

El localizador que tomé como ejemplo es LOC 9179238290205, en nuestro ADM se ofrece desayuno y en la página de Expedia no aparece el suplemento.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61e6dbaf180627febd70b0f9?purchaseGroupId=374539#heading_61e6dbaf180627febd70b0f9

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Estimados,

¿Nos ayudan con alguna novedad?

Saludos

**Comment by josecaserez** [comment]
Al menos en los logs nuestros se puede ver que en el Avail se incluyo como Amenities del room **Free breakfast**:
```
"id": "200092360",
				"room_name": "Deluxe Room",
				"rates": [
					{
						"id": "211106282",
						"available_rooms": 12,
						"refundable": true,
						"fenced_deal": true,
						"fenced_deal_available": false,
						"deposit_required": false,
						"merchant_of_record": "expedia",
```
						"amenities": {
							"2192": {
								"id": 2192,
								"name": "Free WiFi"
							},
							"1073742786": {
								"id": 1073742786,
								**"**name": "Free breakfast"****
							}
						},

mientras que en los GetBooking te los ratifican que están incluidos:
```
"amenities": [
					_2192,
					1073742786_
]
```
Por lo que podes reclamar que el cuarto solicitado los incluia

**Comment by gabrielmarinsaldaJT** [comment]
Chicos

Sobre estos casos recomiendo dos cosas:

1- Reclamarle al proveedor en caso de alguna incidencia en destino. Nuestros logs, como indica José, están mostrando que ofrecen Free Breakfast, por lo que no es culpa nuestra
2- Eliminar el mapeo del hotel con Expedia en la BlackList para evitar futuros problemas

Saludos!
