### ISSUE TITLE
[Control de reservas] 

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#330]
### Idea a implementar

Buenas tardes,
Respondiendo a **una de las actividades troncales del Departamento Operaciones, el control de reservas**, nos es imposible saber la cantidad de reservas que se van controlando por día y quién lo hace. Por ello, pido por favor alguna implementación que nos permita saber quién controla y cuando, **en tiempo real**. 
Se nos ocurre a través de filtros, BI o acceso a la base de datos live (solo para realizar esta consulta)
Quedamos atentos a novedades.
¡Muchas gracias!

**Comment by abrahamfariaz** [comment]
Buenos días, ¿Alguna novedad? 
Es un ticket importante para Operaciones
Muchas gracias

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, cómo va?

Lo charlé con Guada en nuestrar reuniones

Es muy poco performante para nuestra Base de Datos una consulta de este estilo y generaría demasiado tráfico y carga.
Ésto puede generarnos mucho problemas con el sistema y actualmente estamos casi al límite de funcionamiento

Podemos prepararles algo a futuro para cuando salgamos con el nuevo ADM

Saludos!

**Comment by abrahamfariaz** [comment]
Gabi,
Muchas gracias Gabi por contemplar esta idea y esperamos pueda concretarse de alguna manera en la próxima versión del administrador.
Abrazos!
