### ISSUE TITLE
[Expedia] Reserva cancelada sin correo de aviso

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#331]
### Descripcion del error

Buenas tardes,
La reserva 9184159011943 (891634) fue cancelada por el cancelador automático sin dar aviso alguno al vendedor por correo electrónico. Adjunto link de la reserva y captura de la totalidad de correos enviados al vendedor. 

### Paso a paso para reproducir el error

1. Entrar a la reserva y verificar la fecha de cancelación
2. Ver la imagen y comprobar la ausencia de correos electrónicos notificando próximo vencimiento

### Captura del error

![image](https://user-images.githubusercontent.com/40358708/150190794-b51043f2-f0be-43a7-89af-c2276716ab81.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61df527a180627febdb962c7?purchaseGroupId=373985#heading_61df527a180627febdb962c7

**Comment by abrahamfariaz** [comment]
Adjunto otros tres casos:

**9183844237259**

![image](https://user-images.githubusercontent.com/40358708/150191266-7fffe995-8148-4333-903d-fc7f0320c18f.png)

https://adm.ebooking.com.ar/bookings/detail/61cdb715e33eae5c77733cf4?purchaseGroupId=371772#heading_61cdb715e33eae5c77733cf4

**9183844251881**

![image](https://user-images.githubusercontent.com/40358708/150191385-f76c1977-dd8c-4fc5-abfe-5ff14acf9dc0.png)

https://adm.ebooking.com.ar/bookings/detail/61cdb718e33eae5c77734e39?purchaseGroupId=371772

**9183844298679**

![image](https://user-images.githubusercontent.com/40358708/150191478-5800d881-2a6d-4702-96e9-13bc1e6f13f1.png)

https://adm.ebooking.com.ar/bookings/detail/61cdb71ae33eae5c77737a8c?purchaseGroupId=371772

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, este error se debió a que el MailSender se llenó y dejo de trabajar

Si vuelve a suceder por favor reportarlo
