### ISSUE TITLE
[ADM] Quitar contacto duplicado de Hotel Trader

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#336]
### Descripcion del error

Equipo.

Por favor eliminar contacto duplicado en el adm del nuevo proveedor Hotel Trader: https://adm.ebooking.com.ar/providers/edit/hoteltraderhotel

El que queda ya tiene registro de las vías de contacto con el proveedor.

Saludos,
Juan Manuel

### Paso a paso para reproducir el error

Eliminar contacto duplicado.

### Captura del error

![image](https://user-images.githubusercontent.com/88722251/150366035-72bd87af-e74b-4caf-97d3-de830f93686c.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/providers/edit/hoteltraderhotel

### Plataforma

Google Chroome

**Comment by djguille** [comment]
Ya se eliminó el duplicado.
