### ISSUE TITLE
[SERVICIO y/o PROVEEDOR] Modificar Voucher

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#337]
### Descripcion del error

Debido a cierre de un hotel (Plaza Hotel) hay dos reservas que necesitan una modificación del voucher, ya que los respectivos proveedores han asignado un nuevo hotel (mismo meal plan, mismas habitaciones). 

### Paso a paso para reproducir el error

ir a adm y modificar voucher de reservas 

LOC: 38056926
LOC: 792249136

### Captura del error

![RESTEL 38056926](https://user-images.githubusercontent.com/98116205/150397806-f1c06923-a90f-49e4-a202-bab70d97e2f7.png)
![SMYROOMS 792249136](https://user-images.githubusercontent.com/98116205/150397817-95eac30d-9339-4a56-bb2b-dbc1f1b4b345.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/618bdcf7cd3d65290152aaeb?purchaseGroupId=365860#heading_618bdcf7cd3d65290152aaeb

**Comment by mvalentinalucero** [comment]
adjunto link restante: https://adm.ebooking.com.ar/bookings/detail/618be7a9cd3d65290113d30e?purchaseGroupId=365860#heading_618be7a9cd3d65290113d30e

**Comment by abrahamfariaz** [comment]
Caso resuelto

**Comment by abrahamfariaz** [comment]
Reabro issue por caso pendiente de modificación: https://adm.ebooking.com.ar/bookings/detail/618be7a9cd3d65290113d30e?purchaseGroupId=365860#heading_618be7a9cd3d65290113d30e

¡Muchas gracias!

**Comment by GuadaVivas** [comment]
cierro issuel-
