### ISSUE TITLE
[Salidas] Duplicidad en número de teléfono

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#339]
### Idea a implementar

Al ingresar a cualquier salida, en el margen inferior derecho, se visualizan dos veces el número de teléfono para contactar a la empresa.

![image](https://user-images.githubusercontent.com/40358708/150530944-ac22d731-bba0-4367-90fc-d0fc6e836768.png)

¿Es factible dejar uno solo? 
Gracias!

Link: https://ebooking.com.ar/#/salidas/detalle/0106HCIL8B/altiplano-de-guatemala

**Comment by abrahamfariaz** [comment]
Buenas tardes. ¿Alguna novedad?
Gracias!

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado por @MatiFrencia
