### ISSUE TITLE
[Aéreos] Peticiones para establecimiento

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#340]
### Idea a implementar

Buenos días,
Al cotizar una reserva de aéreo y pasar al checkout, aparece en el detalle un cuadro "peticiones para establecimiento", lo cual es incorrecto debido a que estamos en el servicio de aéreos

![image](https://user-images.githubusercontent.com/40358708/150532651-813acdfa-f197-4641-8644-1a86b7da524a.png)

Dejo link de búsqueda para que puedan elegir cualquier opción y verificar lo indicado
¡Gracias!

Link: https://ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-11-12!2022-11-19!BSB!MAD&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Issue asignada para front, les solicito que lo saquen

**Comment by gabrielmarinsaldaJT** [comment]
@IvanFacundoRosas @ivanpuglia 

Podrían liquidar ese cuadro porfas? Si la reserva es un FlightService, no debería ir

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Gracias!

**Comment by abrahamfariaz** [comment]
Buenos días, 
¿Alguna novedad?
Muchas gracias

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!

En la proxima publicación lo verán reflejado

**Comment by abrahamfariaz** [comment]
Buenas tardes,
No sé cuál será su fecha de publicación pero aún sigue existiendo el inconveniente

![image](https://user-images.githubusercontent.com/40358708/189920189-3676f41a-e714-4016-abc0-b0bef8331d8b.png)

Link de búsqueda: https://ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-04-03!2023-04-17!COR!EZE&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

Seleccione esta opción

![image](https://user-images.githubusercontent.com/40358708/189920356-531c1b55-86b7-4d0c-8a11-aa8963b133f9.png)

Aguardo tu pronta respuesta, gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Hicieron un refresh?

![image](https://user-images.githubusercontent.com/26115345/189932151-9c0bf637-2d94-43b3-81eb-d237f490ebc6.png)


Saludos

**Comment by abrahamfariaz** [comment]
Estimados,
¡Excelente el cambio! Sin embargo, ¿Qué función viene a tener ahora "Referencia"? Dado que era una especie de notas y observaciones para el agente de viajes.
Si la función de "Referencias" son notas y observaciones, entonces sugiero eliminar dicha casilla de todos los servicios

**Comment by gabrielmarinsaldaJT** [comment]
Hola Abraham!

La función referencia está para que las agencias lo tomen como lo que es, una Referencia
Ese campo no llega al hotel ni a ningún proveedor, solamente es un indicativo que las agencias tienen para referirse a sus reservas. 
Hemos visto que algunos clientes escriben "Grupo González" o "Grupo Cuba 2022" en todas las reservas que hacen mas allá de que sean de diferentes pasajeros o diferentes tipo de servicios

El campo Peticiones Especiales es para el proveedor, esos mensajes (no siempre) llegan a nuestro provider y posteriormente al hotel. Mucha gente lo usa para especificar que un pasajero es discapacitado y necesita una habitación en planta baja, o tiene cierta alergia a alguna comida, por poner un ejemplo

Espero haber aclarado sus dudas

Saludos!

**Comment by abrahamfariaz** [comment]
Hola Gabi, ¿Cómo estás?
Volvió a aparecer "peticiones para el establecimiento"
![image](https://user-images.githubusercontent.com/40358708/199597989-981a7a25-a8bb-4cef-9511-15d32252b174.png)
¿Podrías corroborar nuevamente los cambios realizados?

**Comment by gabrielmarinsaldaJT** [comment]
Hola Abraham!

Lamento lo sucedido, encontramos que hubo un problema con unos nuevos cambios subidos que generaron que se volvieran atrás otras cosas previamente solucionadas

Esperamos no vuelva a ocurrir

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Por cierto, no te dije pero ya lo solucionamos

Te pido nos des un rato para publicar, en unos minutos lo verás reflejado

**Comment by abrahamfariaz** [comment]
Gabi,
Muchas gracias!
