### ISSUE TITLE
[Abreu] No aparecen los suplementos opcionales

### ISSUE THREAD

**Issue by IvanFacundoRosas** [toselli/issues#342]
/circuitos/detalle/5fb0c9a8ce5389395baeb0c5/tesoros-de-turquia-temporada-21-22?currency=USD&residence=AR&nationality=AR

Agregar como tiene Wamos

**Comment by IvanFacundoRosas** [comment]
Al icebox hasta comunicarme con Abreu

**Comment by natisalino** [comment]
Hola Ivan, te paos los contactos que nos pasó Abreu
Si me llegan a pasar algo màs, te aviso, copiame cuando les escribas por favor,
Gracias


Hola Nati, 
....te paso estos 2 contactos de nuestros IT, son ABREU ONLINE pero seguro son lo mismo. Estoy intentando conseguirles un Teléfono pero por ahora no lo tengo......avisame si te responden por correo. y si te sirve.
Igualmente sigo buscándote una opción mejor.
client.itsupport@abreuonline.com (IT Client XML Support) 
supplier.itsupport@abreuonline.com (IT Supplier XML Support)
Fede
