### ISSUE TITLE
[OPTIMIZADOR] Errores en los suplementos y meal plan

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#343]
### Descripcion del error

Equipo.

Les presento algo que creo es un error que aparece en el Opt y lo veo cada vez con más frecuencia, refiero a que difiere lo que se ofrece en el regimen de comida con los suplementos. Es decir, en muchos casos (como el ejemplo que les dejo) se muestra en la misma reserva un régimen que incluye desayuno y en los suplementos dice que no incluye desayuno.
Les adjunto imágen.

Saludos,
Juan Manuel

### Paso a paso para reproducir el error

Diferencias en meal plan de las opciones que trae el Opt

### Captura del error

![image](https://user-images.githubusercontent.com/88722251/150563733-d1e817f0-5ea7-4c73-805d-843aea58981d.png)

### Link al error y/o Localizador

--

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Juan! Cómo estás?

Muchísimas gracias por notificarlo

Ésto nos sirve de gran ayuda para continuar con nuestro desarrollo 

Te pido que si vuelves a ver otra discrepancia de este estilo, por favor nos notifiques

Saludos!

**Comment by gabrielmarinsaldaJT** [comment]
Estimados, cómo están?

Esta issue ya fue analizada por el equipo y hemos planificado un desarrollo para este sprint que permite agregar nuevos mealplans a nuestra base de datos y reprocesarlos, con el fin de poder mapearlos y que ya no vuelvan a aparecer sin procesar

Saludos !
