### ISSUE TITLE
[🔥HOTFIX🔥] [REPORTE EXPEDIA] No funciona

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#344]
### Descripcion del error

Buenas tardes,
No se puede descargar el gross proffit de Expedia desde la pestaña Reportes >> Reporte Expedia por Período. No lanza ningún error. 
¿Nos pueden ayudar? 

### Paso a paso para reproducir el error

1. Entrar al link
2. Intentar descargar el reporte del período 01/12/2021 - 31/12/2021
3. Verificar error

### Captura del error

![image](https://user-images.githubusercontent.com/40358708/150584121-3b2a0149-3d7c-4f7e-85c2-1920339a7142.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/reports/expediaReportByPeriod

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!!
