### ISSUE TITLE
[W2M] Modificar costo 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#345]
### Descripcion del error

Hola Chicos!

Tengo la siguiente reserva, que necesito modificar el costo a 80.25$ usd, nosotros ya lo hemos hecho pero,  La misma se encuentra optimizada por lo que la vendedora sigue visualizando 1.313,07.
Solicitamos modificar así ella logre verlo correcto.
Gracias!

### Paso a paso para reproducir el error

n/a

### Captura del error

N/A

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6091a1156a4313837d0eb006?purchaseGroupId=346829#heading_6091a1156a4313837d0eb006

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Listo, recomiendo poner como inactualizable
