### ISSUE TITLE
[VivaWyndham ] Solicito logs de cancelación

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#346]
### Descripcion del error

Hola Chicos, 

Necesito por favor los logs de cancelación, get cancel, de las siguientes reservas: 

- https://adm.ebooking.com.ar/bookings/detail/5f3d1aae7c9977090caf0536?purchaseGroupId=335253#heading_5f3d1aae7c9977090caf0536
- https://adm.ebooking.com.ar/bookings/detail/609fe4a610375e45d18d3c11?purchaseGroupId=354721#heading_609fe4a610375e45d18d3c11

Reclaman el pago de las reservas, y las mismas esta canceladas a término, reclaman desde pagos. 
Gracias. 

### Paso a paso para reproducir el error

n/a

### Captura del error

n/a

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/5f3d1aae7c9977090caf0536?purchaseGroupId=335253#heading_5f3d1aae7c9977090caf0536 / https://adm.ebooking.com.ar/bookings/detail/609fe4a610375e45d18d3c11?purchaseGroupId=354721#heading_609fe4a610375e45d18d3c11

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Logs reestablecidos

Por favor revisar la reserva
