### ISSUE TITLE
[Panamericana De Viajes] Modificación de reserva.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#347]
### Descripcion del error

Estimados buenas tardes,
Necesito me puedan ayudar con la reserva 3PGD5C. No se está actualizando correctamente el cambio que realizo la vendedora desde su plataforma. El cambio es agregar un infante de 2 años a la reserva **- EMMA DE LA ROSA (2 Edad / Age)**
Aparte de ello descubrimos que al intentar agregar un pasajero más desde nuestra plataforma no podemos elegir si es adulto o niño y no se actualiza una vez ejecutamos la modificación.

### Paso a paso para reproducir el error

1- Buscar reserva

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/151049785-69d2d607-84e5-4507-8007-796711158b7e.png)
![image](https://user-images.githubusercontent.com/45457355/151049877-aa9b2348-64bc-4386-9a08-a5623b81e23f.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6196a29b8c277e78240e6920?purchaseGroupId=362466#heading_6196a29b8c277e78240e6920 https://www.panamericanadeviajes.net/users/bookings.aspx?onlyQuotations=false

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Agreguen el pasajero y yo lo seteo como infante

De todas maneras, abro issue para el equipo de front para que agreguen el cambio necesario para elegir el tipo de pasajero

Saludos!
