### ISSUE TITLE
[IBEROSTAR y PALLADIUM] Reservas en Error

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#348]
### Descripcion del error

Hola chicos, 

Tenemos el siguiente problema con **Iberostar**:
Reclaman el pago de reservas que nosotros las tenemos en estado Error. No obstante los último getbooking de las mismas llegan con un estado "Modified" que para el proveedor esas si se encuentran confirmadas. Por ahora hemos detectado algunas pero solamente porque nos reclaman el pago. Le solicitamos a Iberostar que nos adjunte una lista de las que les figuran en este estado. 
Por otro lado, reclamamos al proveedor y nos respondieron lo siguiente:

![image](https://user-images.githubusercontent.com/87333634/151228161-b02d4f79-7ced-4bd4-aee3-c34c98dbd079.png)

Nos reclaman un ejemplo de mensaje de error, pero en los ultimos Getbooking, no existe tal mensaje. 
Les adjunto los links de las reservas que estan en error y reclaman pagos:

- https://adm.ebooking.com.ar/bookings/detail/615a6e40a72e6126546efb66?purchaseGroupId=361888#heading_615a6e40a72e6126546efb66
- https://adm.ebooking.com.ar/bookings/detail/612ed943f71cdf3b0ddf5c5f?purchaseGroupId=359609#heading_612ed943f71cdf3b0ddf5c5f

Y respecto a **Palladium**
Ocurre un problema similar al de Iberostar, en el cual las respuestas en los getbooking vienen con el estado MODIFIED. Con este proveedor solo detectamos reservas optimizadas, con esta respuesta. 
Les adunto los links:

- https://adm.ebooking.com.ar/bookings/detail/619cdb99361d3c9a82601b50?purchaseGroupId=363704#heading_619cdb99361d3c9a82601b50
- https://adm.ebooking.com.ar/bookings/detail/61bb3269eb4a9f986c448dc4?purchaseGroupId=369111#heading_61bb3269eb4a9f986c448dc4
- https://adm.ebooking.com.ar/bookings/detail/618cfecb7929fcbde071ce44?purchaseGroupId=365455#heading_618cfecb7929fcbde071ce44

Muchas gracias. 

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

Google Chroome

**Comment by mvalentinalucero** [comment]
Agrego en relación a este inconveniente. Con un mismo localizador se vinculan múltiples reservas (con diferente our record, pasajeros y voucher). Adjunto los LOC en los que he detectado esto. 

- 348829710J-JI : https://adm.ebooking.com.ar/bookings?dateFrom=2021-07-28&recordLocator=348829710J-JI

- 345583800J-JI : https://adm.ebooking.com.ar/bookings?dateFrom=2021-07-28&recordLocator=345583800J-JI

- 347479250M-JI : https://adm.ebooking.com.ar/bookings?dateFrom=2021-07-28&recordLocator=347479250M-JI

-347342300L-JI : https://adm.ebooking.com.ar/bookings?dateFrom=2021-07-28&recordLocator=347342300L-JI

- 348829660J-JI : https://adm.ebooking.com.ar/bookings?dateFrom=2021-07-28&recordLocator=348829660J-JI

¡Muchas gracias!

**Comment by GuadaVivas** [comment]
Alguna novedad? Estàn ingresando varias con el mismo inconveniente.

**Comment by GuadaVivas** [comment]
Palldium confirmando acerca de las modified:

![image](https://user-images.githubusercontent.com/87333634/153943551-ba32ec84-58e6-4a64-a8ea-82970c9a20b2.png)

**Comment by mvalentinalucero** [comment]
¡Hola Chicos! Adjunto captura de mails con palladium sobre locs duplicados. 

La reserva que envìe a confirmar fue: LOC 358343250L-JI, para el pax DANIEL ARCANGIOLI. Me responden con una captura de su sistema en la que se ve que bajo el mismo LOC hay dos reservas con el mismo pax. Entro a chequear al adm. y efectivamente existen dos reservas bajo ese mismo loc pero con pax distintos. 

![palladium 2](https://user-images.githubusercontent.com/98116205/154127611-bd3677d2-2cef-40ea-bfce-e7c6acb07646.png)

![palladium 1](https://user-images.githubusercontent.com/98116205/154127565-e6d55f6a-7e1e-47c2-ac2f-26575dda316b.png)

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Teniendo un procedimiento listo para realizar y habiendo solucionado el tema de las reservas MODIFIED

Cierro issue

**Comment by JuanBachmann** [comment]
Equipo,

Solicité una cancelación a Palladium por una reserva que no me permitía cancelar el ADM, adjunto respuesta:

![image](https://user-images.githubusercontent.com/88722251/155022605-a2b42461-e7a3-48e3-93f8-8c6bff72a803.png)


![image](https://user-images.githubusercontent.com/88722251/155022152-97bea26d-168b-4069-a090-9e565bc88f57.png)

Necesito que se cancelen las siguientes reservas: 

- 358802860M-JI (841091): https://adm.ebooking.com.ar/bookings/detail/6202a1e33a1aeeb117c1dac7?purchaseGroupId=359605#heading_6202a1e33a1aeeb117c1dac7
- 358802860M-JI (841092): https://adm.ebooking.com.ar/bookings/detail/6202a1e53a1aeeb117c1f822?purchaseGroupId=359605#heading_6202a1e53a1aeeb117c1f822
- 361389170J-JI (886573): https://adm.ebooking.com.ar/bookings/detail/620e412b5858bf664b92f750?purchaseGroupId=371525#heading_620e412b5858bf664b92f750

Aguardo respuestas.

Desde ya, gracias.

Saludos,
Juan Manuel

**Comment by GuadaVivas** [comment]
Se cierra, solucionado.
