### ISSUE TITLE
AVIS Revisar

### ISSUE THREAD

**Issue by moliveto** [toselli/issues#35]
https://adm.tosellitours.com/bookings/detail/60faf2f29860fe8bbe47ad26?purchaseGroupId=358194#heading_60faf2f29860fe8bbe47ad26

[link](https://adm.tosellitours.com/bookings/detail/60faf2f29860fe8bbe47ad26?purchaseGroupId=358194#heading_60faf2f29860fe8bbe47ad26)

**Comment by gabrielmarinsaldaJT** [comment]
El error recibido es el siguiente:

```
<Messages.Message>
		<Id>31003 BizRule</Id>
		<Type>1</Type>
		<Description>Unable to make a reservation</Description>
</Messages.Message>
```
Se envía mail al proveedor para consultarle al respecto

**Comment by gabrielmarinsaldaJT** [comment]
El proveedor indica lo siguiente:

> Estimados buen día,
> 
> La consulta es correcta. El problema deriva en que el sistema no permite realizar alquileres nacionales por cuestiones contractuales con la corporación y zonas de territorios de venta. En este caso la reserva debe ser realizada con Avis/Budget Argentina con los medios y/o herramientas que provean las firmas controlando el alquiler dentro del territorio argentino.
> 
> Saludos
