### ISSUE TITLE
[BANDA DE AHORRO] No permite ver tarifas

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#351]
### Idea a implementar

Buenos días,
La banda de ahorro no permite ver la tarifa de las reservas.

![image](https://user-images.githubusercontent.com/40358708/151360482-304e7adc-e1bb-4cac-b92b-bdd23e697f85.png)

También hay otros casos que no se entiende el número que aparece

![image](https://user-images.githubusercontent.com/40358708/151361547-24c07263-fd0e-41b1-ad66-6b8714bb32c4.png)

Adjunto un link random para visualizar: https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca908b286315a56f0ce1f7d/iberostar-punta-cana?checkIn=2022-06-01&checkOut=2022-06-10&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by abrahamfariaz** [comment]
Buenas tardes,
Acaba de ingresar otro reclamo al respecto 
¿Nos pueden ayudar por favor?

![image](https://user-images.githubusercontent.com/40358708/155788854-d35e0fc8-3eff-4afa-9e8a-50a3515a02e9.png)

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Esta issue está duplicada con otra que tenemos en nuestro repositorio

Ya lo están viendo los Ivanes

Saludos!
