### ISSUE TITLE
[GlobalTrend] LOGS DE CHECK OUT/GETBOOKING

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#353]
### Descripcion del error

Hola Chicos!

Necesito los logs del check out o de el ultimo getbooking, donde demuestre que las reserva se encuentra en error. Yo en su momento la vi y la coloque inactualizable debido a que traia el error ""Errors><Error Code="101" ShortText="Erro ao Gerar Reserva"/></Errors>". Pero ahora reclaman el pago de una y al parecer es esta en Error y necesito enviarle la evidencia. 

https://adm.ebooking.com.ar/bookings/detail/611312e44b463ea0a1b1a5e6?purchaseGroupId=358734#heading_611312e44b463ea0a1b1a5e6

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/611312e44b463ea0a1b1a5e6?purchaseGroupId=358734#heading_611312e44b463ea0a1b1a5e6

### Plataforma

Google Chroome

**Comment by GuadaVivas** [comment]
alguna novedad?

**Comment by djguille** [comment]
Lamentablemente no existen esos logs. NO hay registros de logs anteriores al 01-09-2020 y lo que están entre 10- 06-2021 hasta el 20-10-2021. De tener reserva que necesiten el log de las fechas mencionadas van a tener que ir al sistema del proveedor directamente.
