### ISSUE TITLE
[JUMBO] Poner en cero reserva opt

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#355]
### Descripcion del error

¡Hola Chicos! Necesito cambiar a cero a esta reserva optimizada 8460405311 para que le figure en cero a la vendedora. Tampoco podemos sincronizar el voucher. Gracias! 

### Paso a paso para reproducir el error

-

### Captura del error

![reserva 8460405311](https://user-images.githubusercontent.com/98116205/152003242-ac61b559-9a75-4069-a8b6-aaaa440ed85a.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61c5c6a5e10bf587be9eef9b?purchaseGroupId=367032#heading_61c5c6a5e10bf587be9eef9b

### Plataforma

Google Chroome

**Comment by djguille** [comment]
Este voucher no se puede sincronizar porque esta pagado. Hablar con Pago a proveedores.
