### ISSUE TITLE
[Cupos] Información transfer

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#356]
### Idea a implementar

Buenas tardes,
Al elegir un cupo online, y situarnos sobre la sección _Información Transfer_, nos genera duda el equipaje. Miremos un caso:

Link (único cupo online disponible, avanzar hasta el checkout): https://ebooking.com.ar/#/cupos-confirmados/detalle/617ac20e3e6c092f2d34ab5f/cupos-confirmados-a-cartagena-desde-cor?from=5a21b01efc2d5608730462bf&quota=615f142f354c3dad20fe08e3&token=1028AL1OYO

![image](https://user-images.githubusercontent.com/40358708/152037681-4670dea4-d30f-48de-9216-5d0832093c13.png)

¿Una valija para dos pasajeros o una valija por cada pasajero? 

Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos! Cómo están?

¿Una valija para dos pasajeros o una valija por cada pasajero?
Es una sóla valija para todo el viaje, si los pasajeros van a usar una valija para dos, no lo sabemos

Además, la info que ven en los cupos, es info que cargan los muchachos de cupos, deberían consultarle a ellos para una información mas precisa

Saludos!
