### ISSUE TITLE
[Cupos] Coherencia de formato de fechas

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#357]
### Idea a implementar

Buenas tardes,
Sería excelente mantener una coherencia en el formato de las fechas dado que por momento vemos AÑO/MES/DIA, DIA/MES/AÑO, MES/DIA/AÑO o DIA/MES/AÑO, lo cual confunde y es peligroso a la hora de gestionar la información. 
Esta incoherencia la podemos encontrar ahora en la pestaña CUPOS

Link (checkout): https://ebooking.com.ar/#/cupos-confirmados/finalizar-compra/628b8a2bd3093f6121f60f80?token=0214IT6BQ6&from=5a21b01efc2d5608730462bf

![image](https://user-images.githubusercontent.com/40358708/169828930-5d50255f-1aa5-45a9-8606-131ec86c2a1a.png)

Link (Avail): https://ebooking.com.ar/#/cupos-confirmados/detalle/620aa0b2405b4f1daca88873/punta-cana-desde-cor-con-bahia-pr%C3%ADncipe?from=5a21b01efc2d5608730462bf&quota=61ca0ee1932f4170b2e12fc6&token=0214IT6BQ6

Seleccione hotel Bahía Príncipe Grand Bavaro con esta disponibilidad

![image](https://user-images.githubusercontent.com/40358708/169829265-bdf20118-bfbf-4d33-a165-add4e7034387.png)

Gracias!

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad? Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Listo!

![image.png](https://images.zenhubusercontent.com/6154b05d87ee2058afd73e2b/8f59cba3-455a-4232-b154-a3070b7447fd)

Se verá reflejado en la próxima pubicación
