### ISSUE TITLE
[DISNEY] Filtro no funciona

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#359]
### Idea a implementar

Al ingresar a la pestaña Disney >> Paquetes, y seleccionar una propiedad, podemos encontrar un filtro en la parte superior

![image](https://user-images.githubusercontent.com/40358708/152041045-c5f812be-3b29-4f1a-9d57-bb20cb9ffc37.png)

Al tocar el botón MODIFICAR, aparece un cartel de página no encontrada

![image](https://user-images.githubusercontent.com/40358708/152041158-9763b189-3dfd-4cc1-b060-25192127bc30.png)

Link: https://ebooking.com.ar/#/disney/disponibilidad/5ca906bc86315a56f0cdd57e/hilton-orlando-lake-buena-vista-disney-springs-area-lake-buena-vista-US?checkIn=2022-04-14&checkOut=2022-04-19&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, este filtro no va a venir mas y estamos preparando un proyecto de rework en el sitio de Disney

Cierro issue
