### ISSUE TITLE
[Agencias] Botón borrar cliente y usuarios

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#362]
### Idea a implementar

Buenos días,
Sería excelente tener un botón para eliminar agencias y usuarios, ya que existen muchas duplicidades, y agencias y usuarios inactivos.

![image](https://user-images.githubusercontent.com/40358708/152801057-aa47e667-fe13-4207-a879-d87ae48f0b5e.png)

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Lamentablemente no podemos poner un boton para eliminar agencias o users

Está explicado en otras issues del mismo tipo

Saludos!
