### ISSUE TITLE
[TBO] Reserva JT Mock - no existe pero si en cancelador

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#364]
### Descripcion del error

Hola Chicos!

Tenemos la siguiente situación con una reserva. Originalmente, se tomó con el localizador GP7ON8. Pero la misma al quedarnos sin crédito, el proveedor la canceló, por lo que trajo una incidencia en destino.
Por consecuente, el proveedor levantó otra y a nosotros nos llegó en JT Mock. 
Cuando vimos a la Mock, intentamos cambiar todos los datos, para dejar confirmada y completa la misma (la primera cancelada sin gastos.) Dentro de la Mock modificamos nombre de agencia,el número de voucher, agregamos datos del otro pasajero y en la pestaña comparar propiedad quisimos agregar el nombre de la propiedad, y a partir de ahí, las reservas para el pasajero LUIS ALBERTO BORETTO no se encontraron o no las permite abrir (se intentó con otras canceladas y en error de distinto proveedor). Sumado a que aparece en el cancelador del optmizer la Mock (J5E59J), la cual NO debe figurar cancelada.
No puedo compartirles link, ya que no andan.
Reserva original que debe permanecer cancelada sin gastos y no permite abrir: **GP7ON8**
Reserva que levanto el proveedor que debe tener los datos de la de arriba: **J5E59J**
Nombre pax líder: **LUIS ALBERTO BORETTO**

Muchas gracias!

### Paso a paso para reproducir el error

n/a

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/152845478-410c911a-1b89-4e8d-a9c7-2d22e3d1df68.png)

![image](https://user-images.githubusercontent.com/87333634/152845683-a79231c1-954f-4d47-beec-dd66a6a1724e.png)

### Link al error y/o Localizador

n/a

### Plataforma

Google Chroome

**Comment by josecaserez** [comment]
Ya se corrigió la reserva **J5E59J**:
https://adm.ebooking.com.ar/bookings/detail/61fccd18643bbcb0161d6f5e?purchaseGroupId=369888#heading_61fccd18643bbcb0161d6f5e

Reserva **GP7ON8**:
https://adm.ebooking.com.ar/bookings/detail/61d9aec11c5189bc25a123ae?purchaseGroupId=369888#heading_61d9aec11c5189bc25a123ae

A futuro tratar de consultar con Gabriel Toselli o Jose Abraham si es posible pisar los datos de la reserva de Mock en la original.

Para buscar al pasajero notar que en el filtro Pasajero solo se puede buscar por apellido o nombre a pesar que en la lista de reservas se muestra el nombre completo, algunas veces se hacen búsquedas porque en la reserva quedo el nombre completo en campo nombre o campo apellido:

https://adm.ebooking.com.ar/bookings?dateFrom=2021-08-18&passenger=BORETTO
https://adm.ebooking.com.ar/bookings?dateFrom=2021-08-18&passenger=LUIS%20ALBERTO

**Comment by GuadaVivas** [comment]
Muchas gracias José! La proxima que necesita pasar datos de la real a la Mock, hago una issue, porque creo que desapareció cuando editamos el comparar propiedad. 
Saludos.
