### ISSUE TITLE
[VIVA WYINDHAM] Reservas en error 504 

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#365]
### Descripcion del error

¡Hola Chicos! Tengo 5 reservas de Viva Wyndham en estado revisar, los logs indican ERROR 504 y desde la propiedad me dicen que por lo menos una de ellas (el ejemplo que yo les envíe a ellos) está en estado confirmada en su sistema.

### Paso a paso para reproducir el error

-

### Captura del error

![ISSUE eror 504](https://user-images.githubusercontent.com/98116205/153050212-755dc26f-82f6-4937-8b0e-3e3371e7bc43.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61f4663ed679ad77cb6ce900?purchaseGroupId=375790#heading_61f4663ed679ad77cb6ce900

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, un error 504 es que su server se cayó

Recomiendo consultar al proveedor por el estado de las reservas indicándole el nombre del pasajero, estadía y hotel para que les confirmen que las reservas nunca se hicieron en su sitio

Saludos!

**Comment by mvalentinalucero** [comment]
Chicos, envìe el mail a viva tal como recomendaron y me indican que las reservas se encuentran confirmadas en su sitema. Adjunto foto 

![viva](https://user-images.githubusercontent.com/98116205/155523574-7e7f2efe-2304-4054-b5ed-0ee6ffae8773.png)

**Comment by gabrielmarinsaldaJT** [comment]
CHICOS DEJEN DE REABRIR ISSUES

Sobre el tema:

Ya que el provider nos confirmó que están OK, debemos proceder con cada reserva según corresponda

1. Si el vendedor va a querer la reserva, marcarla como confirmada y notificarle
2. Si el vendedor no la quiere, cancelarla o hacer lo que el vendedor quiera
3. Si la reserva entró en gastos, iniciar la gestión con el proveedor y demostrarle que la reserva dió error 504 cuando quisimos confirmarla
