### ISSUE TITLE
[ADM] Imposibilidad de exportar a Excel

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#367]
### Descripcion del error

Hola Chicos! Me escribe Marcelo de las casas y me comenta que no puede exportar al Excel desde adm. Yo probe desde mi adm y puedo perfectamente pero me dice que ni el ni Paula pueden hacerlo. Adjunto abajo captura del mail en el que comenta el problema. Y captura que me envia de su adm. 

### Paso a paso para reproducir el error

-

### Captura del error

![issue exportar excel](https://user-images.githubusercontent.com/98116205/153262215-e5a29530-edfc-42ef-8fdc-a48c43946a79.png)
![issue exportar excel 2](https://user-images.githubusercontent.com/98116205/153262240-2fff487a-364c-48c0-b02f-495da9b016c5.png)

### Link al error y/o Localizador

-

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Solved!
