### ISSUE TITLE
ERROR SIGN 

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#37]
Estimados buenas tardes,
Solicito nos puedan ayudar con la consulta realizada por Marce de las Casas,
Cristian Gulli esta teniendo inconvenientes con el voucher F942250 el cual en SistAgent figura con sign de Karla Rojas, al visualizarlo desde SQL en CprHead figura correctamente como adjunto en la siguiente imagen, pero así mismo en SistAgent sigue bajando mal con sign de Karla, aunque se sincronice o modifique desde la tabla,

![image](https://user-images.githubusercontent.com/45457355/127056689-9415a19d-9009-4dac-b479-ce2771a8ac99.png)

![image](https://user-images.githubusercontent.com/45457355/127057022-22a87435-112f-4b76-81e0-cad5a9c075ee.png)

Muchas gracias,
Juan Lavigne

**Comment by gabrielmarinsaldaJT** [comment]
Solved
