### ISSUE TITLE
Dejar Voucher en cero LOC 24797

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#370]
### Descripcion del error

Hola Chicos! La vendedora me pide dejar en 0 la reserva con LOC 24797, los pax tuvieron que cambiar fechas por covid positivo y la vendedora ha hecho la gestión offline con infinitas para modificar las fechas y por el monto de la diferencia de cambiar fechas. Lo que me pide es dejar el voucher en CERO. 

Gracias!

### Paso a paso para reproducir el error

--

### Captura del error

-
![voucher en cero](https://user-images.githubusercontent.com/98116205/153622223-ba7ad6b4-ab5e-4c72-b8f7-d0af3edde68b.png)
![voucher en cero 2](https://user-images.githubusercontent.com/98116205/153622238-7e6d18af-ee45-44f0-9970-de0163810a26.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6153cdedfd72f57d03d2c923?purchaseGroupId=359838#heading_6153cdedfd72f57d03d2c923

### Plataforma

Google Chroome

**Comment by djguille** [comment]
Reenviar este caso a Auditoria para que determinen como solucionarlo.
