### ISSUE TITLE
[Cruceros] No hay fotos en ningún crucero

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#376]
### Descripcion del error

Al realizar cualquier búsqueda en la pestaña cruceros de todas las plataformas, nos encontramos con que no hay ninguna imagen

### Paso a paso para reproducir el error

1. Entras al link
2. Verificar que ningún crucero tiene imagen 

### Captura del error

![image](https://user-images.githubusercontent.com/40358708/154273996-eaa63e73-6824-48b6-a326-1f4375631a98.png)
![image](https://user-images.githubusercontent.com/40358708/154274027-9da1ea25-2397-4b98-9294-6b426d065f3c.png)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/cruceros/buscar/6/caribe?nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD&minDuration=-1&maxDuration=-1&departureDateFrom=2022-05-01&departureDateTo=2022-05-31

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Hace rato venimos investigando esto y encontramos que es mas grave de lo que parece

Apenas tengamos la solución les avisamos

Saludos!

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos! Cómo va?

Levantamos las imágenes de Costa, estamos trabajando para levantar las del resto

Saludos

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes, 
¿Tienen alguna novedad? Sumado a la falta de fotos, ahora no es posible buscar cruceros en el Caribe.
![image](https://user-images.githubusercontent.com/40358708/199598961-d2e6eb05-0cf0-4086-b42b-8c355583acc2.png)
Gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Las issues de cruceros las pasamos a todas a nuestro backlog, ya que todas están contempladas para la reestructuración de Cruceros en eBooking

Cierro issue para evitar duplicidad

Saludos!
