### ISSUE TITLE
[Todas las plataformas] No funciona botón para ordenar el precio de manera ascendiente

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#377]
### Descripcion del error

Al realizar una búsqueda en cualquier servicio de cualquier plataforma de Toselli, aparece la opción para filtrar por precio de manera ascendente o descendente. Por defecto se ordena de manera descendente, pero al querer ordenarlo de manera ascendete, no funciona. 
Si este botón no va a ordenar más de manera ascendente, sugiero quitarlo como botón y dejarlo como solo texto. 

### Paso a paso para reproducir el error

1. entrar al link adjuntado (o realizar cualquier búsqueda en el administrador) 
2. Tocar "Precio" y verificar que no funciona

### Captura del error

![image](https://user-images.githubusercontent.com/40358708/154275546-0afe4374-4980-4b40-8599-fb65c75e6fb8.png)
![Uploading image.png…]()

### Link al error y/o Localizador

https://travel.tosellitours.com/#/alojamiento/buscar?id=5a21b157fc2d560873053fdc&name=las-vegas-y-sus-alrededores-nevada--estados-unidos&checkIn=2022-05-12&checkOut=2022-05-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Issue levantada para los chicos de front, no tiene sentido ordenar de mas cara a mas barata asique eliminaremos la flecha hacia abajo que genera confusión

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Gracias!

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Gracias
