### ISSUE TITLE
[CUPOS] Reserva cancelada que ocupa lugares.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#392]
### Descripcion del error

Estimados buenas tardes,
Poseemos esta reserva loc 867475 la cual está cancelada y aun así está ocupando espacio en los cupos registrados.

### Paso a paso para reproducir el error

1- Buscar reserva en ADM
2- Verificar cupos disponibles

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/154356945-6dd75ec5-fb8e-47dc-976f-16c2947920e0.png)
![image](https://user-images.githubusercontent.com/45457355/154356958-ad6c87c0-4a79-4e8b-ab4b-9bf38d7fba9c.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6193bda02b64a927fa630321?purchaseGroupId=366697#heading_6193bda02b64a927fa630321

**Comment by Jlavign** [comment]
¿Estimados buenas tardes,
Tendrán novedades?

**Comment by djguille** [comment]
Lo vimos con Gabriel Marinsalda y Andres Albuerne y ya esta solucionado
