### ISSUE TITLE
[Agencia PuntoAr] Mantenimiento página blanca

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#393]
### Descripcion del error

El día 14/01 envié a la casilla de Sistemas el pedido de cambios en su página blanca del cliente PuntoAr y no logré tener respuesta alguna.

![image](https://user-images.githubusercontent.com/40358708/154490947-73b00d7b-301d-4aad-b44d-9bf5f7307268.png)

Les realizo una issue por este medio para ver la posibilidad de solucionar este pedido del cliente. 
Paso en limpio:

- ¿Es posible que agreguen en forma de columna a la derecha la sección de cotizaciones que tienen en su página principal?.
- Cuando un usuario quiere ingresar al apartado de WhatsApp, la pagina lo redirecciona al inicio y no al link de nuestro chat.

Adjunto link del cliente.

### Paso a paso para reproducir el error

No lo sé

### Link al error y/o Localizador

https://adm.ebooking.com.ar/agencies/edit/59edd13c438ed857eca76055

**Comment by abrahamfariaz** [comment]
Buenos días, ¿Alguna novedad?
El cliente continúa a la espera
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Sobre lo que nos comentan.

¿Es posible que agreguen en forma de columna a la derecha la sección de cotizaciones que tienen en su página principal?.
A que se refiere con esto? Que cotizador?
Cuando un usuario quiere ingresar al apartado de WhatsApp, la pagina lo redirecciona al inicio y no al link de nuestro chat.
Abro issue para los chicos de front

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, ambas cosas son configurables desde el sitio

No sé quién es el encargado de hacerlas, pero cuando lo hagan, por favor notifiquennos para republicarles el sitio

Nota sobre el WhatsApp:

Por favor cargarlo como indica la sugerencia del sitio, no lo pongan asi nomas porque no está bien

![image.png](https://images.zenhubusercontent.com/6154b05d87ee2058afd73e2b/f478256b-cb64-4be8-a7a4-a3a454e6cd25)

![image.png](https://images.zenhubusercontent.com/6154b05d87ee2058afd73e2b/ccbde56b-0607-4679-9f16-d5be4b063924)
