### ISSUE TITLE
SOLICITUD DE LOGS

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#394]
### Descripcion del error

¡Hola Chicos! Necesito los logs de la reserva con loc 37430054 creada en el 2021 para enviarle a Marcelo de las Casas. 

¡Gracias!

### Paso a paso para reproducir el error

-

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/5fb3f77488d4646b874f1141?purchaseGroupId=351684#heading_5fb3f77488d4646b874f1141

### Plataforma

Google Chroome

**Comment by josecaserez** [comment]
Ya se cargaron, se pueden consultar en el historial de la reserva.
