### ISSUE TITLE
OPTIMIZER - CAMBIOS 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#396]
### Descripcion del error

Hola chicos,
Les traemos a colación la siguiente lista, para realizar algunas modificaciones en el Optimizer. Ustedes luego nos dirán si son viables, o no:

- [ ] Arreglar el **contador** del optimizer para que funcione cuando le aplicamos el filtro.
- [ ] De haber varios suplementos, dejar el que sea más abarcativo. Por ejemplo que tiene: Free breakfast / room only / All inclusive, que se visualice solo All inclusive. 
🚫 Si se incluye en la misma línea Free Breakfast, dejar únicamente Breakfast.
🚫 Si se incluye en la misma línea Full Breakfast, dejar únicamente Breakfast. 
🚫 Que no se muestren suplementos Free Wifi ni Free high - speed internet. 

Por el momento, solo esas.
Muchas gracias. 

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

Google Chroome

**Comment by GuadaVivas** [comment]
Hla Gabi,

Qué opinas que en la primera visualización del optmizer en vez que diga suplemento, se muestre el régimen de comida?

![image](https://user-images.githubusercontent.com/87333634/155582485-3e3bb08e-0c95-4cb1-bd78-e4c5578a11cf.png)

**Comment by GuadaVivas** [comment]
Hola Gabi,
Traigo otros puntos:

- [ ] En las reservas canceladas optimizadas, no borrar el suplemento en el adm. 
- [ ] En el apartado de reportes del optimizer agregar columna con el **Régimen de comida**

**Comment by GuadaVivas** [comment]
Hola Gabi! 
Te adjunto la imagen del error que encontramos: 
![image](https://user-images.githubusercontent.com/87333634/156588921-c1f9f7d4-1775-429f-8c25-009b3ef6d0e6.png)
Gracias!

**Comment by GuadaVivas** [comment]
Hola chicos!
Agrego a la issue, el meal planner siguen sin funcionar. 
En la mayoría, no trae el tipo de meal plan correspondiente a la que indica la reserva.
Gracias.

**Comment by gabrielmarinsaldaJT** [comment]
Hola Guada!!

Pasamos esta issue a nuestro Backlog

En cuanto Gabi Toselli lo crea conveniente lo veremos y lo haremos en un sprint

Saludos y muchas gracias!!
