### ISSUE TITLE
No puedo sincronizar voucher 

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#399]
### Descripcion del error

¡Hola Chicos!! No estoy pudiendo sincronizar el voucher de la reserva 8140964313. A pedido del vendedor hicimos una modificación en el costo de cancelación, pero no puedo sincronizarlo. 

¡Aguardo respuesta!

¡Gracias!

### Paso a paso para reproducir el error

-
![image](https://user-images.githubusercontent.com/98116205/155195368-fcf53650-f31f-4ad5-92ea-4da63ebdac74.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61a61ab046588464e8bb2320?purchaseGroupId=367121#heading_61a61ab046588464e8bb2320

### Plataforma

Google Chroome

**Comment by djguille** [comment]
Esto es algo que tiene que ver auditoria porque no se pueden sincronizar vouchers una vez pasada la fecha de check in o que tengan gastos de cancelacion.
