### ISSUE TITLE
FALLO AGENCIA VOUCHER

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#4]
Estimados buenas tardes,
Necesitamos ingresar la agencia al voucher LANDA MARIA INES
Yo intente pero no me permite y me informa sobre el siguiente error cuando intento hacerlo.

Adjunto url de reserva.

https://adm.ebooking.com.ar/bookings/detail/60aafde84a7c7ecbd6fc6e27?purchaseGroupId=355236#heading_60aafde84a7c7ecbd6fc6e27

![image](https://user-images.githubusercontent.com/45457355/124820739-3e3eb800-df44-11eb-8f0c-45ef319a5f97.png)

![image](https://user-images.githubusercontent.com/45457355/124820782-4ac31080-df44-11eb-8e99-fec4322d13e7.png)

**Comment by moliveto** [comment]
Esta agencia esta cargada con datos incompletos le falta el codigo de sistagen

![image](https://user-images.githubusercontent.com/1890103/124938589-cd98a980-dfde-11eb-8803-8bc0d1f4e21c.png)

**Comment by moliveto** [comment]
Este es un ejemplo en el cual esta cargada la agencia completa con codigo de sistagen

![image](https://user-images.githubusercontent.com/1890103/124938715-e86b1e00-dfde-11eb-959e-04ba8464d895.png)

**Comment by moliveto** [comment]
Codigo del sistagen que se deberia cargar en cliente para que se vinculen:

![image](https://user-images.githubusercontent.com/1890103/124939187-4a2b8800-dfdf-11eb-9c2c-a65ad106b077.png)

**Comment by moliveto** [comment]
Debes cargar el codigo ese en la agencia
