### ISSUE TITLE
[CUPOS] No dirige a grupo correcto.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#400]
### Descripcion del error

Estimados buenas tardes,
Al intentar ingresar a la reserva desde el cupo lleva a otra reserva inexistente.
Lo lleva al grupo 377923.

### Paso a paso para reproducir el error

1- Verificar Link de reserva

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/155404292-4b9dddc6-fbfe-45c2-9383-614de4546983.png)
![image](https://user-images.githubusercontent.com/45457355/155404307-9a397d9b-bb66-4437-9145-da6d66036118.png)
![image](https://user-images.githubusercontent.com/45457355/155404406-2322a65b-fc77-459a-a91f-dbe1d317faa3.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/airQuotas/edit/61ca0920932f4170b28ecb94

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Estamos trabajando en un fix grande para cupos y este issue está duplicado con uno que nos pasó la gente de Rosario

Eliminamos esta issue por duplicidad

Saludos!
