### ISSUE TITLE
[Agencias] Eliminar usuario

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#402]
### Descripcion del error

Hola chicos!

Favor eliminar usuario isabella@firenzeviajes.com, debido a que no pertenece más a la minorista. 
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/users/edit/59edd190438ed857eca79b01/59edd114438ed857eca7536e

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Fijense y cambienle el nombre o algo para evitar problemas

No vamos a eliminar más agencias/usuarios porque esto generó un problema de concurrencia y estuvimos varios días averiguando que era

A partir de ahora, les recomiendo que las renombren de otra manera para evitar confusiones en los filtros de los users

Saludos!
