### ISSUE TITLE
Roles - Adm

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#407]
### Descripcion del error

Hola Chicos! 

Les pedimos las siguientes modificaciones en cuanto roles y visualización de pestañas en el adm.

- [x] Pestaña blacklist: Se le quite la posibilidad a cualquier otro rol que no sea STAFFROOT, de visualizarla. 
- [x] Pestaña Configuración: Solo que la visualice STAFFROOT, la misma está vacía para otros roles. 
- [x] Pestaña reportes: solo para STAFROOT BI por agencias. BI por proveedores, BI por incidencias, BI por vendedores y BI Dashboard.

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/156369854-10e644f2-700f-44a5-af04-6958c9067f3a.png)
![image](https://user-images.githubusercontent.com/87333634/156369894-9f06faba-8a09-4746-90d8-d703898893a1.png)
![image](https://user-images.githubusercontent.com/87333634/156369947-64b4d404-855b-4042-80c1-096f302410e4.png)

### Link al error y/o Localizador

.

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos, cómo va?

Estos roles que indican son los correctos?

Pagos accede al optimizer para ver un reporte y el resto de las pestañas de reportes BI estamos nosotors y Directory

Está ok asi?

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Muchas gracias

**Comment by gabrielmarinsaldaJT** [comment]
Ok, chicos, no hay drama, lo dejo asi entonces

Pagos necesita entrar para verificar ciertas cosas de los Vouchers, me temo que no puedo sacarlos

Saludos!

**Comment by abrahamfariaz** [comment]
Hola Gabi,
¿Se podrá dejar entonces toda la parte de BI solo a los STAFFROOT?
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Hola Abe

Los reportes están para STAFFROOT, vos necesitás solo ese?

**Comment by abrahamfariaz** [comment]
Hola Gabi,
Los reportes están visibles también para STAFFADMIN, que la mayoría de la empresa tiene este rol y es peligroso que tengan acceso a esta información sensible.
Muchas gracias

**Comment by gabrielmarinsaldaJT** [comment]
Listo chicos!

Recuerden que pagos si puede acceder a las optimizaciones porque necesitan info de ciertos reportes

Saludos!
