### ISSUE TITLE
Estados inusuales: Ineedtoursightseeing + sabre

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#41]
Buenos días chicos,

Tengo la siguiente reserva en pendiente, tomada Test test de **Ineedtoursighseeing:** 

https://adm.ebooking.com.ar/bookings/detail/60df76e55130f17725425b6d?purchaseGroupId=357456#heading_60df76e55130f17725425b6d

 Podrán indicarme si la cancelarán o debo colocarla en Error?

**Y tengo la reserva de Sabre:**

https://adm.ebooking.com.ar/bookings/detail/60f1db1b2c73a78e8a2f520f

Podrán confirmarme si la coloco en Error inactualizable?
Contemplo el siguiente error en el log en método PassengerDetails: WARN.SWS.HOST.ERROR_IN_RESPONSE">EndTransactionLLSRQ: ITINERARY REQUIRED TO COMPLETE TRANSACTION</Message></SystemSpecificResults></Warning>

Gracias :)

**Comment by moliveto** [comment]
@GuadaVivas necesito splitear el issue
Ineedtoursighseeing para @julianbenegaslane 
Sabre para @gabrielmarinsaldaJT

**Comment by GuadaVivas** [comment]
Hola Marce, necesitas que te haga issues distintas ahora y esta la cierre?

**Comment by gabrielmarinsaldaJT** [comment]
@GuadaVivas Cómo estás?

Te cuento que desde Sabre podés ponerla en error.

Devolvió lo siguiente:

`<Warning timeStamp="2021-07-16T15:24:01.949-05:00" type="BusinessLogic">
					<SystemSpecificResults>
						<Message code="WARN.SWS.HOST.ERROR_IN_RESPONSE">EndTransactionLLSRQ: ITINERARY REQUIRED TO COMPLETE TRANSACTION</Message>
					</SystemSpecificResults>
				</Warning>
				<Warning timeStamp="2021-07-16T15:24:01.977-05:00" type="BusinessLogic">
					<SystemSpecificResults>
						<Message code="WARN.SWS.HOST.ERROR_IN_RESPONSE">EndTransactionLLSRQ: ITINERARY REQUIRED TO COMPLETE TRANSACTION</Message>
					</SystemSpecificResults>
				</Warning>`

Intenté replicarlo pero ya no puedo porque la tarifa parece ser que no existe más

**Comment by gabrielmarinsaldaJT** [comment]
Para futuros casos, recomiendo hacer lo que indica @moliveto 

Hacer una issue por cada caso y por cada proveedor diferente

Saludos

**Comment by GuadaVivas** [comment]
Chicos, listo, solucionado. Cierro issue, gracias.
