### ISSUE TITLE
[Usuario] Eliminar

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#412]
### Descripcion del error

Hola Chicos!

Por favor, eliminar el siguiente usuario:

https://adm.ebooking.com.ar/users/edit/59edd1bc438ed857eca7a86f/59edd151438ed857eca76694

gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/users/edit/59edd1bc438ed857eca7a86f/59edd151438ed857eca76694

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Usuario seteado como inactivo

Recomiendo que a partir de ahora los comencemos a setear de esta manera para evitar errores de concurrencia en MongoDB

Saludos!
