### ISSUE TITLE
[Jumbo] Modificar costo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#417]
### Descripcion del error

Hola chicos!
Necesitamos modificar el costo de una reserva, que se encuentra optimizada y no está pagada al proveedor.
Lo solicita Paula Loschi del área de pagos
Hay que modificarle a **6.449,12** usd 
El cambio de costo es a raiz de devoluciòn del proveedor por una reubicación. 
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61efe6759d663514c54079b8?purchaseGroupId=375193#heading_61efe6759d663514c54079b8

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Saludos.

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado

Le seteamos el precio indicado y la pusimos como inactualizable, ya que Jumbo nos vuelve a dejar el precio como estaba
