### ISSUE TITLE
[Restel] Logs por incidencia

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#419]
### Descripcion del error

Hola chicos!
Podrán brindarnos de la reserva **38369093** el log de la reserva para reclamarle al proveedor, ya que la misma fue confirmada en Santa Cruz y debería de haberse confirmado en Bariloche. 
Es una incidencia por error de mapeo. 
Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/157754926-9b6efef7-50d2-40a8-8566-c5475e9a3781.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/61d4753acf11f4b69a8f13d6?purchaseGroupId=373120#heading_61d4753acf11f4b69a8f13d6

### Plataforma

.

**Comment by josecaserez** [comment]
Los logs se encuentran en el historial de la reserva: 
https://adm.ebooking.com.ar/serviceLogs/list?basketId=61d47538cf11f4b69a8f0d1f

Lo mas importante es remarcar que tanto en Avail como en los GetBooking aparece como código de hotel **991475**, que en ese momento según su data estática figuraba:

"PropertyCodes","HotelName","CountryCode","CountryName","CityName","Address","State","Locality","Zip","Stars","Latitude","Longitude","Phone","Email","Rooms"
"991475","PATAGONIA HOTEL","AG","","RIO GALLEGOS","AV EZEQUIEL BUSTILLO 1231","SANTA CRUZ - PATAGONIA","","R8400",3",-41.131405,"-71.324585"," / 054 2966 444 970 INT","","44"

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Reclamen con éstos logs

[RQ.txt](https://github.com/toselli/issues/files/8652154/RQ.txt)
[RS.txt](https://github.com/toselli/issues/files/8652155/RS.txt)

Saludos!
