### ISSUE TITLE
[HYD] Logs

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#427]
### Descripcion del error

Hola chicos!

Solicitamos los logs de cancelación, de la siguiente reserva. 
(Creemos que por la fecha, no se van a encontrar).
Reclama el proveedor al area de pagos. 

Gracias!

### Paso a paso para reproducir el error

 .

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/5e0513f6b0985c8955724960?purchaseGroupId=307897#heading_5e0513f6b0985c8955724960

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Equipo,

Alguna novedad?

Gracias!

**Comment by GuadaVivas** [comment]
Se cierra issue, no van a haber logs.
