### ISSUE TITLE
[VivaWyndham] Modificar costo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#428]
### Descripcion del error

Hola chicos!

Necesitamos modificar el costo de una reserva optimizada debido a que se le quitó una noche a la reserva.
Auditoria nos envió el siguiente correo, demostrando como debería de quedar el cambio:

![image](https://user-images.githubusercontent.com/87333634/159076549-4f6a032d-dfaa-442f-af34-05015f15e446.png)

Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/620e32f85858bf664b16fb31?purchaseGroupId=365421#heading_620e32f85858bf664b16fb31

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Estimados,

Nos solicitan nuevamente el cambio, esperamos novedades.

Gracias.

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos.

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos.

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos.

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos.

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos.

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos.

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos.

**Comment by gabrielmarinsaldaJT** [comment]
Listo chicos!
