### ISSUE TITLE
Error de CORS en auto/provider

### ISSUE THREAD

**Issue by IvanFacundoRosas** [toselli/issues#429]
**Cómo reproducir**
Correr adm local -> pegarle a muldermapping en skynet
Ejecutar el mapeo automático en restelhotel

**Screens**
![image.png](https://images.zenhubusercontent.com/6155ae8aac087248d9523339/d517b457-9031-4261-a74d-b5847adc5256)
![image.png](https://images.zenhubusercontent.com/6155ae8aac087248d9523339/b0fb5746-422a-4725-8527-56bcc9364c7e)

**Posible causa**
No están permitidos todos los orígenes en el controller "auto". Revisar la configuración de los otros contollers.

**Comment by julianbenegaslane** [comment]
solucionadinsimo en toselli/tensor-mapping#ea4876b
