### ISSUE TITLE
Modificar Ebooking/Toselli Tours campo con titulo erroneo

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#43]
**Describe the bug**
Donde dice NOMBRE DEL HOTEL deberia decir NOMBRE DE LA ATRACCION
ya que estamos dentro de la pestaña atracciones, y ese es el filtro para buscar una atracción especifica en una ciudad. 

SD

**To Reproduce**

Link: 
https://travel.tosellitours.com/#/atracciones/buscar?destinationId=5a21b159fc2d560873053fe7&destinationName=san-francisco-y-sus-alrededores-california--estados-unidos&fromDate=2021-10-31&toDate=2021-11-01&nationality=GT&residence=GT&occupancies=2*30,30*0*&disney=false&currency=U

**Expected behavior**
Donde dice NOMBRE DEL HOTEL deberia decir NOMBRE DE LA ATRACCION

**Screenshots**
![image](https://user-images.githubusercontent.com/88200755/127673962-c1283502-bd65-4424-b4f3-6cf5c627b012.png)

**Desktop (please complete the following information):**
 - Browser [CHROME]

**Additional context**

**Comment by ivanpuglia** [comment]
@gabrielmarinsaldaJT cuando puedas vemos esto porque al parecer el texto del titulo no esta en la UI y no se por donde lo busca
