### ISSUE TITLE
europamundo error al confirmar

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#433]
### Descripcion del error

Hola chicos, puden por favor chequear el motivo de porque dio erro reste tour al tomarlo?
Grupo Ebooking: 384288
Gracias
Nati 

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/160464521-e127f983-095a-451e-a9af-772eead1e0d8.png)

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!
