### ISSUE TITLE
Europamundo 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#434]
### Descripcion del error

Tour no figura en ebooking y si en europamundo 
Nombre del tour: 
España de Norte a Sur 

### Paso a paso para reproducir el error

Filtre por pais: españa
por proveedor: europamundo
por nombre de circuito: norte

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/160473359-bc4842b1-0043-4586-b34f-351699d02ea6.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/circuitos/buscar?cities=&countries=ES&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=norte&nationality=AR&residence=AR&currency=EUR

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Hola Nati!

Solucionado

Saludos
