### ISSUE TITLE
[Hoteltrader] RESERVAS CON DIFERENCIA NO SE CANCELAN 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#435]
### Descripcion del error

Hola chicos!

Tenemos reservas de Hoteltrader con estado **Con Diferencia** , desconocemos la naturaleza del mismo, pero desde la propiedad nos indican que la tienen activa, es decir que no se autocancelan (las no cobradas tienen el autocancel) En el proveedor, también las vemos activas. Todas las que estan bajo este estado es para el hotel The Row.
Vemos en notas tienen "Al actualizar el BeginService y EndService el periodo de reserva cambio de 28/3/2022 00:00:00-31/3/2022 00:00:00 a 28/3/2022 16:00:00-31/3/2022 12:00:00. Si desea confirmar este cambio, hagalo manualmente."
En este caso debemos tratarlas como reservas confirmadas y pasarlas a este estado? 
Se podrá reclamar al proveedor algún intento de GetCancel? (Esto no lo visualizo en los logs)
Abajo les dejo el link de ejemplo de 3 con check in pasado.

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62391f4a241aabbc379c4786?purchaseGroupId=383498#heading_62391f4a241aabbc379c4786 / https://adm.ebooking.com.ar/bookings/detail/622f741e9f01deb473c4bfe0?purchaseGroupId=375874#heading_622f741e9f01deb473c4bfe0 / https://adm.ebooking.com.ar/bookings/detail/6231e8d5ef2ed801d1d71f77?purchaseGroupId=381494#heading_6231e8d5ef2ed801d1d71f77

**Comment by GuadaVivas** [comment]
Hola chicos! 
Sumo a esto, las políticas de cancelación de HotelTrader, no están siendo las mismas que muestran ellos en su web. Unas tenemos un día después y otras tenemos hasta tres días después:
Aquí adjunto ejemplos de algunas:

- https://adm.ebooking.com.ar/bookings/detail/62324a5aef2ed801d1e4c723?purchaseGroupId=376833#heading_62324a5aef2ed801d1e4c723
- https://adm.ebooking.com.ar/bookings/detail/6245bde69571170c2ce0fb86?purchaseGroupId=384754#heading_6245bde69571170c2ce0fb86
- https://adm.ebooking.com.ar/bookings/detail/62437d069571170c2c7d7505?purchaseGroupId=384512#heading_62437d069571170c2c7d7505
- https://adm.ebooking.com.ar/bookings/detail/6233df11483b945803836f2b?purchaseGroupId=383034#heading_6233df11483b945803836f2b

**Comment by BelenBidondo** [comment]
Buen día
alguna novedad con respecto a estos casos?
algunas reservas tienen fecha de cancelación en los próximos días
saludos

**Comment by mvalentinalucero** [comment]
Chicos buenas tardes alguna novedas sobre esto?

**Comment by mvalentinalucero** [comment]
Hola chicos, alguna novedad? Veo que las reservas son pasadas. De todas formas, por que hay esa diferencia en las políticas de cancelación?

**Comment by mvalentinalucero** [comment]
Hola chicos, alguna novedad? Veo que las reservas son pasadas. De todas formas, por que hay esa diferencia en las políticas de cancelación?

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

hemos hecho un cambio con el proveedor hoteltrader

A partir de ahora ya no tendremos mas problemas

Saludos!
