### ISSUE TITLE
[Ebooking] Cambio de tarifas

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#436]
### Descripcion del error

Hola chicos, 
Les traigo un inconveniente de cambio de tarifas en el ebooking.
Muchas gracias.

### Paso a paso para reproducir el error

1) Se realiza la busqueda, y queremos seleccionar el hotel Barceló 
![image](https://user-images.githubusercontent.com/87333634/160849248-ca4e29fd-a060-4f4d-9670-2387270b42e7.png)
2) Selecciono la búsqueda y el costo de la reserva cambia bastante:
![image](https://user-images.githubusercontent.com/87333634/160849737-befe46d4-b0b1-4fdd-b9fc-18a932795632.png)

### Captura del error

.

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8c33986315a56f0bb5215/barcelo-bavaro-beach?checkIn=2022-12-06&checkOut=2022-12-13&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Solucionado!
