### ISSUE TITLE
[Ebooking] Visualización de factura

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#437]
### Descripcion del error

Hola chicos!

Nos llega un reporte de error de una agencia que no puede visualizar las facturas con su usuario. Nosotros hemos intentado cambiarle la clave pero entramos a su cuenta y efectivamente no las visualiza.
Por otro lado, entrando con nuestras cuentas personales, si podemos verlas a las últimas.
Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/160852224-21342580-4c33-4afc-b02b-9815ca49fb90.png)

![image](https://user-images.githubusercontent.com/87333634/160852039-94a0bd88-ea0c-4970-a543-15906406b594.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/mi-cuenta/mis-facturas

**Comment by abrahamfariaz** [comment]
Buenos días, ¿Tienen alguna novedad de este caso?
Muchas gracias

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Ingresé al usuario de la agencia y puedo verlas normalmente

Saludos!
