### ISSUE TITLE
[Mail de cancelación] En reservas cobradas

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#439]
### Descripcion del error

Hola chicos!
Tenemos varios casos que reclaman, que de reservas confirmadas, cobradas, le llega al vendedor y agencia el mail de reserva próxima a caducar.
Aquí les comparto algunos localizadores de ejemplos:
933012
935828
935985
937361 
945832 

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by GuadaVivas** [comment]
Hola chicos! 
 Para sumar al reclamo de los mails, también llegan avisos de reserva a caducar sobre las que ya estan canceladas, ejemplo: 936414
Gracias.

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

@josecaserez está con este tema y lo hemos solucionado

Ante cualquier nueva eventualidad, ruego nos avisen

Saludos!
