### ISSUE TITLE
[170 reservas en un grupo ] Modificar cantidad 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#440]
### Descripcion del error

Hola chicos!
La agencia introdujo 170 reservas en un mismo grupo **382002**. No puede abrirlas y nosotros tampoco. 
Solicitamos por favor que las mismas se separan en grupos distintos. Ya le dimos aviso que no coloquen mas de 20 en un mismo grupo.
Por otro lado, ver la forma que el sistema, al tomar una reserva, te impida seguir agregando más de 20 reservas en un mismo grupo.
Gracias! 

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2021-09-30&purchaseGroupId=382002

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Estimados.

Alguna novedad?

Saludos!
