### ISSUE TITLE
[Ebooking] Impuesto PAIS y RG (Front y Back)

### ISSUE THREAD

**Issue by djguille** [toselli/issues#443]
### Idea a implementar

A continuación, te detallo mi solicitud de ajuste sobre  frond end y en el Admin vinculado a la carga de productos internacionales que conllevan impuesto PAIS y RG  
•	A nivel back end 
 
Agregar 2 columnas que se identifiquen de la siguiente manera. Una que sea para agregar 
30% IMPUESTO PAIS 
35% RG SUGERIDOS EN AÉREO 

 y la otra para agregar
30% IMPUESTO PAIS 
35% RG SUGERIDOS EN SERVICIOS TERRESTRES 
![image](https://user-images.githubusercontent.com/18582394/161266861-fcff0f5d-bd7d-410f-a44f-cf6c37a5eac6.png)

•	A nivel front end se deberían mostrar las dos columnas con los importes ingresados a nivel back end. 
Arriba de ambas columnas debería decir DEBÉS SUMAR ESTOS IMPUESTOS SI ABONÁS EN AR$ 
Luego, cada columna debería estar titulada de la siguiente manera: 
30% IMPUESTO PAIS 
35% RG SUGERIDOS EN AÉREO 
 

30% IMPUESTO PAIS 
35% RG SUGERIDOS EN SERVICIOS TERRESTRES 
 
 A modo de ejemplo, debería verse así
![image](https://user-images.githubusercontent.com/18582394/161267127-c663dab3-a4ae-4f8d-8185-f66760be36a8.png)

Esto lo solicita Sebastian Chirino
Saludos.

**Comment by gabrielmarinsaldaJT** [comment]
Done!
