### ISSUE TITLE
reservas circuitos Wamos quedan como pendientes 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#444]
### Descripcion del error

Hola chicos, como estan? las reservas de circuitos de Wamos quedan como pendientes, les consulté a ellos, y en sus sitema estan ok.
Voy a proceder a cancelar una, pero necesitaria que la 385290 quede activa y con status confirmado para poder liquidarle a la agencia.
Gracias!

### Paso a paso para reproducir el error

Se completa la reserva
Queda en status pendiente

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/161757339-86dbd8f5-cb05-4bf9-b6cd-f096dacc1b9f.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2021-10-05&provider=WAMOS

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Solved!!
