### ISSUE TITLE
[Enterprise] MODIFICAR VOUCHER

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#447]
### Descripcion del error

Hola Chicos!

Solicitamos, por favor, actualizar en el adm, para luego sincronizar el voucher, la oficina de retiro y devolución del auto de la reserva **1635209354COUNT**

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/161846425-cff1eb4b-d82c-4f65-a9e9-cd5d1e7d6714.png)
![Uploading image.png…]()

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/623259caef2ed801d1ef9bbc?purchaseGroupId=380894#heading_623259caef2ed801d1ef9bbc

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Estimados.

Alguna novedad?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Done!
