### ISSUE TITLE
Reserva de Wamos tiene como costo el precio de venta

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#449]
### Descripcion del error

Hola chicos, estoy vuendo que el precio de venta que muestra wamos, a nosotros nos los muestra en Ebooking como neto y sobre eso lo esta marcando. 
Por otro lado hay unas tax obligatorias que deben ir en Impuestos, en este caso de U$d 108 que no las esta sumando. 

Tarifa al pasajero: 
![image](https://user-images.githubusercontent.com/88200755/162027340-7a0b8911-4e31-439c-90a2-25e455d9d2ce.png)

Detalle mayorista: 
![image](https://user-images.githubusercontent.com/88200755/162027388-3126e405-b952-4613-87f5-19f587082cc8.png)

Localizador de ebooking: 
3324736

### Paso a paso para reproducir el error

.

### Captura del error

Ebooking: 
Costo: 
![image](https://user-images.githubusercontent.com/88200755/162027635-04ac4376-77b0-4247-884f-1fe84198f53f.png)

Venta: 
![image](https://user-images.githubusercontent.com/88200755/162027694-656729a2-89a6-47fa-9fda-586660e5deff.png)

### Link al error y/o Localizador

.

**Comment by mvalentinalucero** [comment]
Chicos sumo la siguiente reserva con el mismo inconveniente: 

Loc 3358232

![image](https://user-images.githubusercontent.com/98116205/168661060-2bdc3064-a403-41d1-8039-314e8efa0ed9.png)

![image](https://user-images.githubusercontent.com/98116205/168661139-57639adb-d083-43ce-acf1-dcc6ffdbb294.png)

![image](https://user-images.githubusercontent.com/98116205/168661192-81001687-56f1-48ce-a7fe-48d22d79cd6f.png)

**Comment by mvalentinalucero** [comment]
Chicos buenas tardes,

Sumamos siguiente rva 

![image](https://user-images.githubusercontent.com/98116205/171722908-4f845953-94a2-4c48-85e3-7158f9a3acca.png)
![image](https://user-images.githubusercontent.com/98116205/171723168-22326ecf-74d2-40e6-b598-5e3ac21cb582.png)
![image](https://user-images.githubusercontent.com/98116205/171723210-5e204b0c-f14b-4882-b9ac-6b6cd2f72e40.png)

**Comment by mvalentinalucero** [comment]
Chicos buenas tardes, alguna novedad sobre estas diferencias?

**Comment by gabrielmarinsaldaJT** [comment]
Listo!
