### ISSUE TITLE
Agencia inexistente SistAgent

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#46]
Estimados buenas tardes.
El motivo de la presente es para solicitarles ayuda para encontrar a la agencia **Asociacion Mutual Farmaceutica Florentino Ameghino ( AMFFA)** en el SistAgent, el código de la misma es A4855, pero con él o los datos asociados no devuelve resultados.
El CUIT es 30571014803 

Desde ya, gracias chicos!
Saludos,
Agostina

**Comment by moliveto** [comment]
Listo @agostinaf25
