### ISSUE TITLE
[Iberostar] Modificar moneda

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#468]
### Descripcion del error

Hola chicos!

Desde pagos nos solicitan que modifiquemos la moneda de la reserva, de Euros a Dolares. Intentamos hacerlo por la base, pero no pudimos.
Por el otro lado, en los logs la moneda esta en USD.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/620cee81103ab3c60a04fe7b?purchaseGroupId=377938#heading_620cee81103ab3c60a04fe7b

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado! ✅
