### ISSUE TITLE
[Assit Card] Reservas en Revisar 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#469]
### Descripcion del error

Hola chicos!

Al tomar reservas con assist card nos trae en un error, quedando en revisar ";Balance error for pre purchase of agency 2007".
Consultamos con el proveedor y efectivamente no termina de realizarse. 
Abajo dejo la respuesta de ellos, del error por integración.
Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/164244612-58f20315-1c98-47dc-8087-16d526004bcf.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/625ecd08e05c66c9290399f8?purchaseGroupId=386509#heading_625ecd08e05c66c9290399f8

### Plataforma

Google Chroome

**Comment by GuadaVivas** [comment]
Cualquier cosa reenviamos, el correo a Sistemas

**Comment by julianbenegaslane** [comment]
a hacer:
- [ ] ignorar tarifas de precompra
- [ ] mostrar titulo de tarifa acompañando a titulo de producto

**Comment by julianbenegaslane** [comment]
arreglado para proxima publicacion
