### ISSUE TITLE
[Travel Tosell Tours] No se visualizan imagenes

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#470]
### Descripcion del error

Hola chicos!
Queremos reportar que cuando seleccionamos la propiedad, no figura la imagen de la misma.
Les dejo unos ejemplos:

- [ ] https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca944b886315a56f0d58f87/red-roof-inn-hilton-head-island?checkIn=2022-05-12&checkOut=2022-05-15&nationality=US&residence=US&occupancies=2*30,30*0*&currency=USD
- [ ] https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca97ffe86315a56f0dad8c8/home2-suites-by-hilton-hilton-head?checkIn=2022-05-12&checkOut=2022-05-15&nationality=US&residence=US&occupancies=2*30,30*0*&currency=USD

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/164295836-622e16e6-9851-4a37-bb11-0d20d6b84032.png)
![Uploading image.png…]()

### Link al error y/o Localizador

https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca944b886315a56f0d58f87/red-roof-inn-hilton-head-island?checkIn=2022-05-12&checkOut=2022-05-15&nationality=US&residence=US&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Al parecer unas fotos que se bajan de Expedia son con un formato no permitido por nuestro server

Las hemos modificado y ahora se ven correctamente

Saludos!

**Comment by abrahamfariaz** [comment]
Hola Gabi!
En uno de los ejemplos que te pasamos, sigue sin visualizarse aún

![image](https://user-images.githubusercontent.com/40358708/169851597-2d84c6c1-e546-43be-8b91-22b901f7175a.png)

Te paso nuevamente el link de este ejemplo: https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca944b886315a56f0d58f87/red-roof-inn-hilton-head-island?checkIn=2022-06-17&checkOut=2022-06-21&nationality=US&residence=US&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Ya revisamos el caso perp Expedia no tiene fotos para ese hotel en particular

Si quieren pueden cargarlas a mano

Necesito que me pasen un comprimido con no mas de 20 fotos y lo subimos

Saludos!
