### ISSUE TITLE
[Toselli Tours] Actualizar imagen 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#472]
### Descripcion del error

Hola chicos!

Solicitamos eliminar la siguiente imagen de traveltosellitours, debido a que es antigua:
![image](https://user-images.githubusercontent.com/87333634/164482851-5dab5985-c688-4775-9b2f-781e518cc19d.png)
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://travel.tosellitours.com/#/

### Plataforma

Google Chroome

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Done it!
