### ISSUE TITLE
[764573] Correos a usuario de Evangelina

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#473]
### Descripcion del error

Chicos buenas tardes,

Necesitamos de su ayuda ya que todos los días le llega al usuario de Karla, el voucher de la reserva **764573**. Como Karla no está mas, se derivan al correo de Evangelina Irigoyen.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/5fa04c598d09ff68c4ebae03?purchaseGroupId=340474#heading_5fa04c598d09ff68c4ebae03

**Comment by gabrielmarinsaldaJT** [comment]
Hola Guada!

Pueden modificar el vendedor y el usuario de la reserva si lo desean

Con ésto, ya no debería llegarle mas el mail a Karla Rojas

Saludos!
