### ISSUE TITLE
No arroja resultado de I Need Tours en Traslados

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#474]
### Descripcion del error

la busqueda de raslados en una ciudad importante (madrid) n arroja resultados de I Need Tours, y en el sistema de ellos, figura ok la busqueda

Tambien me notofocaron los vendedores que no arroja resultaods en Atracciones

### Paso a paso para reproducir el error

Cotizar un traslado y al realizar la busquesda, no arroja el resultado

![image](https://user-images.githubusercontent.com/88200755/164721264-34849ebc-5e4f-4bb4-bfd9-9baf05102043.png)

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/164721161-057fdd89-7f6c-4512-a6c3-a246f61e7212.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/traslados/buscar?transferType=0&landingTime=true&arrivalDate=2022-05-22&arrivalTime=23:45&arrivalPointDataId=5cc2b77d17d9690b0443c34c&arrivalPointDataName=riu-plaza-espana-madrid--spain&arrivalPointDataSmartSearchEnum=1&destinationPointDataId=MAD&destinationPointDataName=madrid-spain-mad-barajas&destinationPointDataSmartSearchEnum=3&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Hola Nati! Cómo estás?

Levantado el mapeo con INeedTours

Podrías chequearlo porfas?

Saludos
