### ISSUE TITLE
Special Tours - hay un tur queno figura 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#476]
### Descripcion del error

Tour Special Tours no figura, 
Pero el proveedor esta activo en Ebooking, arroja otros resultados

### Paso a paso para reproducir el error

Tanto filtrando por pais (Noruega) 
como filtrando por proveedor no arroja este tour "Todo Fiordos"
Incluso arroja otros tours de este destino/operador, pero este no
En ambos filtros, arroja otros resultados
Codigo del tour ST22257

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/164943086-0e431769-3298-4261-a140-0569290f8f2f.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/circuitos/buscar?cities=&countries=NO&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=&nationality=AR&residence=AR&currency=USD&page=1

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Hola Nati, no tengo ningun tour de Special con ese código

Serías tan amable de pasarme un código exacto?

**Comment by gabrielmarinsaldaJT** [comment]
Nati, tenés el code?

**Comment by gabrielmarinsaldaJT** [comment]
Hola Nati!

Levantamos varios ahora con el nombre Todo Fiordos

Podrías revisar porfas?

Saludos
