### ISSUE TITLE
[Tosell Tours] Disney

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#477]
### Descripcion del error

Hola chicos!
Reporto lo siguiente. 
Del siguiente link, como ejemplo, dentro del servicio Disney,  cuando seleccionamos una propiedad para el paquete de disney, **no trae la opción de los tickets.** Podrán ver esto cuando pasan a la página del check out.
Por otro lado, necesitamos que traiga la **misma cantidad de resultados**, que otras pestañas, porque actualmente trae dos. En las páginas siguientes, también muestra dos opciones de alojamiento.
Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/165389778-5994f99b-6523-4870-b9f6-4a38edd32b34.png)
![image](https://user-images.githubusercontent.com/87333634/165389982-7fca2b84-2994-4486-9fbb-4215518400e8.png)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/disney/buscar?id=5aa7dd3f3dfcee50fc39c792&name=orlando&checkIn=2022-05-19&checkOut=2022-05-23&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chroome

**Comment by GuadaVivas** [comment]
Se solucionó.

**Comment by abrahamfariaz** [comment]
Buenos días,
Esto no está solucionado. Brindo dos ejemplos en los cuales no se puede proseguir

**Ejemplo 1:** https://www.ebooking.com.ar/#/disney/disponibilidad/5ca8e86186315a56f0c8a443/wyndham-garden-lake-buena-vista-disney-springs-resort-area-lake-buena-vista-US?checkIn=2022-08-25&checkOut=2022-08-30&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/40358708/181282650-440bc6f1-758d-4067-a5dc-3f90b31d1664.png)

Ejemplo 2: **** https://www.ebooking.com.ar/#/disney/disponibilidad/5ca8c8c586315a56f0bf7cb5/disney-s-all-star-music-resort-lake-buena-vista-US?checkIn=2022-08-25&checkOut=2022-08-30&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/40358708/181283036-1c649226-3c0b-4f13-8681-9f603a966132.png)

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Cierro issue ya que es el mismo problema que la #600

Lo seguimos en esa

Saludos
