### ISSUE TITLE
[Ebooking] Disponibilidad de TBO

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#478]
### Descripcion del error

Hola chicos!
Queremos reportar que con , por lo que vemos, en la disponibilidad de TBO, muestra un cartel grande, que estéticamente no queda optimo y puede generar hasta confusión visual.
Por el momento vemos que sucede con este proveedor.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/165557894-9d1cbd1a-45fd-49ec-b11f-4194e038f6bb.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca8d67f86315a56f0c471c4/live-aqua-beach-resort-cancun-cancun-mexico?checkIn=2022-07-14&checkOut=2022-07-19&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
@IvanFacundoRosas @ivanpuglia 

Se podrá comprobar que el Lenght de esos mensajes no sea de un determinado tamaño que rompa el cuadro del front?
Es decir, si es mayor a X cantidad de caracteres, directamente no lo muestren

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Solucionado

**Comment by abrahamfariaz** [comment]
Buenas tardes Gabi, ¿cómo estás?
Te adjunto el mismo link en la misma propiedad que te brindo Guadalupe pero con otras fechas para que puedas observar cómo el inconveniente persiste aún:
![image](https://user-images.githubusercontent.com/40358708/185208575-f903ea51-4b8a-42df-8db9-901cd693ebf7.png)

Link: https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca8d67f86315a56f0c471c4/live-aqua-beach-resort-cancun-cancun-mexico?checkIn=2022-11-17&checkOut=2022-11-23&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

Además, veo que no es solo con TBO sino  con Abreu también 

![image](https://user-images.githubusercontent.com/40358708/185208686-2bd72b4a-fa26-48d9-8a84-e4b7a6859727.png)

Muchas gracias

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, cómo va?

Olvidé avisarles que lo verían después de la próxima publicación! 😄 

Revisé en nuestro entorno local y sí está solucionado

Disculpen el malentendido

Saludos
