### ISSUE TITLE
[Ebooking] Disney 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#479]
### Descripcion del error

Hola chicos!
¿Podrán por favor indicarnos y chequear, si Abreu Disney está integrado? ¿Y si debería de estar mostrando la disponibilidad?
Muchas gracias.

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/disney

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

AbreuDisney está deshabilitado desde el 22 de Diciembre de 2021
No sabemos porqué, pero cuando un proveedor se deshabilita es porque nos han solicitado hacerlo

Saludos!
