### ISSUE TITLE
Consulta de Fechas

### ISSUE THREAD

**Issue by moliveto** [toselli/issues#48]
https://adm.ebooking.com.ar/tours/edit/5ebea1b567716b9eeb03647b

![image](https://user-images.githubusercontent.com/1890103/128183545-8def24c2-4316-41b9-a0b6-80ba7999ddf0.png)

**Comment by aletatan** [comment]
@moliveto necesitaria algo mas de informacion de tu parte como para poder darte soporte
gracias!
