### ISSUE TITLE
Reserva No reembolsable. Políticas de cancelación. 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#49]
Buenas tardes chicos, 

Tengo la siguiente reserva:
 https://adm.ebooking.com.ar/bookings/detail/60c3f00cb431eac483b664c3?purchaseGroupId=349443#heading_60c3f00cb431eac483b664c3 
Está como no reembolsable.
La misma originalmente fue tomada reembolsable con Nuitee y la ultima que es de Restel la trajo así. La vendedora ahora pide cancelar y de Restel nos indican que efectivamente es no reembolsable y eso implica tener que negociar la cancelación sin gastos.
Habrá alguna forma de saber por qué se tomo no reembolsable o si hay algún error por parte de Restel que trajo la reserva así, y reclamamos? 

Gracias!

**Comment by josecaserez** [comment]
Consulte el historial de la reserva y en el metodo **GetCancellationPolliciesResponse** cuando se busco decia que tenia gastos de cancelación recien 3 dias antes:

**_"En caso de cancelación con menos de 3 dias de la entrada del cliente el hotel facturará 100 % de la estancia."_**

Sin embargo, despues de la primera actualización despues del checkout, en el metodo **GetCancellationPoliciesAfterCheckOutResponse** se paso a que tiene gastos de cancelación:

_**"En caso de cancelación el hotel facturará 97 % de la estancia."**_

y de hecho agrego una nota por el cambio:

**_12/06/2021 La reserva se actualizó, y ahora presenta gastos de cancelación, revisar. - estado anterior Confirmed_**

**En resumen, es un problema de Restel y/o el hotel que cambiaron las politicas despues de tomarse la reserva.**

Tengo sacados los request y responses de todo el flujo de la reserva si los necesitan para hacer el reclamo.

**Comment by GuadaVivas** [comment]
Hola José

Perfecto, muchas gracias.
Si, si es posible, adjuntame todos los logs necesario para iniciar el reclamo a restel.

**Comment by GuadaVivas** [comment]
Chicos listo. Cancelada sin gastos. Cierro issue
