### ISSUE TITLE
Deja elegir agencia, peor no vendedor

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#491]
### Descripcion del error

Hola chicos, en Ebooking, en el check out se puede elegir agencia, pero no vendedor y por ende no deja cerrar la reserva

recien no me dejaba con ninguna, probé con tres
Me parece que es con esta agencia puntual: Menendez, 
Porque luego probñe con Alamr por ejemplo y me dejó. 

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/166457862-9718a9bf-b92b-46ed-b1d9-0b40eb35f454.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento/finalizar-compra/6271260fb660267d0501e14a?currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Hola Nati!

Por lo que vemos, la agencia no tienen a ningún usuario activo al momento

Consultalo con operaciones o la persona encargada de cargar agencias y usuarios

Saludos!
