### ISSUE TITLE
[toselli tours/ebooking ] Descripción del costo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#494]
### Descripcion del error

Hola chicos!
En la descripción del costo, muestra discrepancia, ya que dice el costo + reserva por noche y en realidad el costo es igual al costo total de la reserva. 
Abajo adjunto imagenes para explicar. 
Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/167004668-c0edb63e-7155-4772-9b44-21d172f0973e.png)
![image](https://user-images.githubusercontent.com/87333634/167004860-83bf9ad9-e9e9-40a3-b6f5-c68440369101.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/buscar?id=5a21b155fc2d560873053f77&name=madrid-y-sus-alrededores-madrid--espana&checkIn=2023-03-05&checkOut=2023-03-08&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Solucionado de parte de los chicos de front
