### ISSUE TITLE
[ATI] Sin sistemas

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#501]
### Descripcion del error

Hola chicos!
Visualizamos el siguiente mensaje de American Tours, en la web de ellos:
"El centro de datos de terceros de ATI se vio afectado por un ataque a la red que derribó temporalmente sus sistemas y, por lo tanto, los sistemas de ATI que residen en el centro de datos.
Estos sistemas incluyen los servicios de reservas y las aplicaciones de comunicaciones de ATI, incluido el correo electrónico2
Damos aviso por si es necesario tomar alguna medida desde nuestro lado.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![Uploading image.png…]()

### Link al error y/o Localizador

https://www.americantours.com/

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Gracias por avisar!

Saludos
