### ISSUE TITLE
[Expedia] Modificar costo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#502]
### Descripcion del error

Hola chicos!
Necesitamos por favor modificar la siguiente reserva, no pagada al proveedor, de Expedia. Sería a 257.46 usd 
![image](https://user-images.githubusercontent.com/87333634/168592425-ff8b71ee-1f16-4142-880a-763f2e6f782c.png)
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/624ed1ea3e10a8ddb057e56b?purchaseGroupId=385376#heading_624ed1ea3e10a8ddb057e56b
### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Modificado

Ruego por favor revisen y pongan como inactualizable para evitar problemas
