### ISSUE TITLE
Ebooking/JuanToselli - cupos a Europa y Exoticos

### ISSUE THREAD

**Issue by djguille** [toselli/issues#509]
### Descripcion del error

En la pagina principal, en la parte de salidas figura cupos a Europa y Exóticos. Al seleccionar la opción de "Mas cupos de Europa y Exoticos", la pagina te lleva a cupos de Caribe y no a los de Europa.

### Paso a paso para reproducir el error

En la pagina principal, en la parte de salidas figura cupos a Europa y Exóticos. Al seleccionar la opción de "Mas cupos de Europa y Exoticos", la pagina te lleva a cupos de Caribe y no a los de Europa.

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/cupos-confirmados

**Comment by ivanpuglia** [comment]
Error de carga, para solucionar un conflicto de ruteo se cambio el campo Ruteo Web de "cupos-confirmados-offline" por "cupos-confirmados-europa"
