### ISSUE TITLE
Alta web agencia DVIAJES

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#51]
Estimados buenas tardes
El motivo del presente es para solicitarles si podrían activar una página blanca para la agencia DVIAJES 59edd167438ed857eca76b15
Oportunamente, @moliveto y @aletatan les envié los archivos pertinentes para el caso
Quedo atenta
Y desde ya, gracias!

Saludos,
Agos

**Comment by moliveto** [comment]
https://adm.ebooking.com.ar/agencies/edit/59edd167438ed857eca76b15

**Comment by moliveto** [comment]
deviajes.agenciavirtual.net

**Comment by agostinaf25** [comment]
Buenas! Tenemos novedades de esto?
Gracias!
Agos
