### ISSUE TITLE
[Error de mapeo] TBO 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#512]
### Descripcion del error

Hola chicos!
Les traemos el siguiente caso, creemos que se trata de un error de mapeo.
El hotel que la agencia quiere se llama **"Parador Santo Domingo de la Calzada"**, pero la reserva en el adm así como en la página de tbo dice:**"Palacios"** Santo Domingo de la Calzada, España. Al ver que no había ninguna dirección exacta en ninguno de los dos sistemas, se envió a reconfirmar con el proveedor, quienes respondieron: 

![image](https://user-images.githubusercontent.com/87333634/168678887-906d6dcf-de3a-4bb6-8557-82ff7c721027.png)

La propiedad que tbo tiene en su sistema es a 125 km. del domicilio que deberia ser, y ninguna de las dos propiedades coincide con la pedida por el pasajero.
Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6271f450b4490199b4e37304?purchaseGroupId=390876#heading_6271f450b4490199b4e37304

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos, cómo están?

Para estos casos usen la BlackList

Ustedes tienen acceso a ella

https://adm.ebooking.com.ar/blackList

Busquen el hotel
Busquen el mapeo de TBO y eliminenlo

Saludos!
