### ISSUE TITLE
[Ebooking] Error visualización reservas

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#514]
### Descripcion del error

Hola chicos!
Tenemos un problema de visualización de reservas confirmadas, en el ebooking, para la agencia **Torralba Viajes.**
En el apartado mis reservas, solo puede ver las de la primera página, la misma trae 10, pero hemos comprobado que la agencia tiene reservada más de 10.
Por otro lado, indica que no le llegan los correos de confirmación.
Ya hemos procedido a resetear la clave. Pero el problema persiste. 
torralbaviajes@gmail.com
Contraseña: Mayo2022

Muchas gracias!

### Paso a paso para reproducir el error

![image](https://user-images.githubusercontent.com/87333634/169380539-a113b185-6a71-4b41-83fd-e464edb60a34.png)
No pasa a la página 2

### Captura del error

.

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/mi-cuenta/mis-reservas/lista?page=2

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado
