### ISSUE TITLE
[Adm] Cupos

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#517]
### Descripcion del error

Hola chicos!
Desde el área de cupos, nos solicitan eliminar una reserva que se encuentra cancelada, para poder liberar ese lugar:
Cupo loc: GPMTKIL https://adm.ebooking.com.ar/airQuotas/edit/620a4b24671c27d3c4e3e8e8
Reserva loc: 909234 https://adm.ebooking.com.ar/bookings/detail/620bc7fdbe0f051f2fae06cd?purchaseGroupId=377886#heading_620bc7fdbe0f051f2fae06cd
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/169602396-3d94db43-0d1d-4ec1-bb1f-dd43ebe3e890.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/620bc7fdbe0f051f2fae06cd?purchaseGroupId=377886#heading_620bc7fdbe0f051f2fae06cd

### Plataforma

Google Chroome

**Comment by mvalentinalucero** [comment]
Chicos buenas tardes, alguna novedad sobre esto?

**Comment by gabrielmarinsaldaJT** [comment]
Listo para el pasajero Nicoli

**Comment by gabrielmarinsaldaJT** [comment]
Liberado el lugar del pasajero Porporato, Quinteros y Croato
