### ISSUE TITLE
[ebooking] Reservas aereos - Multidestino

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#518]
### Descripcion del error

Hola chicos!
Cuando hacemos una búsqueda en el ebooking en el apartado aéreos, no trae resultados multidestino para Europa.
Les adjuntamos el link de ejemplo: 
https://www.juantoselli.com/#/vuelos/buscar?flightType=3&classPref=Y&segments=2022-09-08!!AEP!BVA%7C2022-09-15!!BVA!BER&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/87333634/169609406-2f5194f3-0580-47ab-b4f2-48ff5f42cedc.png)

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://www.juantoselli.com/#/vuelos/buscar?flightType=3&classPref=Y&segments=2022-09-08!!AEP!BVA%7C2022-09-15!!BVA!BER&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Chicos

Si hay dispo

No usen aeropuertos poco frecuentados como esos

En lugar de Aeroparque pongan Ezeiza

En lugar de Beauvais pongan el aeropuerto ORY de París y no usen Berlín, es mas factible encontrar en Frankfurt

Saludos
