### ISSUE TITLE
[Ebooking] Cruceros

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#520]
### Descripcion del error

Hola chicos!
Respecto a cruceros en el caribe, no trae resultados para ninguna fecha ni proveedor.
![image](https://user-images.githubusercontent.com/87333634/169610702-728c88ae-1d4a-4f48-acd6-4a0acaeed78e.png)

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

 https://www.juantoselli.com/#/cruceros/buscar/6/caribe?nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD&minDuration=-1&maxDuration=-1&departureDateFrom=2022-12-01&departureDateTo=2022-12-31

### Plataforma

Google Chroome

**Comment by CandelaMontes** [comment]
Otro error: En los que hay disponibilidad, cuando vamos a elegir la suite no trae fotos, está en blanco
![image](https://user-images.githubusercontent.com/106408928/178579889-da865e6c-f0e7-4f57-99cc-58bafbb17992.png)

**Comment by CandelaMontes** [comment]
Además en el checkout final la página se rompe, no muestra el detalle de la búsqueda ni de precios de la derecha 
![image](https://user-images.githubusercontent.com/106408928/178579976-52044e7b-9a52-40be-a7a3-9572e677c724.png)

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Hemos revisado todo y lo pasamos en limpio a nuestro Product Backlog, son varios temas a revisar

Particularmente lo que muestran acá, es que MSC no devuelve Avail y tiene roto su sistema

Estamos trabajando para reactivar a Costa y a MSC

Saludos!
