### ISSUE TITLE
[puntoarviajes web] Errores página blanca

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#521]
### Descripcion del error

Hola chicos!
Tengo para reportar lo siguiente de la web de **puntoarviajes**:

- [x] Cuando queremos ir a la sección de Salidas, nos tira el siguiente error:
![image](https://user-images.githubusercontent.com/87333634/169848015-ea8cbbda-c444-4a5f-9c77-c2666e24cc67.png)

- [x] Los banners no se están mostrando efectivamente, como se establece en la configuración:
![image](https://user-images.githubusercontent.com/87333634/169848290-262a793d-2c0f-4650-88b9-d22aa50dcae3.png)
![image](https://user-images.githubusercontent.com/87333634/169848447-85699c19-1106-4bae-8f9a-eb4fe28a7a75.png)

Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://www.puntoarviajes.com.ar/#/salidas

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Solucionado

Para que un Banner se vea en el costado derecho, pónganlo como LEFT y no como POPUP, por eso no lo veían
