### ISSUE TITLE
[Ebooking] Sección usuarios

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#522]
### Descripcion del error

Hola chicos!

Cuando queremos agregar un usuario en la sección Mis usuarios, el botón guardar, queda grisado y no permite ejecutar: 
![image](https://user-images.githubusercontent.com/87333634/169859181-cfdfd724-a596-48d1-a184-c5f0b7bc257c.png)

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://ebooking.com.ar/#/mi-cuenta/mis-usuarios

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Chicos! Cómo va?

No teniamos ni idea de que existia este formulario

La verdad está hecho de manera pésima y creo que tenemos que rehacerlo completo

Mientras tanto, pueden agregar usuarios a las agencias desde acá

https://adm.ebooking.com.ar/agencies

Elijen una Agencia y en **opciones** clickean en **usuarios** y arriba a la derecha tienen el botón **+ Nuevo Usuario**

Recuerden que van a tener que setearle una contraseña, no se la olviden y comuníquensela al user

Cierro issue para pasarla en limpio a nuestro Product Backlog

Saludos!
