### ISSUE TITLE
[adm] Modificar costos

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#524]
### Descripcion del error

Hola chicos! 
Necesitamos modificar los costos de las siguientes reservas. Sería **costo total** las mismas se encuentra optimizadas y no están abonadas al proveedor. 

- [x] https://adm.ebooking.com.ar/bookings/detail/6017eeab5aece7595e0ca6c0?purchaseGroupId=345518#heading_6017eeab5aece7595e0ca6c0
**Debe quedar en 0**

- [x] https://adm.ebooking.com.ar/bookings/detail/6021261de2b50f327af5ad29?purchaseGroupId=345518#heading_6021261de2b50f327af5ad29

**Debe quedar en 62.66 usd**

Gracias!

### Paso a paso para reproducir el error

![image](https://user-images.githubusercontent.com/87333634/170131234-2ebd8806-bad0-495f-953a-562bb48e4caa.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6017eeab5aece7595e0ca6c0?purchaseGroupId=345518#heading_6017eeab5aece7595e0ca6c0 / https://adm.ebooking.com.ar/bookings/detail/6021261de2b50f327af5ad29?purchaseGroupId=345518#heading_6021261de2b50f327af5ad29

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Estimados

Alguna novedad??

Saludos
Juan Manuel

**Comment by JuanBachmann** [comment]
Estimados

Alguna novedad??

Saludos
Juan Manuel

**Comment by JuanBachmann** [comment]
Estimados

Alguna novedad??

Saludos
Juan Manuel

**Comment by JuanBachmann** [comment]
Estimados

Alguna novedad??

Saludos
Juan Manuel

**Comment by JuanBachmann** [comment]
Estimados

Alguna novedad??

Saludos
Juan Manuel

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado
