### ISSUE TITLE
[ADM] Error de costos Specialtourscircuit

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#527]
### Descripcion del error

Hola chicos!
Tenemos una reserva por con el proveedor SpecialTourscircuit, que nos trae todos los costos en 0, incluido en los logs, no especifica ningún tipo de precio.
Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/170703236-91a05b40-5368-4183-8275-3d834c2a870f.png)
![image](https://user-images.githubusercontent.com/87333634/170703266-45e4f468-e087-48b6-97ed-42d3579273d8.png)
![image](https://user-images.githubusercontent.com/87333634/170703334-3c604764-c131-4f56-b2a9-86a5c0ee5720.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/627c0d01302ecdf9a88f98f3?purchaseGroupId=392654#heading_627c0d01302ecdf9a88f98f3

### Plataforma

Google Chroome

**Comment by GuadaVivas** [comment]
Hola chicos!
Nos llegó otra consulta con discrepancias en los costos de SpecialTours:
![image](https://user-images.githubusercontent.com/87333634/173413214-c4ae8533-ce09-4e65-85fc-7044af334876.png)
![image](https://user-images.githubusercontent.com/87333634/173413472-0aed61e0-50c6-4a0a-a2a6-f69329dc5b8e.png)

**Comment by mvalentinalucero** [comment]
Chicos alguna novedad?

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!
