### ISSUE TITLE
[Adm] Aviso de caducidad reservas con vouchers

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#530]
### Descripcion del error

Hola chicos!
Nuevamente, estamos con el inconveniente que a vendedores y agencias, les llega el correo de caducidad de reservas con vouchers emitidos.
Les paso algunos ejemplos:

- 985879 
- 988745

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/628edc2c9f4a0caf06d346ee?purchaseGroupId=395598#heading_628edc2c9f4a0caf06d346ee / https://adm.ebooking.com.ar/bookings/detail/62929b88ca269fde9d6b5709?purchaseGroupId=396189#heading_62929b88ca269fde9d6b5709

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver por qué volvió a suceder esto?

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver por qué volvió a suceder esto?

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver por qué volvió a suceder esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver por qué volvió a suceder esto?

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver por qué volvió a suceder esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver por qué volvió a suceder esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver por qué volvió a suceder esto?

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver por qué volvió a suceder esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by gabrielmarinsaldaJT** [comment]
Esto esta solucionado!

Saludos
