### ISSUE TITLE
[Expedia] Diferencia de costos

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#531]
### Descripcion del error

Hola chicos!
Tenemos diferencias de costo con Expedia, hemos tenido casos anteriores, pero no hubieron logs para corroborarlos. 
Podrán explicarnos si se trata de un error o no estamos interpretando correctamente los mismos?
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/171411326-ae84a7b3-0e45-4aeb-80b9-7bfa35967a09.png)
![image](https://user-images.githubusercontent.com/87333634/171411361-015e9875-dd30-4551-af7e-2001385589f8.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62960e447538d32235b4d4f6?purchaseGroupId=396716#heading_62960e447538d32235b4d4f6

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
Hola chicos, han aparecido más casos de este tipo, ya pudieron ver a qué se debe?

**Comment by GuadaVivas** [comment]
Hola chicos,
Adjuntamos imagen de lo que nos respondió el proveedor respecto a la diferencia de costo:
![image](https://user-images.githubusercontent.com/87333634/173064770-4c2c546c-f34e-43c5-a00a-ac69239fe9a3.png)
![image](https://user-images.githubusercontent.com/87333634/173064823-f5ef60f9-51f0-4f64-a63b-80965c82065e.png)
![image](https://user-images.githubusercontent.com/87333634/173064873-a2d3aec9-f403-4dbd-9bd5-46172eb5ffbf.png)

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!
