### ISSUE TITLE
[adm] Error sincronizar vouccher

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#532]
### Descripcion del error

Hola chicos,

No podemos sincronizar el voucher de la reserva 989249.
Gracias!

### Paso a paso para reproducir el error

![Uploading image.png…]()

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6294be3f7538d322356089dc?purchaseGroupId=396358#heading_6294be3f7538d322356089dc

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
Chicos, pudieron ver este error?

**Comment by BelenBidondo** [comment]
Chicos, pudieron ver este error?

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Chicos, pudieron ver este error?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver por qué volvió a suceder esto?

**Comment by BelenBidondo** [comment]
Chicos, pudieron ver este error?

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Chicos, pudieron ver este error?

**Comment by BelenBidondo** [comment]
Chico buenas tardes,
aún no se pueden sincronizar estas reserva ¿pudieron verlo?

**Comment by BelenBidondo** [comment]
Chicos, pudieron ver este error?

**Comment by GuadaVivas** [comment]
Hola chicos! listo, esto, lo cierro.
