### ISSUE TITLE
[Reserva optimizada] Modificar Costo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#534]
### Descripcion del error

Hola chicos!
Expedia nos canceló sin gastos la reserva **9173489297773** Por favor, modificar costo, ya que se encuentra optimizada. 

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/172172000-bf40f5e5-38b7-4539-a1c6-c59e064991dd.png)
![Uploading image.png…]()

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/628f692a9f4a0caf0627ff47?purchaseGroupId=390142#heading_628f692a9f4a0caf0627ff47

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hecho
