### ISSUE TITLE
[adm] Tamaño de vouchers

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#535]
### Descripcion del error

Hola chicos!
Nos han llegado varios correos sobre el tamaño del voucher cuando uno lo descarga en pdf. 
Actualmente estan saliendo, en su mayoría, de forma horizontal. Les dejo un ejemplo.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/172224854-e6fd4fdd-1695-4ce8-bd42-8fa3fca1efb6.png)
![image](https://user-images.githubusercontent.com/87333634/172224903-42d8796c-689d-407e-94ee-257454a97ae4.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6294c2617538d3223554d140?purchaseGroupId=396138#heading_6294c2617538d3223554d140

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!
