### ISSUE TITLE
[adm] Modificar costo optimizado

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#536]
### Descripcion del error

Hola Chicos!
Necesitamos modificar el costo de esta reserva que se encuentra optimizada a **1093.50**, ya que la fecha de check-out se redujo un día, por lo que el costo es menor. Check-out anterior: 25/06/2022, nuevo check-out: 24/06/2022.
Adjuntamos evidencia del cambio en la fecha y en el costo enviado por Paula Loschi por correo
![image](https://user-images.githubusercontent.com/87333634/172681625-e606386d-68a2-47d5-88f5-b3f71d67e770.png)
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6227521cab04d9564bbd006d?purchaseGroupId=363810#heading_6227521cab04d9564bbd006d

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
Chicos nos están reclamando que solucionen este caso para poder hacer nc. Si pueden véanlo por favor

**Comment by BelenBidondo** [comment]
Chicos,
pueden hacer esta modificación por favor?
