### ISSUE TITLE
[Moneda reservas Sirenis] Visualización en euros

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#539]
### Descripcion del error

Hola chicos!
Nos consultan desde el área de pagos, si es posible para reservas de **SIRENIS CUBA** (cadena directa + Omnibees) que la moneda en el adm figure en _Euro_. Así les facilitaría girar los pagos a Cuba.
Tuvimos un inconveniente de falta de pago y este cambio seria para agilizar el mismo.
Cualquier consulta, le pueden preguntar a Marcelo de las Casas quien nos trajo la idea.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6287b499dc4046d18234cbfc?purchaseGroupId=394646#heading_6287b499dc4046d18234cbfc

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Lamentablemente no podemos, la cotizacion que usamos es la que nos envía el proveedor

Mas allá de la imposibilidad de esto

Nosotros no tenemos integrado a Sirenis cuba de manera directa

Las reservas entran por otro proveedor?
