### ISSUE TITLE
[adm] Mail de confirmación no se enviar a agencias

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#546]
### Descripcion del error

Hola chicos!
Recibimos un reclamo de la agencia Aladdin Viajes, que no están recibiendo los mail de confirmación de la reserva. Hemos chequeado usuarios de la agencia y está todo correcto. También hemos buscado mails enviados desde los correos info.ebooking@juantoselli.com y info@ebooking.com.ar y no encontramos.
Localizador: 1012525
Podrán revisar?
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62b45d7880610c9e258b1476?purchaseGroupId=403464#heading_62b45d7880610c9e258b1476

### Plataforma

Google Chroome

**Comment by CandelaMontes** [comment]
Hola Chicos! Otra agencia que reporta que no le legan los mails de confirmación. Es Molinari Viajes, al mail  hector@molinariviajes.com
