### ISSUE TITLE
[adm] Eliminar Cupo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#548]
### Descripcion del error

Hola chicos!
Nos piden cancelar un cupo, desde Producto, que está ocupando lugar. Nosotros no tenemos forma de hacerlo.
![image](https://user-images.githubusercontent.com/87333634/176268376-22b1a212-ee45-43de-857a-922ad2c7bb31.png)
Amparo Carrizo Gonzalez
Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/airQuotas/edit/620a4b24671c27d3c4e3e8e8

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
Desestimar
