### ISSUE TITLE
[adm] Vendedor sin asignar

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#549]
### Descripcion del error

Hola chicos!
Estamos teniendo problemas a la hora de la agencia al elegir vendedor, que no se toman y quedan vacías en la reserva.
Nosotros al cargar agencias, no ponemos vendedor asignado, ya que no es la vision que la agencia tenga un vendedor predilecto.
Habrá alguna forma que el ebooking deje asignar vendedor elegido (y asi en el adm quede el nombre) o si la agencia no pone opción, se cargue una por defecto?
El mayor problema es que nos llegan múltiples consultas, indicando que falta vendedor por lo cual:

- Vendedores no pueden emitir voucher
- No le llega al vendedor, aviso de cancelación y reserva confirmada y no puede hacer seguimiento, cuando la venta es directa.

 Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/176921708-2795a0f5-5063-4e7f-bbfc-c58eed469a59.png)
![image](https://user-images.githubusercontent.com/87333634/176921821-f12758b2-bf0f-4a51-84fd-7c89eb3837c8.png)

### Link al error y/o Localizador

.

### Plataforma

Google Chroome

**Comment by RoDiaz1996** [comment]
Hola! Hay alguna novedad con respecto a esto?

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Hay alguna novedad sobre este tema?

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Hay alguna novedad sobre este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Listo !
