### ISSUE TITLE
Posible error de mapeo

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#55]
¡Buen día!

Les consulto sobre una reserva y les adjunto los links en cuestión. En nuestro admin se nos muestra una propiedad (Element New York Times Square West) diferente al proveedor (TBA Times Square (ex. Staybridge Suites Times Square) y por consiguiente la dirección tampoco coincide.

Administrador: https://adm.ebooking.com.ar/bookings/detail/610846e4a276a1a8792a89ca?purchaseGroupId=355920#heading_610846e4a276a1a8792a89ca

Proveedor: https://americas.lotsofhotels.com/booking/bookingDetails.aspx?fromBookings=true&localizador=X9RYR6&mail=operaciones%40juantoselli.com

Les agradezco si me indican como proceder, o donde se encuentra el error.
¡Gracias, desde ya!

**Comment by gabrielmarinsaldaJT** [comment]
Buenos días

Si consideran que es un error de mapeo, les recomiendo utilizar la herramienta [Blacklist ](https://adm.ebooking.com.ar/blackList) en nuestro ADM

Les recomiendo leer la siguiente page en la Wiki: 
https://github.com/toselli/eBookingV4/wiki/Blacklist-(Eliminar-mapeos)

**Comment by JuanBachmann** [comment]
Buen día, Gabi

El link de la Wiki nos da error. 
¿El instructivo está disponible en otro lugar?

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, sobre el Link de la wiki:

Les va a dar error ya que no pertenecen al repositorio y lamentablemente no podemos agregarlos, ya que estamos en el límite de users

Cuando estén en la oficina les explico el funcionamiento.

Cierro issue
