### ISSUE TITLE
Tour Mapaplus no figura en Ebooking - el proveedor esta activo  

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#552]
### Descripcion del error

tourd emapaplus no fuigura en Ebooking
el proveedor esta activo y muestra otras alternativas de tour

### Paso a paso para reproducir el error

se filtra por país
se filtra por país y por parte del nomrbre del tour
luego se filtra Mapaplus y no da disponibilidad 

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/177639166-8afe751d-c4c9-47b2-a5c3-fd89332a0770.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/circuitos/buscar?cities=&countries=ES&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=norte&nationality=AR&residence=AR&currency=USD

### Plataforma

.

**Comment by natisalino** [comment]
me faltó indicar el nombre del circuito: P.26 GRAN TOUR NORTE DE ESPAÑA 10 DIAS

**Comment by gabrielmarinsaldaJT** [comment]
Agregado!
