### ISSUE TITLE
[Ebooking] visualización detalla de compra

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#553]
### Descripcion del error

Hola chicos!
Tenemos la siguiente agencia Con la cuenta [ventas@laboratoriodeviajes.tur.ar](mailto:ventas@laboratoriodeviajes.tur.ar) | contraseña: Julio2022 , que no pueden visualizar el detalle de compra cuando pasan a la pantalla del check out. Figura el boton y la felcha con la opción pero no funciona.
![image](https://user-images.githubusercontent.com/87333634/177863217-c0a1ed6d-e310-49eb-81e5-c8c61b8a0254.png)
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/finalizar-compra/62c73e2d590d4b59b21b8df4?currency=ARS

### Plataforma

Google Chroome

**Comment by CandelaMontes** [comment]
Hola chicos!
Otra agencia acaba de reportar el inconveniente del detalle de compra, es la agencia REFLEJOS VIAJEROS.

**Comment by CandelaMontes** [comment]
Por otro lado, realizamos prueba de usabilidad y detectamos lo siguiente con respecto a este inconveniente
En varias pestañas no deja ver el detalle de compra. Y según lo que nos han dicho los usuarios, sucede en diferentes pestañas según el usuario. En el de prueba no deja desplegar el detalle en

En EBooking: VEHICULOS/ CRUCEROS

En Juan Toselli: ALOJAMIENTO/ AÉREOS/ ATRACCIONES / DISNEY/ TRASLADOS/ ASISTENCIAS/ RENTAS VACACIONALES

*En rentas vacacionales además no despliega el precio por noche

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos, cómo están?

Estamos revisándolo

Recuerden no enviarnos links de este tipo:
![image](https://user-images.githubusercontent.com/26115345/181101327-435b2ff9-8bcc-4ce6-9489-022d35c9e15f.png)

Ya que no podemos usarlos porque los carritos de compras se eliminan todos los días

Apenas tengamos una resolución les avisamos

Saludos!

**Comment by CandelaMontes** [comment]
Hola Gabi!
Siguen trabajando en esto?
Me fije hoy y sigue sin desplegarse en las plataformas en algunos servicios

**Comment by CandelaMontes** [comment]
Hola chicos!
Me siguen llegando consultas de agencias que no pueden desplegar el detalle de compra! Como van con el tema?

La nueva consulta es del usuario: cecilia@rracostatours.com.pe
Contraseña: turismo2021

**Comment by CandelaMontes** [comment]
Hola chicos! Hoy estuve chequeando esto nuevamente y sigue sin poder desplegarse en por ejemplo esta búsqueda de vehículos.
https://www.juantoselli.com/#/autos/buscar?pickUpDate=2022-10-07&pickUpTime=10:00&pickUpOfficeId=COR&pickUpCityId=5a21b166fc2d560873054028&pickUpCityName=cordoba-y-sus-alrededores-cordoba--argentina&returnDate=2022-10-10&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=ARS

**Comment by CandelaMontes** [comment]
Hola! En la plataforma Ebooking y Juan Toselli en el checkout aun sigue sin desplegarse el detalle.
https://www.juantoselli.com/#/alojamiento/disponibilidad/5ca93ec886315a56f0d4ea70/dickenson-bay-cottages?checkIn=2023-01-03&checkOut=2023-01-16&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD 

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/61441e58fe6f7749634cc726/hotel-chame?checkIn=2023-01-01&checkOut=2023-01-10&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by CandelaMontes** [comment]
Hola Chiquiss en la pestaña vuelos, de toselli tours no me deja desplegar el detalle de compra 
Si elijo la primera opcion de esta búsqueda:

https://travel.tosellitours.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-06-15!2023-06-30!FCO!MAD&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![BMXCRK53S5C3BO2U6K4FHW2UVM](https://user-images.githubusercontent.com/106408928/195182253-61b7bae7-de36-4aff-9554-a70ea523af01.jpg)
