### ISSUE TITLE
[blacklist] vuelve aparecer propiedad

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#556]
### Descripcion del error

Hola chicos!
Estamos teniendo un problema con las propiedades Iberostar Selection Praia do Forte e Iberostar Bahia, traidas con el proveedor Abreu.
Las mismas presentan errores de mapeos cuando hacemos las búsquedas (por ende en el optimizer trae lo mismo) y hemos agregado múltiple vez en la black list, ambos hoteles. Una vez agregada a la misma, al otro día las propiedades aparecen con el proveedor en cuestión.
¿Podrán verlo?
Gracias.

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/178566884-7fc46d03-c034-4720-a2b1-14df0a07c3ee.png)
![image](https://user-images.githubusercontent.com/87333634/178566950-3a82568b-21c2-4130-a311-2ee991d41704.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62cc78516b77bd4ab857b669?purchaseGroupId=406875#heading_62cc78516b77bd4ab857b669

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionad!
