### ISSUE TITLE
[ebooking] Cupos

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#557]
### Descripcion del error

Hola chicos!
Reportamos el siguiente error de lo que sería la pestaña de Cupos:
![image](https://user-images.githubusercontent.com/87333634/178583271-4f5ce676-22c7-4266-abf6-5d42cfcabff3.png)
No nos trae nada, siendo que hay varios cupos cargados para este año

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/cupos-confirmados?fromDate=2022-09-17&toDate=2022-10-17

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Chicos

Si no cargan algun valor en **Saliendo desde** no va a aparecer nada

Saludos

**Comment by CandelaMontes** [comment]
Gabi, realizamos la prueba eligiendo cada uno de los valores en Saliendo desde y no trae disponibilidad, ni si quiera hace el intento de buscar. 
![image](https://user-images.githubusercontent.com/106408928/180304046-97457794-32ff-4a26-9162-ad60b0a51bbd.png)

![image](https://user-images.githubusercontent.com/106408928/180304158-f892bb06-3f57-4c9e-876b-debe8c10307b.png)

**Comment by gabrielmarinsaldaJT** [comment]
Hola a todos, cómo va?

Por lo que veo, están escribiendo **Bariloche** en el filtro de búsqueda

Por mas que revisamos en la base de datos, no hay ningún cupo confirmado saliendo desde Bariloche, por eso es que no les trae nada

Saludos!

**Comment by gabrielmarinsaldaJT** [comment]
Listooo
