### ISSUE TITLE
[ebooking] Búsquedas por destino

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#558]
### Descripcion del error

Hola chicos!
En todas las plataformas, hay búsquedas de ciudades, que para cada servicio, se debe buscar de distintas maneras para que te traigan.
Les comparto un ejemplo con Roma

### Paso a paso para reproducir el error

Por ejemplo:1) En Vehículos pones Roma y te sale
![image](https://user-images.githubusercontent.com/87333634/178584188-7ec3f46e-b900-40a2-95ef-46877e789b75.png)
2) Si pones Rome no sale:
![image](https://user-images.githubusercontent.com/87333634/178584283-a9289579-9828-46a4-9942-072bfe702be5.png)
3) En vuelos, buscas por Roma:
![image](https://user-images.githubusercontent.com/87333634/178584490-2cb6b5cd-3ca0-42aa-a404-aaa168c7c23c.png)
4) Si vas por Rome en vuelos:
![image](https://user-images.githubusercontent.com/87333634/178584739-86a06175-2a9f-4aad-86af-1098754ef166.png)
5) En circuitos por Roma:
![image](https://user-images.githubusercontent.com/87333634/178584978-c8f7998c-4ca0-4d4c-8f40-6ce74d9d1c01.png)

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by CandelaMontes** [comment]
Gabi, en realidad la idea de esta sugerencia era que podamos poner ROMA en cualquier servicio y siempre te aparezca Roma, Italia. 
Porque lo que sucede es que en algunos servicios pones en español y no te aparece nada (por eso lo buscamos en ingles y ahi sí)  y en otros te aparece un roma en arizona. Es como que no está claro y es incómodo para el usuario 💪🏽
