### ISSUE TITLE
Cruceros] Carga de datos en check out

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#559]
### Descripcion del error

Hola chicos!
Tenemos el siguiente problema, cuando queremos cargar datos y finalizar la compra, a la hora de tomar un crucero, con roles de las agencias.
Nosotros usamos credenciales test test en ebooking: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022
Nos permite cargar todos lo datos, pero cuando llegamos al apartado Contacto de Emergencia, no podemos añadir pais, ni por ende número, por lo cual queda griseado para finalizar la compra.
(No adjuntamos link porque el check out se vence)
Gracias!

### Paso a paso para reproducir el error

![image](https://user-images.githubusercontent.com/87333634/178779692-6acd4578-1562-47bb-b63d-96e9e779f760.png)

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

Google Chroome

**Comment by RoDiaz1996** [comment]
Hola! Hay alguna novedad con esto?

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Hay alguna novedad sobre este tema?

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Hay alguna novedad sobre este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Las issues de cruceros las pasamos a todas a nuestro backlog, ya que todas están contempladas para la reestructuración de Cruceros en eBooking

Cierro issue para evitar duplicidad

Saludos!
