### ISSUE TITLE
Aéreo no reembolsable

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#56]
Buenos días, 
Nos informaron a Agencias que un cliente está intentando confirmar la siguiente reserva de aéreos (https://ebooking.com.ar/#/vuelos/finalizar-compra/6112a0c44b463ea0a1196ec5?currency=USD) y le sale el siguiente popup

![image](https://user-images.githubusercontent.com/40358708/129035404-a10cce84-0343-4728-a29f-79a58a0452c5.png)

Tengo entendido que solemos obtener 24 HS para entrar en gastos de cancelación ¿Hay algún motivo por el cual esto no sucede en la búsqueda? En caso negativo, ¿se podrá modificar el popup indicando que no podrá realizar la reserva por política no reembolsable (o similar)?

Muchas gracias!
Abraham

**Comment by gabrielmarinsaldaJT** [comment]
Chicos

Hay varias cosas para remarcar en esta issue:

1- La issue no se puede reproducir, recuerden por favor enviar links de Avail o al menos los parámetros para realizar una búsqueda idéntica a la del problema. Lo que tenemos acá es el link de un "Finalizar compra", estos datos se pierden de un día para el otro. La issue se creó hace 2 días y yo fui asignado hace 1, por lo que no existe mas el dato de qué intentó reservar la agencia.
2- No puedo decirles si la reserva tiene gastos de cancelación, ya que no la puedo replicar ni sé que días buscó la agencia. De igual manera, realicé varas búsquedas y en todas la política de vencimiento es igual: El día de cancelación que nos da Sabre -1 día que agrega el eBooking. Ésto no lo decidimos nosotros desde sistemas
3- En el pop-up dice _"Esta tarifa especial con descuento es no reembolsable. Si elegís cambiar o cancelar esta reserva, no se te reembolsará el pago."_ No es esto lo que necesitan?
En caso de no serlo, ruego le escriban a Gabriel Toselli, porque no podemos cambiar algo tan importante sin autorización

Cierro la issue

Saludos
