### ISSUE TITLE
[aéreos] Detalle de compra

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#561]
### Descripcion del error

Hola chicos!
Les reporto otro inconveniente/sugerencia. 
En los aéreos, cuando vemos los detalles de compra, en el recuadro bordó, no se muestra **impuesto ganancia**, solo el impuesto pais:
![image](https://user-images.githubusercontent.com/87333634/179753873-de570870-4dfc-4d3e-9812-7414a1cf2e2f.png)
Se podrá agregar ahí tambien? O en vez de agregarle, poner un texto de que "si se paga en ARS, se debe sumar el 65%" (o algo similar)
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

No adjunto link ya que se vence. Pero se puede visualizar en cualquier opción, en el check out. 

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Agregado!

En la proxima publicación se verá reflejado
