### ISSUE TITLE
[Vehículos] Búsquedas

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#562]
### Descripcion del error

Hola chicos!
Tenemos un inconveniente en las búsquedas dentro de las plataformas, del servicio de vehículos. 
Para que nos figure los aeropuertos, debemos poner por ejemplo **"Paris y sus alrededores"** Sucede en su mayoría, con todos los paisea.
![image](https://user-images.githubusercontent.com/87333634/179757014-76924824-f851-48c0-85e7-09fac604812c.png)
![image](https://user-images.githubusercontent.com/87333634/179757135-435cc1f3-565b-40b6-866f-ef269c46afe6.png)
![image](https://user-images.githubusercontent.com/87333634/179757199-2d8ce61f-8053-4bde-b198-21b7da5df3bc.png)
![image](https://user-images.githubusercontent.com/87333634/179757413-d048852e-954c-4f68-bd4c-b0e076277c80.png)
Gracias!

### Paso a paso para reproducir el error

.

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Esto es asi porque la mayoria de los aeropuertos están dentro del polígono de "XXXX y sus alrededores" y no en el polígono de la ciudad

No hay nada para hacer

Saludos
