### ISSUE TITLE
[Aéreos] Mal funcionamiento de grilla

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#564]
### Descripcion del error

Hola chicos, tenemos un inconveniente con la grilla en el apartado de aéreos. Cuando tocamos una opción, se queda cargando y no lleva a elegida en la lista más abajo.
Hicimos la búsqueda desde Córdoba a París y nos pasa con otros destinos.
Las credenciales de prueba son: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) y Junio2022 

Gracias
 

### Paso a paso para reproducir el error

1. ![image](https://user-images.githubusercontent.com/108418973/180516881-fb6f5656-d740-42ca-8368-2f7af02a167c.png)
2. ![image](https://user-images.githubusercontent.com/108418973/180516919-d14444a9-6c4e-4356-aad3-0b4eeca75de2.png)

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/180516711-47fa31a3-105f-44f2-b1cf-f1c076b13c67.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-08-22!2022-08-23!COR!CDG&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD#62dafe04f249eb3e1be66c66

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Rocio!

El error se debía a que Sabre devolvió error en esa tarifa en particular

De hecho, si buscás ahora no vas a encontrar esa tarifa

Cierro issue

Saludos!

**Comment by gabrielmarinsaldaJT** [comment]
Aclaración:

Vamos a agregar un validador que indique problemas con la tarifa y que no quede cargando en loop como te pasó

**Comment by RoDiaz1996** [comment]
Gabi volví a probar y sigue pasando el error. Tocas una opción en la grilla, carga y te vuelve a mostrar la grilla. Te debería llevar a la opción de vuelos que está más abajo disponible, te deja reservar.

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro

Me pasas un link, porfas? Acabo de chequear y todo anda bien

Saludos

**Comment by RoDiaz1996** [comment]
Dale, gracias!

https://ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-08-20!2022-08-25!COR!CDG&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=ARS#62df026ff249eb3e1bc7085c

**Comment by RoDiaz1996** [comment]
Probé de nuevo y anda, Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
👍

**Comment by gabrielmarinsaldaJT** [comment]
Volvió a pasar chicos?

Ruego me avisen

**Comment by CandelaMontes** [comment]
Hola Gabi! Sii, volvió  a ocurrir. Te mando tres links. Uno de cada plataforma

https://www.ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-08-19!2022-09-30!EZE!LIS&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD#62e04e8413158126cecba1c4

https://travel.tosellitours.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-08-19!2022-09-29!COR!GIG&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD#62e04e8513158126cecc8844

https://www.juantoselli.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-08-07!2022-08-17!EZE!SSA&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD#62e04e8013158126cec98e44

**Comment by RoDiaz1996** [comment]
Hola! Hay alguna novedad con esto?

**Comment by CandelaMontes** [comment]
Chicos! En Toselli Tours sigue ocurriendo. En las otras dos plataformas me funcionó bien.
Les dejo link:

https://travel.tosellitours.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-03-02!2023-03-17!IGU!REC&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD#62fe8ff29a13a18a3c1e8328

**Comment by RoDiaz1996** [comment]
¡Hola! Recién probé en la plataforma de TT y me anda, cierro issue.
