### ISSUE TITLE
[Alojamiento] No toma la reserva

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#565]
### Descripcion del error

¡Hola chicos! Tenemos un problema con una agencia **PERU YOUR TRIP** que no puede tomar una reserva de alojamiento. 
El hotel es **Quality Inn Miami Airport - Doral**, completamos todos los datos y finalizamos compra pero salta un error. La reserva es reembolsable y la agencia está bien cargada en el sistema.
Las credenciales de la agencia son: tmalaga@peruyourtrip.com y la contraseña es Julio2022.
El vendedor es Yamil Amado.

### Paso a paso para reproducir el error

1. 
![image](https://user-images.githubusercontent.com/108418973/180566282-548d97ac-2bcb-45a3-89aa-1857ccabf0de.png)
2. 
![image](https://user-images.githubusercontent.com/108418973/180566720-a0fff0e2-5ea7-4679-a0b1-fc80672e5b49.png)
3. 
![image](https://user-images.githubusercontent.com/108418973/180567033-0f4d6bfd-7782-4181-956d-70d6594ec7a5.png)
4.
![image](https://user-images.githubusercontent.com/108418973/180563941-9450830b-11e5-46f8-b5a0-0bc74cf2828e.png)

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/180567249-4718cd69-2f87-4602-8d71-4bdcc0b16a15.png)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/alojamiento/finalizar-compra/62db0d33f249eb3e1b7b4319?currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Rocío

Estos errores son por parte del proveedor 

En este caso particular, devuelve error desconocido por lo que no podemos hacer nada mas

Al ver que hay dos proveedores diferentes que devuelven error desconocido, me atrevo a decir que el problema es por parte del hotel. 

Saludos!

**Comment by RoDiaz1996** [comment]
Bien, gracias
