### ISSUE TITLE
[adm] anular Cupos

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#566]
### Descripcion del error

Buen día chicos!
Solicitamos anular los siguientes pasajeros del cupo, para liberar lugares:

![image](https://user-images.githubusercontent.com/87333634/180786635-be076e6c-198e-4429-a10a-80d0329ce6d1.png)

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/airQuotas/edit/620a4b24671c27d3c4e3e8e8

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Done!
