### ISSUE TITLE
Tour de Europamundo, no figura 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#567]
### Descripcion del error

Tour Viva Italia y Sicilia de Europamundo, no es arrojado en la busqueda

### Paso a paso para reproducir el error

Filtrado por: 

ID: 23134
Parte del nombre. Italia /Sicilia
Ciudad: Palermo
y luego filtrano por proveedor: Europamundo

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/180797697-69617368-065e-46dd-953b-6ae25817663c.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/circuitos/buscar?cities=5a21ab54fc2d5608730203a6&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=italia&nationality=AR&residence=AR&currency=EUR

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!

**Comment by natisalino** [comment]
Hola Gabi M. Mili de BUE me reportó que este tour que ya reportamos en julio no le aparece aún
Bss
Nati
