### ISSUE TITLE
[Alojamiento, suplementos] No funcionan los filtros 

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#569]
### Descripcion del error

¡Hola! Tenemos un problema en el apartado de alojamientos cuando elegimos la propiedad y vamos a la elegir la habitación con los suplementos, hay filtros que significan lo mismo pero te traen diferentes resultados.
Nos pasa con todos los alojamientos.
Las credenciales de prueba son: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) y Junio2022
Gracias.

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/180873970-f0ed6d90-b8d4-456c-8854-6f410e37f5d6.png)
![image](https://user-images.githubusercontent.com/108418973/180874061-39f43a48-cbba-4107-8fc7-3029879deaf4.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca9457286315a56f0d5a33e/seven-hills-village?checkIn=2022-09-20&checkOut=2022-09-30&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=ARS

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro, cómo estás?

Comprendo lo que nos planteás, pero no tenemos manera de agrupar los régimenes de comida ni tampoco los tipos de habitación, ya que eso requiere de un sistema de clasificación que no tenemos desarrollado

Por ahora podemos ofrecer ese filtro para que ayude un poco al usuario al momento de buscar disponibilidad

Cualquier duda que tengas nos podes consultar

Saludos

**Comment by RoDiaz1996** [comment]
Dale Gabi, gracias
