### ISSUE TITLE
Tour special no figura 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#570]
### Descripcion del error

Proveedor activo, tour similar aparece, pero este puntual no
Codigo: 6569-A 

### Paso a paso para reproducir el error

Filtrado por nombre, por codigo y pro proveedor

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/181057148-e2909789-0604-42ac-a6a5-023675b7d519.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/circuitos/buscar?cities=&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=contrastes&nationality=AR&residence=AR&currency=USD

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Levantado el Tour

Pero el problema es que no tiene fechas disponibles y esto es un tema de los datos que nos envía el proveedor
