### ISSUE TITLE
[Ebooking] Agencia no puede visualizar sus reservas

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#571]
### Descripcion del error

¡Hola! Estamos con un problema, la agencia **Sevilla Travel** no puede ver las reservas que realizó en el apartado de Ebooking "Mis reservas". No aparecen en el front, ni en el back. 

Blanqueamos las contraseñas, los roles y no aparecen. A las reservas las podemos ver confirmadas en el administrador con nuestros roles.
Las credenciales son: 
- Usuario: florenciasevilla@sevillatravel.com.ar
- Contraseña: Julio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/181103762-b02f219c-760d-4952-a69f-91e5a8b1e1f2.png)
![image](https://user-images.githubusercontent.com/108418973/181103638-43e20451-7b05-4a14-8510-4b6f7a1d56d8.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/mi-cuenta/mis-reservas/lista?page=1

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro, cómo estás?

Este usuario nos figura creado hace muy poco tiempo y además, no nos figura ninguna reserva en toda nuestra base de datos

Está segura de que no tiene otro usuario?

Encontramos muchas reservas con el usuario MARIA FLORENCIA SEVILLA, cuyo mail es flodanjul2711@gmail.com

Serías tan amable de consultarle si no se trata de una confusión?

**Comment by RoDiaz1996** [comment]
Hola Gabi! 
Ya lo pudimos solucionar, estaba duplicada la agencia. Gracias igual por responder rápido.
