### ISSUE TITLE
[Toselli Tours - Vehículos] No hay resultados

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#572]
### Descripcion del error

¡Hola chicos! Tenemos un problema con el apartado de vehículos en la plataforma de Toselli Tours. 

Hicimos una búsqueda en **Berlin** y en las oficinas de los aeropuertos no trae resultados (primera imagen).
Probamos en **Madrid** y muchos proveedores no traen resultados, probamos con los primeros 10 y después varios aleatorios y todos dicen que no hay resultados (segunda imagen).
Después, probamos en **Roma**, con 10 proveedores y tampoco trae resultados (tercera imagen).

Las credenciales son: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) y contraseña Junio2022

Gracias

### Paso a paso para reproducir el error

1. 
![image](https://user-images.githubusercontent.com/108418973/181357401-4178b5af-629c-43d1-96f1-ea09714f8600.png)
2.
![image](https://user-images.githubusercontent.com/108418973/181357820-94f5e6eb-5582-4c16-a372-2220f7815371.png)

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/181358432-e207cafc-27cb-4dc1-ad12-4dcbc7200cd6.png)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/autos/buscar?pickUpDate=2022-07-27&pickUpTime=10:00&pickUpOfficeId=MAD&pickUpCityId=5a21b155fc2d560873053f77&pickUpCityName=madrid-y-sus-alrededores-madrid-espana&returnDate=2022-07-28&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro

Estoy viendo disponibilidad con todos y cada uno de los proveedores que tienen mapeada esa oficina en esos aeropuertos particulares

Podrías buscar nuevamente por favor?

Además, te recomiendo que no busques dispo para autos con 1 dia de diferencia entre CheckIn y CheckOut, porque no comprendo muy bien, pero no devuelven disponibilidad 

Saludos!

**Comment by CandelaMontes** [comment]
Hola Gabi!
Realice la búsqueda en varios lugares y en Ebooking no trae disponibilidad. 
En madrid por ejemplo. Replico la busqueda en Juan Toselli y si trae 
https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2023-01-01&pickUpTime=10:00&pickUpOfficeId=REC&pickUpCityId=5a21b155fc2d560873053f77&pickUpCityName=madrid-y-sus-alrededores-madrid--espana&returnDate=2023-01-08&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD
![image](https://user-images.githubusercontent.com/106408928/185483756-83c42b20-c39f-4804-a0fd-95dbb08b15c9.png)

https://www.juantoselli.com/#/autos/buscar?pickUpDate=2023-01-01&pickUpTime=10:00&pickUpOfficeId=MAD&pickUpCityId=5a21b155fc2d560873053f77&pickUpCityName=madrid-y-sus-alrededores-madrid-espana&returnDate=2023-01-08&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD
![image](https://user-images.githubusercontent.com/106408928/185483849-d7f18fa0-802d-4aaa-bcaa-aa6963d233b6.png)

**Comment by gabrielmarinsaldaJT** [comment]
Hola Cande!

La primera búsqueda la hiciste en Recife, Brasil

La segunda es en Madrid

De hecho, puedo verse a simple vista:

El aeropuerto de Madrid, es MAD:
![image](https://user-images.githubusercontent.com/26115345/185485291-18021d3a-b03e-44a3-83bf-b41201688262.png)

El aeropuerto de Recife, es REC:
![image](https://user-images.githubusercontent.com/26115345/185485362-8b04aca5-3905-41bf-aaf6-c96ae7fd675c.png)

Y no es que no tenés Avail en Recife, sino que pusiste como oficina de retiro Recife y devolución en Madrid, lo cual es imposible de realizar
