### ISSUE TITLE
[Toselli Tours] Código que no corresponde

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#573]
### Descripcion del error

¡Hola! Chicos tenemos un error, en la plataforma de Toselli Tours, en la pestaña de alojamientos, en la página del hotel **NH Buenos Aires City**, abajo en las habitaciones nos figura un código en color celeste.

Las credenciales son: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) y contraseña Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/181363690-504d04a2-7f52-4590-88b2-107c8c686df8.png)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca8e7bb86315a56f0c88264/nh-buenos-aires-city-buenos-aires--argentina?checkIn=2022-08-13&checkOut=2022-08-19&nationality=PE&residence=PE&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola! Encontré otro código cómo este en Ebooking, en la pestaña cupos:
![image](https://user-images.githubusercontent.com/108418973/182689519-f14c78d6-fd14-44cd-904c-25bbc7fc5a99.png)
https://www.ebooking.com.ar/#/cupos-confirmados/detalle/620a7a6b671c27d3c4949d8b/riviera-maya-y-costa-mujeres-desde-cor-con-palladium?from=5a21b01efc2d5608730462bf&quota=61d5fb77cf11f4b69a5ef8c9&occupancies=2*30,30*0*&nationality=AR&residence=AR&token=02146XZLZQ

Las credenciales son: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) y la contraseña: Junio2022

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado Ro!

En la próxima publicación lo verás reflejado
Saludos
