### ISSUE TITLE
tour europamundo no figura en Ebooking 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#574]
### Descripcion del error

Tour no fugura en ebooking

https://www.europamundo.com/itinerario_menu.aspx?em_search=y&rutaid=796&temp=2022

### Paso a paso para reproducir el error

filtro por nombre y por pais y por proveedor y no da el resultado deseado
proveedor esta actuvo 
replico la busqueda que me indica y es correcto lo que indica la vendedora
arroja resultados del proveedor, pero no el tpour en gestion

reportado por:  Lucia

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/181513339-056665b9-7d6c-48f2-93c2-51b865882b37.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/circuitos/buscar?cities=&countries=CH&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=suiza&nationality=AR&residence=AR&currency=USD

### Plataforma

.

**Comment by natisalino** [comment]
Hola chicos, agrego uno mas de europamundo que no aparece
Escocia desde Londres 
Tour en web europamundo
https://www.europamundo.com/itinerario_menu.aspx?rutaID=759&head=s&em_search=y
ide europamundo: 22876

Busqueda sin resultado  Ebooking: 
https://ebooking.com.ar/#/circuitos/buscar?cities=&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=escocia%20desde&nationality=AR&residence=AR&currency=USD

Captura
![image](https://user-images.githubusercontent.com/88200755/181788401-7af9ad9e-5fa8-4bf9-a4fe-dacc4c4b1bb3.png)

Gracias
Nati

**Comment by gabrielmarinsaldaJT** [comment]
Levantado el Tour!

Saludos
