### ISSUE TITLE
[Budget] Diferencia en plan de seguros

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#575]
### Descripcion del error

Hola chicos!
Tenemos el siguiente inconveniente, en cuanto a la integración con Budget. 

- [ ] La agencia tomó una reserva de alquiler de auto del cual eligió este seguro porque está exento de daños en colisión sin tope de franquicia; el cual no corresponde al seguro **SEE EUROPE X8** que tiene confirmado, del mismo modo tampoco incluye cargos de aeropuerto y one way fee como indica nuestro voucher.

- [ ] Por otro lado, en la web de Budget, se toman los impuestos por separado:

![image](https://user-images.githubusercontent.com/87333634/181630915-37cef14b-36dc-4a10-9d0d-6dbc97664548.png)

- [ ] Le hemos consultado a Budget, y desde su lado nos han informado que no estamos integrando bien:

![image](https://user-images.githubusercontent.com/87333634/181631124-0f4d84c3-b420-4755-848d-f39944f78133.png)
![image](https://user-images.githubusercontent.com/87333634/181631161-addad6af-ac2b-41d8-b3f8-9410c9c41388.png)

Podrán verlo?
Muchas gracias

### Paso a paso para reproducir el error

n/a

### Captura del error

n/a

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62b2395680610c9e2577ebc8?purchaseGroupId=401472#heading_62b2395680610c9e2577ebc8

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Hola chicas, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Buen dia ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Esto debería estar solucionado

Saludos!
