### ISSUE TITLE
[adm] Error al sincronizar voucher 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#576]
### Descripcion del error

Hola chicos!
Estamos teniendo un problema para sincronizar el siguiente voucher:
![image](https://user-images.githubusercontent.com/87333634/181631752-97418886-4c79-42bb-83ac-a6cf883d4321.png)

Desde ayer que estamos intentando, pero figura el mismo error de sincronización (hemos podido realizarlo con otros)
Vemos que la agencia y el proveedor, están bien cargados en el sistema. 
Podrán ayudarnos?
Gracias!

### Paso a paso para reproducir el error

n/a

### Captura del error

n/a

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62b2125aa70912b1be9fd0a7?purchaseGroupId=399295#heading_62b2125aa70912b1be9fd0a7

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
hola chicos, ¿pudieron ver ese error?

**Comment by BelenBidondo** [comment]
Chico buenas tardes,
aún no se pueden sincronizar estas reserva ¿pudieron verlo?

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos, esa reserva está pagada

Saludos!
