### ISSUE TITLE
[Ebooking- Registro] Pide número fijo

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#577]
### Descripcion del error

¡Hola chicos! Estamos con un problema, en el registro de la página Ebooking, nos pide completar un número de teléfono fijo si o si para registrarse. El apartado de celular es opcional y si completamos con los mismos datos, te deja registrarte.
Estaría bueno que el fijo sea opcional también o si se completó el apartado de celular que no te pida un número fijo si o si.
Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/182227990-abaa91ab-79fe-4737-a6bf-35d6799d9ac1.png)
![image](https://user-images.githubusercontent.com/108418973/182228202-09457447-6c53-4ee6-b6b7-3e8d1e3c5407.png)
![image](https://user-images.githubusercontent.com/108418973/182228060-cc615269-411f-4e14-a729-ef7e5616f351.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/mi-cuenta/registro-cliente

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!

Se verá reflejado en la próxima publicación

Saludos!
