### ISSUE TITLE
[correos reiterativos] voucher 2020

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#578]
### Descripcion del error

Hola chicos!
Tenemos el siguiente inconveniente, en el que la vendedora, recibe a su casilla personal, reiteradas veces, el mail con los vouchers de una reserva del 2020.
Desde nuestro lado, hemos cambiado el correo a otras casillas y aun así se actualiza el del usuario de Lucía y vuelven a llegarles.
Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/182461583-8240cec2-bbba-482f-b9e8-09ea9e4d3d72.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/5fa04c598d09ff68c4ebae03?purchaseGroupId=340474#heading_5fa04c598d09ff68c4ebae03

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Eliminado el mail

Saludos!
