### ISSUE TITLE
Nexus no sincroniza 

### ISSUE THREAD

**Issue by moliveto** [toselli/issues#58]
VOUCHER F946915 y F946901 - NO SE VE EN EL SISTEMA

![image](https://user-images.githubusercontent.com/1890103/129370133-d8bc3751-f2b3-4742-800d-4e79d32ba0b3.png)

![image](https://user-images.githubusercontent.com/1890103/129370188-4912e6a5-1354-4004-abf7-1a7f7c7dceb3.png)

Quedo atento!
Gracias y saludos
Miguel

**Comment by gabrielmarinsaldaJT** [comment]
Done it
