### ISSUE TITLE
[Toselli Tours- Alojamientos] Detalle de compra no da el cálculo

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#580]
### Descripcion del error

¡Hola chicos! Estamos con un problema, hicimos una búsqueda a **Maldivas** y en el apartado de **detalle de compra** no nos da el cálculo: al precio neto le sumamos los impuestos y la comisión y el precio que figura es menor.

Las credenciales son: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) y contraseña Junio2022

Gracias

### Paso a paso para reproducir el error

1. 
![image](https://user-images.githubusercontent.com/108418973/182676934-b546ffe6-5e07-4e0c-b34e-138da1b530d7.png)
2.
![image](https://user-images.githubusercontent.com/108418973/182677593-fec238de-794e-4cac-b310-752174d36cf2.png)

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/182677685-ffa18817-549e-489f-b8f3-ca1b127c9186.png)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/alojamiento/finalizar-compra/62eab5f781266729725face3?currency=USD

### Plataforma

Google Chrome

**Comment by CandelaMontes** [comment]
Hola Chicos! Pudieron chequear esto??

**Comment by IvanFacundoRosas** [comment]
Posible solución: toselli/web-nueva#103

**Comment by gabrielmarinsaldaJT** [comment]
Listo!
