### ISSUE TITLE
[Juan Toselli - Salidas] No carga el apartado Sports

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#581]
### Descripcion del error

¡Hola chicos! Notamos que en la plataforma Juan Toselli, en Salidas, Turismo Internacional, cuando tocamos la **pestaña Sports** te lleva a la **pestaña Todas**.
Las credenciales son: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) y la contraseña: Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/182680736-368a1c5b-ceae-4b7a-9e4b-90c9e6c4f438.png)

![image](https://user-images.githubusercontent.com/108418973/182680646-85d7c4c4-36c6-470c-a906-c42db604f76e.png)

### Link al error y/o Localizador

https://www.juantoselli.com/#/salidas/buscar/turismo-internacional/tosellisports

### Plataforma

Google Chrome

**Comment by CandelaMontes** [comment]
Hola! Pudieron ver esto? Se debe a algún tipo de inconveniente o directamente no hay dispo?

**Comment by CandelaMontes** [comment]
Hola Chicos! Sigo viendo el mismo error tanto para Ebooking como para Juan Toselli.

En uno se me pega la pestaña salidas grupales
https://www.juantoselli.com/#/salidas/buscar/turismo-internacional/tosellisports

Y en otro directamente no me da dispo
https://www.ebooking.com.ar/#/salidas/buscar/turismo-internacional/tosellisports

**Comment by gabrielmarinsaldaJT** [comment]
Listo!
