### ISSUE TITLE
[Ebooking- Alojamiento] Misma imagen para varios alojamientos

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#582]
### Descripcion del error

¡Hola! Detectamos un problema en Ebooking, en alojamientos, en la búsqueda de **Maharashtra India** varios alojamientos tienen la misma imagen como referencia. 
Las credenciales son: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) y la contraseña: Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/182682159-15eae61b-9fb4-4dd8-8cd4-0d06fed67519.png)
![image](https://user-images.githubusercontent.com/108418973/182682220-3ce01d43-95a2-4522-97ea-e5222a1784bb.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/buscar?id=5a463f51fc0b9d5df192cb03&name=maharashtra-maharashtra--india&checkIn=2023-01-16&checkOut=2023-01-19&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Esto se debe a que el hotel no tiene foto.

Cuando esto sucede, lee una imagen por defecto

Saludos
