### ISSUE TITLE
[Ebooking- Vehículos] No despliega la oficina de retiro

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#583]
### Descripcion del error

¡Hola chicos! Estamos con un problema, en Ebooking, en la pestaña de vehículos, si buscamos alguna ciudad de **Cuba** no nos despliega las **oficinas de retiro**. 
Las credenciales son: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) y la contraseña: Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/182683540-2a9a0a25-50a5-447e-b19c-dac8d0a272a6.png)
![image](https://user-images.githubusercontent.com/108418973/182683635-877fdf83-14f8-4055-b9dd-c904716eba08.png)
![image](https://user-images.githubusercontent.com/108418973/182683728-7315b80c-ac17-48bc-839c-ff723ce1fbd8.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

No tenemos autos en esos lugares de Cuba

Saludos!
