### ISSUE TITLE
[Ebooking - Atracciones] No deja reservar la atracción

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#584]
### Descripcion del error

¡Hola! Encontramos un problema en la plataforma Ebooking, en el apartado de **Atracciones**. Hicimos una búsqueda en Buenos Aires y cuando quise reservar una excursión por el Delta del Tigre me salta un error (imagen 1)
Además, en otra excursión se repite la información en la página del Checkout (imagen 2). En este caso al querer confirmar la excursión me da error (imagen 3).
Las credenciales son: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) y la contraseña: Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

1.
![image](https://user-images.githubusercontent.com/108418973/182686287-e7014516-73e6-4727-a487-b94cc9b4ff9b.png)
2.
![image](https://user-images.githubusercontent.com/108418973/182687268-7452c9bd-67e5-4c0a-ab76-5703bc9485e7.png)
https://ebooking.com.ar/#/atracciones/finalizar-compra/62eac22d8126672972876953?currency=USD
3.
![image](https://user-images.githubusercontent.com/108418973/182687573-585e119d-fdaa-4bd7-865b-ec10d2b3d57d.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/atracciones/buscar?destinationId=5a458122fc0b9d5df191f47f&destinationName=buenos-aires-provincia-buenos-aires--argentina&fromDate=2022-09-23&toDate=2022-09-25&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
Hola chicos me paso lo mismo con otra atracción, en la plataforma de Juan Toselli. Quise reservar la atracción "Tour privado de 10 horas en Londres con chofer" y me salió ese error.
![image](https://user-images.githubusercontent.com/108418973/184019452-a8b1793c-1966-46a7-ba70-23cdf85bc62a.png)
https://travel.tosellitours.com/#/atracciones/buscar?destinationId=5a21aafcfc2d56087301cfda&destinationName=londres-inglaterra--reino-unido&fromDate=2022-11-10&toDate=2022-11-15&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD
Las credenciales son las mismas.
Gracias

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Hay alguna novedad sobre este tema?

**Comment by RoDiaz1996** [comment]
¡Hola! ¿Hay alguna novedad?

**Comment by RoDiaz1996** [comment]
¡Hola chicos! Encontré otro caso en dónde se repite la información:
![image](https://user-images.githubusercontent.com/108418973/191093610-4261aeb9-2145-4d15-923d-d48fe388cbfc.png)

Gracias

**Comment by RoDiaz1996** [comment]
¡Hola! ¿Alguna novedad sobre este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Hola @RoDiaz1996 !!

Estuve revisando el caso y encontré lo siguiente:

El problema con la reserva de Viator surgió por dos problemas

1- El proveedor tiene algunos problemas cuando los nombres/apellidos de los pasajeros son **test test** por lo que te sugiero que hagas pruebas con nombres propios o el tuyo. 
2- El error de la Imagen 2 es del eBooking en general y sucede cuando, por algún motivo, hicieron un **Volver** en la página y ésto falló generando que la reserva se intente duplicar. Estamos trabajando en una solución integral para ésto, asique no estará listo hasta dentro de unos días.
3- Las duplicidades en las Descriptions de las Atracciones ya ha sido solucionada, te pido la revises porfa y me comentes si ves algo mal. 


Saludos!
