### ISSUE TITLE
[autos] oficina de retiro

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#586]
### Descripcion del error

Hola chicos!
Tenemos el siguiente inconveniente con la reserva 1891521163COUNT, no figura la oficina de reitro ni devolución en el adm, por ende el voucher no lo muestra.

- [ ] En la web de Alamo, tenemos la info:

![image](https://user-images.githubusercontent.com/87333634/182695972-13929db8-e4bc-45c0-ac9e-f19219d1e97d.png)

- [ ] De paso les pedimos corroborar que los costos, sean correctos:

![image](https://user-images.githubusercontent.com/87333634/182696173-beb58adb-3801-49fa-9436-715c37368c1c.png)
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62ccaf5e6b77bd4ab85518ac?purchaseGroupId=409863#heading_62ccaf5e6b77bd4ab85518ac

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Done!
