### ISSUE TITLE
[Ebooking- Universal] No figura Universal

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#587]
### Descripcion del error

¡Hola chicos! Hemos recibido varios reclamos porque no figura Universal como proveedor directo, sólo aparecen ActionTravelSightseeing y Viator.
Las credenciales son: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) y contraseña Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/183492349-077cf2d5-0170-4c9a-b746-ad8c34c98c62.png)
![image](https://user-images.githubusercontent.com/108418973/183492418-1cfc6b3b-a105-4a4e-9469-2863855e36da.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5aa7dd3f3dfcee50fc39c792&destinationName=orlando-y-sus-alrededores-florida--estados-unidos&fromDate=2022-08-15&toDate=2022-08-31&nationality=AR&residence=AR&occupancies=6*30,30,30,30,30,30*0*&disney=false&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!

**Comment by RoDiaz1996** [comment]
Gabi, probé y no me trae nada de disponibilidad. Busqué desde ahora hasta el año que viene y me dice sin resultados:
![image](https://user-images.githubusercontent.com/108418973/184372647-842496c1-4fbe-409e-97a7-bc6d027df496.png)
https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5aa7dd3f3dfcee50fc39c792&destinationName=orlando-y-sus-alrededores-florida-estados-unidos&fromDate=2022-09-10&toDate=2023-09-10&nationality=AR&residence=AR&occupancies=6*30,30,30,30,30,30*0*&disney=false&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Hola Rocio

Ahora si sale Universal

De todas maneras, te recomiendo no buscar con un año entero entre CheckIn y CheckOut, ya que algunos proveedores pueden responder con errores o incluso demorar tanto tiempo que nosotros cortamos la conexión con ellos para esa búsqueda

Si revisás, vas a encontrar dispo con Universal para todas las fechas entre el 10/09/2022 a 10/09/2023

Saludos!
