### ISSUE TITLE
[Ebooking- Vuelos de cabotaje] Precios muy elevados

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#588]
### Descripcion del error

¡Hola! Tenemos un problema con los vuelos de cabotaje en Argentina, cuando buscamos nos figuran con los impuestos y son precios sumamente elevados. 
Sabemos que si son vuelos de cabotaje se hacen offline, queremos saber si hay forma de no sumarle los impuestos o poner que consulten a sus vendedores para que no aparezcan esos precios. 
Les dejo unos ejemplos.
Las credenciales son: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) y contraseña Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/183494114-d9f55914-ab45-4601-b363-2085fff8a15a.png)
https://ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-11-10!2022-11-17!COR!BRC&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=ARS
![image](https://user-images.githubusercontent.com/108418973/183494381-ce50653b-f9c7-4852-b2fe-6bb3397d95f2.png)
https://ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-09-20!2022-09-25!BUE!CPC&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=ARS
![image](https://user-images.githubusercontent.com/108418973/183494563-798417c5-5399-44c0-ba32-d4864b07ea98.png)
https://ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-10-10!2022-10-15!MDZ!SLA&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=ARS

### Link al error y/o Localizador

https://ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-11-10!2022-11-17!COR!BRC&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=ARS

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!

El problema era con la cotización de ese momento
