### ISSUE TITLE
ERROR NEXUS TRANSF

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#59]
Estimados buenas tardes,
Los voucher F946915 y el F946901, no están aparecen en el sistema, y por lo tanto no pueden facturarlos.
No se a que se debe, intente sincronizarlo pero me arroja el cartel que adjunto en las imágenes, igual para ambos.

![image](https://user-images.githubusercontent.com/45457355/129412140-274391d1-8643-48e2-a978-81f309d039a8.png)
![image](https://user-images.githubusercontent.com/45457355/129412153-44236eb2-23c6-4b14-9d4d-71203ccd9d19.png)

LINKS de las reservas:

https://adm.ebooking.com.ar/bookings/detail/6112d49e4b463ea0a16070dc?purchaseGroupId=358722#heading_6112d49e4b463ea0a16070dc

https://adm.ebooking.com.ar/bookings/detail/6112d49e4b463ea0a16070cf?purchaseGroupId=358722#heading_6112d49e4b463ea0a16070cf

**Comment by gabrielmarinsaldaJT** [comment]
Cierro issue por duplicidad con https://github.com/toselli/issues/issues/58
