### ISSUE TITLE
[AVIS] Error oficina de retiro 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#590]
### Descripcion del error

Hola chicos!
Les reporto un error en el código de la oficina de retiro de un auto de Avis. 
El vendedor al reservar solicitó una Oficina de devolución y el sistema trajo un código que correspondía a otra Oficina de devolución en otro país, debido a esto el pasajero en destino tuvo que abonar de forma particular.
Le consulta al proveedor y nos respondió:

![image](https://user-images.githubusercontent.com/87333634/183511909-61dac406-252d-4b5c-98ec-9b53476c81df.png)

La Oficina de Devolución que se solicitó a AVIS era "Fuengirola, España" con código FG3 y el sistema trajo el código KQ8 que corresponde a Kazakhstan, pero en BUDGET la oficina KQ8 según el proveedor si correspondo a Fuengirola, es decir el sistema trajo un código de BUDGET para un vehículo tomado con AVIS.
Podrán revisarlo?
Gracias. 

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62bcc207e24a953248d0b213?purchaseGroupId=405527#heading_62bcc207e24a953248d0b213

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Eliminamos la oficina para que ya no suceda

Avis usa ese código para una cosa y Budget para el otro
