### ISSUE TITLE
[Ebooking- Alojamientos] Diferencias de tarifas en H+ Hotel München

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#591]
### Descripcion del error

¡Hola chicos! Tenemos un problema con un alojamiento, una agencia, la vendedora y nosotros hicimos la misma búsqueda y nos figuran diferentes resultados. La agencia ve una tarifa menor, la vendedora y nosotros vemos una tarifa mayor.
Desde el usuario de Nati Salino, de Cele Pagliero y desde el nuestro vemos la tarifa de 2.944,55 (imagen 2)
Las credenciales son: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) y contraseña Junio2022
Desde el usuario de la agencia ve la tarifa de 1.101,83, ingresando con el siguiente link (imagen 3). Si hacemos la búsqueda manual con sus credenciales no figura ese precio.
Link: https://www.ebooking.com.ar/#/alojamiento/finalizar-compra/62f17ce74c356b310857fbc9?currency=USD
Credenciales: novelliviajes@gmail.com y contraseña: Agosto2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/183516611-461758bb-e535-49ec-b224-a65349fd1d0e.png)
![image](https://user-images.githubusercontent.com/108418973/183514561-a224cbd1-2f79-4521-ba97-5d161fe4efa5.png)
![image](https://user-images.githubusercontent.com/108418973/183515574-cb03e721-839f-4e55-bd48-5046878bb2cf.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/finalizar-compra/62f17ce74c356b310857fbc9?currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Este problema era un error que tenía Yalago

Ya se solucionó en una issue vieja

Saludos!
