### ISSUE TITLE
Europamundo - error al tomar reserva dependiendo de la edad

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#592]
### Descripcion del error

Esta reserva deja avanzar cuando se pone la edad que viene por defecto (30 años) pero no cuando se ponene las edades reales de los pax (75 y 78 años). Entiendo que es porque este tour no tiene descuento de pax club (pax repitente o pax mayor de 65 años) pero no deberia ser un condicional para poder cerrar la reserva, ya que la edad marca un descuento, no la disponibilidad. 

### Paso a paso para reproducir el error

En el siguiente link, probar la disponibilidad previo a poner 30 años a cada pax y marcado una fecha cualquiera de salida
y luego hacerlo ponienndo 75 y 78 años, marcando una fecha, en la segunda opcion no da dsiponibilidad. 

https://www.ebooking.com.ar/#/circuitos/detalle/60979891ce0699c1b2b909f7/sur-de-grecia-y-peloponeso-2022?currency=USD&residence=AR&nationality=AR

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/183672681-a4ccb746-70f5-4e18-a9cc-697f029fda57.png)

![image](https://user-images.githubusercontent.com/88200755/183672840-48d6a3c4-23b3-4f03-9164-bfa5563e7bfc.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/circuitos/detalle/60979891ce0699c1b2b909f7/sur-de-grecia-y-peloponeso-2022?currency=USD&residence=AR&nationality=AR

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Hola Nati!

Esto es lo que habiamos hablado de los pasajeros club

Dejé abierta la issue pero ya está hecho

Saludos!
