### ISSUE TITLE
[Avis] Información reflejada

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#594]
### Descripcion del error

Hola chicos!
Tuvimos una incidencia con respecto a la reserva 34065857AR0. El problema está en que la oficina de drop off (CB7) de Avis, es solo para huéspedes del hotel, pero al momento de hace la búsqueda en el ebooking, no lo aclara, como así tampoco en el adm (por ende no en el voucher). La oficina es virtual y solo se le ofrece a los huesped del hotel 

![image](https://user-images.githubusercontent.com/87333634/183752428-a282083e-b7ce-4241-80c8-286dd1227a1d.png)

![image](https://user-images.githubusercontent.com/87333634/183752482-c6d02715-076d-40d2-80af-eb31abf1963c.png)

¿Podrán revisarlo?
Gracias.

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62a1ef90fd0f32a9797bf6c4?purchaseGroupId=384340#heading_62a1ef90fd0f32a9797bf6c4

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Guada!

Revise la info que nos llega de Avis y no tiene mas nada que podamos agregarle. La verdad es bastante floja su static data

Me parece correcto borrarla para evitar problemas

Si me dan el OK, la eliminamos

Saludos

**Comment by GuadaVivas** [comment]
Hola Gabi!
Si procedé a eliminarla! Así evitamosss problemas, gracias :)

**Comment by gabrielmarinsaldaJT** [comment]
Eliminada!
