### ISSUE TITLE
[adm] Error al sincronizar vochers

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#595]
### Descripcion del error

Hola chicos!
No estamos pudiendo sincronizar los siguientes vouchers:

- [x] https://adm.ebooking.com.ar/bookings/detail/62ebddc34c356b3108896542?purchaseGroupId=405841#heading_62ebddc34c356b3108896542
- [x] https://adm.ebooking.com.ar/bookings/detail/62ebddc34c356b31088858ec?purchaseGroupId=405841#heading_62ebddc34c356b31088858ec

![image](https://user-images.githubusercontent.com/87333634/183753719-002249f4-8326-43c8-bae2-2d3c92e52f71.png)
Nos salta ese cartel.

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62ebddc34c356b3108896542?purchaseGroupId=405841#heading_62ebddc34c356b3108896542 / https://adm.ebooking.com.ar/bookings/detail/62ebddc34c356b31088858ec?purchaseGroupId=405841#heading_62ebddc34c356b31088858ec

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
Chico buenas tardes,
aún no se pueden sincronizar estas reserva ¿pudieron verlo?

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!
