### ISSUE TITLE
Tour de Europamundo USA no figura 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#596]
### Descripcion del error

figura el proveedor
figuran otros circuitos del destino del proveedor
no figura este y sus alternativas 

Web Europamundo
https://www.europamundo.com/itinerario_menu.aspx?em_search=y&rutaid=793&temp=2022

### Paso a paso para reproducir el error

Filtramos por la palabra "oeste" y luego por provedor Europamundo

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/183763017-109657ab-c68e-4378-bbf8-f637b8ef4f6e.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/circuitos/buscar?cities=&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=oeste&nationality=AR&residence=AR&currency=USD

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Listoo
