### ISSUE TITLE
[Ebooking- Cupos] No hay disponibilidad 

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#597]
### Descripcion del error

¡Hola chicos! Detectamos un inconveniente en la pestaña **Cupos** de Ebooking, en Curacao desde Buenos Aires, al buscar la disponibilidad del hotel **Blue Bay Curacao The Hill** no muestra disponibilidad (imagen 2).

Además, tenemos una sugerencia porque cuando scrolleamos una parte de la información de la derecha se desplaza junto con nuestro movimiento y tapa información (imagen 3). Creemos que la lógica es para poder apretar "agregar al carrito", la sugerencia es que el botón agregar al carrito esté abajo como en alojamiento (imagen 4).

Las credenciales son: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) y contraseña Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

1.
![image](https://user-images.githubusercontent.com/108418973/184010596-37ff2b54-fccc-4dbd-b103-5585b16be75d.png)
2.
![image](https://user-images.githubusercontent.com/108418973/184010721-51904556-16b1-4e3c-9bc8-c60a315cd5a5.png)
3.
![image](https://user-images.githubusercontent.com/108418973/184011001-dbaf8efa-6dbb-4eec-898a-727bb42239b9.png)
4.
![image](https://user-images.githubusercontent.com/108418973/184011176-6d38ac23-db04-4d24-b52e-db2098b822d5.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/cupos-confirmados/detalle/622220af914a4fb62c55fd3c/curacao-desde-buenos-aires?from=5a458122fc0b9d5df191f47f&quota=62057805671c27d3c42b02c1&occupancies=2*30,30*0*&nationality=AR&residence=AR&token=030483J16D

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Muchas veces hay hoteles que no dan avail porque no tienen mas dispo o porque no tienen contrato. Hay algún proveedor que si de disponibilidad en ese hotel pero esté fallando en cupos?
No podemos hacer mucho mas lamentablemente

Sobre la sugerencia del front, podemos hablarlo con los chicos para que lo modifiquen, pero recuerdo que eso se pidio que funcionara de esa forma

Saludos!

**Comment by RoDiaz1996** [comment]
Busqué en la pestaña de alojamientos el hotel y me sale que hay disponibilidad (no reembolsable).
![image](https://user-images.githubusercontent.com/108418973/184373818-132c3d54-4e22-4ae8-bfb7-44cd3b60e123.png)
![image](https://user-images.githubusercontent.com/108418973/184374016-cc4589a4-9745-4018-b2c7-d308914f33b7.png)

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8de4886315a56f0c67277/blue-bay-curacao-the-hill-sint-michiel-?checkIn=2022-10-21&checkOut=2022-10-28&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

A nosotras nos parece mejor si agregar carrito está abajo pero si te pidieron específicamente que esté como ahora, se deja así. Es una sugerencia porque se ve mejor de otra forma.

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Hay alguna novedad sobre este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

La dispo no reembolsable no se ve en cupos

Saludos!
