### ISSUE TITLE
[Juan Toselli - Aéreos] Error en varios destinos

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#598]
### Descripcion del error

¡Hola! Tenemos un problema en la plataforma Juan Toselli en la pestaña aéreos en **Varios Destinos**. Hicimos una búsqueda: Buenos Aires- Madrid- Frankfurt y nos dice que no se encontraron resultados (imagen 1), pero cuando hacemos la búsqueda por separado, sólo ida, si encontramos vuelos.
Las credenciales son: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) y contraseña Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

1.
![image](https://user-images.githubusercontent.com/108418973/184013148-4705068f-18d9-4feb-a1f1-67981ed71382.png)
https://www.juantoselli.com/#/vuelos/buscar?flightType=3&classPref=Y&segments=2022-11-12!!EZE!MAD%7C2022-11-22!!MAD!HHN&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD
2.
![image](https://user-images.githubusercontent.com/108418973/184013253-9cde99d6-5f1f-4353-b6dc-344e08b0b9c4.png)
https://www.juantoselli.com/#/vuelos/buscar?flightType=1&classPref=Y&segments=2022-11-12!!EZE!MAD&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD
3.
![image](https://user-images.githubusercontent.com/108418973/184013345-7dc89ebb-b591-4931-aa0f-46110cd6b0c5.png)
https://www.juantoselli.com/#/vuelos/buscar?flightType=1&classPref=Y&segments=2022-11-22!!MAD!FRA&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Link al error y/o Localizador

https://www.juantoselli.com/#/vuelos/buscar?flightType=3&classPref=Y&segments=2022-11-12!!EZE!MAD%7C2022-11-22!!MAD!HHN&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!
