### ISSUE TITLE
[Hotelbedssighseeing] Error 500

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#599]
### Descripcion del error

Hola chicos!
Estamos queriendo tomar una atracción con Hotelbedsighseeing.
De hecho cuando hago la búsqueda con mi usuario, no lo encuentro, pero la vendedora lo sigue visualizando y me envía para tomarla (me aparece y desaparece el proveedor)
Cuando me apareción la dispo, intenté dos veces tomarla y me dio el siguiente error 500:

![image](https://user-images.githubusercontent.com/87333634/184134894-f41099a1-7de0-457f-aeb2-a1e9faf2ddc8.png)

![image](https://user-images.githubusercontent.com/87333634/184134976-f60839a2-24ca-45c4-b374-629cc92a2d62.png)

![image](https://user-images.githubusercontent.com/87333634/184135029-21167377-4488-41db-8a91-637472cce83f.png)

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://ebooking.com.ar/#/atracciones/buscar?destinationId=5a21aafcfc2d56087301cfda&destinationName=londres-inglaterra--reino-unido&fromDate=2022-10-10&toDate=2022-10-13&nationality=AR&residence=AR&occupancies=5*30,30,30,30,30*0*&disney=false&currency=USD

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos, cómo va? 

Un error 500 es un error interno del proveedor

Podrían consultarle qué pasa usando ese RQ y esa RS?

Saludos
