### ISSUE TITLE
ERROR BUSQUEDA MSC

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#60]
Estimados buenas tardes,
Tenemos el siguiente inconveniente con una bvusqueda de Cruceros.

¨Chicos,
Estuve intentando hacer una búsqueda en Cruceros, naviera MSC, y en Doble me da perfecto, pero cuando agrego los menores me da error. 
Este link es la búsqueda con los menores¨

https://www.ebooking.com.ar/#/cruceros/buscar/6/caribe?cruiseId=1019&nationality=AR&residence=AR&occupancies=2*30,30*2*7,4&currency=USD&minDuration=1&maxDuration=4&departureDateFrom=2022-03-01&departureDateTo=2022-03-31

Cuando elijo la salida del 31/3/22, me salta este error y no me deja seguir.

![image](https://user-images.githubusercontent.com/45457355/129419087-1a263354-0f56-4933-9974-d5bcc0fa19a5.png)

¨Busqué en MSCBOOK, para ver si no era error de ellos, y ahi si me da. Adjunto cotizacion de MSC. Lo que me parece es que MSC tampoco esta cotizando el imp pais, que si salia en sus cotizaciones.¨

![image](https://user-images.githubusercontent.com/45457355/129419130-0d9b92a7-dad0-4777-9cf5-dd76d93df186.png)

**Comment by josecaserez** [comment]
Se estaba produciendo un error por categorias estaticas que no existian al consultar en avail. Ya se subio fix #6389.

En cuanto a el impuesto Pais se esta mostrando correctamente:
![image](https://user-images.githubusercontent.com/44671928/130130884-5fc4dafc-bde7-477a-8f93-0b79c4fca105.png)
