### ISSUE TITLE
[Toselli Tours] Error para tomar reserva con grupo existente

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#602]
### Descripcion del error

¡Hola! Estamos con un problema, intentamos tomar varias reservas con un número de grupo existente y nos salta error.
El número de grupo es 376287 y ya nos había pasado con otro número de grupo 414525, tuvimos que tomar las reservas con un grupo nuevo y en el adm cambiarlos manualmente.
Las credenciales son: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | contraseña Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/185214282-02c8107c-d11b-4249-b6a5-36dd789752aa.png)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/alojamiento/finalizar-compra/62fd30eff27b2604611ee694?currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Esto está hecho a proposito

No dejamos que las agencias puedan cargar mas de 25 reservas por grupo 

De hecho, el mensaje es bastante claro

Por otro lado, no agrupen todas las reservas dentro de un grupo, por favor se los pido
Ustedes pueden hacerlo por sus permisos de usuario, pero no deberían hacerlo ya que va a generar problemas a futuro

Saludos
