### ISSUE TITLE
[Wamos] Discrepancias en costo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#603]
### Descripcion del error

¡Hola chicos!
¿Podrán revisar los costos integrados con el proveedor Wamos?
Nos han reportado nuevamente el inconveniente. En este caso, nos indica Nati Salino, que se está realizando un mark up sobre la tarifa de venta:

![image](https://user-images.githubusercontent.com/87333634/185218922-d33eba98-2391-45f2-bbc0-b48e34de76e5.png)

![Uploading image.png…]()

Muchas garcias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2022-02-17&purchaseGroupId=419590

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Corregimos la integración de Wamos con el tema de las comisiones hace rato
Olvidamos cerrar esto 

Saludos!
