### ISSUE TITLE
[Ebooking- Cruceros] No cargan imágenes

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#604]
### Descripcion del error

¡Hola chicos! Encontramos que en la plataforma el Ebooking, en el apartado **Cruceros**, en la opción "Italia, España, Canarias, Madeira, Portugal, Francia" no cargan las imágenes de portada.
Las credenciales son: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) y contraseña Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/185222430-ac312946-5993-4c69-ae2f-f978355c115c.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/cruceros/detalle/62fd3b76f27b260461219ed6/62fd3b78f27b26046121b71e?currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola! ¿Hay noticias sobre esto?

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

La plataforma de cruceros está siendo reworkeada, por lo que ya sabemos que hay miles de cosas mal 😄 

Estamos trabajando a mil para solucionarlo cuanto antes

Saludos!

**Comment by RoDiaz1996** [comment]
Ahh bueno jajaja esperamos entonces  :+1: 

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Las issues de cruceros las pasamos a todas a nuestro backlog, ya que todas están contempladas para la reestructuración de Cruceros en eBooking

Cierro issue para evitar duplicidad

Saludos!
