### ISSUE TITLE
[Ebooking y Juan Toselli - Salidas] Desplegable

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#605]
### Idea a implementar

¡Hola chicos! Tenemos una sugerencia con respecto a la pestaña salidas en Ebooking y Juan Toselli. 
En dónde ingresamos el destino no se abre un desplegable y no debemos seleccionar la opción (imagen 1) como en alojamiento o en los otros servicios (imagen 2). Puede prestarse a confusión.

Imagen 1:
![image](https://user-images.githubusercontent.com/108418973/185686259-ce8b8be7-425b-4332-ad43-f5036f3b3cad.png)
https://www.ebooking.com.ar/#/salidas/buscar/turismo-nacional

Imagen 2:
![image](https://user-images.githubusercontent.com/108418973/185686485-225bb856-4312-4a64-8220-946a0058a7c7.png)

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Esto no es un desplegable, ahí podés escribir un nombre como "San martin" y al darle Enter te va a filtrar por nombre

Saludos!
