### ISSUE TITLE
[Ebooking - Reservas] No se pueden descargar los vouchers

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#608]
### Descripcion del error

¡Hola! Un cliente nos avisó que no puede **descargar los vouchers de sus reservas confirmadas y pagadas**. Ingresamos con sus credenciales y en las reservas confirmadas y pagadas no figura el botón _descargar voucher_. Se puede enviar y se abre para visualizar, pero no te permite descargar.
Las credenciales son: 
- Usuario: analia@coffeeandtravel.com.ar
- Contraseña: Agosto2022

Gracias.

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/186430968-12bce668-2dc1-43fe-89c2-c8db59f4648a.png)
![image](https://user-images.githubusercontent.com/108418973/186431376-3c44892f-0a6c-40e4-b99d-78a5c693bc43.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/mi-cuenta/mis-reservas/por-grupo/416437/62e977cb8126672972161b08

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Listo!

**Comment by gabrielmarinsaldaJT** [comment]
Ahora los Vouchers se pueden ver y enviar al mismo tiempo

No se pueden poner una opción para que los descarguen, necesitan ser enviados por mail
