### ISSUE TITLE
[Ebooking - Aéreos] Itinerario

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#609]
### Idea a implementar

¡Hola! Vengo con una sugerencia en el apartado de aéreos de las plataformas. Una vez que hacemos la búsqueda de vuelos, nos aparecen las opciones y para ver el itinerario debemos tocar "_Ver itinerario_", estaría bueno sumar cómo botón el ícono de **flecha** que aparece al lado. Ya que si la tocamos no pasa nada.

![image](https://user-images.githubusercontent.com/108418973/186438749-82a06a6a-bee2-4d8c-b620-2e19f0f0e655.png)

Por otro lado, vemos que cuando hay escalas aparece: "**2 escala s**", la s aparece separada de la palabra:

![image](https://user-images.githubusercontent.com/108418973/186439326-63bff72d-e091-4c24-867b-7b63a743cf88.png)

**Comment by gabrielmarinsaldaJT** [comment]
Solucionados ambos problemas!

**Comment by RoDiaz1996** [comment]
¡Hola! Recién hice una búsqueda y me apareció asi:
![image](https://user-images.githubusercontent.com/108418973/188167668-a552fe26-c16c-4a76-ab50-d7a2146929a1.png)
https://ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2022-09-23!2022-09-25!COR!MAD&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Ro

Cuando hacemos cambios en el front, a veces no los ves reflejados porque tu PC guarda un caché en tu explorador. Usualmente esto suele actualizarse solo en unas horas, pero a veces no (Depende de la configuracion de cada PC)

Puedo asegurarte que está OK

En todo caso, hacé Ctrl + R en la página y verás que se muestra bien

Saludos
