### ISSUE TITLE
Color botón 'Agregar al carrito'

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#61]
Estimados buenas tardes
Podríamos modificarle el color del botón 'Agregar al carrito' ?
En Toselli Tours. Digo para que no se pierda en el mismo zócalo gris.

![image](https://user-images.githubusercontent.com/88336164/129791414-e791645b-95d5-476f-af79-f5514cdc8408.png)

Gracias!
Agos

**Comment by aletatan** [comment]
ya esta solucionado, cuando @moliveto publique se verán los cambios
