### ISSUE TITLE
[Todas las plataformas] Pensión completa

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#610]
### Descripcion del error

¡Hola chicos! Estamos con un inconveniente, cuando hacemos búsquedas de alojamientos con **Pensión Completa** y **Todo Incluido** Aparecen opciones que no incluyen esta opción de suplemento.

Hicimos la búsqueda en ARUBA (imagen 1)

- El hotel **Courtyard Aruba Resort** no tiene opción de pensión completa (imagen 2) y no aparece la opción de buscar en los filtros  de los suplementos de la habitación.
- El hotel **Amsterdam Manor Beach Resort** tampoco tiene la opción (imagen 3).
- El hotel **Hilton Aruba Caribbean Resort & Casino** tampoco tiene la opción.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022 

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

Imagen 1.

![image](https://user-images.githubusercontent.com/108418973/186915192-3f515ce3-3bf9-442a-801d-c51503c34a93.png)
![image](https://user-images.githubusercontent.com/108418973/186915296-c3efb260-70b6-4a7d-97e0-6f0c0fbb8d04.png)
https://ebooking.com.ar/#/alojamiento/buscar?id=5a21b14afc2d560873053edb&name=aruba---aruba&checkIn=2022-12-26&checkOut=2023-01-03&nationality=AR&residence=AR&occupancies=2*30,30*0*%7C2*30,30*2*12,9%7C2*30,30*2*12,9&currency=USD

Imagen 2.

![image](https://user-images.githubusercontent.com/108418973/186915958-c83ea69b-d9e1-4d5c-bbcd-5083d9a70523.png)
https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca977c886315a56f0da2dc6/courtyard-aruba-resort?checkIn=2022-12-26&checkOut=2023-01-03&nationality=AR&residence=AR&occupancies=2*30,30*0*%7C2*30,30*2*12,9%7C2*30,30*2*12,9&currency=USD

Imagen 3.

![image](https://user-images.githubusercontent.com/108418973/186916544-d0f80548-3409-4a7c-84d7-9e3ebce3d751.png)
https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca8e0a986315a56f0c6fea5/amsterdam-manor-beach-resort?checkIn=2022-12-26&checkOut=2023-01-03&nationality=AR&residence=AR&occupancies=2*30,30*0*%7C2*30,30*2*12,9%7C2*30,30*2*12,9&currency=USD

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento/buscar?id=5a21b15bfc2d560873053ff6&name=armacao-dos-buzios-y-sus-alrededores-rio-de-janeiro--brasil&checkIn=2023-01-10&checkOut=2023-01-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola! También hicimos la búsqueda a Búzios y los siguientes hoteles aparecen con el filtro **Pensión completa** y no tienen esta opción:
https://ebooking.com.ar/#/alojamiento/buscar?id=5a21b15bfc2d560873053ff6&name=armacao-dos-buzios-y-sus-alrededores-rio-de-janeiro--brasil&checkIn=2023-01-10&checkOut=2023-01-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD
-  Azeda Boutique
- Atlantico Buzios Convention & Resort
- Colonna Park Hotel
- Byblos Pousada

También queremos sugerir que los filtros de los suplementos en las habitaciones se ordenen alfabéticamente, en ocasiones son muchos y es complicado ubicar el que buscamos.
![image](https://user-images.githubusercontent.com/108418973/186934963-0f1b5886-6baf-432d-83d6-f1651e90bfbe.png)

Gracias

**Comment by CandelaMontes** [comment]
Volvi a chequear en EB y JT y esta solucionado. En TT sigue sin traer dispo all inclusive

**Comment by gabrielmarinsaldaJT** [comment]
Hola Cande y Ro

A veces los proveedores cachean su Avail y suelen mostrar resultados un poco dispares

Nosotros no podemos controlar el tipo de pensión que devuelven en las respuestas de los Avails, por lo que muchas veces depende del buen funcionar del servidor de los proveedores

Si ven que algún proveedor da error, o simplemente no aparece en un hotel y saben que **debería** hacerlo porque lo ven en su web directa o en otro portal, pueden avisarnos y lo revisamos con gusto

Saludos!
