### ISSUE TITLE
[Cruceros] Falta información en el check out

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#611]
### Descripcion del error

¡Hola! Estamos con un problema en la pestaña **Cruceros** en las plataformas de Toselli. Buscamos cruceros a Europa, avanzamos hasta la página del check out y no **hay información** en el recuadro verde arriba y en el resumen al margen derecho (imagen 1).
Tampoco aparecen las peticiones del proveedor y no dice "Acepto términos y condiciones..." (imagen 2).

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

Imagen 1.

![image](https://user-images.githubusercontent.com/108418973/186937607-a9e78122-da5c-4df3-a236-e9b9308d8f6b.png)
![image](https://user-images.githubusercontent.com/108418973/186938148-d0e1d5d0-9583-4dbf-8a17-021296f28624.png)

Imagen 2.

![image](https://user-images.githubusercontent.com/108418973/186937970-38366823-d605-42ca-8f23-9fac04432ab4.png)
![image](https://user-images.githubusercontent.com/108418973/186938316-c241291a-f423-40e7-906b-2464fc726190.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/cruceros/finalizar-compra/6308e328f9061a347df30104?currency=USD

### Plataforma

Google Chrome

**Comment by CandelaMontes** [comment]
Hola chicos! Han podido ver este inconveniente? Sigue igual

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Las issues de cruceros las pasamos a todas a nuestro backlog, ya que todas están contempladas para la reestructuración de Cruceros en eBooking

Cierro issue para evitar duplicidad

Saludos!
