### ISSUE TITLE
[Circuitos] Gran diferencia de precios

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#612]
### Descripcion del error

¡Hola chicos! Tenemos un inconveniente en la pestaña de **Circuitos**. Buscamos en Europa, nos aparece un precio del circuito (imagen 1) y a medida que avanzamos **va aumentando la tarifa** hasta terminar en una muy elevada comparada a la primera tarifa. 
Seleccionamos la primera opción y no trae disponibilidad.
Las otras opciones son más altas y cuando seleccionamos nos dice otra tarifa.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

Imagen 1

![image](https://user-images.githubusercontent.com/108418973/186939901-88046d2e-5f5c-4335-a151-386298a1621c.png)

Seleccionamos la opción 1 que es la tarifa que nos decía primero y no hay disponibilidad:
![image](https://user-images.githubusercontent.com/108418973/186940075-840d406a-2537-4ee3-b4fb-a45a04031299.png)

Las otras opciones son más altas y cuando seleccionamos nos dice otra tarifa.
![image](https://user-images.githubusercontent.com/108418973/186940289-20bb046f-d9d8-45f3-9081-6a9283a562a2.png)

Lo mismo pasa en Toselli Tours:
![image](https://user-images.githubusercontent.com/108418973/186940448-b47bffc0-c7a2-4cf6-8df4-afc02a9d5e29.png)
https://travel.tosellitours.com/#/circuitos/detalle/62c1455a2d2f30f41c0a5b73/escapate-a-paris-turistico-lunes?currency=USD&residence=AR&nationality=AR

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/circuitos/detalle/62c1455a2d2f30f41c0a5b73/escapate-a-paris-turistico-lunes?currency=USD&residence=AR&nationality=AR

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Esta info es la que nos envía el proveedor cuando le consultamos por el catálogo

Además, el precio que ves en la lista de arriba es por persona, y seguramente abajo buscaron por mas de una persona y además está sumando impuestos

Por lo que veo, no tenemos nada que hacer

Saludos!
