### ISSUE TITLE
ADM - Sistagen

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#613]
### Descripcion del error

Hola chicos!
Nos reportan desde el area de pagos esta sucediendo que los vouchers se sincronizan al sist con el monto del subtotal, sin incluir los impuetos que terminan haciendo al total. Nos han reportado esto con vouchers de TBO y de Expedia. Sincronizándolos, tampoco cambian el costo. 

![image](https://user-images.githubusercontent.com/87333634/186987398-2cfd55ed-bcc5-4b8e-8768-bf79c1553ced.png)

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/186987672-387b1276-f71e-44a0-a398-5a481216b2e2.png)
![image](https://user-images.githubusercontent.com/87333634/186987717-6561b878-942f-489b-a977-36e190291005.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/629224ffca269fde9def771e?purchaseGroupId=383648#heading_629224ffca269fde9def771e

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado chicos!

En caso de que un Voucher no esté correcto, por favor ir al ADM y apretar **el botón azul** de Sincronizar Voucher

Saludos!

**Comment by mvalentinalucero** [comment]
Gabi, claro, pero los sincronizábamos y el costo seguía siendo el mismo, es decir el que no correspondía.
