### ISSUE TITLE
[WAMOS - MAPAPLUS] VENCIMIENTOS

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#614]
### Descripcion del error

Hola chicos!
Tenemos los siguientes casos

- [ ] https://adm.ebooking.com.ar/bookings/detail/623e2c2f5b25a6ee89e72d9b?purchaseGroupId=381482#heading_623e2c2f5b25a6ee89e72d9b
- [ ] https://adm.ebooking.com.ar/bookings/detail/62cdc03c6b77bd4ab8107b63?purchaseGroupId=410274#heading_62cdc03c6b77bd4ab8107b63

En el que el robot no pudo cancelar las reserva, tampoco tengo logs del get cancel y quedaron confirmadas. No así en el proveedor que sí se han cancelado. Solicitamos por favor revisar las políticas de vencimiento de ambos proveedores, ya que el vencimiento nuestro es muy justo al del check in y las politicas de cancelación. Al parecer el proveedor tiene políticas más restrictivas. 
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/623e2c2f5b25a6ee89e72d9b?purchaseGroupId=381482#heading_623e2c2f5b25a6ee89e72d9b

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, Wamos no cancela reservas

Hay que solicitarlo offline

Saludos!
