### ISSUE TITLE
[Ebooking- Alojamientos] No aparece Palladium como proveedor directo

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#615]
### Descripcion del error

¡Hola chicos! Estamos con un problema, en la pestaña de alojamientos de Ebooking buscamos disponibilidad en el hotel **Grand Palladium Costa Mujeres Resort & Spa** y no nos aparece Palladium como proveedor directo para tomar la reserva y nos comunicamos por aparte con Palladium y nos avisan que si tienen disponibilidad.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/187267998-34f85d70-e270-473b-864a-9d7caea20d73.png)

![image](https://user-images.githubusercontent.com/108418973/187267911-2ed899c0-d6cc-4ce7-8c56-bd2925fcb9da.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8d4cc86315a56f0c3f53d/grand-palladium-costa-mujeres-resort---spa?checkIn=2023-01-12&checkOut=2023-01-20&nationality=AR&residence=AR&occupancies=3*30,30,30*1*14%7C2*30,30*0*%7C2*30,30*0*%7C1*30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

En realidad no hay dispo **unicamente** con la opción de 3 ADT + 1 CHD

Podrías consultarle al proveedor para que te expliquen porqué, pero la conexión funciona bien con Palladium

Saludos!
