### ISSUE TITLE
[AVIS] Agregar información tipo de seguro

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#617]
### Descripcion del error

Hola chicos!
Necesitamos modificar la siguien información en el adm, asi luego de emitirse el voucher, figure en el mismo. La información es respecto al seguro tomado:

![image](https://user-images.githubusercontent.com/87333634/187479515-176b0758-fda3-4807-a4b5-f5e5580a5dbe.png)

Debería ser: **SUPER SEE EUROPE ALL INCLUSIVE - 2W**
El cambio se realizó offline. 

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/63019ded9a13a18a3c0bc3d3?purchaseGroupId=421323#heading_63019ded9a13a18a3c0bc3d3

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Listo!
