### ISSUE TITLE
Tour de mapaplus no figura ren Ebooking

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#618]
### Descripcion del error

Reportado por: Pablo de  MDZ
Tour de Mapaplus figura en la web de ellos, peor no en Ebooking

### Paso a paso para reproducir el error

Link del proveedor: 
OC245 - LA EUROPA DE SIEMPRE 18 DIAS LON/ROM
https://www.mapaplus.com/product?productCode=IT23T-OC245&fareCode=PREVENTA&packageCode=IT23T-OC245&stayCode=17N&beginDate=02/09/2022

Busqueda de Ebooking, filtrando por paises, no arroja busqueda (realizada por el vendedor) 
https://www.juantoselli.com/#/circuitos/buscar?cities=5a21aafcfc2d56087301cfda,5a21b155fc2d560873053f75,5a21aec1fc2d56087303a060&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=&nationality=AR&residence=AR&currency=USD

Busqueda por nombre solo me arroja resultado de Wamos, no de Mapaplus
https://www.juantoselli.com/#/circuitos/buscar?cities=&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=siempre&nationality=AR&residence=AR&currency=USD

### Link al error y/o Localizador

https://www.juantoselli.com/#/circuitos/buscar?cities=&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&circuitName=siempre&nationality=AR&residence=AR&currency=USD

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Agregado!
