### ISSUE TITLE
[Asistencias - Universal Assistance] Políticas de cancelación "No reembolsables" (incorrecto)

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#619]
### Descripcion del error

¡Hola! Tenemos un problema con **Universal Assistance**, nos figura con fechas pasadas, es decir, que son **no reembolsables** y esto no corresponde. Las asistencias son todas reembolsables y se pueden tomar hasta una semana antes del Check in.
Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

**Febrero:**
![image](https://user-images.githubusercontent.com/108418973/187682760-77abed7b-34be-4a92-a694-d4b4d39c16e6.png)
https://www.ebooking.com.ar/#/asistencias/buscar?arrivalDate=2023-02-10&departureDate=2023-02-18&origin=AR&destination=Europa&travelType=Un%20viaje&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Noviembre:**
![image](https://user-images.githubusercontent.com/108418973/187683782-e523c65a-fe8b-4b35-8052-89faf7b15daa.png)
https://travel.tosellitours.com/#/asistencias/buscar?arrivalDate=2022-11-10&departureDate=2022-11-17&origin=US&destination=Europa&travelType=Un%20viaje&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Diciembre:**
![image](https://user-images.githubusercontent.com/108418973/187684450-99bff7af-22e5-44e2-8ac0-bc8415cd5402.png)
https://juantoselli.com/#/asistencias/buscar?arrivalDate=2022-12-07&departureDate=2022-12-14&origin=AR&destination=Centro%20america-Caribe&travelType=Un%20viaje&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/asistencias/buscar?arrivalDate=2023-02-10&departureDate=2023-02-18&origin=AR&destination=Europa&travelType=Un%20viaje&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!
