### ISSUE TITLE
[Vehículos] No se ve la imagen en el Check out

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#620]
### Descripcion del error

¡Hola chicos! Detectamos un inconveniente, en la página del check out de los vehículos no carga la imagen.
Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/187686459-68118279-cd45-42ea-8594-3bd5e5fbdad0.png)
https://juantoselli.com/#/autos/buscar?pickUpDate=2022-11-10&pickUpTime=10:00&pickUpOfficeId=CPT&pickUpCityId=5a430553fc0b9d5df18ba908&pickUpCityName=western-cabo-western-cape--republica-de-sudafrica&returnDate=2022-11-18&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

![image](https://user-images.githubusercontent.com/108418973/187686527-8413702c-3b6d-405b-acec-f3814f593eb5.png)
https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2022-11-01&pickUpTime=10:00&pickUpOfficeId=CDG&pickUpCityId=5a21b155fc2d560873053f75&pickUpCityName=paris-y-sus-alrededores-isla-de-francia--francia&returnDate=2022-11-16&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

![image](https://user-images.githubusercontent.com/108418973/187686594-a06e4d15-ddca-40f8-884c-213acb8dc297.png)
https://travel.tosellitours.com/#/autos/buscar?pickUpDate=2022-11-18&pickUpTime=10:00&pickUpOfficeId=MAD&pickUpCityId=5a21b155fc2d560873053f77&pickUpCityName=madrid-y-sus-alrededores-madrid--espana&returnDate=2022-11-26&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2022-11-01&pickUpTime=10:00&pickUpOfficeId=CDG&pickUpCityId=5a21b155fc2d560873053f75&pickUpCityName=paris-y-sus-alrededores-isla-de-francia--francia&returnDate=2022-11-16&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado !

Está en plena publicación el front, asique lo verás reflejado en la página en unos 30 minutitos
