### ISSUE TITLE
[Aéreos] Discrepancia de precios

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#622]
### Descripcion del error

¡Hola chicos! Encontré una diferencia en precios de aéreos, realicé la búsqueda desde **Córdoba a Bangkok** y me aparecen vuelos con tarifas de USD 10.000 aproximadamente y cuando hago una búsqueda desde **Buenos Aires a Bangkok** me aparecen tarifas de USD 18.000 aproximadamente. Esto pasa en todas las plataformas.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

**Córdoba a Bangkok:**
![image](https://user-images.githubusercontent.com/108418973/187700303-a44e34b3-b5d0-4b99-8d83-c3a2aed635fb.png)
https://travel.tosellitours.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-01-10!2023-01-17!COR!BKK&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD#630f6835d64338b48fe7c108

**Buenos Aires a Bangkok**
![image](https://user-images.githubusercontent.com/108418973/187700693-c0ca7f27-1762-4910-93dd-dd38b39b6d21.png)
https://travel.tosellitours.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-01-10!2023-01-17!EZE!BKK&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Link al error y/o Localizador

https://travel.tosellitours.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-01-10!2023-01-17!COR!BKK&flex=true&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD#630f6835d64338b48fe7c108

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro

Estos precios los ves mas baratos en otros portales?

Cuál es el problema?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Siendo asi el problema, podríamos preguntarle a Sabre o alguien que sepa de aéreos y nos pueda comentar al respecto

Por nuestra parte no hay nada que podamos hacer, nosotros recibimos el precio y los segmentos de un vuelo y los mostramos en la pantalla, pero no filtramos ni los movemos de lugar

Saludos!
