### ISSUE TITLE
[adm] Modificar propiedades

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#623]
### Descripcion del error

Hola chicos!
Necesitamos modificar las siguientes reservas con las siguientes propiedades en el adm, para que luego figuren en los vouchers:

- [x] https://adm.ebooking.com.ar/bookings/detail/62b9d235360eb61e27d8bf34?purchaseGroupId=404663#heading_62b9d235360eb61e27d8bf34

![image](https://user-images.githubusercontent.com/87333634/187763930-836cc897-acaf-432b-870c-f52af048b468.png)

- [x] https://adm.ebooking.com.ar/bookings/detail/62b9d1e7360eb61e27b9cd11?purchaseGroupId=404663#heading_62b9d1e7360eb61e27b9cd11

![image](https://user-images.githubusercontent.com/87333634/187764046-66fe7bde-a853-4fbc-8a8b-5a32a0697a5d.png)

Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Listo chicos

Revisen porfas!
