### ISSUE TITLE
[Asssitcard] Revisar integración - Reservas en error 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#624]
### Descripcion del error

Hola chicos!
Estamos teniendo nuevamente problemas con reservas de Assit card, que nos llega en revisar y nos figura la siguiente nota:

![image](https://user-images.githubusercontent.com/87333634/187996154-5863a175-16cd-4aa8-8bfd-2c5948375a77.png)

Hemos enviado los logs al proveedor y nos indican que las reservas no se hacen, debido a un error en el código:

![image](https://user-images.githubusercontent.com/87333634/187996309-2b9a8dad-1c49-40a7-8a94-6f10e3502f11.png)

Podrán revisarlo?
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62f576c2497936dbd171b887?purchaseGroupId=418829#heading_62f576c2497936dbd171b887

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Cambiado el code

Saludos
