### ISSUE TITLE
[Budget - Avis] Revisar integración

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#625]
### Descripcion del error

Hola chicos! 
Hemos tenido una reunión con Jessica de Budget y nos ha indicado que, por integración, habría que corroborar de nuestro lado:

- [ ] No estamos mostrando para seleccionar el grupo del auto por ejemplo:

![image](https://user-images.githubusercontent.com/87333634/188164366-8962c165-efd8-4a52-a561-e21560d63a4a.png)

![image](https://user-images.githubusercontent.com/87333634/188164745-66621db6-1673-4f12-ac6f-90bc9de251dd.png)

Mostramos solo el LQ

- [ ] Por otro lado, mostramos otra tarifa distinta, que es aquí cuando vemos las diferencias de costos, ya que nosotros, no incluimos el one way fee y local tax (Budget después nos reclama un costo mas caro al momento de pagarla)

![image](https://user-images.githubusercontent.com/87333634/188165297-715be646-7276-47ce-adca-55596234be64.png)

![image](https://user-images.githubusercontent.com/87333634/188165354-015c52a0-08f3-44b3-8f98-1f8a67b7e713.png)

Podrán revisarlo? 
Les dejo los links de búsqueda del ebooking y web de budget. Con Avis, habría que revisarlo lo mismo, puesto que sucede igual.

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2022-11-01&pickUpTime=12:00&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2022-11-30&returnTime=12:00&returnOfficeId=JFK&returnCityId=5a21b153fc2d560873053f73&returnCityName=nueva-york-y-sus-alrededores-nueva-york--estados-unidos&isOnAirport=true&nationality=AR&residence=AR&currency=USD // https://carrental-int.com/budget/res/prereservation.php

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Me pondré en contacto con el proveedor

Pero por lo pronto acá van dos aclaraciones importantes

1- No se pueden agrupar las tarifas por grupos, eso lo hace Budget en su página y nosotros, si bien tenemos la info del grupo, no lo vamos a hacer ya que mostramos a otros proveedores que no tienen esta agrupacion como si tienen Avis/Budget

2- Las inclusiones de tarifas nos llegan por XML, por lo que nosotros solo mostramos lo que ellos nos envían. Revisaremos que es lo que llega y nos pondremos en contacto para saber que es lo que está llegando mal

Saludos

**Comment by GuadaVivas** [comment]
Hola Gabi,
Gracias por la aclaración del primer punto.
Entonces lo importante es ver el tema costos, así ya se pueda cotizar completamente desde nuestra web (los vendedores lo hacen tambien en la web del proveedor)

**Comment by GuadaVivas** [comment]
Hola chicos!
Tendrán alguna novedad? Hemos tenido una incidencia en destino de pasajeros que debieron abonar un tax, que nosotros hemos mostrado que lo incluía y no debía.

**Comment by GuadaVivas** [comment]
chicos, alguna novedad?

**Comment by GuadaVivas** [comment]
Hola chicos! alguna novedad? Seguimos teniendo perdidas respecto a esto. Gracias.

**Comment by GuadaVivas** [comment]
Hola chicos!
Alguna novedad?

**Comment by GuadaVivas** [comment]
Hola chicos!
Alguna novedad?

**Comment by GuadaVivas** [comment]
Hola chicos,
Alguna novedad?

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado hace varios días

Nunca cerramos la issue
