### ISSUE TITLE
[Cupos] No se puede tomar cupos

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#626]
### Descripcion del error

¡Hola chicos! Estamos con un problema, no podemos tomar cupos. Buscamos el cupo a Punta Cana desde Buenos Aires el 27 de noviembre en el hotel Riu República para 3 pax (1 habitación doble y 1 single). Completamos todos los datos en la página el check out y nos dice diferentes cosas. A la vendedora le sale el cartel de la imagen 3 y yo trato de completar y me dice que el nombre no es válido y después no se activa el botón de _Finalizar Compra_.
Las credenciales son :
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias

### Paso a paso para reproducir el error

.

### Captura del error

Imagen 1.
![image](https://user-images.githubusercontent.com/108418973/188192633-50e849d3-b9aa-4bc7-a855-3e3c067305f3.png)

Imagen2.
![image](https://user-images.githubusercontent.com/108418973/188192853-163821cf-ad8e-4d61-a392-265b13171953.png)

Imagen 3.
![image](https://user-images.githubusercontent.com/108418973/188192995-7a9c5ad9-0bd7-42cc-91e1-f45c51a07df9.png)

Imagen 4.
![image](https://user-images.githubusercontent.com/108418973/188193405-b2611ed4-bd54-49c5-9cd0-ebfb3c210299.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/cupos-confirmados?destinationFrom=5a458122fc0b9d5df191f47f&fromDate=2022-11-27&toDate=2023-12-04

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola chico! ¿Hay alguna novedad sobre esto?

**Comment by RoDiaz1996** [comment]
¡Hola! Seguimos con inconvenientes en Cupos, en el proceso de reserva nos saltan diferentes errores.

PORTO GALINHAS DESDE BUENOS AIRES
![image](https://user-images.githubusercontent.com/108418973/193272076-190b1821-7b96-45ba-ad62-359d97e15f67.png)
https://www.ebooking.com.ar/#/cupos-confirmados/detalle/5a50bf57abd921b6ce436b22/porto-galinhas-desde-buenos-aires?from=5a458122fc0b9d5df191f47f&quota=62ed742f4c356b3108a4b0ac&occupancies=2*30,30*1*2&nationality=AR&residence=AR&token=0106MMADJV

![image](https://user-images.githubusercontent.com/108418973/193274060-fd0874f1-1490-40a9-863b-a70f6d246d4d.png)

![image](https://user-images.githubusercontent.com/108418973/193272132-df5de7ef-bf9b-445f-b3d0-1dabffa3804f.png)
https://www.juantoselli.com/#/cupos-confirmados/detalle/5a50bf57abd921b6ce436b22/porto-galinhas-desde-buenos-aires?from=5a458122fc0b9d5df191f47f&quota=62ed742f4c356b3108a4b0ac&occupancies=2*30,30*1*2&nationality=AR&residence=AR&token=0106MMADJV

![image](https://user-images.githubusercontent.com/108418973/193273041-bf03bba0-4c5a-4976-89cc-5555b45f19fa.png)

**Comment by RoDiaz1996** [comment]
¡Hola! ¿Alguna novedad sobre esto?

**Comment by gabrielmarinsaldaJT** [comment]
Solucinado!
