### ISSUE TITLE
[Administrador - Reservas] Aparece el nombre de Karla

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#629]
### Descripcion del error

¡Hola chicos! Estamos con un inconveniente, las agencias GALLO TRAVEL y ANTHONY’S TRAVEL SERVICES toman reservas y se coloca el nombre de **Karla Rojas** cuando corresponde que aparezca como vendedora **Evangelina Irigoyen**. Creemos que es porque firmaron hace mucho tiempo y Karla era su vendedora ¿Habrá posibilidades de cambiarlo?
Gracias.

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/188506982-142ac9cc-f889-467e-bb0d-758e59b693ab.png)
![image](https://user-images.githubusercontent.com/108418973/188507337-c59fd6f3-c3ec-47e2-b956-ea3adb5b86f0.png)

### Link al error y/o Localizador

https://adm.tosellitours.com/bookings?dateFrom=2022-03-05&agency=Anthony

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado

Recuerden deshabilitar los usuarios de vendedores que se hayan ido de la empresa. Quizá la agencia vio a Karla como su vendedora y lo eligio 

Saludos
