### ISSUE TITLE
DISPO PALLADIUM

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#63]
Hola Chicos buenas tardes,
Adjunto pedido de Pablo Negro:

No esta saliendo disponibilidad de Palladium en la web, y me dicen de palladium que tiene dispo. Que les enviemos los Logs
Les paso la búsqueda

https://www.juantoselli.com/#/alojamiento/disponibilidad/5ca9a53d86315a56f0dd7e3f/grand-palladium-bavaro-suites-resort---spa?checkIn=2022-01-05&checkOut=2022-01-16&nationality=AR&residence=AR&occupancies=2*30,30*2*12,9&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Ahora mismo estoy viendo disponibilidad con Palladium

Necesitan alguna habitación en particular?

Saludos
