### ISSUE TITLE
[Administrador] Usuario Matías Casanova

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#630]
### Descripcion del error

¡Hola! Chicos el usuario [matias.casanova@tosellitours.com](mailto:matias.casanova@tosellitours.com) se encuentra mal cargado en la cuenta de Toselli Tours Santa Catalina (imagen 1) ¿Pueden borrar ese usuario? (imagen 2)

Gracias.

### Paso a paso para reproducir el error

.

### Captura del error

Imagen 1.
![image](https://user-images.githubusercontent.com/108418973/188509983-98d1bca0-83d5-42c8-8ec7-da2e94911be3.png)

Imagen 2.
![image](https://user-images.githubusercontent.com/108418973/188510043-54d29b61-46b5-452e-8c17-299636b50c10.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/users?isActive=1&agencyId=540b0fb929116d03c81eb99a

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Desactivado!
