### ISSUE TITLE
[Traslados] Poder ocultar los resultados

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#631]
### Idea a implementar

¡Buenos días chicos! Tenemos una sugerencia para la pestaña **Traslados**. Una vez que realizamos la búsqueda y nos traen los resultados de los vehículos de ida y vuelta, estaría bueno poder ocultar los resultados de ida para ver los de vuelta y no tener que scrollear hasta encontrar los traslados de vuelta. Esto nos sirve a la hora de cotizar para comparar y ahorrar tiempo.
Decimos de **agregar un botón en la flecha para poder ocultarlos**.

![image](https://user-images.githubusercontent.com/108418973/188885720-b4abffe6-55d7-415d-bdcf-a713674ea44f.png)
https://www.ebooking.com.ar/#/traslados/buscar?transferType=1&landingTime=false&arrivalDate=2022-10-01&arrivalTime=10:00&arrivalPointDataId=EZE&arrivalPointDataName=buenos-aires-argentina-eze-ministro-pistarini-intl-&arrivalPointDataSmartSearchEnum=3&departureDate=2022-10-16&departureTime=10:00&destinationPointDataId=5ca9324c86315a56f0d381e3&destinationPointDataName=buenos-aires-inn-hotel-buenos-aires--argentina&destinationPointDataSmartSearchEnum=1&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

**Comment by gabrielmarinsaldaJT** [comment]
Issue elevada a los chicos de front
