### ISSUE TITLE
[Vehículos] Los precios no se ordenan en forma ascendente

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#633]
### Descripcion del error

¡Hola! Encontramos un problema en la pestaña **Vehículos**, al realizar la búsqueda descubrimos que los resultados no se ordenan de forma ascendente en base a los precios.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/188964798-7d4e8565-d398-4e7f-bb51-148cd3171d96.png)
![image](https://user-images.githubusercontent.com/108418973/188964918-aafe4939-ff6c-41be-b3a2-1141a7fcab9b.png)
![image](https://user-images.githubusercontent.com/108418973/188965027-d49f7a42-8ba2-4989-9a5e-0f12da4ff318.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/autos/buscar?pickUpDate=2023-01-25&pickUpTime=10:00&pickUpOfficeId=CTG&pickUpCityId=5a21b159fc2d560873053fec&pickUpCityName=cartagena-de-indias-y-sus-alrededores-bolivar--colombia&returnDate=2023-02-05&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Esto fue hecho así a propósito, ya que las tarifas de vehículos que ves al principio son las tarifas recomendadas por los proveedores y no las mas baratas

Muchas veces las agencias, por reservar la tarifa mas barata, terminaban teniendo problemas ya que al hacer el PickUp del auto tenian muy pocos seguros cubiertos y terminaban pagando la diferencia en destino

Saludos!
