### ISSUE TITLE
[Administrador] Eliminar agencias

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#634]
### Descripcion del error

¡Hola chicos! Estamos necesitando su ayuda para crear, en el administrador de Ebooking, una **opción para eliminar agencias**, ya que hay más de 80 ítems en 4 páginas de agencias EN DESUSO.

¡Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/188966112-97defdb1-7e8a-429f-9d54-46d3e0eca11b.png)
![image](https://user-images.githubusercontent.com/108418973/188966165-6576127c-6a8d-4a7d-a50e-80c56295e676.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/agencies?type=1&fiscalName=en%20desuso&page=1

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

No podemos dar una funcion para eliminar, y tampoco podemos eliminar agencias

Porque pusieron agencias asi????

Si una agencia se duplicaba / creaba dos veces, tienen la funcion de "Fusionar agencias" 

![image](https://user-images.githubusercontent.com/26115345/188968862-a577da78-1f3b-49e7-a89d-de05db3d0b99.png)

Con eso migraban todas las reservas de una a la otra y evitaban problemas

Saludos

**Comment by RoDiaz1996** [comment]
¡Hola Gabi! Si, utilizamos _Fusión de Agencias_ cuando se repiten pero no elimina la agencia, sigue quedando (sólo se desactiva) y debemos cambiarle el nombre para que no se duplique e identificar rápidamente cuál está en uso.

**Comment by CandelaMontes** [comment]
¿Cuál podría ser una solución a esto?

**Comment by gabrielmarinsaldaJT** [comment]
Una consulta

Porque no buscan las agencias que están activas solamente?
