### ISSUE TITLE
Error en costo y venta tour special 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#635]
### Descripcion del error

Loc: 402507254

El tour da error en el costo y venta en Ebooking, ya fue reservado por allí, es necesario ajustarlo para poder facturarlo. 
Localizador Ebooking/Special

El costo debe ser: U$D 961
El precio de venta comisionable debe ser U$D 1233

### Paso a paso para reproducir el error

.

### Captura del error

Costo y Venta Special Tours

![image](https://user-images.githubusercontent.com/88200755/189211835-b36c171b-93c5-404c-9f73-bcb6da5143e0.png)

Costo y Venta (total comisionable) Ebooking

![image](https://user-images.githubusercontent.com/88200755/189212102-6c746a6d-6e31-4824-a09b-359c34bbe207.png)
![image](https://user-images.githubusercontent.com/88200755/189212155-5f7b17b9-4b8f-469e-a5f7-1f184b0ce4b9.png)

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Listo!
