### ISSUE TITLE
Servicios en Ebooking sin vendedor

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#636]
### Descripcion del error

Hola chicos, como estasn?
Van varias agencias que nos indican que al reservar no les deja marcar vendedor. Nosotros vemos ese campo en blanco
Les reporto los que yo detecté porque el equipo o alguein del piso me fue pidiendo que modifique el vendedor a medida que la agencia le fue pidiendo liquidación. estas que les paso son de las ultimas semanas, que fui juntando para reportarles todo en un solo Issue. 
Como les digo, ya estan todos modificados los vendedores, pero les paso localizador o grupo, agencia y vendedor, asi pueden revisarlos
saludos y gracias :) 
Nati

Loc 1043474 – Agencia Silvusky - Andrea
Loc 1043720 – Agencia MV Viajes (Jorge) - Andrea
Loc 13630090AR5 – Agencia Silvusky - Andrea
Grupo 414550-Agencia kely viajes – Celeste 
Grupo 413509- Agencia Soler Rey – Celeste  
Loc 1150408711 – Agencia Beggia – Natalia   
Loc 1048479 – Agencia Travel Solutions – Natalia  
Loc 1049293 – Agencia Taw Travel – Brenda 
Loc 501123779 – AGENCIA MAIN STREET - Andrea
Loc 1047610 – Agencia Silvusky – Andrea
Loc 1053692 – Soler Rey – Celeste  
Loc 1059050 – Agencia Silvusky – Andrea
Loc 1059046 – Agencia Silvusky – Andrea
Grupo 418288 - Agencia Silvusky – Andrea
Grupo 413844 – Agencia Sporting – Andrea
Loc 102-12708073 – Himalaya cerro – Natalia
Loc 1050512 – sporting - Celeste
Loc 1068151 – Donde Vas - Celeste
Loc 1063346 – Soler rey Viajes – Celeste 
Loc 15383766AR6 – mariana Bonelli - Andrea
Loc 9923397798  - cecilia onis – Andrea
Loc 9923397817 – cecilia onis – Andrea
Grupo 425887 – turismo Sporting – Celeste 
Grupo 425090 – Turismo Sporting – Celeste 
Grupo 424982 – Turismo Sporting – Celeste 
Grupo 424969 – Turismo Sporting – Celeste
Grupo 420951 – Tirismo Sporting – Celeste 

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado! Ya no puede volver a suceder

En caso de que algunas reservas no tengan vendedor, notificarle a Operaciones
