### ISSUE TITLE
[Adm] Modificar nombre de propiedad

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#638]
### Descripcion del error

Hola chicos!
Necesitamos por favor modificar el nombre de la propiedad del grupo 424033 (es el mismo, pero ha cambiado el bombre) asi se pueda entregar los vouchers con el nombre correcto.

![image](https://user-images.githubusercontent.com/87333634/189437777-6cc94299-47af-4c05-9183-b10520804399.png)

Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2022-03-09&purchaseGroupId=424033

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
Buenas tardes, la vendedora volvió a insistir sobre esta modificación. Aguardamos novedadessss

**Comment by BelenBidondo** [comment]
hola chicos, cuando puedan modifiquen esto porfa

**Comment by PatricioH96** [comment]
Solucionado.
