### ISSUE TITLE
VOUCHERS CON ERROR AL SINCR.

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#64]
Estimados buenas tardes,
Vendedora me indica que los siguientes vouchers cancelados no están pudiendo ser sincronizados en 0 al book,
Adjunto loc de los mismos y links.

f793041
https://adm.ebooking.com.ar/bookings/detail/5e31859912d9d921d0412294?purchaseGroupId=305087#heading_5e31859912d9d921d0412294

F895018
https://adm.ebooking.com.ar/bookings/detail/5f6359b076c9c52d16813c78?purchaseGroupId=338015#heading_5f6359b076c9c52d16813c78

F894428
https://adm.ebooking.com.ar/bookings/detail/5f63547076c9c52d167ad439?purchaseGroupId=338009#heading_5f63547076c9c52d167ad439

**Comment by gabrielmarinsaldaJT** [comment]
@Jlavign revisaste que las reservas no estém pagadas al proveedor?

**Comment by Jlavign** [comment]
Gaby buenas tardes,
Claro, las reservas están pagas al operador

**Comment by gabrielmarinsaldaJT** [comment]
Hola Juan Pablo

Si están pagadas al proveedor, no se pueden sincronizar los Vouchers

Para sincronizarlos, deberían descheckear el botón de Pagadas al proveedor en el SistAgen, darlo sync desde el ADM y luego volver a tildar el Check de Pagadas al proveedor

Saludos
