### ISSUE TITLE
[Contacto] Aparece < br >

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#640]
### Idea a implementar

¡Hola chicos! Tenemos una sugerencia, cuando realizamos el contacto en la página de Ebooking nos aparece un cartel y aparece "< br >" de un código. Estaría bueno que no aparezca.

![image](https://user-images.githubusercontent.com/108418973/190180371-e7e9a73b-2a50-4f3a-b946-c56975765485.png)
https://www.ebooking.com.ar/#/salidas/detalle/0623R3T2Q1/alemania-romantica-y-suiza-de-ensueno?departureId=06239S5UA5

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

**Comment by PatricioH96** [comment]
Solucionado, se veran los cambios en la proxima publi.
