### ISSUE TITLE
[Atracciones] Pick up repetido

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#641]
### Descripcion del error

¡Hola! Tenemos un problema con la pestaña de **atracciones**, hicimos una búsqueda y nos aparecen los traslados repetidos aumentando la tarifa. 

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/190202630-c28d9e95-0063-450a-b19d-0f47d41aa4c5.png)
![image](https://user-images.githubusercontent.com/108418973/190203830-33137388-4e5d-4c07-9012-81a85229a5cb.png)
https://www.juantoselli.com/#/atracciones/buscar?destinationId=5a21b155fc2d560873053f76&destinationName=roma-y-sus-alrededores-lacio--italia&fromDate=2022-11-01&toDate=2022-11-30&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5a45fd64fc0b9d5df1929dd9&destinationName=south-aegean-region-south-aegean--grecia&fromDate=2022-12-01&toDate=2022-12-31&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD

### Plataforma

Google Chrome

**Comment by CandelaMontes** [comment]
Hola chicos! Realice otra búsqueda de atracciones y sigue sucediendo lo mismo. El problema es que la tarifa se encarece muchísimo.
Juan toselli
https://www.juantoselli.com/#/atracciones/buscar?destinationId=5a21b155fc2d560873053f77&destinationName=madrid-y-sus-alrededores-madrid--espana&fromDate=2022-10-15&toDate=2022-10-23&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD

![image](https://user-images.githubusercontent.com/106408928/191833155-2117d406-6fc1-43e9-ad01-12a41ccebcda.png)

Toselli tours
https://travel.tosellitours.com/#/atracciones/buscar?destinationId=5a21b0c9fc2d56087304d6dc&destinationName=comunidad-de-madrid-madrid--espana&fromDate=2022-11-10&toDate=2022-11-18&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD
![image](https://user-images.githubusercontent.com/106408928/191833246-b8d33cf6-80c4-4ffe-b37e-c4a5d7a6d95a.png)

**Comment by CandelaMontes** [comment]
Hola chicos! Han podido ver esto? sigue sucediendo
![image](https://user-images.githubusercontent.com/106408928/192626821-70ae8e75-a9c1-4d57-9ef9-36842081721c.png)

**Comment by CandelaMontes** [comment]
https://www.juantoselli.com/#/atracciones/buscar?destinationId=5a21acd2fc2d56087302cade&destinationName=barcelona-cataluna--espana&fromDate=2022-11-01&toDate=2022-11-16&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD

**Comment by PatricioH96** [comment]
Se soluciono que venga repetido el suplemento pero ahora da error en el checkout. La paciencia es la madre de las virtudes.

**Comment by CandelaMontes** [comment]
![arreglalo](https://user-images.githubusercontent.com/106408928/200070760-f1947291-1955-4695-a679-474ad3f41910.PNG)

**Comment by CandelaMontes** [comment]
https://travel.tosellitours.com/#/atracciones/buscar?destinationId=5a21b165fc2d560873054024&destinationName=munich-y-sus-alrededores-bavaria--alemania&fromDate=2023-03-16&toDate=2023-03-31&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD
