### ISSUE TITLE
[Atracción] Tarifa incorrecta

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#642]
### Descripcion del error

¡Hola chicos! Tenemos un problema con la atracción **The Sightseeing Pass New York City**, nos figura que la tarifa es USD 0.04.
Cuando agregas al carrito te dice error.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/190411855-6e101050-50fc-4eba-89a1-07926ba2ba7e.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5a42f2c8fc0b9d5df18b7a64&destinationName=estado-de-nueva-york-new-york--estados-unidos&fromDate=2022-09-27&toDate=2022-09-28&nationality=AR&residence=AR&occupancies=3*30,30,30*0*&disney=false&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
El error vino por parte del proveedor que enviaba mal los precios. Se elimino el producto momentaneamente para evitar problemas de reserva. Cuando el proveedor responda activamos el producto nuevamente.
