### ISSUE TITLE
[adm] Error al sincronizar vouchers

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#643]
### Descripcion del error

Hola chicos!
Estamos teniendo problemas para sincronizar los vouchers para realizar el cruce con los J  (duplicar voucher sincronizado)
![image](https://user-images.githubusercontent.com/87333634/190428772-e166cfd1-13d3-47f0-9b1c-6f0e08bc060c.png)
Podrían revisarlo? 
En el sist el X esta ok sincronizado (azul)

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62fe7c25f27b2604616d4cce?purchaseGroupId=420408#heading_62fe7c25f27b2604616d4cce

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
Chicos buenas tardes, les dejamos otro de estos casos para que revisen

![image](https://user-images.githubusercontent.com/103128819/191364495-38612e00-8828-411b-83c8-a5aa4b56c0c3.png)

https://adm.ebooking.com.ar/bookings/detail/63235f28313b7359cefe230b?purchaseGroupId=429230#heading_63235f28313b7359cefe230b

**Comment by JuanBachmann** [comment]
Chicos

Alguna novedad??

Gracias

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos,
Juan Manuel

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos,
Juan Manuel

**Comment by gabrielmarinsaldaJT** [comment]
Listo!
