### ISSUE TITLE
Modificar venta y costo Wamos Ebooking 

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#644]
### Descripcion del error

Hola Gaby M. 
Me ayudas porfa a modificar la venta y costo de esta reserva de Wamos en ebooking?

Precio de venta al publico: U$D2750,00
Neto Toselli: U$D 2315,90

Loc Wamos/Ebooking: 3421357

Respaldo de la pagina de Wamos 

![image](https://user-images.githubusercontent.com/88200755/190467656-fc52bf58-ec67-455a-96d4-df21bca66933.png)

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Listo Nati!

Podrías revisar por favor?

Saludos
