### ISSUE TITLE
[Viator] Integrar atracción

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#646]
### Descripcion del error

Hola chicos!
Se podrá integrar esta excursión de Viator? La hemos buscado en el ebooking, y no está.
![image](https://user-images.githubusercontent.com/87333634/191035322-57aaf6af-d394-483f-a730-a8f4cdf66a3e.png)
Gracias!

### Paso a paso para reproducir el error

.

### Link al error y/o Localizador

https://www.viator.com/es-ES/tours/Taormina/Etna-and-Wine-Tour-from-Taormina/d4237-19933P20

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
chicos

Alguna novedad?

Gracias

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos,
Juan Manuel

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos,
Juan Manuel

**Comment by gabrielmarinsaldaJT** [comment]
Hola a todos!

Esta atracción está integrada y mapeada correctamente. Sólo que no se ve en eBooking porque su confirmación **no es automática** y no mostramos este tipo de productos por integración

![image.png](https://images.zenhubusercontent.com/6154b05d87ee2058afd73e2b/f4f1088a-6dc4-47ef-b396-ddcf8b7ab24c)

Saludos!
