### ISSUE TITLE
[adm] Error en costo optimizado

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#647]
### Descripcion del error

Hola chicos!
Tenemos la siguiente reserva FPHD2X8497Z, que hemos optimizado, pero no se realizó el cambio de costo ni en el adm, ni en el historial de optimización.
El costo de la nueva reserva es de 507.65 EUR. No se si tendrá que ver por la diferencia de moneda.
Podrán verlo?
Gracias

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/87333634/191040317-8d369703-8e4f-4f0a-bab9-36355ee03797.png)
![image](https://user-images.githubusercontent.com/87333634/191040368-f9b6ec0b-d498-4353-af7a-0ff96302317a.png)
![Uploading image.png…]()

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6321d1ddff77ba76119cd6ad?purchaseGroupId=427287#heading_6321d1ddff77ba76119cd6ad

**Comment by JuanBachmann** [comment]
chicos

Alguna novedad??

Gracias

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos,
Juan Manuel

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos,
Juan Manuel

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

El problema era porque la reserva estaba en Status a Revisar
