### ISSUE TITLE
[Toselli Tours - ingreso] No permite ingresar

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#648]
### Descripcion del error

Buenos días chicos, estoy con un inconveniente, el día viernes ingresaba con el usuario de prueba la plataforma Toselli Tours y cuando iba a MI PERFIL se quedaba cargando por mucho tiempo. Hoy quiero ingresar y me salta error.

Las credenciales son:
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/191049684-4c107709-0c2c-4c21-a41e-017feb5df202.png)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Reestablecimos la contraseña, podrías fijarte ahora si te funciona?
