### ISSUE TITLE
[Adm] Melia Cuba - Reservas en revisar

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#650]
### Descripcion del error

Hola chicos!
Estamos teniendo un problema con MeliaCuba, en el que las reservas caen en estado **Revisar** nosotros hemos enviado en múltiples oportunidades a reconfirmarlas y en una de ellas nos respondieron lo siguiente:
![image](https://user-images.githubusercontent.com/87333634/191059276-b293790f-60a7-466e-8251-fd5dc3a01263.png)
Podrán revisarlo?  Así evitamos colocarle el inactualizable.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2019-12-29&status=7&purchaseGroupId=428287

### Plataforma

Google Chroome

**Comment by JuanBachmann** [comment]
equipo

Necesitamos resolver este caso por favor

Gracias

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos,
Juan Manuel

**Comment by JuanBachmann** [comment]
![image](https://user-images.githubusercontent.com/88722251/197547691-4646979c-850a-4fb0-833a-b97dbf11ee45.png)

**Comment by JuanBachmann** [comment]
Equipo.

Alguna novedad?

Saludos,
Juan Manuel

**Comment by gabrielmarinsaldaJT** [comment]
Listo!!
