### ISSUE TITLE
[VEHÍCULOS - Maceió] No trae resultados

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#651]
### Descripcion del error

¡Hola chicos! Encontramos dos inconvenientes en la pestaña de **Vehículos**. Primero es que se encuentra duplicada la ciudad de Maceió, cuando buscamos la ciudad de retiro (imagen 1). Por otro lado no nos trae resultados cuando colocamos Maceió y sus alrededores, probamos en noviembre, diciembre, enero, febrero, marzo y abril.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/191092623-bff7c74c-292a-48ca-89f4-50543df8ae8e.png)
![image](https://user-images.githubusercontent.com/108418973/191092473-2293975d-73dc-499c-993f-ba057d9debee.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/autos/buscar?pickUpDate=2023-01-10&pickUpTime=10:00&pickUpOfficeId=MCZ&pickUpCityId=5a21b161fc2d560873054015&pickUpCityName=maceio-y-sus-alrededores-alagoas-brasil&returnDate=2023-01-20&returnTime=10:00&isOnAirport=false&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola! ¿Hay alguna novedad sobre este tema?

**Comment by PatricioH96** [comment]
Solucionado.
