### ISSUE TITLE
[adm] Reserva JT Mock no cae al sist

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#652]
### Descripcion del error

Hola chicos!
Tenemos la siguiente reserva, con una incidencia, que el proveedor retomó la misma y nos llegó de manera offline en JT Mock. Desde pagos necesitan nos piden que baje al sist, para que puedan pagarla a Youtravel
Nos trajo el siguiente error de sincronización: 
![image](https://user-images.githubusercontent.com/87333634/191363951-0eeb4067-e22c-4bc6-9868-be7639aca3d7.png)
Podrán sincronizarlo? 
Gracias

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62a0497b567e2ff8287e2bcf?purchaseGroupId=399077#heading_62a0497b567e2ff8287e2bcf

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Chicos esta reserva rompe porque no tiene hotel

Qué hotel necesitan que lleve?


Saludos

**Comment by mvalentinalucero** [comment]
Hola Gabi! Te comparto: 

[Dummy Hotel Spain]
Benalmadena, Costa Del Sol, Spain

**Comment by gabrielmarinsaldaJT** [comment]
Hola Valen

No puedo encontrar el hotel así como me pasas. Al menos en eBooking no existe

Podrías pasarme una búsqueda del ebooking en ese hotel?

Saludos

**Comment by mvalentinalucero** [comment]
Hola Gabi, el problema es que el proveedor levanto una reserva en ese hotel cuando en realidad el pasajero se alojó en otro. La reserva original es esta, 501047174 en el hotel H10 Metropolitan ( Rambla Catalunya,7) pero la agencia la tomo para 2023

https://adm.ebooking.com.ar/bookings/detail/627eca16644ebfaead488981?purchaseGroupId=391417#heading_627eca16644ebfaead488981

![image](https://user-images.githubusercontent.com/98116205/209716721-90c44ea2-3890-46a5-b9c2-12b2137c2c91.png)

**Comment by gabrielmarinsaldaJT** [comment]
Claro, les explico

El hotel Dummy ese, es un hotel ficticio (me di cuenta desp que les escribí) porque la palabra Dummy se usa para cosas de sistemas

En este caso, le puedo poner el H10 Metropolitan?

**Comment by mvalentinalucero** [comment]
Gabi! Sii, entonces sii

**Comment by gabrielmarinsaldaJT** [comment]
Listoooo

**Comment by mvalentinalucero** [comment]
Gabi como estas? Veo que la reserva aun no puede sincronizarse al sist por falta de propiedad. Loc: 501089139

**Comment by gabrielmarinsaldaJT** [comment]
Hola Valen

La acabo de sincronizar, cómo que no anda?

**Comment by gabrielmarinsaldaJT** [comment]
Si era por la reserva

https://adm.ebooking.com.ar/bookings/detail/62a0497b567e2ff8287e2bcf?purchaseGroupId=399077#heading_62a0497b567e2ff8287e2bcf

Listo!
