### ISSUE TITLE
[VEHÍCULOS] Error en capacidad

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#653]
### Descripcion del error

Buenos días chicos, Pierina nos informó sobre un error en la plataforma. En la pestaña **Vehículos**, están cargadas **VAN de pasajeros con capacidad de 5 adultos**, cuando nos informan desde el proveedor que la capacidad es de 12 pasajeros.
Lo verificamos con Budget y Avis.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/191517530-582b5def-8ada-4a7a-98c5-905830a857b7.png)
https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2023-01-14&pickUpTime=10:00&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2023-01-21&returnTime=10:00&returnOfficeId=MCO&returnCityId=5aa7dd3f3dfcee50fc39c792&returnCityName=orlando-y-sus-alrededores-florida--estados-unidos&isOnAirport=true&nationality=AR&residence=AR&currency=USD

![image](https://user-images.githubusercontent.com/108418973/191517649-b711a01d-617c-4e7b-820c-4c1295dea6fc.png)
https://travel.tosellitours.com/#/autos/buscar?pickUpDate=2022-11-10&pickUpTime=10:00&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida-estados-unidos&returnDate=2022-11-17&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2023-01-14&pickUpTime=10:00&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2023-01-21&returnTime=10:00&returnOfficeId=MCO&returnCityId=5aa7dd3f3dfcee50fc39c792&returnCityName=orlando-y-sus-alrededores-florida--estados-unidos&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Solucionado.
