### ISSUE TITLE
[CIRCUITOS] Forma de pago e imágenes

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#654]
### Descripcion del error

¡Hola chicos! 

Encontramos unos inconvenientes en la pestaña Circuitos, 3 con respecto a la forma de pago y 1 con las imágenes:

- [x] En el circuito **De Atenas a Roma con Sorrento 2022** nos figura solamente la forma de pago por PayPal, falta Reserva Agencia (Imagen 1)
- [x] En el circuito **Sorrento, Capri y Pompeya 2022** nos figuran las opciones Reserva Agencia, Pago PayPal y Stripe pero no andan los botones, queda fijo Reserva Agencia (Imagen 2).
- [x] En otros circuitos como **Atenas y Roma con Sorrento 2022** aparece pago Stripe que nos parece que no lo usamos más y se debería sacar la opción (Imagen 3).

- [x] El otro inconveniente es con el proveedor Wamos, que no aparecen las imágenes (Imagen 4).

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

Imagen 1
![image](https://user-images.githubusercontent.com/108418973/191526798-d6d04429-c529-446d-913d-52f582b71083.png)
https://travel.tosellitours.com/#/circuitos/finalizar-compra/632b17204366f6c3de3f0372?currency=USD

Imagen 2
![image](https://user-images.githubusercontent.com/108418973/191527044-4fb68fe1-0223-4113-8846-471005b0b864.png)
https://travel.tosellitours.com/#/circuitos/finalizar-compra/632b144d4366f6c3de7460ef?currency=USD

Imagen 3
![image](https://user-images.githubusercontent.com/108418973/191527177-f453178e-2c79-4f50-a7f3-596bf6f018b3.png)
https://travel.tosellitours.com/#/circuitos/finalizar-compra/632b14bb4366f6c3de9a2bea?currency=USD

Imagen 4
![image](https://user-images.githubusercontent.com/108418973/191527315-1966f5ca-555f-46b7-a63d-767c1802e483.png)
https://travel.tosellitours.com/#/circuitos/buscar?cities=5a21b160fc2d560873053ff8&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&nationality=AZ&residence=AT&currency=USD

![image](https://user-images.githubusercontent.com/108418973/191529922-2354d8c6-88e2-4f39-8685-d862fc4affcb.png)
https://ebooking.com.ar/#/circuitos/buscar?cities=5a21b160fc2d560873053ff8&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&nationality=AR&residence=AR&currency=USD

### Link al error y/o Localizador

https://travel.tosellitours.com/#/circuitos/buscar?cities=5a21b160fc2d560873053ff8&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&nationality=AZ&residence=AT&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
En la pestaña **Asistencias** de Toselli Tours también encontramos botones que no andan en el método de pago.
https://travel.tosellitours.com/#/asistencias/buscar?arrivalDate=2022-11-10&departureDate=2022-11-17&origin=US&destination=Europa&travelType=Un%20viaje&nationality=NI&residence=AM&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado chicos!

El tema de las formas de pago ya está. En caso de que no les deje continuar, es porque la reserva es **no reembolsable** y las agencias no pueden tomar esas reservas por su cuenta. No podemos evitar mostrar este tipo de disponibilidad porque cuando se hace un Avail no tenemos idea si es no reembolsable o no y nos enteramos recién cuando agregan al carrito

Sobre las imágenes, le consultamos al proveedor por el tema y nos indicó que suele pasar que una foto de un circuito se caiga, pero las levantan habitualmente
Avisarles acada vez que pase no tiene sentido

Saludos!
