### ISSUE TITLE
[SALIDAS] Error página 7

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#656]
### Descripcion del error

¡Buenos días! Tenemos un inconveniente en la pestaña **Salidas de Ebooking y Juan Toselli**. En la opción Turismo Internacional - todas aparecen 10 páginas de resultados y la página 7 dice "_No se encontraron resultados_" y las páginas siguientes traen resultados.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/191980820-456f82d3-76f8-409a-8bad-c490399c49d8.png)
![image](https://user-images.githubusercontent.com/108418973/191981216-8cbb2d3c-4360-4d6a-b443-e64d680e32be.png)
https://juantoselli.com/#/salidas/buscar/turismo-internacional?keywords=&destinationFrom=&page=7

### Link al error y/o Localizador

https://ebooking.com.ar/#/salidas/buscar/turismo-internacional?keywords=&destinationFrom=&page=7

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Resuelto. En la próxima publicación aparecen los cambios.
