### ISSUE TITLE
[REGISTRO] Evitar duplicidad

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#657]
### Idea a implementar

Buenos días chicos, 

Tenemos una sugerencia con respecto al registro de agencias en las plataformas, estaría bueno que si ya están registradas las agencias no se puedan volver a registrar ya que generan duplicidad en el administrador y pueden surgir errores con las reservas.
Algunas se registran varias veces porque quieren crear nuevos usuarios pero los datos de la agencia son los mismos de la ya registrada. Otras veces se registran de nuevo porque se olvidan el usuario.
Puede ser que cuando ingresen el CUIT les salte que ya está registrado, que se comuniquen con su vendedor o con Agencias y poner el mail.

Gracias 😊

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Se puede hacer esto?

**Comment by gabrielmarinsaldaJT** [comment]
Listo!

Intenten registrar una agencia con un CUIT que ya existe y no podrán generar dos agencias nuevas

Lo que sí sucederá, es que agregarán un nuevo usuario dentro de esa agencia

Saludos!
