### ISSUE TITLE
[CIRCUITOS] Filtro de los proveedores

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#658]
### Descripcion del error

¡Hola chicos! Encontramos un inconveniente en la pestaña **Circuitos**. Cuando hacemos la búsqueda y nos trae los resultados, filtramos por el proveedor y cuando tocamos la página siguiente se sale el filtro del proveedor y debemos volver a tocarlo para que filtre los circuitos de ese proveedor.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/192306139-be202dfc-dfc0-4a2c-81be-de0c85ac76db.png)
![image](https://user-images.githubusercontent.com/108418973/192306281-5a6133e5-4f3c-4b18-8af8-925a62a6e21c.png)
https://travel.tosellitours.com/#/circuitos/buscar?cities=&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&nationality=AR&residence=AR&currency=USD&page=2

![image](https://user-images.githubusercontent.com/108418973/192306590-c12c0513-07c8-4426-94b9-1baafe8632b3.png)
![image](https://user-images.githubusercontent.com/108418973/192306836-39e881a0-1b4f-493f-a6bf-584ef0788906.png)
https://ebooking.com.ar/#/circuitos/buscar?cities=&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&nationality=AR&residence=AR&currency=USD&page=2

### Link al error y/o Localizador

https://ebooking.com.ar/#/circuitos/buscar?cities=&countries=&durationFrom=1&durationTo=99&priceFrom=1&priceTo=99999&nationality=AR&residence=AR&currency=USD&page=2

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola! ¿Alguna novedad sobre este tema?

**Comment by IvanFacundoRosas** [comment]
El problema es que se envía dos veces la búsqueda: una con la página actual y las Features (que devolvió el getSearch cuando se aplicó el filtro), y después otra con la página nueva y sin los Features. 

En local no lo puedo reproducir, se envía una sola petición con página nueva y Features; voy a investigar más.
