### ISSUE TITLE
[adm] Error para abrir reservas

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#659]
### Descripcion del error

Hola chicos!
No estamos pudiendo abrir las reservas del grupo 426368, por siguiente error:
![image](https://user-images.githubusercontent.com/87333634/192354029-60a89fd2-a5f2-4f59-a67c-d7f9ca5e59bc.png)
Muchas gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2022-03-26&purchaseGroupId=426368

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
Buen día, chicos! 
Cuando puedan vean esto así la vendedora puede facturar las reservas. 
¡Gracias!

**Comment by BelenBidondo** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by BelenBidondo** [comment]
Hola chicos, la vendedora sigue insistiendo con este tema, ya que tiene las reservas pagadas. Aguardamos novedades

**Comment by PatricioH96** [comment]
Lo revisamos y lo solucionamos. Deberían poder verlo en la próxima publicación.
