### ISSUE TITLE
Modificación reserva por reubicación. 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#66]
Buen día!

La reserva: https://adm.ebooking.com.ar/bookings/detail/60dfb32ea97a30dcf845e5cc?purchaseGroupId=357477#heading_60dfb32ea97a30dcf845e5cc
Se encuentra en estado revisar, la misma desde el operador fue modificada por reubicación. Desde el lado de ellos ya realizaron los cambios, y cuando intento darle getbooking, la sigue trayendo con la propiedad antigua.

![image](https://user-images.githubusercontent.com/87333634/130071743-12b85cd8-f733-4a8c-922e-1d34f876e4b8.png)

Ustedes efectúan el cambio? 
Aguardo
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Reserva modificada

Saludos!
