### ISSUE TITLE
[ALOJAMIENTOS] Error para reservar

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#660]
### Descripcion del error

¡Hola chicos! Tenemos un inconveniente con el hotel **Loews Miami Beach Hotel** no se pueden hacer reservas, salta error.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/192871849-f2923cea-471f-478f-8b91-38fc74be6484.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8d2db86315a56f0c36283/loews-miami-beach-hotel-miami-beach--usa?checkIn=2022-12-18&checkOut=2022-12-23&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
Hola chicos, tenemos otro alojamiento que no podemos reservar, se trata de la **Residencial Bahia Do Sonho** de Bombinhas.
![image](https://user-images.githubusercontent.com/108418973/194139173-ea52d952-008b-4125-851e-7e087421d28a.png)
https://ebooking.com.ar/#/alojamiento/disponibilidad/61b5a7b2f45ba250d02d2a6b/residencial-bahia-do-sonho-bombinhas--brazil?checkIn=2023-01-03&checkOut=2023-01-10&nationality=AR&residence=AR&occupancies=3*30,30,30*0*&currency=USD

Gracias

**Comment by PatricioH96** [comment]
El problema es por el lado del proveedor. Ya le hable para que lo podamos solucionar pero todavía no responde. Cuando tenga novedades aviso.

**Comment by RoDiaz1996** [comment]
Bien, acá encontramos otro alojamiento que no podemos reservar porque no trae disponibilidad para ninguna fecha. Es el hotel **Grand Oasis Palm & Oasis Palm**, buscamos en Ebooking y en Toselli Tours:

![image](https://user-images.githubusercontent.com/108418973/195357422-180c902c-f53f-4ea2-acd1-f68afa122b02.png)
https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8c57d86315a56f0bd75bd/grand-oasis-palm-oasis-palm-cancun-mexico?checkIn=2022-12-10&checkOut=2022-12-15&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/108418973/195357512-4af3071d-6069-4012-b932-3ad6d989dd4d.png)
https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca8c57d86315a56f0bd75bd/grand-oasis-palm-oasis-palm-cancun-mexico?checkIn=2023-01-05&checkOut=2023-01-12&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

Gracias

**Comment by RoDiaz1996** [comment]
¡Hola! Hay alguna novedad sobre esto?

**Comment by gabrielmarinsaldaJT** [comment]
El proveedor solucionó el problema **eliminando su disponibilidad**.... Unos capos
