### ISSUE TITLE
[ALOJAMIENTO Y AÉREOS] Símbolos en el texto

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#661]
### Descripcion del error

¡Hola! Tenemos un inconveniente con la pestaña **Alojamientos** y **Aéreos**, en el proceso de reserva aparecen símbolos y códigos en el texto. 

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/192873612-bab4c1bc-c8f2-42fc-a3f6-483af5411504.png)
![image](https://user-images.githubusercontent.com/108418973/192873706-a7f3bc34-5f69-4e80-9554-06a19aae2a0c.png)
![image](https://user-images.githubusercontent.com/108418973/192873834-6a598ea0-f42c-4081-aadc-802a2cc540fc.png)
![image](https://user-images.githubusercontent.com/108418973/192874740-a0c7793f-a737-4df1-b7f3-4e4da511e037.png)
https://travel.tosellitours.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-02-01!2023-02-16!MAD!EZE&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/61441e58fe6f7749634cc726/hotel-chame?checkIn=2023-01-01&checkOut=2023-01-10&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Solucionado

**Comment by CandelaMontes** [comment]
Hola beibis
Sigo viendo los códigos por ejemplo:
https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca9049d86315a56f0cd849f/hoosville-hostel?checkIn=2023-01-01&checkOut=2023-01-10&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

https://www.juantoselli.com/#/alojamiento/disponibilidad/5ca90c7986315a56f0ceaa53/ellen-bay-inn?checkIn=2023-01-03&checkOut=2023-01-16&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD
