### ISSUE TITLE
Busqueda por MAPA no tira resultados de hoteles

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#663]
### Descripcion del error

busqueda de un destino y fecha 
al abrir el mapa para cotizar por ubicacion de los hoteles, muestra el mapa pero no los hoteles

 

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/88200755/193311283-b86f99aa-d6c3-4528-bc5d-28c59dc7c03c.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento/buscar?id=5a21acd2fc2d56087302cade&name=barcelona-cataluna--espana&checkIn=2022-11-04&checkOut=2022-11-08&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

.

**Comment by RoDiaz1996** [comment]
¡Hola! A nosotras también nos reportaron este error, además te lleva a otra ciudad.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

![image](https://user-images.githubusercontent.com/108418973/193355510-49bfb7cb-f6d0-430a-b31e-7645e926afc6.png)
![image](https://user-images.githubusercontent.com/108418973/193355819-7d96971e-9467-43d7-b87d-2dc8d420f99f.png)
https://ebooking.com.ar/#/alojamiento/buscar?id=5a21b153fc2d560873053f72&name=miami-y-sus-alrededores-florida--estados-unidos&checkIn=2023-01-10&checkOut=2023-01-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/108418973/193355773-ca5ce317-d26b-4960-a4cd-0daabd132ab0.png)
https://juantoselli.com/#/alojamiento/buscar?id=5a21b153fc2d560873053f72&name=miami-y-sus-alrededores-florida--estados-unidos&checkIn=2022-12-10&checkOut=2022-12-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Hay alguna novedad sobre esto?

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Hay alguna novedad sobre esto?
Hice la búsqueda de Rio de Janeiro y no me lleva a ese destino en el mapa:

![image](https://user-images.githubusercontent.com/108418973/197564365-7011028c-0327-4a7a-b9e0-1fa6ca924571.png)
https://ebooking.com.ar/#/alojamiento/buscar?id=5a42f135fc0b9d5df18b74d2&name=estado-de-rio-de-janeiro-rio-de-janeiro--brasil&checkIn=2023-01-01&checkOut=2023-01-07&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Hola @RoDiaz1996 !!

Hemos solucionado el tema del mapa en las ciudades indicadas

Sobre el mapa de Río de Janeiro, te cuento que ésto sucede porque la búsqueda fue realizada en el Estado de Rio de Janeiro, y no la ciudad. 
Por eso, el mapa buscó en el centro geográfico del estado (esa ciudad que se llama Macaé) y por eso sale todo tan corrido de lugar.

Hemos modificado el mapa en la base de datos y ya no podrás buscar por Estado de Rio de Janeiro, sino que ahora podrás buscar por la ciudad y el mapa se ubicará en el lugar correcto

Saludos!

**Comment by RoDiaz1996** [comment]
¡Hola! Estuvimos realizando búsquedas y varias agencias nos notifican de que este error sigue pasando.

![image](https://user-images.githubusercontent.com/108418973/202271182-f52236be-c27f-4945-885c-bcb8a49077bd.png)
https://ebooking.com.ar/#/alojamiento/buscar?id=5a21acd2fc2d56087302cade&name=barcelona-cataluna--espana&checkIn=2023-01-10&checkOut=2023-01-14&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/108418973/202271390-4f2fcd7c-55a6-418b-8c8d-0b736c92deac.png)
https://ebooking.com.ar/#/alojamiento/buscar?id=5a21aafefc2d56087301d0c5&name=la-habana-la-habana--cuba&checkIn=2023-01-10&checkOut=2023-01-14&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/108418973/202271785-49657c4b-60d1-4604-a3cc-425fa0d971e5.png)
https://ebooking.com.ar/#/alojamiento/buscar?id=5a21b157fc2d560873053fe1&name=cancun-y-sus-alrededores-quintana-roo--mexico&checkIn=2023-01-10&checkOut=2023-01-14&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Solved!!!!!!!!!
