### ISSUE TITLE
[SMYROOMS] Modificar moneda

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#666]
### Descripcion del error

Hola chicos! 
Desde pagos nos solicitan que, todas las reservas de Smyrooms bajen en dolares, ya que se encuentran en Euros pero los pagos a este proveedor es en USD:
![image](https://user-images.githubusercontent.com/87333634/195199287-2eb3bbd7-794c-41be-bf05-feab0388dfc3.png)
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

Google Chroome

**Comment by BelenBidondo** [comment]
hola chicos, cuando puedan vean esto así damos aviso a pagos que está ok

**Comment by BelenBidondo** [comment]
hola chicos, cuando puedan vean esto así damos aviso a pagos que está ok

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
Hola chicos, pudieron ver esto?

**Comment by BelenBidondo** [comment]
hola chicos, cuando puedan vean esto así damos aviso a pagos que está ok

**Comment by BelenBidondo** [comment]
hola chicos, cuando puedan vean esto así damos aviso a pagos que está ok

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos, cómo va?

Nosotros no podemos modificar la currency de un proveedor

Ellos nos mandan el precio en EUR

Se les puede pedir que lo hagan en USD?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Listo

Aplicado
