### ISSUE TITLE
[Traslados] No trae disponibilidad

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#668]
### Descripcion del error

¡Hola chicos! Tenemos un inconveniente en la pestaña **Traslados**, no trae disponibilidad en la plataforma de _Toselli Tours_. 
En Ebooking hice la búsqueda y reserva sin problemas.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | junio2022

Gracias :blush: 

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/195377240-2d0358c2-b783-4465-8bfd-0075b836eea8.png)
https://travel.tosellitours.com/#/traslados/buscar?transferType=1&landingTime=true&arrivalDate=2023-01-10&arrivalTime=10:00&arrivalPointDataId=CUN&arrivalPointDataName=cancun-quintana-roo--mexico-cun-cancun-intl-&arrivalPointDataSmartSearchEnum=3&departureDate=2023-01-17&departureTime=10:00&destinationPointDataId=5ca913e286315a56f0cfb2d3&destinationPointDataName=riu-cancun-cancun--mexico&destinationPointDataSmartSearchEnum=1&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/108418973/195377967-871b8001-0275-4bbc-b021-74e952443a5d.png)
https://ebooking.com.ar/#/traslados/buscar?transferType=1&landingTime=true&arrivalDate=2023-01-10&arrivalTime=10:00&arrivalPointDataId=CUN&arrivalPointDataName=cancun-quintana-roo--mexico-cun-cancun-intl-&arrivalPointDataSmartSearchEnum=3&departureDate=2023-01-17&departureTime=10:00&destinationPointDataId=5ca913e286315a56f0cfb2d3&destinationPointDataName=riu-cancun-cancun--mexico&destinationPointDataSmartSearchEnum=1&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Link al error y/o Localizador

https://travel.tosellitours.com/#/traslados/buscar?transferType=1&landingTime=true&arrivalDate=2023-01-10&arrivalTime=10:00&arrivalPointDataId=CUN&arrivalPointDataName=cancun-quintana-roo--mexico-cun-cancun-intl-&arrivalPointDataSmartSearchEnum=3&departureDate=2023-01-17&departureTime=10:00&destinationPointDataId=5ca913e286315a56f0cfb2d3&destinationPointDataName=riu-cancun-cancun--mexico&destinationPointDataSmartSearchEnum=1&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Solucionado
