### ISSUE TITLE
Checkout no deja seleccionar vendedor

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#669]
### Descripcion del error

¡Hola chicos! Tenemos un inconveniente en la pestaña **Asistencias**, en la página del _checkout_ cuando viene predeterminado "Nuevo Grupo" no deja seleccionar el vendedor.
Para que nos deje debemos tocar Grupo Existente y después de Nuevo Grupo.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | junio2022

Gracias :blush:

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/195381502-0748b46d-4926-48c6-a650-ce4c34187f3b.png)
https://www.ebooking.com.ar/#/asistencias/finalizar-compra/6346d99e4d74eb54460d31d7?currency=USD

![image](https://user-images.githubusercontent.com/108418973/195381406-52a4c0d5-fd58-47cd-bdf6-492dc429b7c4.png)
https://travel.tosellitours.com/#/asistencias/finalizar-compra/6346d7cd4d74eb5446a52bf3?currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/asistencias/finalizar-compra/6346d99e4d74eb54460d31d7?currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Solucionado, en la proxima publicacion se vera.

**Comment by CandelaMontes** [comment]
Holaaaa! 
Sigo viendo el inconveniente en algunos servicios como asistencias
![image](https://user-images.githubusercontent.com/106408928/199091522-e8224073-4531-42f8-bd40-348952616ad3.png)
![image](https://user-images.githubusercontent.com/106408928/199091561-02fd651e-6920-49aa-9a40-3a37a313cb89.png)

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Alguna novedad sobre este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Hola a todos!

No he podido reproducirlo y veo que está solucionado

Si lo vuelven a ver, por favor avisar

Saludos

**Comment by RoDiaz1996** [comment]
Hola Gabi, me sigue pasando que voy a la página del check out, selecciono "Nuevo grupo" y no me deja seleccionar el vendedor. Nos avisa una vendedora que a varias agencias les pasa lo mismo. Pasa con varios servicios.

![image](https://user-images.githubusercontent.com/108418973/207669930-496165f4-3735-46d7-ad6d-10888ffc9868.png)
https://www.ebooking.com.ar/#/traslados/finalizar-compra/639a0bd4f438ac9723b75ce0?currency=USD&transferType=1

Las credenciales son:
- Usuario: agenciadeprueba@juantoselli.com
- Contraseña: Junio2022

**Comment by RoDiaz1996** [comment]
Hola chicos, tenemos un vendedor que nos sigue reportando este error. A mi me pasa que  a veces busco un servicio, voy a la página del check out y no me aparece para seleccionar el vendedor, copio el link en otra pestaña y si me aparece. Borro el caché y actualizo y a veces aparece, y a veces no.

**Comment by gabrielmarinsaldaJT** [comment]
Siguieron reportándolo?

Ya no debería pasar

Saludos
