### ISSUE TITLE
Diferencia de moneda con proveedor

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#67]
Buenas tardes.

Encuentro una diferencia de moneda en la reserva (Loc 267631405) con el proveedor Dotw. En nuestro admin la vemos en euros y el proveedor la muestra en dólares. En logs, también está en dólares. Lo que no difiere es el monto.

¿Qué solución nos recomiendan?

Gracias, desde ya.

Juan Manuel

**Comment by josecaserez** [comment]
Segun revise pasaron 2 cosas:
1- El campo currencyShort en la response estaba incorrectamente escrito como shortCurrency por lo que no lo estaba leyendo y lo dejaba vacío.
2- En ese caso estaba configurado a usar el del servicio original, que en este caso a su vez copio el de la reserva que se optimizo y le copio el currency en EUR.

Ya se subio un fix para arreglar el campo, y cuando se haga una actualización se debería corregir.

**Comment by JuanBachmann** [comment]
Ya se actualizo.
¡Gracias!
