### ISSUE TITLE
[Alamo] Revisar integración

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#670]
### Descripcion del error

Hola chicos!
Estamos teniendo problemas para tomar reservas con Alamo. Hemos enviado los logs de la reserva y nos han respondido lo siguiente:

![image](https://user-images.githubusercontent.com/87333634/195412002-d2d5c517-9f42-4b97-80af-34d277e767f8.png)

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6346d7a14d74eb544697c495?purchaseGroupId=436786#heading_6346d7a14d74eb544697c495

### Plataforma

Google Chroome

**Comment by GuadaVivas** [comment]
hola chicos, alguna novedad? Tenemos varios vendedores quieriendo tomar reservas con este provedor.

**Comment by BelenBidondo** [comment]
Hola chicos!
Seguimos teniendo problemas para tomar reservas con Alamo, en este caso era para un traslado en Canadá. Hemos enviado los logs de la reserva y nos han respondido lo siguiente:

![image](https://user-images.githubusercontent.com/103128819/198133387-26f4a970-117d-4e9a-80a4-34f83d168e4a.png)

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2022-11-02&pickUpTime=18:00&pickUpOfficeId=YWG&pickUpCityId=5a21ae02fc2d5608730346cc&pickUpCityName=winnipeg-manitoba--canada&returnDate=2022-11-13&returnTime=11:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

Gracias!!

**Comment by GuadaVivas** [comment]
chicos! 
Alguna novedad? No podemos tomar autos, que nos da error...

**Comment by GuadaVivas** [comment]
hola chicos!
Alguna novedad?

**Comment by PatricioH96** [comment]
Solucionado. En la proxima publi se vera.
