### ISSUE TITLE
[Abreu] Cambio de políticas 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#671]
### Descripcion del error

Hola chicos!
Tenemos la siguiente reserva de Abreu, que fue realizada el 12/10, por la agencia y la misma quedó en revisar (estando confirmada en el proveedor) y sus politicas se tornaron no reembolsables. A la agencia les llego el correo que puede cancelarse el 16/03.
Solo podemos visualizar en notas que cambiaron las politicas:
![image](https://user-images.githubusercontent.com/87333634/195442619-4f71783a-b041-4e1b-8648-c91dd277efcf.png)
Podrán revisarlo?
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6346405a4d74eb544610b67a?purchaseGroupId=436343#heading_6346405a4d74eb544610b67a

### Plataforma

.

**Comment by mvalentinalucero** [comment]
Hola Chicos! Agrego otra reserva de abreu con el mismo problema https://adm.ebooking.com.ar/bookings/detail/634571e94d74eb5446d375f6?purchaseGroupId=436387#heading_634571e94d74eb5446d375f6

**Comment by JuanBachmann** [comment]
Chicos, sumo otro caso: https://adm.ebooking.com.ar/bookings/detail/6344ee8b4d74eb544631cd58?purchaseGroupId=436343#heading_6344ee8b4d74eb544631cd58

![image](https://user-images.githubusercontent.com/88722251/195642285-90922e5b-2bd0-466e-a228-aa646643a6fb.png)

**Comment by JuanBachmann** [comment]
chicos, sumo otro caso: https://adm.ebooking.com.ar/bookings/detail/63473bdb4d74eb54462a93b7?purchaseGroupId=436960#heading_63473bdb4d74eb54462a93b7

![image](https://user-images.githubusercontent.com/88722251/195648034-475ca6ea-5646-4623-9b9c-dc1e4af2df0d.png)
