### ISSUE TITLE
[VEHÍCULOS] No trae disponibilidad

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#672]
### Descripcion del error

¡Hola chicos! Tenemos un inconveniente en la pestaña **Vehículos** de todas las plataformas, no trae resultados en el destino Bogotá. Hay 4 oficinas de retiro y sólo trae en una.

Las credenciales hijo:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/195877699-4161845e-ad4d-4d6f-9af6-c02826557544.png)
https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2022-12-10&pickUpTime=10:00&pickUpOfficeId=BOG&pickUpCityId=5a21b14afc2d560873053ed6&pickUpCityName=bogota-bogota-d-c-colombia&returnDate=2022-12-17&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

![image](https://user-images.githubusercontent.com/108418973/195878311-55ea0cd6-0850-4fdb-b962-b69745e26d09.png)
https://juantoselli.com/#/autos/buscar?pickUpDate=2023-02-10&pickUpTime=10:00&pickUpOfficeId=C6E&pickUpCityId=5a21b14afc2d560873053ed6&pickUpCityName=bogota-bogota-d-c---colombia&returnDate=2023-02-17&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

![image](https://user-images.githubusercontent.com/108418973/195877830-20378c7b-94bb-4664-8c3e-3a7df38c08ec.png)
https://travel.tosellitours.com/#/autos/buscar?pickUpDate=2023-01-10&pickUpTime=10:00&pickUpOfficeId=ZO6&pickUpCityId=5a21b14afc2d560873053ed6&pickUpCityName=bogota-bogota-d-c---colombia&returnDate=2023-01-17&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2022-12-10&pickUpTime=10:00&pickUpOfficeId=BOG&pickUpCityId=5a21b14afc2d560873053ed6&pickUpCityName=bogota-bogota-d-c-colombia&returnDate=2022-12-17&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Las otras oficinas no traen disponibilidades porque el proveedor las cerró
