### ISSUE TITLE
[ALOJAMIENTO] No trae disponibilidad

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#673]
### Descripcion del error

Buenos días chicos, tenemos un problema en la pestaña Alojamientos, el hotel **Nickelodeon Hotels & Resorts Riviera Maya** no trae disponibilidad. Verificamos en la web del hotel y si tiene disponibilidad para la fecha que buscamos. También, no carga la imagen del hotel y falta información.
El Toselli Tours si nos trae disponibilidad y hay información sobre el alojamiento.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

Ebooking:
![image](https://user-images.githubusercontent.com/108418973/196212236-bd78bea4-9b95-4424-afc2-4bbb0fe5cd95.png)

Toselli Tours:
![image](https://user-images.githubusercontent.com/108418973/196213497-8b965642-935c-4092-919a-3e49996e6be6.png)
https://travel.tosellitours.com/#/alojamiento/disponibilidad/60764e4c89671db6f0d3b5f2/nickelodeon-hotels-resorts-riviera-maya-solidaridad--mexico?checkIn=2022-12-01&checkOut=2022-12-06&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/60624421e856e958a4ebb303/nickelodeon-hotels-resorts-riviera-maya-playa-del-carmen-playacar-mexico?checkIn=2022-12-01&checkOut=2022-12-06&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
Encontramos otro alojamiento que no trae disponibilidad para ninguna fecha. Es el hotel **Grand Oasis Palm & Oasis Palm** , buscamos en Ebooking y en Toselli Tours:

![image](https://user-images.githubusercontent.com/108418973/196215193-a0c8bd5f-bf5d-495a-8364-59a535d8ef59.png)
[https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8c57d86315a56f0bd75bd/grand-oasis-palm-oasis-palm-cancun-mexico?checkIn=2022-12-10&checkOut=2022-12-15&nationality=AR&residence= AR&ocupaciones=2*30,30*0*&moneda=USD](https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8c57d86315a56f0bd75bd/grand-oasis-palm-oasis-palm-cancun-mexico?checkIn=2022-12-10&checkOut=2022-12-15&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD)

![image](https://user-images.githubusercontent.com/108418973/196215193-a0c8bd5f-bf5d-495a-8364-59a535d8ef59.png)
[https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca8c57d86315a56f0bd75bd/grand-oasis-palm-oasis-palm-cancun-mexico?checkIn=2023-01-05&checkOut=2023-01-12&nationality=AR&residence=AR&occupancies= 2*30,30*0*&moneda=USD](https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca8c57d86315a56f0bd75bd/grand-oasis-palm-oasis-palm-cancun-mexico?checkIn=2023-01-05&checkOut=2023-01-12&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD)

Gracias

**Comment by PatricioH96** [comment]
https://www.ebooking.com.ar/#/alojamiento/disponibilidad/60764e4c89671db6f0d3b5f2/nickelodeon-hotels-resorts-riviera-maya-solidaridad--mexico?checkIn=2022-12-01&checkOut=2022-12-06&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD este link si trae disponibilidad. Eliminamos la opcion que no dejaba buscar reservas.

**Comment by PatricioH96** [comment]
https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca9d19b86315a56f0e0aec8/grand-oasis-palm-cancun--mexico?checkIn=2022-12-01&checkOut=2022-12-06&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD Mismo caso con este hotel. Este link trae disponibilidades y se elimino la opcion que no dejaba buscar reservas.
