### ISSUE TITLE
[EBOOKING - CUPOS] Cupo sin información

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#677]
### Descripcion del error

Buenos días chicos, encontré un error en la pestaña _Cupos_, hay una salida sin información. Se trata de **Punta Cana y Bayahibe desde COR con Iberostar**.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/196717947-eab17692-d766-41f8-a7a1-0666e5da5620.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/cupos-confirmados/detalle/620aa03c405b4f1dac9e43f9/punta-cana-y-bayahibe-desde-cor-con-iberostar?from=5a21b01efc2d5608730462bf&quota=62a9df357936bd38edf7362e&token=0214CS98M0

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
A la hora de actualizar los tours se cargo dos veces el mismo token. El cambio se  va a ver en la próxima publicación.
