### ISSUE TITLE
[AÉREOS] No trae resultados con niños

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#679]
### Descripcion del error

¡Hola chicos! Tenemos un problema en la pestaña **Aéreos** de las plataformas de Toselli, cuando realizamos la búsqueda sin niños nos trae resultados y cuando agregamos un niño no dice que _no se encontraron resultados_.

Las credenciales son:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/197198254-72627073-7105-4a8a-9696-fb4258e9a8ed.png)
![image](https://user-images.githubusercontent.com/108418973/197198554-e6b5c7df-8ad0-441c-887b-88aee5fb25cc.png)
https://www.ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-04-02!2023-04-09!COR!FLN&flex=false&nationality=AR&residence=AR&occupancies=1*30*1*5&currency=USD

![image](https://user-images.githubusercontent.com/108418973/197198496-832ed7e3-7f6d-44f9-9c38-c364de387d83.png)
![image](https://user-images.githubusercontent.com/108418973/197198636-1ac0c10b-1a83-4eac-8751-9f611dd4ff0b.png)
https://juantoselli.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-04-04!2023-04-09!COR!FLN&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*1*8&currency=USD

![image](https://user-images.githubusercontent.com/108418973/197198752-a8ffe4d1-190d-4fb1-b233-140b189bcd74.png)
![image](https://user-images.githubusercontent.com/108418973/197198889-dc078fb5-f40f-4ba3-ae4a-4ed5408acaa2.png)
https://travel.tosellitours.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-04-02!2023-04-09!COR!FLN&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*1*12&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-04-02!2023-04-09!COR!FLN&flex=false&nationality=AR&residence=AR&occupancies=1*30*1*5&currency=USD

### Plataforma

Google Chrome

**Comment by CandelaMontes** [comment]
Hola Chicos! Pudieron ver esto?

**Comment by CandelaMontes** [comment]
Holaa!
Sigue sucediendo en todas las plataformas si colocamos edades de 0 y 1 años!
https://www.ebooking.com.ar/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-03-01!2023-03-16!EZE!MAD&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*1*1&currency=USD

https://travel.tosellitours.com/#/vuelos/buscar?flightType=2&classPref=Y&segments=2023-03-01!2023-03-16!EZE!MAD&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*1*1&currency=USD

**Comment by gabrielmarinsaldaJT** [comment]
Listo! Lo verán reflejado en la próxima publicación
