### ISSUE TITLE
Consulta por tarifa

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#68]
Buenas tardes.

Consulto por tarifas del Hotel Soneva Jani, en Maldivas.
Dejo link de nuestro Ebooking:
https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8c69986315a56f0be37ad/soneva-jani?checkIn=2021-12-28&checkOut=2022-01-03&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

La consulta es para saber las tarifas que nos trae el Ebooking son correctas, ya que, la vendedora nos reclama que las tarifas son muy elevadas.
Gracias, desde ya.

Saludos.
Juan Manuel

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Por lo que revisé, el proveedor devuelve ese precio

No estamos agregando ningún MarkUp adicional ni estamos haciendo algún cálculo mal

Además, puedo notar que muchos otros proveedor no devuelven disponibilidad para este hotel en esas fechas

Por lo que mi conclusión es que GRN no tiene disponibilidad para ese hotel en esas fechas y pone esos precios caros para evitar que alguien reserve

Les recomiendo enviar un mail al proveedor GRN para consultarles y aclarar la situación, pero no hay nada que podamos hacer desde nuestro lado

**Comment by gabrielmarinsaldaJT** [comment]
Adjunto una captura de pantalla del Response del provider

![image](https://user-images.githubusercontent.com/26115345/130620598-05d7a4ac-d30e-4370-b885-fbb8b629b0d9.png)

**Comment by JuanBachmann** [comment]
¡Gracias!
