### ISSUE TITLE
[CUPOS] No se pueden tomar 

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#681]
### Descripcion del error

¡Hola! Tenemos un problema en la pestaña _Cupos_, no se pueden reservar. Hacemos la búsqueda desde Córdoba, cuando vamos a la página del check out completamos los datos, tocamos finalizar compra y queda cargando.

Me pasó con estas salidas:
- [Punta Cana desde COR con Ocean](https://www.ebooking.com.ar/#/cupos-confirmados/detalle/620e5fbe5858bf664bb75537/punta-cana-desde-cor-con-ocean?from=5a21b01efc2d5608730462bf&quota=62a9df357936bd38edf7362e&token=0217NW18XI)
- [Punta Cana desde COR con Ocean](https://www.ebooking.com.ar/#/cupos-confirmados/detalle/620e5fbe5858bf664bb75537/punta-cana-desde-cor-con-ocean?from=5a21b01efc2d5608730462bf&quota=62a9e3fa7936bd38ed0a7fc8&token=0217NW18XI)
- [Punta Cana desde COR con Ocean](https://www.ebooking.com.ar/#/cupos-confirmados/detalle/620e5fbe5858bf664bb75537/punta-cana-desde-cor-con-ocean?from=5a21b01efc2d5608730462bf&quota=62f15f5c4c356b3108670aa4&token=0217NW18XI)
- [Punta Cana desde COR con Riu](https://www.ebooking.com.ar/#/cupos-confirmados/detalle/620aa032405b4f1dac9e3bff/punta-cana-desde-cor-con-riu?from=5a21b01efc2d5608730462bf&quota=62f15f5c4c356b3108670aa4&token=0214VWIM8A)

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/197271737-8c6b57b4-2143-4bf6-a730-bfefbb10d9ad.png)
![image](https://user-images.githubusercontent.com/108418973/197271853-e2bb6139-6978-4e73-aa56-085daff7fd4b.png)
![image](https://user-images.githubusercontent.com/108418973/197272050-64b2e5a9-af8d-4611-8056-04474b99d171.png)
![image](https://user-images.githubusercontent.com/108418973/197272112-5368aee3-22ea-4ecd-be22-b1a76c80f47e.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/cupos-confirmados?destinationFrom=5a21b01efc2d5608730462bf&fromDate=2022-10-21&toDate=2023-10-21

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola! ¿Hay alguna novedad sobre este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Done it!
