### ISSUE TITLE
[Expedia] Cambios vencimiento

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#683]
### Descripcion del error

Hola chicos!
Tenemos las siguientes reservas de Expedia, que no se han cancelado manual, ni el robot las canceló creemos que es porque su vencimiento fue antes que la creación:

- [ ] https://adm.ebooking.com.ar/bookings/detail/61c1c5dee10bf587bebd6594?purchaseGroupId=370388#heading_61c1c5dee10bf587bebd6594
- [ ] https://adm.ebooking.com.ar/bookings/detail/62278b88ab04d9564b6a676b?purchaseGroupId=381487#heading_62278b88ab04d9564b6a676b
- [ ] https://adm.ebooking.com.ar/bookings/detail/62cf09a34b52a78424f01c94?purchaseGroupId=384684#heading_62cf09a34b52a78424f01c94
- [ ] https://adm.ebooking.com.ar/bookings/detail/6197f82f27738254ef7dcadd?purchaseGroupId=366615#heading_6197f82f27738254ef7dcadd
- [ ] https://adm.ebooking.com.ar/bookings/detail/61a3285c582e64845bf6d3e1?purchaseGroupId=368420#heading_61a3285c582e64845bf6d3e1

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by GuadaVivas** [comment]
Por el momento estas son las que hemos encontrado, que nos reclaman los pagos de las mismas.

**Comment by GuadaVivas** [comment]
Hola chicos!
Alguna novedad?

**Comment by GuadaVivas** [comment]
Hola chicos!
Alguna novedad?

**Comment by GuadaVivas** [comment]
Hola chicos!
Alguna novedad?

**Comment by mvalentinalucero** [comment]
Chicos buenas tardes, sumo otra reserva que ha detectado el equipo de pagos que NO tiene voucher emitido y nunca se cancelo automaticamente 

https://adm.ebooking.com.ar/bookings/detail/6353cbd93f050887b530f23b?purchaseGroupId=411747#heading_6353cbd93f050887b530f23b

**Comment by GuadaVivas** [comment]
Hola chicos!
Pudieron ver esto?

**Comment by GuadaVivas** [comment]
alguna novedad?

**Comment by GuadaVivas** [comment]
hola chicos!
Pudieron ver algo de esto?

**Comment by GuadaVivas** [comment]
Hola chicos!
Alguna novedad?

**Comment by GuadaVivas** [comment]
Hola chicos, alguna novedad? Si bien de pagos no volvieron a reclamar esto, debemos darle un cierre y resolución. Gracias

**Comment by GuadaVivas** [comment]
Hola chicos!
Dejo otro caso de estos:
https://adm.ebooking.com.ar/bookings/detail/64a561fb3a111dcb7f636731?purchaseGroupId=472075#heading_64a561fb3a111dcb7f636731

**Comment by GuadaVivas** [comment]
chicos, pudieron ver esto?

**Comment by GuadaVivas** [comment]
chicos! esto quedo solucionado?

**Comment by GuadaVivas** [comment]
Hola chicos! esto se vio?

**Comment by GuadaVivas** [comment]
Hola chicos!
Entiendo que esto esta siendo revisado, podran darnos un update?

**Comment by GuadaVivas** [comment]
Hola chicos, procedemos a cerrar este problema, entiendo que ya fue resuelto. Los que nos pediran los pagos los iremos viendo en el momento
