### ISSUE TITLE
[Cupos] Error en asistencias 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#684]
### Descripcion del error

Hola chicos!
Hay un problema cuando se toman cupos por el ebooking, las asistencias de Universal Assitance, vienen cobradas y confirmadas, pero no figuran los nombres. Por lo que cuando reclamamos al proveedor nos da la opción de: cancelar y emitir offline, o tomar por aparte por integración (ellos la tienen confirmada y por ello no pueden modificarlo, se debe retomar)
Les dejo un ejemplo:
https://adm.ebooking.com.ar/bookings/detail/6331cb3800620e2dce83f8f7?purchaseGroupId=432113#heading_6331cb3800620e2dce83f8f7
Podrán revisar si se trata de algo de nuestro lado? Ya que les hemos enviados los logs, pero no recibimos respuesta sobre ello por parte del proveedor. 

### Paso a paso para reproducir el error

![image](https://user-images.githubusercontent.com/87333634/199511862-20349821-437d-49eb-a759-b2c4669a3c50.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2022-05-02&purchaseGroupId=432113

### Plataforma

Google Chroome

**Comment by GuadaVivas** [comment]
hola chicos
alguna novedad?

**Comment by GuadaVivas** [comment]
Hola chicos,
Alguna novedad?

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!
