### ISSUE TITLE
[TOSELLI TOURS] Aparecen las percepciones de Argentina

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#685]
### Descripcion del error

¡Buen día! Nos notificaron sobre un inconveniente, la agencia de Ecuador VCR REPRESENTACIONES realizó una reserva y en el **detalle de la tarifa están las percepciones de Argentina (RG)**. Revisamos y la agencia está bien cargada en Toselli Tours.
Les dejo la reserva del administrador.

Las credenciales son:
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/200834437-ea48c29d-725d-4fd4-86f4-cfcc50340d8b.png)

### Link al error y/o Localizador

https://adm.tosellitours.com/bookings/detail/6365879b7a6cb2e89cd448b5?purchaseGroupId=443013#heading_6365879b7a6cb2e89cd448b5

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola! ¿Hay alguna novedad con respecto a este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Done it!
