### ISSUE TITLE
[TOSELLI TOURS] Cambio de designación en el ingreso

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#686]
### Idea a implementar

Buen día, les traigo una propuesta para realizar un cambio. En el ingreso a la página de Toselli Tours aparecen las opciones: Travel Agencies y Business, esta última opción es para que ingresen los pasajeros a ver las tarifas sin desgloce de precios. Se presta a confusión y proponemos que Business se cambie a Customers o Passengers. 

![image](https://user-images.githubusercontent.com/108418973/200839636-bd18a0a7-02e3-403b-aef4-926c8d79dd7a.png)
https://www.tosellitours.com/

Gracias :blush:

**Comment by RoDiaz1996** [comment]
¡Hola! ¿Saben si se puede hacer este cambio?

**Comment by gabrielmarinsaldaJT** [comment]
Solved! Lo verán en la próxima publicación
