### ISSUE TITLE
[Adm] Modificar reserva 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#688]
### Descripcion del error

Hola chicos!
Necesitamos modificar lo siguiente en la reserva RES028619-4480 :

- [x] Agregar pasajera: Hilt Peletti/ Rocio Magalii (no nos guarda cuando la cargamos nosotros)
- [x] Actualizar costo a  2819.34 USD

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/62d96fb8f249eb3e1bcbbbac?purchaseGroupId=403632#heading_62d96fb8f249eb3e1bcbbbac

### Plataforma

Google Chroome

**Comment by mvalentinalucero** [comment]
Chicos buenos dias! Agrego una reserva más en la que el vendedor NO ve a la pasajera líder y cuando queremos cargar su DNI y dejar guardado su nombre no podemos. El nombre que necesitamos poner es HAIDE ESTHER ALVAREZ DNI: 3884841

LOC: SI11768DC

https://adm.ebooking.com.ar/bookings/detail/637a3d897e5891d0ad0655c5?purchaseGroupId=445997#heading_637a3d897e5891d0ad0655c5

**Comment by mvalentinalucero** [comment]
Chicos buenos dias! Agrego otra reserva en la que debemos modificar la cantidad de pasajeros: 

LOC: 350598735

https://adm.ebooking.com.ar/bookings/detail/637e6ed3c93fbeb082300628?purchaseGroupId=447963#heading_637e6ed3c93fbeb082300628

Necesitamos quitar a la pasajera ANDREA VANESA FERREYRA y dejar como única pasajera a GUADALUPE BELTRAN y también modificar el numero en el apartado de ocupación. 

Gracias!

**Comment by JuanBachmann** [comment]
Chicos les dejo una reserva donde necesitamos invertir los nombres, y que el titular de la reserva sea GONZALO ANDRES PENALVA

- https://adm.ebooking.com.ar/bookings/detail/633cba60852eb75b689d3317?purchaseGroupId=435022#heading_633cba60852eb75b689d3317

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Todo listo chicos!
