### ISSUE TITLE
RESERVAS TEST EXPEDIA LOC 9192441702694 Y 9187451573182

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#69]
Estimados buenas tardes,
Caso reservas Expedia TEST, no aparecen en la plataforma y nos solicitan pago por las mismas, 
Ya hay cadena con Karina por las mismas. dejo en constancia el error.

**Comment by gabrielmarinsaldaJT** [comment]
Buenos días

Después de revisar, veo que el proveedor no implementa el método GetFutureBookings porque no existe en su integración

Se le consulta al proveedor sobre el mismo y nos aclaran que no hay manera de implementarlo, y que incluso no tienen otra forma de obtener todas las reservas de un cliente por fecha de creación u otro parámetro que no necesite los RecordLocator de las mismas

Entonces, acordamos que nos envíen un listado de todas las reservas confirmadas que tenemos con Expedia, para poder compararlas con las que tenemos guardadas en nuestro inventario

**Comment by gabrielmarinsaldaJT** [comment]
Conversación con Ana Aliseris vía Skype

> 09:45
> Hola Ana, cómo estás?
> Te escribo para consultarte lo siguiente
> Existe alguna manera de obtener todos las reservas que tenemos en Expedia buscándolas por fecha?
> 
> Ana, 10:02
> no por la API
> 
> con el acceso que tienen a voyager no te devuelve el listado?
> 
> 10:08
> Si, por le Voyager se puede
> El problema que tenemos
> 
> Ana, 10:09
> si me das un rango de fechas igual podemos sacar un listado internamente
> 
> 10:09
> Es que nos gustaría tener una manera de comparar los inventarios para evitar que alguans reservas queden activas en su sitio y en el nuestro no estén
> 
> Ana, 10:09
> te entiendo

**Comment by gabrielmarinsaldaJT** [comment]
Conversación con Gerardo Rodríguez sobre la posibilidad de implementar el mismo **affiliate_reference_id** a todas las reservas de Expedia:

> Hola Gabriel! Es critico que mantengais enviando un codigo unico por reserva en el AffiliateReferenceID, ya que usamos esa informacio para identificar reservas duplicadas
> 
> siempre recomendamos a los partners enviar en el affiliateReferenceID vuestro codigo interno que identifica cada reserva, ya que se entiende que vuestro codigo por reserva tambien es unico, y ademas este campo se entrega en los Financial estatement conjuntamente con el ItineraryID, y hemos visto que es de valor para los equipos de Finanzas de los partners, les simplifica tener el numero de reserva de EPS y el interno en el mismo informe para hacer las reconciliaciones
> 
> mas dicho esto, no es necesiario que envieis vuestro codigo interno de reserva. Si enviarlo os genera algun problema, podeis generar un esquema unico de ID y enviarlos en su lugar, lo importante es que sea un numero unico por reserva
> 
>

**Comment by gabrielmarinsaldaJT** [comment]
Una vez recibamos el listado de reservas, se los adjuntaré junto con la lista de las reservas en nuestro sitio para verificar que ambas coincidan

**Comment by Jlavign** [comment]
Buenísimo, seguimos con la gestión, muchas gracias por la info!
