### ISSUE TITLE
[TRASLADOS] Opciones del desplegable

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#690]
### Descripcion del error

¡Hola! Encontramos un inconveniente en la pestaña Traslados, buscamos el aeropuerto de Madrid y nos aparece último en las opciones, cuando estamos colocando el código IATA "MAD".
Además, hay algunos destinos sin iconos.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/202268317-60b46140-e77d-48ce-829e-db1c4b17503f.png)
![image](https://user-images.githubusercontent.com/108418973/202268410-5684eb8c-901b-4450-80ad-41ca9b87bfb5.png)
![image](https://user-images.githubusercontent.com/108418973/202268461-eebca5df-db12-4107-ab9e-542f1425dd11.png)
![image](https://user-images.githubusercontent.com/108418973/202268527-f8f82047-d0a4-44e0-9a6b-b9be70a17087.png)

![image](https://user-images.githubusercontent.com/108418973/202269486-c47cb983-b5de-4d5e-a2a5-20a28d19120f.png)
https://travel.tosellitours.com/#/traslados

### Link al error y/o Localizador

https://ebooking.com.ar/#/traslados

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Hay alguna novedad sobre este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!

A partir de ahora, si quieren ingresar algún aeropuerto, sólo ingresen las 3 letras del código IATA 

Lo verán reflejado en la próxima publicación
