### ISSUE TITLE
[SALIDAS / CRUCEROS] No aparece la imagen

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#695]
### Descripcion del error

Hola chicos, hay la salida COSTA FORTUNA 7 NOCHES de cruceros no tiene imagen.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/204799461-745e0639-c0ee-4b64-824b-489453fb2e87.png)
![image](https://user-images.githubusercontent.com/108418973/204799558-fc141aa6-6182-4276-bcfc-3c5ef21322ad.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/salidas/detalle/1128MGVKO1/costa-fortuna-7-noches?departureId=1128467C85

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Se solucionará en conjunto con lo de cruceros.
