### ISSUE TITLE
[ALOJAMIENTOS] Riu República sólo adultos

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#697]
### Descripcion del error

¡Buenos días chicos! Una vendedora nos comunicó sobre un inconveniente, el hotel **Riu Republica** aparece como opción en una búsqueda de disponibilidad de 1 adulto y 2 niños, cuando el hotel es **exclusivo para adultos**.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/205675025-22c39113-a69a-4415-8c7f-ac61324ef2f0.png)
![image](https://user-images.githubusercontent.com/108418973/205675225-81023e62-6e70-480c-99f8-16ab0083e14c.png)
![image](https://user-images.githubusercontent.com/108418973/205675392-ca29bf6f-36a2-4da7-b665-5094de7f9005.png)
![image](https://user-images.githubusercontent.com/108418973/205675840-3b259e9a-22f4-42ea-97ae-2362d408c4b0.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8d0bd86315a56f0c2bbdc/hotel-riu-republica-punta-cana-dominican-republic?checkIn=2023-05-10&checkOut=2023-05-18&nationality=AR&residence=AR&occupancies=1*30*2*5,7&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Buenas. El error es por parte del proveedor que devuelve el hotel cuando no deberia. Ahora les hablo y pongo aca cuando me contesten y lo solucionen.

**Comment by gabrielmarinsaldaJT** [comment]
Cierro issue

**Comment by RoDiaz1996** [comment]
¿Se solucionó este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!!

Les explico nuevamente.

Nosotros no podemos filtrar la información que nos manda el proveedor. Si el hotel es AdultsOnly o lo que sea, y el proveedor nos devuelve una disponibilidad que no es correcta, no podemos sacarla del listado de disponibilidades porque en ningún lugar de nuestra información de hoteles está el apartado "Sólo adultos"

Mi recomendación para evitar problemas, es notificar al proveedor de esta mala práctica y poner el mapeo entre el hotel y el proveedor en la [blacklist](https://adm.ebooking.com.ar/blackList) para que no entren reservas de alguna agencia

Saludos!

**Comment by gabrielmarinsaldaJT** [comment]
En cualquier caso, entré a revisar y no hay dispo con ningún proveedor

Seguramente lo han actualizado los brokers
