### ISSUE TITLE
[CUPOS] Error en Juan Toselli

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#700]
### Descripcion del error

¡Hola! Tenemos un inconveniente con la pestaña _Cupos_. En el cupo **RIVIERA MAYA Y COSTA MUJERES DESDE BUE CON PALLADIUM**, buscamos disponibilidad y nos salta error. En Ebooking no tenemos problemas.

Credenciales:
Juan Toselli: agenciadeprueba@juantoselli.com | Junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/206206056-0e2f744c-f635-4f87-8695-10ca6c814db7.png)
![image](https://user-images.githubusercontent.com/108418973/206207009-eaee1009-6aa3-41de-84fa-942116edd59b.png)

### Link al error y/o Localizador

https://www.juantoselli.com/#/cupos-confirmados/detalle/620a6809671c27d3c471d661/riviera-maya-y-costa-mujeres-desde-bue-con-palladium?from=5a458122fc0b9d5df191f47f&quota=636e671f885f503a18f1a6ba&occupancies=2*30,30*0*&nationality=AR&residence=AR&token=0214BFB7HB

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado por @MatiFrencia !!
