### ISSUE TITLE
[Cupos] Modificar costo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#701]
### Descripcion del error

Hola chicos!
Necesitamos modificar el costo del cupo 997734
Nos indican que se vendió con una promo, pero el voucher generado tiene un precio de venta mayor.
El costo deberia ser: 

Precio de venta: $ 51340 (tarifa) + $8000 (tasas)

Total: 59340

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/629e6a7cfd0f32a97916b9d0?purchaseGroupId=398646#heading_629e6a7cfd0f32a97916b9d0

### Plataforma

 .

**Comment by BelenBidondo** [comment]
Hola chicos! Cuando puedan modifiquen esto por favor. Gracias!

**Comment by BelenBidondo** [comment]
Hola chicos! Cuando puedan modifiquen esto por favor. Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Nunca hice un cambio en cupos, no entiendo que son tasas

Eso que me pasan es PVP? Es Costo?

Saludos

**Comment by BelenBidondo** [comment]
Hola Gabi! Lo que hay que modificar es el PVP a 59340. El costo está ok

![image](https://user-images.githubusercontent.com/103128819/209990478-673a3396-b505-4665-bbc9-9c6a6cf63d9a.png)

**Comment by gabrielmarinsaldaJT** [comment]
Done!
