### ISSUE TITLE
[alojamiento] Modificar costo en adm

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#702]
### Descripcion del error

Hola chicos!
Solicitamos por favor modificar los costos de las siguientes reservas optimizadas, ya que la encargada realizó gestiones con el proveedor:
![image](https://user-images.githubusercontent.com/87333634/206295981-68a12850-605f-4143-8feb-19ef5bc3e46d.png)

- [x] NP98996PT : Modificar a 5540.38 USD 
https://adm.ebooking.com.ar/bookings/detail/631b31485810eff8bb0f7b07?purchaseGroupId=421573#heading_631b31485810eff8bb0f7b07

- [x] HN93236YP : Modificar a 3777.78 USD
https://adm.ebooking.com.ar/bookings/detail/631b31885810eff8bb34a045?purchaseGroupId=421573#heading_631b31885810eff8bb34a045

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/631b31485810eff8bb0f7b07?purchaseGroupId=421573#heading_631b31485810eff8bb0f7b07 / https://adm.ebooking.com.ar/bookings/detail/631b31885810eff8bb34a045?purchaseGroupId=421573#heading_631b31885810eff8bb34a045

**Comment by gabrielmarinsaldaJT** [comment]
Done!
