### ISSUE TITLE
[adm] Modificar nombre

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#703]
### Descripcion del error

Hola chicos!
Seguimos con el incoveniente para modificar desde nuestro lado nombre y apellido del pasajero en el adm.
Necesitamos modificar apellido de pax lider a: **KATHERINE MARTINEZ**
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6388c67bb5017a0e7c9520a4?purchaseGroupId=443020#heading_6388c67bb5017a0e7c9520a4

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Done!

**Comment by BelenBidondo** [comment]
Hola Gabi! lo seguimos viendo igual

**Comment by gabrielmarinsaldaJT** [comment]
Por favor ponganla como inactualizable 🙏

**Comment by BelenBidondo** [comment]
Listo Gabi, ahora si! Gracias!!

**Comment by BelenBidondo** [comment]
Hola Gabi! De nuevo no estamos pudiendo modificar los pasajeros, te dejo dos más 

En la reserva 1240008 el pasajero lider es Andrea Anastasia Giovannini DNI 21628106     

https://adm.ebooking.com.ar/bookings/detail/63b42b90f233dab1277df731?purchaseGroupId=455814#heading_63b42b90f233dab1277df731

 

En la reserva 1240009 el pasajero lider es GINO VICENTE MARRUCO GIOVANNINI  DNI 46506802

https://adm.ebooking.com.ar/bookings/detail/63b42b8cf233dab1277afb2c?purchaseGroupId=455814#heading_63b42b8cf233dab1277afb2c
