### ISSUE TITLE
[ALOJAMIENTOS] Símbolos en la descripción

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#704]
### Descripcion del error

¡Holaa! Chicos encontramos unos símbolos en la descripción de un alojamiento. En la pestaña Alojamientos, el hotel STEEL HOUSE COPENHAGEN en Juan Toselli, Ebooking y Toselli Tours.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/207691858-4b55476f-4c8a-4228-828c-213e55ba34a7.png)
https://www.juantoselli.com/#/alojamiento/disponibilidad/5ca93f2d86315a56f0d4f57a/steel-house-copenhagen?checkIn=2023-07-01&checkOut=2023-07-14&nationality=AR&residence=AR&occupancies=1*30*0*&currency=USD

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca93f2d86315a56f0d4f57a/steel-house-copenhagen-copenhagen-denmark?checkIn=2023-07-01&checkOut=2023-07-14&nationality=AR&residence=AR&occupancies=1*30*0*&currency=USD

https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca93f2d86315a56f0d4f57a/steel-house-copenhagen-copenhagen--denmark?checkIn=2023-06-01&checkOut=2023-06-14&nationality=AR&residence=AR&occupancies=1*30*0*&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca93f2d86315a56f0d4f57a/steel-house-copenhagen-copenhagen-denmark?checkIn=2023-07-01&checkOut=2023-07-14&nationality=AR&residence=AR&occupancies=1*30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by CandelaMontes** [comment]
Hola Chicos!
Pudieron ver esto? 
Siguen apareciendo 😅

**Comment by CandelaMontes** [comment]
En este link también sucede
https://www.juantoselli.com/#/alojamiento/disponibilidad/5ca957d486315a56f0d78678/ericeira-chill-hill-peach-garden?checkIn=2023-07-01&checkOut=2023-07-14&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

https://www.ebooking.com.ar/#/alojamiento/finalizar-compra/63a0860f332498c51504567a?currency=USD

**Comment by CandelaMontes** [comment]
Hola! Si tienen alguna novedad les agradecería 🤗

**Comment by CandelaMontes** [comment]
Holaaaaa Siguen apareciendo estos símbolos. Pudieron verlo?

**Comment by gabrielmarinsaldaJT** [comment]
Listoooooooo
