### ISSUE TITLE
[adm] Modificar costos

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#705]
### Descripcion del error

Hola chicos!
Por motivos de modificación de fechas, necesitamos por favor modificar costo y precio de venta de las siguientes reservas:

- [x] https://adm.ebooking.com.ar/bookings/detail/638096c8a50b0367e7d174d5?purchaseGroupId=440183#heading_638096c8a50b0367e7d174d5

**LOCALIZADOR :RS86521VG – COSTO  :  $4,222.68 USD -  VENTA USD 5278.35**

- [x] https://adm.ebooking.com.ar/bookings/detail/6380ad19a50b0367e74c55aa?purchaseGroupId=440183#heading_6380ad19a50b0367e74c55aa

**LOCALIZADOR : MT12019LN – COSTO  $2,449.37 USD – VENTA USD 3061.71**

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by JuanBachmann** [comment]
Equipo

Insistimos

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Listo chicos

En estos casos, tienen que tener en cuenta que la optimización se pierde, y les pido por favor que modifiquen las fechas como realmente son ahora, porque sino la reserva se va a optimizar de vuelta y se va a hacer mal

Saludos
