### ISSUE TITLE
[Reservas No Reembolsables] Tomadas por la agencia

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#706]
### Descripcion del error

Hola chicos!
Les escribimos para advertir que, la agencia, puede pasar al check out, para tomar reservas no reebolsables de atracciones (al menos estas nos han reportado)
Entendemos que las mismas quedan en error ya que no podemos visualizar nigún tipo de estado ni localizador. 
Podrán corroborarlo?
![image](https://user-images.githubusercontent.com/87333634/208524694-571ef700-1158-4a05-bcd5-f95e40295081.png)
De todas formas, hemos enviado al proveedor consultando si las tienen.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2022-06-19&purchaseGroupId=406337

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

El problema es que las opciones de disponibilidad de Universal no tienen ninguna política de cancelación en el momento del Avail
Una vez la agregan al carrito, buscamos la política de cancelación en el proveedor y nos da que son No Reembolsables

Está bien que no les deje reservar

Saludos!
