### ISSUE TITLE
[VEHÍCULOS] No hay disponibilidad de vehículos

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#707]
### Descripcion del error

¡Hola chicos! Encontramos un inconveniente en la pestaña **Vehículos**, no hay disponibilidad para San Juan, Puerto Rico en ninguna de las oficinas que aparecen como opciones. Probamos en distintas fechas en Juan Toselli, Ebooking y Toselli Tours.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/208926826-7adc5af7-c88a-4510-9d12-8c93c32fc2a9.png)
https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2023-03-10&pickUpTime=10:00&pickUpOfficeId=BQN&pickUpCityId=5a21b151fc2d560873053f49&pickUpCityName=puerto-rico-san-juan-puerto-rico&returnDate=2023-03-17&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

![image](https://user-images.githubusercontent.com/108418973/208926866-1f229190-ad17-469c-83d8-87a3550c91fd.png)
https://www.juantoselli.com/#/autos/buscar?pickUpDate=2023-02-10&pickUpTime=10:00&pickUpOfficeId=SJU&pickUpCityId=5a21b151fc2d560873053f49&pickUpCityName=puerto-rico-san-juan-puerto-rico&returnDate=2023-02-17&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

![image](https://user-images.githubusercontent.com/108418973/208926909-b1788c0f-c320-4a84-bab9-d582c5136922.png)
https://travel.tosellitours.com/#/autos/buscar?pickUpDate=2023-04-10&pickUpTime=10:00&pickUpOfficeId=Y36&pickUpCityId=5a21b151fc2d560873053f49&pickUpCityName=puerto-rico-san-juan-puerto-rico&returnDate=2023-04-17&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2023-03-10&pickUpTime=10:00&pickUpOfficeId=BQN&pickUpCityId=5a21b151fc2d560873053f49&pickUpCityName=puerto-rico-san-juan-puerto-rico&returnDate=2023-03-17&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Revisamos y no tenemos código de tarifa válida para Puerto Rico

Saben si tenémos algún código de tarifa para este país?
Si lo tienen, por favor pásenlo que lo agregamos sin drama

Saludos!

**Comment by RoDiaz1996** [comment]
¡Hola Gabi! No, yo hice una búsqueda y cómo vi varias oficinas cómo opción busqué y no me trajo ninguna disponibilidad

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Así es

Tenemos las oficinas mapeadas, pero como no tenemos ningún código de tarifa que responda para Puerto Rico, no te a devolver disponibilidad nunca

Las rentadoras no te dieron nada como un **RateCode**, **VehicleRate** o algo así?

**Comment by RoDiaz1996** [comment]
No consultamos con las rentadoras, osea que cuando no hay resultados pero hay oficinas es porque falta ese RateCode o VehicleRate?

**Comment by gabrielmarinsaldaJT** [comment]
Ok, ahora les consulto yo entonces

El tema es que cuando hicimos la integración nos dieron códigos de tarifas que responden a X paises

Ninguno de esos paises era Puerto Rico

**Comment by gabrielmarinsaldaJT** [comment]
Agregado Puerto Rico y pueden ver dispo **sin embargo, da error al reservar. Se le consulta al provider**

**Comment by RoDiaz1996** [comment]
Genial Gabi, quedamos a la espera de la respuesta

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!!
