### ISSUE TITLE
[VEHÍCULOS] No se puede tomar un auto

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#708]
### Descripcion del error

Hola chicos, tenemos una vendedora que nos comunica que una agencia y ella no pudieron reservar un auto por la página. El estado queda en error, dejamos el Response de los logs.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022

Gracias😊 

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/209139349-a387d2ab-a63b-4914-8773-488ae4d2dbc2.png)
![image](https://user-images.githubusercontent.com/108418973/209139423-e848eaa8-fad0-4b77-b82b-aa619a57ecd4.png)
![image](https://user-images.githubusercontent.com/108418973/209139521-1120c12b-8d2c-4f72-b9d0-8b8df230c390.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/63a302616d615cf8129416f2?purchaseGroupId=454066#heading_63a302616d615cf8129416f2

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Nos avisaron desde National que no deberíamos mostrar disponibilidad en Brasil.
Por eso te da el error

ya no volverá a pasar

Saludos!
