### ISSUE TITLE
[adm] Modificar costo

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#710]
### Descripcion del error

Hola chicos!
Necesitamos actualizar el costo de la siguiente reserva, cancelada y optimizada. Nos solicitan desde pagos. USD 229,26
![image](https://user-images.githubusercontent.com/87333634/209559697-b85bb6ff-8d4e-465b-a614-af9790cb79f7.png)

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/630351e19a13a18a3c27f3d0?purchaseGroupId=415350#heading_630351e19a13a18a3c27f3d0

**Comment by gabrielmarinsaldaJT** [comment]
Listo
