### ISSUE TITLE
[adm] No figura propiedad

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#711]
### Descripcion del error

Hola chicos!
En la siguiente reserva, no nos el nombre ni los datos de la propiedad.
El proveedor nos trae la siguiente 
![image](https://user-images.githubusercontent.com/87333634/209716822-9e0e08bd-e73d-48bb-824b-d12c9a1f5e9a.png)

Solicitamos por favor modificar y también revisar que nos haya llegado correcto por integración.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/63a5c046ca0d0918800ee1ba?purchaseGroupId=454662#heading_63a5c046ca0d0918800ee1ba

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Parece ser que el proveedor no devuelve correctamente la propiedad con el método GetProperty

Les recomiendo que verifiquen si está bien mapeada y le den el Chequeado porque lo intenté replicar y sigue devolviendo todos los campos del hotel sin nombre ni nada

**Comment by BelenBidondo** [comment]
> https://adm.ebooking.com.ar/bookings/detail/63a5c046ca0d0918800ee1ba?purchaseGroupId=454662#heading_63a5c046ca0d0918800ee1ba

Gabi, ahora ni se abre la reserva, podrías fijarte?
