### ISSUE TITLE
[SALIDAS] Error de tipeo

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#713]
### Descripcion del error

¡Hola chicos! Encontramos un error de tipeo en la salida **SUDÁFRICA: GRAN TREK FIN JNB**, dice _SUPLEMENTO PER PERSONA EN BASE SINGLE DESDE USD 575_

Credenciales:

Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/210100543-aa34d0c9-5556-45e0-ab9a-5b6227d34779.png)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/salidas/detalle/1214LDMYJG/sudafrica--gran-trek-fin-jnb?departureId=121433XR3K

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola ro!

Esto tenés que reportárselo a sebastian.chirino@juantoselli.com

Ya que es él quien la carga y las edita

Saludos!
