### ISSUE TITLE
[ALOJAMIENTOS] Filtrar con pileta

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#714]
### Idea a implementar

Hola, tenemos una sugerencia para la pestaña **Alojamientos**, en comodidades estaría bueno agregar la opción _Pileta_ para filtrar los diferentes alojamientos.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

![image](https://user-images.githubusercontent.com/108418973/210101069-7db4709b-2380-413a-b131-83fc19fbbc64.png)
https://www.ebooking.com.ar/#/alojamiento/buscar?id=5a21b167fc2d56087305403a&name=florianopolis-y-sus-alrededores-santa-catarina--brasil&checkIn=2023-01-25&checkOut=2023-02-01&nationality=AR&residence=AR&occupancies=2*30,30*1*8&currency=USD

Gracias😊

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Lamentablemente no contamos con esa información

La data estática de Expedia no indica si un hotel tiene pileta / piscina o no

Saludos!
