### ISSUE TITLE
[adm] Error para modificar nombres

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#716]
### Descripcion del error

Hola chicos!
Seguimos sin poder modificar los nombres en las reservas del adm.
Solicitamos modificar lo isguiente:

- [ ] https://adm.ebooking.com.ar/bookings/detail/63aca2dccb4ee9f22d5f2053?purchaseGroupId=455814#heading_63aca2dccb4ee9f22d5f2053 
Andrea Anastasia Giovannini
RENZO VITTORIO MARRUCO GIOVANNINI

- [ ] https://adm.ebooking.com.ar/bookings/detail/63aca2dccb4ee9f22d5f25dd?purchaseGroupId=455814#heading_63aca2dccb4ee9f22d5f25dd
Sergio Raul Marruco
GINO VICENTE MARRUCO GIOVANNINI

- [ ] https://adm.ebooking.com.ar/bookings/detail/63ad98a097774e22c9e9b9a7?purchaseGroupId=455814#heading_63ad98a097774e22c9e9b9a7
Andrea Anastasia Giovannini
RENZO VITTORIO MARRUCO GIOVANNINI

- [ ] https://adm.ebooking.com.ar/bookings/detail/63ad989f97774e22c9e99e54?purchaseGroupId=455814#heading_63ad989f97774e22c9e99e54
Sergio Raul Marruco
GINO VICENTE MARRUCO GIOVANNINI

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos!

Ya pueden modificarlos ustedes

Les subimos un fix para que no les dé error

Saludos!
