### ISSUE TITLE
[ALOJAMIENTOS] Error tarifa

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#719]
### Descripcion del error

¡Hola chicos! Nos informan de un error en la tarifa del **Hotel Alexandra**, nos figura que es USD 47.546,98.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/210617507-79ff888f-801f-414d-b445-887eab5359e0.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca9313586315a56f0d36184/hotel-alexandra?checkIn=2023-05-21&checkOut=2023-05-25&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Por lo que veo, el hotel muestra un precio correcto.
Es decir, el que nos envía este precio carísimo es el mismo proveedor

No hay mucho que pueda hacer

Saludos!

**Comment by RoDiaz1996** [comment]
Busqué en la página del Hotel y no coinciden las tarifas:
![image](https://user-images.githubusercontent.com/108418973/211076884-78435118-b764-4494-a19d-a97109a967ca.png)
![image](https://user-images.githubusercontent.com/108418973/211076927-3e14420c-da1a-4c83-a922-f9feb2646bbb.png)
![image](https://user-images.githubusercontent.com/108418973/211077001-8a4aa18c-8ec8-4b47-b0b1-6b4c820eae84.png)

**Comment by gabrielmarinsaldaJT** [comment]
Mail enviado a Hotelbeds para consultarles

Desde nuestro lado, vemos que estamos interpretando bien el total del proveedor, por lo que no podemos hacer nada mas que reclamarles

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Esto nos informan desde el proveedor

![image.png](https://images.zenhubusercontent.com/6154b05d87ee2058afd73e2b/a5fc4496-b243-417e-a9a5-ee1fb8fa4707)

**Comment by RoDiaz1996** [comment]
Aja y en español? Que es rack ?
