### ISSUE TITLE
[adm] Modificar costos cupos 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#721]
### Descripcion del error

Hola chicos!
Desde el área de cupos, nos solicitan modificar los siguientes costos:

- [ ] https://adm.ebooking.com.ar/bookings/detail/63b58a89a764b7fa21013914?purchaseGroupId=457269#heading_63b58a89a764b7fa21013914
![image](https://user-images.githubusercontent.com/87333634/211377011-a40355f8-95d0-4f8b-b783-3d42c053b61b.png)
![image](https://user-images.githubusercontent.com/87333634/211377219-07c9467e-07cb-43a7-9743-35ca38148ac6.png)

- [ ] https://adm.ebooking.com.ar/bookings/detail/63ab600df6636c1036c6bb55?purchaseGroupId=455493#heading_63ab600df6636c1036c6bb55
![image](https://user-images.githubusercontent.com/87333634/211377117-9cafb6ea-3ca6-4c17-aa8c-f78264dea080.png)
![image](https://user-images.githubusercontent.com/87333634/211377187-13e7c487-33d4-4015-9f51-2a54fa1db5d9.png)

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Mismo caso que el issue #600

**Comment by mvalentinalucero** [comment]
Hola Gabi, lo que necesita el vendedor es que el cuadro tarifario quede exactamente como compartimos en las capturas de pantalla.

**Comment by mvalentinalucero** [comment]
![image](https://user-images.githubusercontent.com/98116205/213789952-3b7c7755-cca1-4aa4-93a5-f56e059c2feb.png)

**Comment by JuanBachmann** [comment]
Chicos
Sumo otro caso en el que necesitamos modificar el cuadro tarifario

https://adm.ebooking.com.ar/bookings/detail/63d810bc8d46b0e871fc448c?purchaseGroupId=463974#heading_63d810bc8d46b0e871fc448c

Localizador: 1282254 // Voucher: X364239

![image](https://user-images.githubusercontent.com/88722251/215855816-c780637f-d561-4ee0-bd43-432519a8ffa8.png)


Gracias!

**Comment by mvalentinalucero** [comment]
Chicos buenas tardes, sumo otro caso LOC: 1289718

![image](https://user-images.githubusercontent.com/98116205/217043698-487e5bab-ca74-4279-a2d4-6eff72a11270.png)

**Comment by JuanBachmann** [comment]
Chicos

Sumamos otro caso:

Necesitamos editar esta reserva y su respectivo voucher.

Reserva: 1203154

Voucher: X305337


![image](https://user-images.githubusercontent.com/88722251/217632512-82f97c1f-607e-42cf-9305-73773b5c35ec.png)

Aguardamos.
Gracias.

**Comment by mvalentinalucero** [comment]
Chicos buenos dias, han podido ver esto? Desde producto nos estan consultando

**Comment by mvalentinalucero** [comment]
Chicos buenas tardes, agrego otro caso: VOUCHER  X387361

https://adm.ebooking.com.ar/bookings/detail/63f7985c447f3b63e45db8c0?purchaseGroupId=469836#heading_63f7985c447f3b63e45db8c0

![image](https://user-images.githubusercontent.com/98116205/221269438-43a0f983-b1b9-48cc-9232-08303af577ab.png)

**Comment by mvalentinalucero** [comment]
Chicos como estan? Sumo otras tres reservas que necesitan que su cuadro tarifario quede exactamente asi como paso debajo:

![image](https://user-images.githubusercontent.com/98116205/228039699-39f2d9c2-b917-43cb-b50a-92ee0cabbf18.png)

En las tres reservas debe quedar el mismo cuadro que pase arriba.

https://adm.ebooking.com.ar/bookings/detail/637cc4b9172e3997094ece27?purchaseGroupId=447430#heading_637cc4b9172e3997094ece27

https://adm.ebooking.com.ar/bookings/detail/6372a9d5885f503a180f0a0a?purchaseGroupId=445579#heading_6372a9d5885f503a180f0a0a

https://adm.ebooking.com.ar/bookings/detail/636a5682c972f94f1943b98a?purchaseGroupId=443842#heading_636a5682c972f94f1943b98a

**Comment by mvalentinalucero** [comment]
Chicos buenas tardes, 

Han podido ver esto?

**Comment by mvalentinalucero** [comment]
Chicos buenas tardes, han podido ver esto?

**Comment by mvalentinalucero** [comment]
Hola chicos, esto ya esta para cerrarse?

**Comment by gabrielmarinsaldaJT** [comment]
Hola Valen!!

La verdad no sè si puntualmente esto està listo
Pero hemos modificado tanto el tema de Cupos que es probable que este error ya no exista, se haya cambiado por otro y estè solucionado

Yo la cierro, en caso de que suceda algo similar, abrimos otra issue, les parece?

Saludos
