### ISSUE TITLE
[DISNEY] No se puede reservar la atracción Disneyland Paris Express

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#722]
### Descripcion del error

¡Hola chicos! Tenemos un inconveniente con la atracción **Disneyland Paris Express: A Magical Day in Disneyland from Paris**, cuando se intenta reservar queda en error. 

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/211823808-25db4bf6-cf62-42fb-ae18-09fb6bcd58b2.png)
https://adm.ebooking.com.ar/bookings/detail/63976a9ed9331b48f20993b8?purchaseGroupId=452130#heading_63976a9ed9331b48f20993b8

![image](https://user-images.githubusercontent.com/108418973/211823891-9a4d2066-e480-490e-bab0-e8f33dba87d9.png)
https://adm.ebooking.com.ar/bookings/detail/639b2045b374c7ec292d378a?purchaseGroupId=452931#heading_639b2045b374c7ec292d378a

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/63976a9ed9331b48f20993b8?purchaseGroupId=452130#heading_63976a9ed9331b48f20993b8

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
En la próxima publi lo veran reflejado!
