### ISSUE TITLE
[PÁGINA BLANCA] Error en el registro

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#723]
### Descripcion del error

¡Hola! Tenemos un inconveniente con la agencia Corradi Viajes, la cual contrata el servicio de página blanca. Cuando se registra un cliente en la página de Corradi Viajes llega un mail a mail [info.ebooking@juantoselli.com](mailto:info.ebooking@juantoselli.com) y debería llegar a nuestro mail [atencion.plataformas@juantoselli.com](mailto:atencion.plataformas@juantoselli.com).

Por otro lado, en el administrador queda registrada como una agencia nueva sin ser relacionada con la agencia Corradi Viajes.

Gracias :blush

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/211880663-f8d656a0-5d51-4b93-bda2-ad4187e44ba3.png)
![image](https://user-images.githubusercontent.com/108418973/211880755-09fa55f6-2739-44dd-86b0-453ce5e78607.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/agencies/edit/63beb026c3708218da5f2445

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado!

Lo del tema de que se registra una nueva agencia, es porque los test que generan ustedes tienen otros datos de facturación, por lo que son clientes diferentes

Si quieren agregarle uno nuevo a Corradi Viajes, deben poner el mismo CUIT que tiene la empresa

![image.png](https://images.zenhubusercontent.com/6154b05d87ee2058afd73e2b/0d02ac7e-d110-46a3-972b-2dd0ccad7975)
