### ISSUE TITLE
[ebookig] Mytrasnfergroup

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#727]
### Descripcion del error

Hola chicos!
Podrán revisar si esta correcta la credenciales de Mytransfergroup? Por lo que vi, no se encuentra mas en el ebooking, y aquellas tomadas tiempo atras, no las podemos cancelar.
Desde el proveedor nos consultan si hay algun problema desde nuestro lado.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by GuadaVivas** [comment]
Hola chicos!
Alguna novedad?

**Comment by GuadaVivas** [comment]
alguna novedad?

**Comment by gabrielmarinsaldaJT** [comment]
Hola chicos

Se cambió la API de integración y desp de esto quedó funcionando

Entré a revisar pero se cayó de nuevo!!! 😢 

Apenas lo vean ellos les avisamos

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Hola @PatricioH96 te dejo los detalles del caso

El provider cambió la API hace 1 mes y ya lo solucionamos, pero parece ser que se cayó de nuevo

Adjunto logs para que les envíes de unas pruebas que realizé. Es importante enviarlos HOY porque sino se van a eliminar de la base de datos Live

https://adm.ebooking.com.ar/serviceLogs/edit/6435714be70b017d17d1c37f

Enviarles mails a

- andres@polittan.com
- gortiz@mytransfergroup.com
- julio@polittan.com
- angela@polittan.com
