### ISSUE TITLE
[adm] Modificar propiedades

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#728]
### Descripcion del error

Hola chicos
Necesitamos por favor, modificar las siguientes propiedades, por reubicación:

- [x] https://adm.ebooking.com.ar/bookings/detail/63bd95dd356a506d9f84e9bd?purchaseGroupId=458916#heading_63bd95dd356a506d9f84e9bd 

Hotel: Pousada Vila PortuguesaDirección: , R. Serigado, 20 - Centro, Bombinhas - SC, 88215-000, Brazil

- [x] https://adm.ebooking.com.ar/bookings/detail/6317833dcb4d716d9440d05e?purchaseGroupId=420877#heading_6317833dcb4d716d9440d05e

New Hotel Name: Millennium Broadway Times SquareNew Hotel Adress: New York. Address, 145 West 44th Street, New York, 10036

gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by BelenBidondo** [comment]
Hola chicos, aguardamos las modificaciones, una de las reservas hace check in el 28/01

**Comment by BelenBidondo** [comment]
Pudieron ver esto?

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, el primero está listo

El segundo no lo encuentro

Podrían pasarme un link de búsqueda de ejemplo en eBooking de ese hotel? No importa ni fecha ni nada, sólo encuéntrenlo en eBooking y avisennos

**Comment by BelenBidondo** [comment]
> Millennium Broadway

Gabi te dejo link de eBooking

https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca9435486315a56f0d56909/millennium-hotel-broadway-times-square-new-york--usa?checkIn=2023-02-16&checkOut=2023-02-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/103128819/215858856-9afec79d-4fa4-43e6-9940-f65ac6424176.png)

**Comment by BelenBidondo** [comment]
Hola chicos, agregamos otra reserva para modificar la propiedad y el suplemento, voucher X373646 (hacen check in el 19/02)

https://adm.ebooking.com.ar/bookings/detail/63dd645a614ad693ca8a0b23?purchaseGroupId=465271#heading_63dd645a614ad693ca8a0b23

Nuevo hotel: 
![image](https://user-images.githubusercontent.com/103128819/218500236-f66c642b-a82a-460c-80c7-ada66a057317.png)

Suplemento: Bed & breakfast

**Comment by BelenBidondo** [comment]
Hola! aguardamos estas modificaciones

**Comment by BelenBidondo** [comment]
chicos pudieron ver esto?

**Comment by gabrielmarinsaldaJT** [comment]
Done!
