### ISSUE TITLE
[adm] Modificar edad

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#730]
### Descripcion del error

Hola chicos!
Modificar por favor, edad de niño a 16
Gracias

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6376c1b9244f0a773ca102d6?purchaseGroupId=446597#heading_6376c1b9244f0a773ca102d6

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Done
