### ISSUE TITLE
[ASISTENCIAS] Error al tomar cupo

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#733]
### Descripcion del error

Hola chicos,
Creo una nueva issue sobre las asistencias de Universal Assitance de los cupos porque aparece todo ok en el ADM, con el nombre de los pasajeros, pero el proveedor nos confirma que no se toman. Así que debemos tomarlas por aparte en Ebooking u offline.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/216092160-56cc4848-bfc5-453a-8479-a1e9fff0efb1.png)
![image](https://user-images.githubusercontent.com/108418973/216092320-90ed9134-d772-43c3-a0e2-48a92a3a8637.png)
![image](https://user-images.githubusercontent.com/108418973/216092560-66b43d20-554b-478e-8907-42f6b0fdbb19.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/63d7c18a2912d0ad5b13eb38?purchaseGroupId=463846#heading_63d7c18a2912d0ad5b13eb38

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
¡Hola!
La agencia tomó otro cupo y sigue el error

![image](https://user-images.githubusercontent.com/108418973/217618466-613ede5d-d5aa-4346-918c-e6d2bdca63e8.png)
https://adm.ebooking.com.ar/bookings/detail/63e24cb9e17100be7dfe30a6?purchaseGroupId=465980#heading_63e24cb9e17100be7dfe30a6

![image](https://user-images.githubusercontent.com/108418973/217618566-fe744392-7b57-4328-89ba-0af0c9affacc.png)

Espero su respuesta

**Comment by RoDiaz1996** [comment]
¡Hola chicos! ¿Pudieron ver esto?

**Comment by gabrielmarinsaldaJT** [comment]
Solucionado por @MatiFrencia hace muuuuuucho

**Comment by RoDiaz1996** [comment]
Hola! ¿Seguros que está solucioando? Una agencia tomó un cupo el 8 de marzo y no se tomó la asistencia, tuve que pedirla offline.

![image](https://user-images.githubusercontent.com/108418973/233162236-7827843c-795f-4966-8c1e-eb2a1866f221.png)
![image](https://user-images.githubusercontent.com/108418973/233162986-a9d6f9f5-b777-4aad-af12-42ea2a396f5e.png)
![image](https://user-images.githubusercontent.com/108418973/233163076-d63ae68a-7eef-41a0-8178-02af52ebdbb9.png)

**Comment by RoDiaz1996** [comment]
Holiii

**Comment by RoDiaz1996** [comment]
¡Hola! ¿pudieron ver este tema?

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Saludos,
Abraham
