### ISSUE TITLE
[AGREGAR USUARIO] Mail y contraseña juntos

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#734]
### Idea a implementar

Buenos días chicos, 

Tenemos una sugerencia, cuando las agencias agregan un nuevo usuario deben poner el mail y en la siguiente página ingresar la contraseña. Esto es confuso para algunas porque nos escriben solicitando registrar una contraseña. Estaría bueno que al lado de dónde se pide el mail, se pida una contraseña.

![image](https://user-images.githubusercontent.com/108418973/216094755-02f200db-3efa-4db6-a06d-87e38884f7dd.png)
https://travel.tosellitours.com/#/mi-cuenta/mis-usuarios/agregar

![image](https://user-images.githubusercontent.com/108418973/216094828-bb5e99a0-b68b-4e28-a2a9-08e34fc9361f.png)
https://www.ebooking.com.ar/#/mi-cuenta/mis-usuarios/agregar

![image](https://user-images.githubusercontent.com/108418973/216094897-3864c389-de9d-4904-b02b-b128ca34d0aa.png)

Gracias 😊

**Comment by abrahamfariaz** [comment]
Hola,
¿Alguna novedad de esta sugerencia?
Saludos,
Abraham
