### ISSUE TITLE
[AEREOS] Equipaje

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#735]
### Descripcion del error

¡Hola! 

Nos notificaron un error, cuando tomás un vuelo en Ebooking dice que incluye una valija por adulto y desde aéreos les confirmaron que no incluye equipaje en bodega.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/216127031-e6d3118f-b36a-4035-a94d-886643b58f23.png)
![image](https://user-images.githubusercontent.com/108418973/216127495-86a99beb-6dee-4872-af7f-52e3ebdbc59b.png)
![image](https://user-images.githubusercontent.com/108418973/216127578-4678a7b2-3379-450a-b95f-96f9f1751192.png)
https://www.ebooking.com.ar/#/vuelos/buscar?flightType=1&classPref=Y&segments=2023-05-07!!EZE!MAD&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/vuelos/buscar?flightType=1&classPref=Y&segments=2023-05-07!!EZE!MAD&flex=false&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by CandelaMontes** [comment]
Hola!
Han visto algo de esto? Se debe a algún tipo de error en la integración?
Quedo atenta!

**Comment by CandelaMontes** [comment]
Hola!
Han visto algo de esto? Se debe a algún tipo de error en la integración?
Quedo atenta!

**Comment by gabrielmarinsaldaJT** [comment]
Hola! Ese equipaje que aparece ahi es el ícono del equipaje de mano

El de bodega tiene la forma de una valija

Saludos!
