### ISSUE TITLE
[ALOJAMIENTOS] Tayrona: Error hoteles

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#737]
### Descripcion del error

¡Buen día!

Tenemos un inconveniente con el destino Tayrona, Colombia. En primer lugar no se puede seleccionar el destino en el desplegable para ver todos los alojamientos en lista y comparar las tarifas. Por otro lado, todos los alojamientos no muestran disponibilidad o dan error.

Credenciales:
Juan Toselli: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com) | Junio2022
Toselli Tours: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/217545180-c87227a6-6996-4e01-934f-ceeefc1cb534.png)
https://www.juantoselli.com/#/alojamiento/disponibilidad/5ca8cc1d86315a56f0c1072d/cabanas-arrecife-tayrona-santa-marta--colombia?checkIn=2023-03-10&checkOut=2023-03-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/108418973/217545316-154616a8-eb45-4b06-9be0-e393832f61a3.png)
https://ebooking.com.ar/#/alojamiento/disponibilidad/5dd8b12bbefb76dbcf0aa3cd/tayrona-angel-lodge-santa-marta--colombia?checkIn=2023-04-10&checkOut=2023-04-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/108418973/217545415-1982bc5c-7811-4814-b871-c98659ea900d.png)
https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca8c93f86315a56f0bfbb97/hotel-tayrona-santa-marta--colombia?checkIn=2023-03-20&checkOut=2023-03-27&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Link al error y/o Localizador

https://travel.tosellitours.com/#/alojamiento/disponibilidad/5ca8c93f86315a56f0bfbb97/hotel-tayrona-santa-marta--colombia?checkIn=2023-03-20&checkOut=2023-03-27&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Hola Ro!

Un tema que lo habiamos charlado hace un tiempo

El destino Tayrona no existe como tal, ya que el lugar donde está ubicado este parque nacional es Santa Marta, Magdalena, Colombia
Si buscan ahí, obtendrán lugares cercanos a este parque nacional
De igual manera, puedo inventarles un polígono para que tengan resultados al buscar Tayrona, pero no es correcto hacer esto y puede generarnos problemas

Sobre los hoteles, ahora reviso mapeos, pero puede ser que ningún provider devuelva Avail

Saludos!

**Comment by gabrielmarinsaldaJT** [comment]
Bien, ahí les aparecerá el lugar como Tayrona
![image.png](https://images.zenhubusercontent.com/6154b05d87ee2058afd73e2b/9133f49b-6ba8-4950-9a14-a491a414edfb)

**Comment by gabrielmarinsaldaJT** [comment]
Por otro lado, esos hoteles están mapeados sólamente con proveedores que casi no dan disponibilidad y otros que no se usan en el eBooking pero si en el optimizer. Cualquier otra cosa me consultan

Saludos!
