### ISSUE TITLE
[adm] Agregar pasajero

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#744]
### Descripcion del error

Hola chicos!
Por favor, necesitamos agregar un adulto a la siguiente reserva, ya que no estamos pudiendo realizarlo 

- [x] https://adm.ebooking.com.ar/bookings/detail/6388d77bcc59aedb1b1fa8d1?purchaseGroupId=450348#heading_6388d77bcc59aedb1b1fa8d1

 **Faust, carlos Manfredo  23.894.704**

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6388d77bcc59aedb1b1fa8d1?purchaseGroupId=450348#heading_6388d77bcc59aedb1b1fa8d1

### Plataforma

.

**Comment by BelenBidondo** [comment]
Hola chicos, cuando puedan pueden ver esto para que podamos agregar los pasajeros nosotros?

**Comment by BelenBidondo** [comment]
chicos pudieron ver esto?

**Comment by gabrielmarinsaldaJT** [comment]
Listo!!
