### ISSUE TITLE
[adm] Enteprise

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#748]
### Descripcion del error

Hola chicos!
Estamos teniendo un error, en el que nuestro adm, no muestra las oficinas de retiro ni devolucion, ademas tampoco se refleja en nuestro voucher.
Cuando mandamos a consultar al proveedor, ellos si la tienen correcta, pero por algun error no estamos pudiendo mostrarlo:
![image](https://user-images.githubusercontent.com/87333634/225429652-9b7b5914-f338-407c-bc9b-e948a590de8a.png)

![image](https://user-images.githubusercontent.com/87333634/225429763-50a76cd6-9536-49ae-b12a-47736381098b.png)

![image](https://user-images.githubusercontent.com/87333634/225429943-f2d26e2e-b04d-4608-9bec-f02cf7c88655.png)

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6410c41d7d4bb9b1cfa99b02?purchaseGroupId=475319#heading_6410c41d7d4bb9b1cfa99b02

### Plataforma

.

**Comment by mvalentinalucero** [comment]
Chicos, sumo otro caso donde figura vacio el apartado de oficina de retiro y devolucion

1646954896COUNT 

https://adm.ebooking.com.ar/bookings/detail/640f457b2946b8de3e588bc1?purchaseGroupId=474911#heading_640f457b2946b8de3e588bc1

![image](https://user-images.githubusercontent.com/98116205/225727893-f2ed674a-f6d4-4913-8571-4dd368883745.png)

**Comment by gabrielmarinsaldaJT** [comment]
Listos ambos!
