### ISSUE TITLE
[adm] Direcciòn

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#757]
### Descripcion del error

Hola chicos!
Podrán agregar la siguiente dirección en la reserva?
Iberostar Las Letras Gran Via - Dirección C/ Gran Vía 11, 28013 Madrid, España

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/63fe40df51066a9e3bb73041?purchaseGroupId=471260#heading_63fe40df51066a9e3bb73041

### Plataforma

.

**Comment by gabrielmarinsaldaJT** [comment]
Hola!

Listo

Es un caso especial, por eso lo hacemos
Pero la info incompleta que sale es como la devuelve el proveedor, no podemos hacer mucho al respecto

Saludos
