### ISSUE TITLE
[ALOJAMIENTO] No aparece Hotel

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#766]
### Descripcion del error

Hola chicos, 

Les consulto porque reservo el hotel _The Gate Hotel_ en Florencia, Italia y cuando quiero reservar el traslado no me aparece para seleccionarlo. También, probé buscando el hotel directamente en la pestaña alojamientos y no aparece. ¿Saben que puede ser?

Credenciales:
Usuario: agenciadeprueba@juantoselli.com
Contraseña: Junio2022

Gracias 😊 

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/233159703-2e58d224-91bd-477c-9e02-f756e8ab985f.png)
https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca9ff2186315a56f0e3c516/the-gate-hotel?checkIn=2023-08-10&checkOut=2023-08-15&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/108418973/233159791-f029f140-cbf5-48d6-880a-c96fb6fbedc5.png)
https://ebooking.com.ar/#/alojamiento

![image](https://user-images.githubusercontent.com/108418973/233159852-f10f92fa-c621-4641-bdef-039e5df68ac6.png)
https://ebooking.com.ar/#/traslados

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
Hola chicos, ¿Pudieron ver este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Solved


Busquenlo como "The gate hotel florencia"
![image](https://github.com/toselli/issues/assets/26115345/dec6cfce-e9fc-44b6-a769-6946e0b47161)
