### ISSUE TITLE
[ATRACCIONES] Cirque Du Soleil por Action

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#767]
### Descripcion del error

¡Hola chicos!

Tenemos otro inconveniente con Action, en las atracciones no aparece para _Cirque Du Soleil_. Aparece solamente con el proveedor Viator.

Credenciales:
Usuario: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com)
Contraseña: Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/233166679-d7ce37af-c61e-4813-9a64-41ad94cc5232.png)
![image](https://user-images.githubusercontent.com/108418973/233166792-be2fc293-2d24-4dc7-85a6-d785efdac994.png)

https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5a21b157fc2d560873053fdc&destinationName=las-vegas-y-sus-alrededores-nevada--estados-unidos&fromDate=2023-07-01&toDate=2023-07-09&nationality=AR&residence=AR&occupancies=3*30,30,30*0*&disney=false&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5a21b157fc2d560873053fdc&destinationName=las-vegas-y-sus-alrededores-nevada--estados-unidos&fromDate=2023-07-01&toDate=2023-07-09&nationality=AR&residence=AR&occupancies=3*30,30,30*0*&disney=false&currency=USD

### Plataforma

Google Chrome

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Saludos,
Abraham
