### ISSUE TITLE
ERROR BUSQUEDA [ATRACCIONES]

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#77]
Estimados,
Vendedora esta intentando tomar un Big Bus en Miami, el tkt deluxe, y no le deja tomarlo porque le da con gastos desde 2020.

Indica que:
¨Me resulta muy raro porque es un servicio de lo mas común, que no suele tener gastos hasta unos días antes.¨

Adjuntamos link de búsqueda:

https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5a21b153fc2d560873053f72&destinationName=miami-y-sus-alrededores-florida--estados-unidos&fromDate=2021-11-08&toDate=2021-11-09&nationality=AR&residence=AR&occupancies=1*30*0*&disney=false&currency=USD

**Comment by julianbenegaslane** [comment]
Es el comportamiento esperado;
> Este servicio está sujeto a un cargo por cancelación del 100% (no reembolsable) para todas las cancelaciones recibidas una vez reservado el mismo.

Se agrega este detalle en pagina de checkout.
