### ISSUE TITLE
[TRASLADOS] No se puede tomar traslado

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#776]
### Descripcion del error

¡Hola chicos!

Estaba intentando tomar un traslado **desde el aeropuerto de Dublín al hotel GLASHAUS** y que queda en error.
Les dejo las imágenes de la reserva y el link de búsqueda.

Credenciales:
Usuario: [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com)
Contraseña: Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/234669410-9f6dadb5-b9fb-4da9-ace6-e53af9c15f22.png)
https://adm.ebooking.com.ar/bookings/detail/64496b418c3472322ffe9b56?purchaseGroupId=486157#heading_64496b418c3472322ffe9b56

![image](https://user-images.githubusercontent.com/108418973/234669678-23e9a532-89f9-4eb4-a1c6-d4ce7fa41e4e.png)

### Link al error y/o Localizador

https://ebooking.com.ar/#/traslados/buscar?transferType=1&landingTime=false&arrivalDate=2023-09-10&arrivalTime=10:00&arrivalPointDataId=DUB&arrivalPointDataName=dublin-ireland-dub&arrivalPointDataSmartSearchEnum=3&departureDate=2023-09-15&departureTime=10:00&destinationPointDataId=5ca8c80f86315a56f0bf1d16&destinationPointDataName=glashaus-hotel-tallaght--eire-ireland&destinationPointDataSmartSearchEnum=1&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
Hola chicos, ¿Pudieron ver este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Hola!

Error por parte del proveedor, no hay nada que podamos hacer
