### ISSUE TITLE
[TRASLADOS] No trae disponibilidad

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#780]
### Descripcion del error

¡Hola chicos!

Noté en la pestaña de traslados que no hay disponibilidad en Berlín. Busco con el código IATA, BER, y aparece "Berlin". Me dice que hay un error y en la página de Mozio si me aparece disponibilidad.

Credenciales:
Usuario: agenciadeprueba@tosellitours.com | agenciadeprueba@juantoselli.com
Contraseña: Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://user-images.githubusercontent.com/108418973/235946250-6d893fd4-5eb0-4241-9ac7-76140ae90a90.png)
![image](https://user-images.githubusercontent.com/108418973/235946710-9643e944-5c16-40f0-8776-6f5eb6181f9c.png)
https://www.ebooking.com.ar/#/traslados/buscar?transferType=1&landingTime=false&arrivalDate=2023-10-17&arrivalTime=12:15&arrivalPointDataId=BER&arrivalPointDataName=berlin&arrivalPointDataSmartSearchEnum=3&departureDate=2023-10-21&departureTime=16:05&destinationPointDataId=60d6cf507607b5163bbd4e31&destinationPointDataName=sunflower-hostel-berlin-berlim-&destinationPointDataSmartSearchEnum=1&nationality=AR&residence=AR&occupancies=1*30*0*&currency=USD

![image](https://user-images.githubusercontent.com/108418973/235947296-9f2484a5-4ca6-4c4b-8370-31912a5cf5d8.png)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/traslados/buscar?transferType=1&landingTime=false&arrivalDate=2023-10-17&arrivalTime=12:15&arrivalPointDataId=BER&arrivalPointDataName=berlin&arrivalPointDataSmartSearchEnum=3&departureDate=2023-10-21&departureTime=16:05&destinationPointDataId=60d6cf507607b5163bbd4e31&destinationPointDataName=sunflower-hostel-berlin-berlim-&destinationPointDataSmartSearchEnum=1&nationality=AR&residence=AR&occupancies=1*30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
Hola chicos, ¿Pudieron ver este tema?

**Comment by gabrielmarinsaldaJT** [comment]
Listo!

El airport no tenía una Location válida
