### ISSUE TITLE
[MOZIO] Agregar leyenda de reprogramación

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#783]
### Idea a implementar

Buenos días chicos,

Una vendedora nos informa que tenía una reserva con Mozio, los pax iban a llegar más tarde y ellos no le permitieron reprogramar el traslado porque toda repro, según lo que indican, tiene que ser hasta 24 hs antes. 
En los vouchers no está esa información, sólo se especifica lo que se ve en la siguiente imagen. ¿Se puede agregar?

![image](https://github.com/toselli/issues/assets/108418973/d87c10c1-80c5-4ed4-9a32-514886e3c889)

Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Que mensaje quieren agregar? Me lo podrían pasar exactamente como quieren que salga?

**Comment by RoDiaz1996** [comment]
Que diga "Toda reprogramación debe realizarse mínimo 24 horas antes del inicio del servicio"

**Comment by RoDiaz1996** [comment]
Hola! Se puede agregar esto?

**Comment by abrahamfariaz** [comment]
Buenas tardes,
Alguna novedad?
Gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Muchas gracias,
Abraham

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Gracias,
Abraham

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?

**Comment by abrahamfariaz** [comment]
Buenos días,
¿Alguna novedad?
Gracias
