### ISSUE TITLE
[ATRACCIONES] Se repiten atracciones

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#784]
### Descripcion del error

¡Hola chicos!

Tenemos un inconveniente en la pestaña atracciones. Hice la búsqueda en Venecia y aparecen las atracciones _"Leyendas de Triana, Tour a Pie"_ y _"Sevilla Encantada: Misterios y Leyendas"_ repetidas varias veces con la misma información.

Credenciales:
Usuario: agenciadeprueba@tosellitours.com | agenciadeprueba@juantoselli.com
Contraseña: Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://github.com/toselli/issues/assets/108418973/282b03b4-b0f4-4b48-a35c-aeae6b683f55)
![image](https://github.com/toselli/issues/assets/108418973/d2ce9eb7-9a05-4bc3-aa95-21b6f456545b)

### Link al error y/o Localizador

https://travel.tosellitours.com/#/atracciones/buscar?destinationId=5a21ab4bfc2d56087302000e&destinationName=venecia-veneto--italia&fromDate=2023-09-12&toDate=2023-09-19&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
Hola! Pudieron ver esto?

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad de este caso?
Muchas gracias!
