### ISSUE TITLE
[ALOJAMIENTOS] Error en tarifa

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#791]
### Descripcion del error

Hola chicos,

Encontré un inconveniente en el hotel **Dolce CampoReal Lisboa** no coinciden las tarifas. Les dejo las imágenes de Ebooking y de la página del hotel.

Credenciales:
Usuario: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com)
Contraseña: Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://github.com/toselli/issues/assets/108418973/49f7fae0-8cb9-42fc-b703-c053b78a9e62)
![image](https://github.com/toselli/issues/assets/108418973/4cb27089-cfb0-41a9-a314-49bd1d07ff85)
https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca8ed0086315a56f0c98bab/dolce-camporeal-lisboa?checkIn=2023-10-10&checkOut=2023-10-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

![image](https://github.com/toselli/issues/assets/108418973/d008ca75-ecca-4f57-b4b7-46b8f71dbcc4)
https://be-p2.synxis.com/?NCK=organic&_ga=2.261885704.482965497.1684936439-315037978.1684936439&_gl=1*1qff361*_ga*MzE1MDM3OTc4LjE2ODQ5MzY0Mzk.*_ga_LDTQ9PXJSG*MTY4NDkzNjQzOS4xLjEuMTY4NDkzNjUzMC42MC4wLjA.&adult=2&arrive=2023-10-10&chain=5136&child=0&currency=USD&depart=2023-10-17&hotel=81431&level=hotel&locale=en-GB&rooms=1&src=SBE

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca8ed0086315a56f0c98bab/dolce-camporeal-lisboa?checkIn=2023-10-10&checkOut=2023-10-17&nationality=AR&residence=AR&occupancies=2*30,30*0*&currency=USD

### Plataforma

Google Chrome

**Comment by RoDiaz1996** [comment]
Hola! Pudieron ver esto?

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Gracias
