### ISSUE TITLE
[ATRACCIONES] No se puede tomar atracción de Universal

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#793]
### Descripcion del error

¡Hola!

Nos comunica un vendedor que no puede tomar una excursión de universal, le sale error al tocar la opción para agregar al carrito.

Credenciales:
Usuario: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com)
Contraseña: Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://github.com/toselli/issues/assets/108418973/f9f47594-34d4-41a4-88a3-b2f33925f42f)
![image](https://github.com/toselli/issues/assets/108418973/f99d5491-24b2-4fdd-8722-1c4a7650379d)

### Link al error y/o Localizador

https://www.juantoselli.com/#/atracciones/buscar?destinationId=5aa7dd3f3dfcee50fc39c792&destinationName=orlando-y-sus-alrededores-florida--estados-unidos&fromDate=2023-07-22&toDate=2023-07-23&nationality=AR&residence=AR&occupancies=3*30,30,30*0*&disney=false&currency=USD

### Plataforma

Google Chrome

**Comment by abrahamfariaz** [comment]
Buenas tardes,
Agrego otros 2 casos a este pedido:
- [Link 1](https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5aa7dd3f3dfcee50fc39c792&destinationName=orlando-florida&fromDate=2023-09-21&toDate=2023-09-23&nationality=AR&residence=AR&occupancies=1*30*1*10&disney=true&currency=USD)
- Imagen 1
![image](https://github.com/toselli/issues/assets/40358708/b32ddd1a-78c5-4814-9f7c-465060e4ee92)
- [Link 2](https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5aa7dd3f3dfcee50fc39c792&destinationName=orlando-y-sus-alrededores-florida-estados-unidos&fromDate=2023-09-25&toDate=2023-09-29&nationality=AR&residence=AR&occupancies=1*30*1*10&disney=false&currency=USD)
- Imagen 2
![image](https://github.com/toselli/issues/assets/40358708/017b6c66-d4ac-4208-b68b-2cdddbcdf2b4)
Todos están fallando al tomar
¿Podrán ayudarnos?

**Comment by abrahamfariaz** [comment]
Buenas tardes,
Aguardamos respuesta!
Saludos,
Abraham

**Comment by abrahamfariaz** [comment]
Hola,
Tienen alguna novedad de este caso?
Saludos,
Abraham

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?

**Comment by abrahamfariaz** [comment]
Ya funciona.
