### ISSUE TITLE
[ASISTENCIAS] Tarifa en 0

### ISSUE THREAD

**Issue by RoDiaz1996** [toselli/issues#795]
### Descripcion del error

Hola chicos,

Nos informa un vendedor que aparece la tarifa de Assist Card en 0.

Credenciales:
Usuario: [agenciadeprueba@tosellitours.com](mailto:agenciadeprueba@tosellitours.com) | [agenciadeprueba@juantoselli.com](mailto:agenciadeprueba@juantoselli.com)
Contraseña: Junio2022

Gracias 😊

### Paso a paso para reproducir el error

.

### Captura del error

![image](https://github.com/toselli/issues/assets/108418973/51166f4a-be5f-4b56-bfc8-ecc724dc9cc7)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/asistencias/buscar?arrivalDate=2023-06-30&departureDate=2023-08-10&origin=AR&destination=Centro%20america-Caribe&travelType=Un%20viaje&nationality=AR&residence=AR&occupancies=2*62,58*0*&currency=USD

### Plataforma

Google Chrome

**Comment by abrahamfariaz** [comment]
Buenas tardes,
Alguna novedad?
Muchas gracias
