### ISSUE TITLE
Localizador 9188134855537 discrepancia comisión

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#8]
Estimados buenas tardes,

Consulta de la vendedora:
![image](https://user-images.githubusercontent.com/45457355/124972383-a9e65b00-e000-11eb-8c96-85e1c61ee55d.png)

Les quiero realizar una consulta respecto a la reserva 9188134855537 dado que tengo dudas respecto a las tarifas que se muestran.

Al tomar el total comisionable (245.54 USD) y multiplicarlo por 0.8 obtengo un costo de 196.4 USD y no coincide con el costo (subtotal) actual de 206.25 USD. La diferencia es de 9.9 USD que coincide con el monto Gravado. ¿Me pueden por favor explicar qué sucede? ¿Hay algo que no esté viendo?

URL RESERVA 

https://adm.ebooking.com.ar/bookings/detail/60d21e4ce93cba68516ea6b1?purchaseGroupId=356890#heading_60d21e4ce93cba68516ea6b1

**Comment by barkergabe** [comment]
Yo quiero agregar otra cosa.
https://adm.tosellitours.com/bookings/detail/60e732bdbe7e93b778305b2a?purchaseGroupId=357697#heading_60e732bdbe7e93b778305b2a
En ese grupo de reservas.
Tenemos unas reservas para una mayorista donde le estamos dando el 20%
Pero a su vez tenemos un 3% extra de comision mas el 2% de gasto de Gestion.
Entonces razon por la que la comision es tan pequeña es por que a nosotros expedia nos da la comision sobre la tarifa que en este ejemplo es Usd 1481 por cada reserva.
Pero nosotros damos la comision del 20% sobre el total, es decir los 1481 + los 260.
Entonces esa comision extra que damos nosotros en relacion a lo que nos liquida expedia, es lo que nos come el extra mark up a nosotros. Se entiende?
Tenemos que ver de resolver eso. Donde la comision que nosotros damos es SIEMPRE sobre la tarifa y no tener en cuenta los impuestos.

**Comment by moliveto** [comment]
Sobre la primera reserva

![image](https://user-images.githubusercontent.com/1890103/124980919-57f70280-e00b-11eb-8721-5b83bb1521f1.png)

**Comment by moliveto** [comment]
Sobre la 2da reserva:

![image](https://user-images.githubusercontent.com/1890103/124984883-20d72000-e010-11eb-984d-25d2af768763.png)

**Comment by moliveto** [comment]
[Expedia calculo de comision.xlsx](https://github.com/toselli/issues/files/6787053/Expedia.calculo.de.comision.xlsx)

**Comment by barkergabe** [comment]
Claro Marce.
Pero el GrossProffit va por fuera. Es como la optimizacion
es algo que no va para los vendedores.
No lo podemos tener en cuenta.
Vos estas tomando ese dato cuando en realidad NUNCA existio. Es algo extra.
Como puede ser que esa reserva, Dando un 20% y recargando 16 % mas un 3% mas un 2% (21% total) deberiamos tener por lo menos 1%.... pero no llegamos ni a eso... por eso digo que hay algo que esta mal. Como que algo cambio
Y como te digo el .84 no se por que esta asi, ya que yo siempre puse que al menos cubrieramos el costo de LATAM que es el 17%... entonces como maximo tendria que ser .83.
Bueno, cuando puedas lo vemos.
Gracias por la explicacion, pero sigamos investigando por que evidentemente algo lago que no esta bien.
Abrazo!!

**Comment by gabrielmarinsaldaJT** [comment]
Hola a todos

Se puede cerrar esta issue?

Saludos
