### ISSUE TITLE
DISPONIBILIDAD [IBEROSTAR]

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#80]
Estimados buenas tardes,
Walter indica que no haya disponibilidad con tarifas especiales que debería traer Iberostar, adjunto cap:
![image](https://user-images.githubusercontent.com/45457355/131183080-1bc27b01-bff4-4b71-b392-9d20ca92bb1b.png)
Adjunto link:
https://www.ebooking.com.ar/#/alojamiento/disponibilidad/5ca8d5ac86315a56f0c4360f/iberostar-dominicana?checkIn=2022-05-14&checkOut=2022-05-19&nationality=AR&residence=AR&occupancies=3*30,30,30*0*&currency=USD

**Comment by JuanCruzMedina** [comment]
Se revisó en el proveedor y no está llegando el descuento informado en ninguno de los campos. Se solicita enviar el mail o la información de  la promoción en donde se informaba el tipo de oferta y la validez de la misma (IMPORTANTE conocer el período).
Se enviará un correo al proveedor preguntando la vía y formato el cual enviaran la oferta.

**Comment by JuanCruzMedina** [comment]
Se envió un correo a iberostar notificando que no estaba llegando el descuento.

**Comment by Jlavign** [comment]
Juan Cruz buenas tardes, tenes novedades sobre Iberostar y la disponibilidad con los descuentos solicitados?
