### ISSUE TITLE
ERROR DISPO [RENTAS VACACIONALES]

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#81]
Estimados buenos días,
No se encuentra disponibilidad en Rentas Vacacionales, 
Adjunto búsqueda realizada y pedido del vendedor:

https://www.ebooking.com.ar/#/casas/buscar?id=5a21b153fc2d560873053f72&name=miami-y-sus-alrededores-florida--estados-unidos&checkIn=2021-12-12&checkOut=2022-01-11&nationality=AR&residence=AR&occupancies=4*30,30,30,30*0*&currency=USD

![image](https://user-images.githubusercontent.com/45457355/131511806-0d911ff1-0d07-45ca-8c97-0fbd9066c11c.png)

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Hemos corregido la tarea de los datos estáticos de OceanBeds y la semana que viene debería mostrar dispo, ya que el finde corre la tarea correspondiente

De cualquier manera, la búsqueda por +30 días por lo general no trae resultados en ningún provider

Cierro issue porque no hay mas nada que hacer
