### ISSUE TITLE
Clientes no pueden autogestionar el alta de usuarios

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#813]
### Idea a implementar

Buenos días,
Los clientes no pueden completar la creación de usuarios por su cuenta debido a que la plataforma no toma la contraseña establecida. Sucede que pueden autogestionarse para crear dicho usuario pero les salta un error de contraseña incorrecta.
Pueden utilizar el usuario agenciadeprueba@juantoselli.com con contraseña 123456 e ir a MIS USUARIOS

![image](https://github.com/toselli/issues/assets/40358708/338df11d-0252-4688-b388-7b6c8ca406a1)

Crear un usuario

![image](https://github.com/toselli/issues/assets/40358708/d161e10c-bf0f-4464-9ec1-4232edc993e7)

E intentar ingresar, para poder verificar el error.

**Comment by MatiFrencia** [comment]
![image](https://github.com/toselli/issues/assets/88749621/fbcc2900-46b0-4767-8b26-5e6cc2158f33)
![image](https://github.com/toselli/issues/assets/88749621/db44e730-84e1-4da9-aab2-376ff0944467)
Yo entré con ese usuario y contraseña que me pasaste, probé agregar un usuario y me anduvo correctamente, agregué 2 usuarios de hecho.

Si te vuelve a pasar , probá cerrando sesion y volviendo a loguearte.

Saludos!!
