### ISSUE TITLE
[Administrador] Incorporar filtros para encontrar reservas emitidas en X período

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#815]
### Idea a implementar

Buenas tardes,
Al buscar reservas emitidas (cobradas) en X períodos, nos encontramos con que no podemos realizarlo por el Administrador, por lo que debemos recurrir al MongoDB.
Básicamente buscamos responder a la pregunta ¿Cuáles fueron las reservas emitidas desde el X hasta el X?
Pedimos por favor darle importancia a este pedido porque es una actividad que se realiza diariamente.
Gracias!

**Comment by gabrielmarinsaldaJT** [comment]
Hola @abrahamfariaz como va?

Consulta

Te referís a las fechas en que fue emitido el Voucher?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Agregado el filtro en el adm



![Image](https://github.com/toselli/issues/assets/26115345/291d37cf-48da-4590-be4c-7ec5faa419dc)


Un pequeño detalle: No usar el tag de hotfix, ya que ese lo usamos para casos donde un error no permite continuar con el uso del sistema y debe ser solucionado de manera urgente (Por eso tiene los fueguitos)
