### ISSUE TITLE
Consulta por oferta de RedTuristica

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#82]
Hola, equipo.

El proveedor RedTuristica me consulta si recibimos correctamente la oferta de ellos particularmente por el hotel THE TIDES CONDOMINIUM en el polígono HOLLYWOOD BEACH mediante la conexión XML.

Espero me puedan ayudar.
Gracias, desde ya.

Saludos,
Juan.

**Comment by gabrielmarinsaldaJT** [comment]
Estimados

Por favor no se olviden de adjuntar links de búsqueda / reservas en las issues

**Comment by gabrielmarinsaldaJT** [comment]
Cierro issue, no tengo fechas para buscar y tampoco tengo la cantidad de pasajeros
