### ISSUE TITLE
[COMING 2 TRANSFER] Reserva sin politica de vencimiento en jt mock

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#826]
### Descripcion del error

Reserva que notifico el payment del 12/4 a las 10 hs por una reserva que no muestra gastos de cancelación, es una reserva que estaba en revisar de coming2transfer con inicio de servicio 10/5 y finalización 12/4 (dia de la fecha), cuando doy getbooking pasa a confirmada. 

### Paso a paso para reproducir el error

payment
reserva en revisar jt mock

### Captura del error

![image](https://github.com/toselli/issues/assets/98116205/54dfc746-c979-4fca-8507-049c255f0c88)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6618dbe0ad4fe9d4dc05d756?purchaseGroupId=591499#heading_6618dbe0ad4fe9d4dc05d756

**Comment by gabrielmarinsaldaJT** [comment]
Chicos una consulta

La reserva está dentro del ADM de Coming2? Que politicas de cancelacion tiene ahi?

**Comment by PatricioH96** [comment]
Solucionado.
