### ISSUE TITLE
Alojamiento Action Travel (No estamos recibiendo parte del inventario del proveedor)

### ISSUE THREAD

**Issue by Rourke909** [toselli/issues#827]
### Descripcion del error

No estamos visualizando el tipo de habitacion **Large 2 Bedroom Suite - Partial Ocean View (1King/2Doubles)** 
la misma se encuentra disponible en **Action Travel** segun reportan, mientras que nosotros solo recibimos Suites de una room o habitaciones dobles.

### Paso a paso para reproducir el error

https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca901a586315a56f0cd10df/doubletree-resort---spa-by-hilton-hotel-ocean-point?checkIn=2024-07-01&checkOut=2024-07-10&nationality=AR&residence=AR&occupancies=2*30,30*2*10,14&currency=USD

Link de disponibilidad

### Captura del error

![image](https://github.com/toselli/issues/assets/143418128/26348e49-b0b0-45a6-9071-2cb2c5facf93)

### Link al error y/o Localizador

https://ebooking.com.ar/#/alojamiento/disponibilidad/5ca901a586315a56f0cd10df/doubletree-resort---spa-by-hilton-hotel-ocean-point?checkIn=2024-07-01&checkOut=2024-07-10&nationality=AR&residence=AR&occupancies=2*30,30*2*10,14&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Listo!
