### ISSUE TITLE
ERROR DISPO [CRUCEROS]

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#83]
Estimados buenos días,
Podrían verificar la disponibilidad proporcionada:
![image](https://user-images.githubusercontent.com/45457355/131855633-6917f38d-c77d-4aaa-b15d-26c3d09dca1e.png)
![image](https://user-images.githubusercontent.com/45457355/131855697-6e14f53e-3319-42da-b424-fec45581852b.png)
https://www.ebooking.com.ar/#/cruceros/detalle/612e8b73f71cdf3b0d565a72/612b4ca03978350841e403c2?currency=USD

**Comment by Jlavign** [comment]
Buenas tardes,
Tendrán novedades?

**Comment by Jlavign** [comment]
Buenas tardes,
Tendrán novedades?

**Comment by josecaserez** [comment]
Lo estuve revisando, viene pocas opciones de cabinas internas en la response y todas son descartadas por no adecuarse a la occupancy solicitada al incluir un niño. Las opciones solo permiten 2 o 4 pasajeros por cabina, siendo que otras explicitamente permiten 2, 3 o 4.
