### ISSUE TITLE
[RENTA DE VEHICULO/DOLLAR] No podemos visualizar la Jeep Compass (MIAMI)

### ISSUE THREAD

**Issue by IgnacioaguirreJT** [toselli/issues#830]
### Descripcion del error

Issue por gestión enviada el 7 de febrero de 2024, 
no podemos visualizar el vehiculo **Jeep Compass** para recoger en la oficina de MIAMI INTERNATIONAL AIRPORT
y devolverlo en la misma oficina.

Patricio, del equipo de sistemas, nos ha respondido en su momento que el proveedor no nos envia este producto,
en respuesta a la peticion que se le realizo, independientemente de esto, necesitamos actualizacion de este caso
para que el vendedor Leopoldo Gimenez pueda adquirir el servicio.

### Paso a paso para reproducir el error

Link de disponibilidad: https://www.juantoselli.com/#/autos/buscar?pickUpDate=2024-06-21&pickUpTime=20:30&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2024-07-04&returnTime=14:30&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Captura del error

![image](https://github.com/toselli/issues/assets/143418128/4f7ddd19-da14-4622-8317-ae4d4995a921)
![image](https://github.com/toselli/issues/assets/143418128/917e4b7c-5ae5-49b2-bbf0-708775c5a602)

Screenshots del producto en cuestion en la pagina de Dollar.

### Link al error y/o Localizador

https://www.juantoselli.com/#/autos/buscar?pickUpDate=2024-06-21&pickUpTime=20:30&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2024-07-04&returnTime=14:30&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
El proveedor sigue sin enviarnos el producto mencionado en la issue. Se le reitera la consulta y el pedido de que reviertan la situacion.

**Comment by PatricioH96** [comment]
Se cierra la issue porque el proveedor no contesta de manera reiterada. Aun asi se mantiene abierta la gestion hasta que se resuelva el tema completamente.

**Comment by IgnacioaguirreJT** [comment]
Patri alguna novedad de este pedido?, me acaba de consultar el vendedor.
