### ISSUE TITLE
Agregar pasajero RES005152-5065

### ISSUE THREAD

**Issue by BelenBidondo** [toselli/issues#832]
### Descripcion del error

Por favor agregar pasajero a la reserva X683413 

Nombre: MARIA LUDMILA LLAVER  
DNI 36960954 

### Paso a paso para reproducir el error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/656094dc836b95dbcddeb7be?purchaseGroupId=524665#heading_656094dc836b95dbcddeb7be

**Comment by gabrielmarinsaldaJT** [comment]
✅
