### ISSUE TITLE
[Enterprise] Información incompleta en adm

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#833]
### Descripcion del error

Buenas tardes chicos !
Necesitamos por favor, agregar la informacion a la reserva de auto, para que el vendedor pueda entregar voucher:
https://adm.ebooking.com.ar/bookings/detail/64eca9e4836e54e895e2b9ac?purchaseGroupId=522746#heading_64eca9e4836e54e895e2b9ac
Ya que la trae incompleta
![image](https://github.com/toselli/issues/assets/87333634/1f6f620b-ec86-4ccc-bd90-9fffca60fd00)

**Por otro lado, podrán chequear la integración y a que se debe esto?**

Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/64eca9e4836e54e895e2b9ac?purchaseGroupId=522746#heading_64eca9e4836e54e895e2b9ac

### Plataforma

.

**Comment by PatricioH96** [comment]
Se le envio un mail al proveedor solicitando detalles del punto de retiro porque no tenemos esos datos en nuestro sistema. Cuando respondan se generará en la base de datos y se podrá actualizar la informacion.

**Comment by PatricioH96** [comment]
Listo.
