### ISSUE TITLE
(Error en Autos, proveedor todos) No arroja resultados Napoles, Italia (NAP)

### ISSUE THREAD

**Issue by IgnacioaguirreJT** [toselli/issues#834]
### Descripcion del error

Equipo, no estariamos encontrando vehiculos disponibles para adquirir, nuestra comercial buscaba dispo de Avis, la cual existe, pero no podemos encontrarla, ni de ningun otro proveedor, debido a que directamente no nos arroja resultados,

### Paso a paso para reproducir el error

La búsqueda es la siguiente, **eBooking**/**Vehiculos**

Ciudad de retiro: **Napoles Campania Italia**

Retira el auto en **Napoles Aeropuerto el 25/05 (cod: NAP)** a las **15**
Deja en Estacion de **Tren de Napoles  el 30/05 (cod: NP5)** a las **15**

Es con **Avis**, una **SUV**

### Captura del error

![image](https://github.com/toselli/issues/assets/143418128/7101f0ee-15b7-4889-8041-1fc0173522b5)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2024-05-25&pickUpTime=15:00&pickUpOfficeId=NAP&pickUpCityId=5a21ab4cfc2d5608730200b2&pickUpCityName=napoles-campania--italia&returnDate=2024-05-30&returnTime=15:00&returnOfficeId=NP5&returnCityId=5a21ab4cfc2d5608730200b2&returnCityName=napoles-campania-italia&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Solved! ✅
