### ISSUE TITLE
Necesitamos mail voucher X863893 VivaWyndham

### ISSUE THREAD

**Issue by IgnacioaguirreJT** [toselli/issues#835]
### Descripcion del error

Equipo, no esta bajando el voucher de la reserva en titulo correctamente, 
el pdf que descarga tira error, y al visualizarlo tambien.

### Paso a paso para reproducir el error

ADM, RESERVAS, VOUCHER X863893 

### Captura del error

![image](https://github.com/toselli/issues/assets/143418128/12e63851-b9a7-4496-b502-6484f0084e8e)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/65c68622c643a2fd16499295?purchaseGroupId=571800#heading_65c68622c643a2fd16499295

**Comment by PatricioH96** [comment]
Solucionado
