### ISSUE TITLE
Reportes multiples de error al descargar facturas

### ISSUE THREAD

**Issue by IgnacioaguirreJT** [toselli/issues#838]
### Descripcion del error

Equipo,
nos han llegado multiples reportes de un error 505 Bad Gateway al querer descargar facturas de eBooking y Juan Toselli

### Paso a paso para reproducir el error

Parece ser un error general y no de un tipo de busqueda especifico,
les adjunto las screenshots y reportes.

### Captura del error

![image](https://github.com/toselli/issues/assets/143418128/77e50f30-f2c8-48f9-8b66-c6f806824d2c)
![image](https://github.com/toselli/issues/assets/143418128/6f21ebde-c2d5-4ee1-9508-1e0b9c79cceb)
![image](https://github.com/toselli/issues/assets/143418128/a03f3de2-3ca9-44a0-8379-f30d061d594c)

### Link al error y/o Localizador

https://ebooking.com.ar/#/mi-cuenta/mis-facturas

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Estimados, cómo va?

Estuvimos revisando el caso desde esta mañana y vemos que el servidor de AFIP está caido y no responde

Les enviamos un mail solicitando soporte y no nos han respondido

Quedamos a la espera

Saludos
