### ISSUE TITLE
agregar infante a reserva e ebook

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#839]
### Descripcion del error

agregar infante a reserva 

DATOS: Simon Oro Campillay 70083367

agregar en apartado de pasajeros y en apartado de ocupacion porfis 

### Paso a paso para reproducir el error

https://adm.ebooking.com.ar/bookings/detail/662018bdc130900ef2c8db5b?purchaseGroupId=594225#heading_662018bdc130900ef2c8db5b

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/662018bdc130900ef2c8db5b?purchaseGroupId=594225#heading_662018bdc130900ef2c8db5b

**Comment by PatricioH96** [comment]
Listo
