### ISSUE TITLE
MODIFICACION VOUCHER

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#84]
Estimados buenos días,
Me podrían ayudar modificando los comentarios del siguiente voucher?
![image](https://user-images.githubusercontent.com/45457355/131859304-57a0a963-4ff8-4255-871d-590106a6454f.png)
Ya que el mismo fue modificado con Operador y ahora tiene otro horario de check in:
![image](https://user-images.githubusercontent.com/45457355/131859541-5faae3bc-9b99-44f8-9589-5440ff4d9853.png)

**Comment by moliveto** [comment]
Link de la reserva?

**Comment by Jlavign** [comment]
Marce buenas tardes, adjunto link 
https://adm.ebooking.com.ar/bookings/detail/61240977481ac04688f16bc8?purchaseGroupId=359081#heading_61240977481ac04688f16bc8

**Comment by Jlavign** [comment]
Buenas tardes, tendrán novedades?

**Comment by gabrielmarinsaldaJT** [comment]
Done it.
