### ISSUE TITLE
[AssistCard] No se pueden decargar voucher del proveedor 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#841]
### Descripcion del error

Hola chicos!
No se estan descargando los vouchers del proveedor Assit Card.

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/65ef5beb834b27bb21f46d98?purchaseGroupId=580661#heading_65ef5beb834b27bb21f46d98

### Plataforma

.

**Comment by PatricioH96** [comment]
[22360364.pdf](https://github.com/toselli/issues/files/15296474/22360364.pdf)
[22360363.pdf](https://github.com/toselli/issues/files/15296475/22360363.pdf)
