### ISSUE TITLE
Europcar/Autos al llegar al check out no se confirman los servicios.

### ISSUE THREAD

**Issue by IgnacioaguirreJT** [toselli/issues#842]
### Descripcion del error

Equipo buenas, nos reporta una ejecutiva que esta pudiendo adquirir un vehiculo de *Europcar* 
la disponibilidad parece estar apareciendo bien, el problema yace luego de agregar al carrito la reserva y colocar todos los datos,
al intentar confirmar la misma se toma con error, no se confirma.

Esto esta pasando con la mayoria de las opciones disponibles del proveedor Europcar

### Paso a paso para reproducir el error

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2024-05-22&pickUpTime=09:00&pickUpOfficeId=ADB&pickUpCityId=5a43451ffc0b9d5df18da576&pickUpCityName=i%CC%87zmir-i%CC%87zmir-turquia&returnDate=2024-05-23&returnTime=09:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Captura del error

![image](https://github.com/toselli/issues/assets/143418128/115fd3ac-cf21-4fb5-a3b1-47811a60c31c)

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2024-05-22&pickUpTime=09:00&pickUpOfficeId=ADB&pickUpCityId=5a43451ffc0b9d5df18da576&pickUpCityName=i%CC%87zmir-i%CC%87zmir-turquia&returnDate=2024-05-23&returnTime=09:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
El proveedor ya funciona correctamente. 

![image](https://github.com/toselli/issues/assets/108674150/78a76e8a-545e-45c0-bf3a-a874e9028246)
