### ISSUE TITLE
Expedia en error confirmadas en la web

### ISSUE THREAD

**Issue by BelenBidondo** [toselli/issues#845]
### Descripcion del error

Reservas que en el adm al tomarse quedaron en error se confirmaron en la web de Expedia. Algunas cambian de estado con getbooking.

### Paso a paso para reproducir el error

-

### Captura del error

![image](https://github.com/toselli/issues/assets/103128819/e56c8d5f-98ad-480f-a297-d0663ada6a62)
![image](https://github.com/toselli/issues/assets/103128819/7632396c-c970-44e2-ae1b-dcd56ad2a396)
![image](https://github.com/toselli/issues/assets/103128819/5b33c5fc-1ba8-4df4-a693-1c343f938f1d)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2021-01-01&beginServiceFrom=2024-05-10&status=4&provider=expedia

**Comment by PatricioH96** [comment]
El proveedor nos confirma de que las 4 reservas que nos quedaron con error nunca se crearon de su lado, por lo que no existen.
