### ISSUE TITLE
Atraccion (City Tour Miami) Action Travel - No visualizamos servicio

### ISSUE THREAD

**Issue by IgnacioaguirreJT** [toselli/issues#846]
### Descripcion del error

Equipo, nos reportan que no estan visualizando el servicio perteneciente a Action Travel llamado "**City Tour Miami +Bay Tour Compartido (Miami Beach, South Beach y Downtown) - Regular**"

![image](https://github.com/toselli/issues/assets/143418128/6a2df32f-3862-470c-a760-423814efb889)

### Paso a paso para reproducir el error

Seccion atracciones, Miami y sus alrededores, del **23/08/24** al **31/08/24** , 2 adultos.

### Captura del error

Link de disponibilidad donde deberia aprecer:  https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5a21b153fc2d560873053f72&destinationName=miami-y-sus-alrededores-florida--estados-unidos&fromDate=2024-08-23&toDate=2024-08-31&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/atracciones/buscar?destinationId=5a21b153fc2d560873053f72&destinationName=miami-y-sus-alrededores-florida--estados-unidos&fromDate=2024-08-23&toDate=2024-08-31&nationality=AR&residence=AR&occupancies=2*30,30*0*&disney=false&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
Listo
