### ISSUE TITLE
[dotw] jt mock

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#847]
### Descripcion del error

Hola chicos!
El proveedor levanto esta reserva https://adm.ebooking.com.ar/bookings/detail/664c46615f2b060da6b56e22?purchaseGroupId=606940#heading_664c46615f2b060da6b56e22 por una reubicaciòn.
Podrán agregarnos los datos que faltan? es decir **agenncia**, **vendedor**, estado **cobrada**.
Es decir tiene que quedar asi con estos datos https://adm.ebooking.com.ar/bookings/detail/662aa0788d7117cbc84b48e3?purchaseGroupId=587036#heading_662aa0788d7117cbc84b48e3 

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/664c46615f2b060da6b56e22?purchaseGro

### Plataforma

.

**Comment by GuadaVivas** [comment]
Buenas tardes
Alguna novedad?

**Comment by PatricioH96** [comment]
listo
