### ISSUE TITLE
[Tourmed] Error en ocupancy

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#848]
### Descripcion del error

Hola chicos
De la reserva https://adm.ebooking.com.ar/bookings/detail/664ca0654c2695f900749974?purchaseGroupId=607094#heading_664ca0654c2695f900749974 el proveedor no tiene el child en su reserva, le ha llegado solo para adultos, ademas indican que para ese tipo de habitaciòn no es posible ubicar niño.
Podrán chequear de donde viene el error? 
![image](https://github.com/toselli/issues/assets/87333634/84ff948d-5bb8-4f36-b00f-39263d3eeb69)

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/664ca0654c2695f900749974?purchaseGroupId=607094#heading_664ca0654c2695f900749974

### Plataforma

.

**Comment by GuadaVivas** [comment]
alguna novedad?

**Comment by PatricioH96** [comment]
listo

**Comment by gabrielmarinsaldaJT** [comment]
Hola!!

Estuve viendo y nosotros le pedimos correctamente la habitación a Tourmed
En los logs está bien solicitado el CHD

Les escribí un mail consultándole

**Comment by gabrielmarinsaldaJT** [comment]
Hola! 

El problema està solucionado para futuras reservas, ya no puede volver a pasar

El tema serìa retomar la reserva que tenia CHD porque desde nuestro lado se tomò mal

Saludos
