### ISSUE TITLE
Error toma reserva No Reembolsable atracciones 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#85]
Chicos buen día,

Estoy intentando tomar una reserva de aracciones para una vendedora, la misma es No reembolsable:
https://travel.tosellitours.com/#/atracciones/finalizar-compra/61321d04e231a35f4fb06b3f?currency=USD

Me da este error:
![image](https://user-images.githubusercontent.com/87333634/132010103-435f784b-bcb0-489f-bc70-f5f4ff329a14.png)

Gracias!

**Comment by julianbenegaslane** [comment]
Solucionado, los cambios se vana  ver reflejados en la proxima publicacion.
