### ISSUE TITLE
[WAMOS] Error al dar getbooking

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#851]
### Descripcion del error

Reserva confirmada en web de proveedor y en estado pendiente en nuestro sistema, al dar getbooking figura el siguiente error: "el proveedor no implementa esta funcion"

### Paso a paso para reproducir el error

-

### Captura del error

![image](https://github.com/toselli/issues/assets/98116205/a608c6fd-d57a-477c-8324-c725b657e545)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6657846bfe072e43dbb07d17?purchaseGroupId=610498#heading_6657846bfe072e43dbb07d17

**Comment by PatricioH96** [comment]
El proveedor no utiliza el método GetBooking para la actualización de reservas. La manera de constatar y actualizar el estado de las mismas es comunicándonos por mail con los contactos asignados al proveedor. Se les consulta en el día de la fecha la posibilidad de implementar esos métodos o si ya los tienen implementados y no nos notificaron.

**Comment by PatricioH96** [comment]
El proveedor nos paso la documentacion para integrar los metodos faltantes. Estamos en desarrollo.

**Comment by PatricioH96** [comment]
Fin del desarrollo, los metodos estan implementados.
