### ISSUE TITLE
[BlueDiamond] Reservas en Revisar

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#853]
### Descripcion del error

Hola Chicos!
Las reservas de BlueDiamondHotetec, han quedado en revisar. 
No logro ver mensaje de error en el Getbooking y tampoco cambia el estado cuando se efectua el mismo.
Gracias!

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings?dateFrom=2021-12-10&status=7&provider=blue

### Plataforma

.

**Comment by GuadaVivas** [comment]
https://adm.ebooking.com.ar/bookings?dateFrom=2021-12-10&status=7&provider=gaviota 
Hola chicos, pasa lo mismo con GaviotaHotetec

**Comment by PatricioH96** [comment]
Listo.
