### ISSUE TITLE
[Coris] Error al crear reserva

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#854]
### Descripcion del error

Hola chicos!
Hay un inconveniente cuando se toman las reservas de Coris, ya que las mismas quedan confirmadas pero no traen localizador. El proveedor al parecer no las tiene y debe emitirlas offline.
![image](https://github.com/toselli/issues/assets/87333634/28daa10c-960c-4b4b-bf66-aa8a3a8b0fe2)

### Paso a paso para reproducir el error

.

### Link al error y/o Localizador

.

### Plataforma

https://adm.ebooking.com.ar/bookings/detail/66609a4b7148e3c56dc37cd5?purchaseGroupId=613354#heading_66609a4b7148e3c56dc37cd5

**Comment by PatricioH96** [comment]
Listo. Quedaran algunas reservas que haya que seguir gestionando pero el error que provoco ese inconveniente ya esta solucionado.
