### ISSUE TITLE
Tren Brightline Orlando-Miami (Action Travel)

### ISSUE THREAD

**Issue by IgnacioaguirreJT** [toselli/issues#856]
### Descripcion del error

No se puede adquirir el tren brightline desde Orlando a Miami, solo viceversa, necesitamos visualizar el servicio tanto Smart como Premium.

### Paso a paso para reproducir el error

Atracciones, Tren Brightline
Día 08/01/2025
ORLANDO – MIAMI       HORARIO 09.30HS
Clase Premium
4 paxs

### Captura del error

![image](https://github.com/toselli/issues/assets/143418128/06522dff-13cd-4d84-b59d-9aaff5c45ff6)

### Link al error y/o Localizador

https://ebooking.com.ar/#/atracciones/buscar?destinationId=5a21b153fc2d560873053f72&destinationName=miami-y-sus-alrededores-florida--estados-unidos&fromDate=2025-01-08&toDate=2025-01-09&nationality=AR&residence=AR&occupancies=4*30,30,30,30*0*&disney=false&currency=USD

### Plataforma

Google Chrome

**Comment by PatricioH96** [comment]
El vendedor se confundio. Si se busca un tren que vaya del punto A al punto B se tiene que poner en destino el nombre de la ciudad del punto A.
