### ISSUE TITLE
[Expedia] Error en información

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#858]
### Descripcion del error

Hola chicos!
Tenemos de nuevo el problema con las reservas de Expedia que indican que incluye el trasnfer gratis sin cargo al hotel, pero desde el hotel y el proveedor dicen que no.
Será un problema de Expedia? Se le puede reclamar el trasnfer a ellos o el problema viene de nuestro lado?
![image](https://github.com/toselli/issues/assets/87333634/34b9c68d-5581-4ea0-934f-acc969980571)
Tenemos 3 que la vendedora reclama:
9040844178787
9055833434207
9039581167527
Aguardamos.

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

.

### Plataforma

.

**Comment by GuadaVivas** [comment]
Hola chicos! 
Esto ya quedo integrado para que se borre y no vuelva a suceder ?

**Comment by gabrielmarinsaldaJT** [comment]
Listooo
