### ISSUE TITLE
[ADM] Modificar propiedad FECHA LIMITE DE CAMBIO 14/07/2024

### ISSUE THREAD

**Issue by mvalentinalucero** [toselli/issues#859]
### Descripcion del error

Modificar en las reservas 1936789//1936788 la propiedad. Corresponde cambiar en ambas a HOTEL ATRLANTICO MADRID (GRAN VIA 38, MADRID, ESPAÑA)

https://adm.ebooking.com.ar/bookings/detail/66753848a2148a60af895412?purchaseGroupId=620480#heading_66753848a2148a60af895412

https://adm.ebooking.com.ar/bookings/detail/66753848a2148a60af8952db?purchaseGroupId=620480#heading_66753848a2148a60af8952db

### Paso a paso para reproducir el error

-

### Link al error y/o Localizador

-

**Comment by PatricioH96** [comment]
Listo
