### ISSUE TITLE
Avis en Ebooking no muestra plan SUPER SEE EUROPE ALL INCLUSIVE

### ISSUE THREAD

**Issue by natisalino** [toselli/issues#86]
**Describe the bug**
Avis en Ebooking no muestra plan SUPER SEE EUROPE ALL INCLUSIVE, solamente muestra el plan SEE EUROPE

**To Reproduce**
1. Realizzo la busqueda con la oficna, fechas y horario de pick up y drop off
2. En la barra derecha quiero seleccionar en tarifa para filtrar el plan Super see europ All Inclusive y solo fugura See Europe

 Link Ebooking: 
https://ebooking.com.ar/#/autos/buscar?pickUpDate=2021-09-19&pickUpTime=12:00&pickUpOfficeId=S6P&pickUpCityId=5a21b155fc2d560873053f77&pickUpCityName=madrid-y-sus-alrededores-madrid--espana&returnDate=2021-10-12&returnTime=12:00&nationality=AR&residence=AR&currency=USD
Link Avis: 
https://carrental-int.com/avis/res/availability.php 
**Screenshots**
![image](https://user-images.githubusercontent.com/88200755/132039084-96fa902f-6cc7-4902-a93a-2cdac665ae51.png)
web de avis si lo muestra
![image](https://user-images.githubusercontent.com/88200755/132039162-be173c07-f9f6-4bf8-a412-c1187d8f1ee6.png)

**Desktop (please complete the following information):**
 - OS: [Window]
 - Browser [chrome]
 - Version [?]

**Additional context**

**Comment by gabrielmarinsaldaJT** [comment]
Hola @natisalino 

He revisado lo que nos planteaste y puedo ver la tarifa que nos solicitas

Serías tan amable de revisar otra vez?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Cierro issue por falta de respuesta

**Comment by natisalino** [comment]
Hola Gabyn pasa que esto me llega al Gmail, y no lo reviso seguido. No me
dejó hacer cuenta con mail de Toselli.
Volví a hacer búsqueda y si me figura ahora em plan. Gracias
Nati
