### ISSUE TITLE
[Omnibees] Agregar adulto

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#860]
### Descripcion del error

Hola chicos
Necesito agrega runa adulto a la reserva 
https://adm.ebooking.com.ar/bookings/detail/6683ee0ed42fe60437102e00?purchaseGroupId=590900#heading_6683ee0ed42fe60437102e00
Por error eliminé un pasajero y cuando intento "Agregar pasajero" no puedo, no funciona el boton.
Los datos son:
Edgard Alejandro Rodriguez Cala DNI: 01062762887 - cubano

### Paso a paso para reproducir el error

.

### Captura del error

.

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6683ee0ed42fe60437102e00?purchaseGroupId=590900#heading_6683ee0ed42fe60437102e00

### Plataforma

.

**Comment by PatricioH96** [comment]
listo
