### ISSUE TITLE
Vehiculos Avis, no vemos disponibilidad en destinos en Francia

### ISSUE THREAD

**Issue by IgnacioaguirreJT** [toselli/issues#867]
### Descripcion del error

Buenas tardes equipo,
no estamos visualizando disponibilidad del proveedor avis, hemos probado tanto con el link de disponibilidad que nos ha enviado el vendedor, tanto como filtrando en Paris y sus alrededores y seleccionando oficinas random de Avis. No encontramos resultados.

### Paso a paso para reproducir el error

Vehiculos,
Retiras en: [Nice Gare 06 - GK7]
El mar 24, septiembre 2024, 09:30Hrs.

DEVOLVEMOS EN AEROPUERTO DE NICE 30SEP 0625HS DE LA MANANA

### Captura del error

![image](https://github.com/user-attachments/assets/52eaa658-7d84-47b9-ae1c-4bd8dbf7ef15)

### Link al error y/o Localizador

https://www.juantoselli.com/#/autos/buscar?pickUpDate=2024-09-24&pickUpTime=09:30&pickUpOfficeId=GK7&pickUpCityId=5a458de8fc0b9d5df192064f&pickUpCityName=nice-cote-d-azur-provence-alpes-cote-d-azur-francia&returnDate=2024-09-30&returnTime=06:30&returnOfficeId=NCE&returnCityId=5a458de8fc0b9d5df192064f&returnCityName=nice-cote-d-azur-provence-alpes-cote-d-azur-francia&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by gabrielmarinsaldaJT** [comment]
Listo!!!

Ahora si sale
