### ISSUE TITLE
Avis o Budget Vehiculos Ausencia de productos

### ISSUE THREAD

**Issue by IgnacioaguirreJT** [toselli/issues#873]
### Descripcion del error

Buenas chicos, reportamos ausencia de los proveedores Budget o Avis, fue cotizado bajo distintas fechas sobre enero, pero no sale ni en los proveedores

![image](https://github.com/user-attachments/assets/b1606bde-8686-4409-936a-94010742a09f)

### Paso a paso para reproducir el error

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2025-01-19&pickUpTime=10:00&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2025-02-03&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

Link de disponibilidad enviado por el vendedor, 

### Link al error y/o Localizador

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2025-01-19&pickUpTime=10:00&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2025-02-03&returnTime=10:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

### Plataforma

Google Chrome

**Comment by IgnacioaguirreJT** [comment]
Equipo adjunto link de dispo de otro caso por el mismo ticket en cuestion.

https://www.ebooking.com.ar/#/autos/buscar?pickUpDate=2024-10-18&pickUpTime=20:00&pickUpOfficeId=MIA&pickUpCityId=5a21b153fc2d560873053f72&pickUpCityName=miami-y-sus-alrededores-florida--estados-unidos&returnDate=2024-11-02&returnTime=06:00&isOnAirport=true&nationality=AR&residence=AR&currency=USD

![image](https://github.com/user-attachments/assets/dc953c9d-a29b-413a-b2be-abba373ac2ec)

**Comment by gabrielmarinsaldaJT** [comment]
Listo!
