### ISSUE TITLE
RESTEL LOC 37517820

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#88]
### Descripcion del error

MODIFICACION DE NOMBRE PAX LIDER,
AGENCIA TOMO MAL NOMBRE DE PASAJERO LIDER, 
DEBE MODIFICARSE PARA ENVIAR VOUCHER A AGENCIA,
OPERADOR YA MODIFICO DESDE SU PLATAFORMA DICHO ERROR.
NO SE ACTUALIZA EN ADM CORRECTAMENTE EL CAMBIO REALIZADO.

### Paso a paso para reproducir el error

LOC 37517820

### Captura del error

![image](https://user-images.githubusercontent.com/45457355/132261568-52b59a6a-2ea8-4e43-9393-b000adc062d9.png)
DE GONZALEZ A GOMEZ

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/612ac70fd858fdd2e266cba1?purchaseGroupId=359081#heading_612ac70fd858fdd2e266cba1

**Comment by Jlavign** [comment]
Buenas tardes,
Tendrán novedades?

**Comment by josecaserez** [comment]
> Buenas tardes,
> Tendrán novedades?

Es un error nuestro esta configurado para que solo guarde el nombre que vino de Restel cuando no haya ninguno guardado. Se esta trabajando en un fix pero se detectaron algunos cambios en la respuesta lo que ocasiono una demora al subir la correccion.

**Comment by josecaserez** [comment]
Ya se subio el fix. Cuando se actualice deberia corregirse.
