### ISSUE TITLE
VIATOR

### ISSUE THREAD

**Issue by Jlavign** [toselli/issues#9]
Estimados buenas tardes,

No se descargan vouchers de Viator, 
Adjunto link de reserva y error:

https://adm.ebooking.com.ar/bookings/detail/5df7c961b7eba3842202d414?purchaseGroupId=305132#heading_5df7c961b7eba3842202d414

![image](https://user-images.githubusercontent.com/45457355/124989482-8e397f80-e015-11eb-8a48-a188e223fcb9.png)

**Comment by julianbenegaslane** [comment]
Arreglado de manera local, una vez publicado va a estar funcionando

https://github.com/toselli/eBookingV4/pull/6245
