### ISSUE TITLE
Modificar nombre de pax lider

### ISSUE THREAD

**Issue by JuanBachmann** [toselli/issues#90]
### Descripcion del error

Buenas tardes, Equipo.

Necesito completar los datos del pax líder, de las siguientes reservas : 
- FJMSMLJ/01 (Pasajero líder: IVAN IVANISEVICH)
- QPK6LKO/01 (Pasajero Líder: CRISSI/SILVIA DEL VALLE)

Ambas muestran incompleto el nombre del pasajero líder en nuestro Admin, pero en el sitio del proveedor sí se visualiza el nombre completo de cada pasajero.
Espero nos puedan ayudar.

Saludos,
Juan Manuel.

### Paso a paso para reproducir el error

Modificar nombres de pasajeros líder en el ADM

### Captura del error

![image](https://user-images.githubusercontent.com/88722251/132394398-20ab05be-824d-46c7-877f-872794fdb681.png)

![image](https://user-images.githubusercontent.com/88722251/132394442-b5523693-1385-4be4-b650-ff8a15c91233.png)

### Link al error y/o Localizador

FJMSMLJ/01 - QPK6LKO/01

### Plataforma

Google Chroome

**Comment by gabrielmarinsaldaJT** [comment]
Estimados, unas cosas para que tengan en cuenta

La issue está bien planteada, tiene buenas imágenes y la info me sirvió

Pero les recomiendo pasar directamente el link del adm a la reserva y explicar el porqué ustedes no pudieron actualizar el nombre del pasajero

De todas maneras es una buena issue y está muy bien detallada

Al problema lo resolví, asique ahora solamente deben esperar a que publiquemos para que el nombre del pasajero no se vuelva a borrar y ustedes puedan actualizarlo normalmente sin miedo a perder los datos

Saludos

**Comment by JuanBachmann** [comment]
Buen día, Gabi

¡Gracias!
