### ISSUE TITLE
Reserva en revisar Expedia - Con gastos. 

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#91]
### Descripcion del error

La reserva de Expedia, no se canceló por autocancel, ahora se encuentra en revisar y en gastos. Envié un correo al customer de Expedia y no me respondieron por lo que opté enviándole los logs de cancelación al equipo de support. No obtuve una respuesta final de cancelaciòn sin gastos. 
Necesito que me confirmen si finalmente se encuentra en Error y si es problema de ellos, en caso de corresponder, cuáles logs enviarles para reclamar. 

### Paso a paso para reproducir el error

1) Entre a la reserva
2) Se encontraba rara desde cuando esta confirmada, vendedor tampoco pudo cancelarla en su momento.
3) No posea boton de cancelar.
4) Autocancel no funcionó
5) Envié correo al customer para cancelar sin gastos, no respondieron
6)Envié correo con logs del primer metodo get cancel, tampoco me dieron respuesta final. 

### Captura del error

Tengo captura de la respuesta de Expedia. Desconozco a qué refiere, de todas formas he respondido si finalmente me pueden decir que este cancelada FOC:

![image](https://user-images.githubusercontent.com/87333634/132523571-57a86c6b-8a24-4a79-8df6-10e0ff469865.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/612e7c06f71cdf3b0ddd1525

### Plataforma

Google Chrome ?

**Comment by GuadaVivas** [comment]
Adjunto nueva respuesta:

![image](https://user-images.githubusercontent.com/87333634/132524703-577b89b4-7d91-4710-a8cc-8d0fa673ec93.png)

**Comment by gabrielmarinsaldaJT** [comment]
Me unassigno de la issue ya que no tengo mas por hacer
