### ISSUE TITLE
Mis reservas  - Plataforma web

### ISSUE THREAD

**Issue by agostinaf25** [toselli/issues#95]
### Descripcion del error

No visualizo las rvas en Mi cuenta - Mis rvas
Puntualmente en http://savitur.agenciavirtual.net/

### Paso a paso para reproducir el error

Usuario: hola@test.com
Contraseña: 123456789

### Link al error y/o Localizador

http://savitur.agenciavirtual.net/

**Comment by IvanFacundoRosas** [comment]
El error es porque el usuario hola@test no tiene permiso `ViewAllReservations`
