### ISSUE TITLE
Fórmula Costo de Gestión - Toselli Tours

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#97]
### Descripcion del error

Buenos días, quisiera saber la fórmula por la cual se deriva el costo de gestión, ya que desde Pagos escuche Neto agencia - Costo, pero no coinciden los montos. 
Esto lo preciso para coordinar la facturación entre el Departamento Agencias y el Departamento Pagos. 
Dejo el link de una reserva de Toselli Tours para que puedan tomarla como muestra. 
Muchas gracias!

### Paso a paso para reproducir el error

No hay error alguno, se trata de una consulta. 

### Captura del error

No hay error alguno, se trata de una consulta. 

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/6137def763015f93a2ccd6a4?purchaseGroupId=359888#heading_6137def763015f93a2ccd6a4

**Comment by gabrielmarinsaldaJT** [comment]
Estimados, cómo están?

Les paso;

Nombre | Monto 
-- | -- 
NoImponible | 77,05
Gravado | 1,27
Exento | 0
IVA | 0
AdministrativeFeePercentage | 0,02
Total | 1,5716
