### ISSUE TITLE
Agencias dadas de alta sin explicitar quién las cargo

### ISSUE THREAD

**Issue by abrahamfariaz** [toselli/issues#98]
### Descripcion del error

Al revisar agencias activas y cargadas en el administrador de Ebooking, existen varias que no indican quién fue el usuario de Toselli que las creo. 

### Paso a paso para reproducir el error

1. Entrar al administrador de Ebooking
2. Clientes

Se despliega por defecto los clientes cargados y dados de alta. Se puede visualizar casos como (se brinda nombre de fantasía) Mónica, WWW.DREAMARGENTINA.COM, THEILER VIAJES y otros.

### Captura del error

Agencia dada de alta sin explicitar por quién...

![image](https://user-images.githubusercontent.com/40358708/133105387-3d165c49-6e43-487c-9a0a-9c4e2e0556a6.png)

Agencia dada de alta que explícita por quién...

![image](https://user-images.githubusercontent.com/40358708/133105541-da0acd74-ee12-43e3-baca-e69da933a69e.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/agencies/edit/613bc7d8724fedf6562e15f5

**Comment by abrahamfariaz** [comment]
Buenos días, ¿Alguna novedad?

**Comment by gabrielmarinsaldaJT** [comment]
Hola Abe!

Bueno, ya mismo nos ponemos a revisar esos users y vemos que está pasando

Quienes son los que habitualmente realizan estas tareas? Ustedes en operaciones?

Saludos

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, cómo va?

El tema ya se solucionó para agencias a futuro

Saludos

**Comment by abrahamfariaz** [comment]
Buenos días Gabi,
Acabo de hacer una prueba de registro de agencias desde EBOOKING y me la cargó y activó. Lo cuál es un problema grande dado que la agencia esta lista para operar 🚨 
Adjunto captura
![image](https://user-images.githubusercontent.com/40358708/154734641-c3ba805d-940b-4a87-a080-7293eefc7740.png)
![image](https://user-images.githubusercontent.com/40358708/154734687-e036bb27-c17f-4dce-a26a-a42c16ed2d76.png)

La agencia al registrarse debe quedar siempre en "Pendiente de Habilitación"

**Comment by gabrielmarinsaldaJT** [comment]
@abrahamfariaz con qué usuario estás agregando la agencia??

**Comment by abrahamfariaz** [comment]
@gabrielmarinsaldaJT cuando alguien va al botón "Registrarte" y carga su agencia (adjunto captura), inmediatamente se carga como agencia activada y ya puede comenzar a reservar, sin previo análisis humano de su condición crediticia.

![image](https://user-images.githubusercontent.com/40358708/154763612-3b3d250e-7afd-4d75-9730-3cd66a051491.png)

**Comment by abrahamfariaz** [comment]
Buenos días, ¿Alguna novedad? 
Las agencias se continúan registrando y están por defecto activadas, sin control humano alguno de su condición crediticia
Gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes, ¿Alguna novedad?
Gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes, ¿Alguna novedad?
Muchas gracias

**Comment by abrahamfariaz** [comment]
Buenas tardes,
¿Alguna novedad?
Gracias!

**Comment by abrahamfariaz** [comment]
Buenos días, 
¿Alguna novedad?
Gracias

**Comment by gabrielmarinsaldaJT** [comment]
Chicos, solucionado el tema

En la proxima publicación verán los cambios

Aclaración:

-Si alguien edita la agencia (osea, le cambia algún dato y le da al botón Guardar) va a pasar a ser el usuario que figure donde dice "Creada por xxxx" porque no podemos agregar un campo de edición o notas como tienen en los bookings

**Comment by abrahamfariaz** [comment]
Buenos días Gabi,
¿Cuándo ocurrirá la próxima actualización? Ya que acabo de crear una agencia de prueba y sigue ocurriendo.

![image](https://user-images.githubusercontent.com/40358708/181272186-87d130a8-6831-4326-ac54-eb95c4c1e77f.png)
![image](https://user-images.githubusercontent.com/40358708/181272223-912a9da8-d8d0-470d-8712-a9c72f123030.png)

Registrada desde el formulario

**Comment by gabrielmarinsaldaJT** [comment]
Publicado chicos!
