### ISSUE TITLE
Cambio de propiedad -  Error de mapeo?

### ISSUE THREAD

**Issue by GuadaVivas** [toselli/issues#99]
### Descripcion del error

Hola chicos
Tengo una reservas de travco que el vendedor me indica que fue tomada para la propiedad Hilton Garden Inn Times Square, no obtante me reclama que envió el voucher a la agencia con ese hotel.
Por el otro lado cuando entro a la reserva, esta confirmada para The Manhattan at Times Square, y el vucher efectivamente mustra eso (sumado a que el proveedor lo tiene para esta propiedad y le confirma al vendedor lo mismo).
Le explique la situación al vendedor  y me indico que antes de realizar el reclamo con nosotroa, el visualizaba el Hilton. Nos pasa evidencia.
Finalmente, lo que interpreto en el responde del check out es correcto el Manhattan, pero el response no especifica el problema. Será de ahí el error?

### Paso a paso para reproducir el error

1- Vendedor entra a la reserva visualiza que esta en el Hilton, envia voucher a la agencia.
2 - Vendedor manda a reconfirmar reserva y travco indica que esta para el Manhattan.
3 - Vendedor nos da aviso para reclamarle a travco que no es lo que reservó.
4- Visualizo que desde siempre fue para el Manhattan, no encuentro evidencia que haya sido tomada alguna vez para el Hilton. 

### Captura del error

Captura de evidencia por parte del vendedor que fue para el Hilton: 

![image](https://user-images.githubusercontent.com/87333634/133308957-a465a99c-3411-4c3e-af1a-3bdfecd4372e.png)

![image](https://user-images.githubusercontent.com/87333634/133308762-84f7b1c5-7abb-4fb4-8d18-6507180a6ad3.png)

Captura como lo veo en el adm:

![image](https://user-images.githubusercontent.com/87333634/133309271-b987e0fa-c7bf-45e8-a48b-5d43189ab7ca.png)
![image](https://user-images.githubusercontent.com/87333634/133309330-a0a40d91-5021-49d9-bf90-5326e630d506.png)

### Link al error y/o Localizador

https://adm.ebooking.com.ar/bookings/detail/60d4c3c1407f894067f72677?purchaseGroupId=357077

### Plataforma

Chrome

**Comment by gabrielmarinsaldaJT** [comment]
@GuadaVivas Necesito que me pases el Voucher que Emilio le envió a la agencia con el hotel **Hilton Garden Inn Times Square**

Serías tan amable de conseguirme eso?

**Comment by GuadaVivas** [comment]
Excelente, ahì le pido.

**Comment by GuadaVivas** [comment]
Chicos, cierro la issue ya que Emilio no volvió a reclamar sobre lo mismo. Hice la búsqueda nuevamente, y entiendo que ya se arregló porque en el Check out con Travco , ya aparecía el Hilton.
Gracias.
